{
 "title": "Cassandra Yandex",
 "description": "Monitoring Cassandra with Prometheus using JXM exporter",
 "tags": [ "cassandra" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "cassandra_namespace",
    "query": "label_values(cassandra_endpoint_active, namespace)"
   },
   {
    "name": "cassandra_cluster",
    "label": "Cluster",
    "query": "label_values(cassandra_endpoint_active{namespace=\"$cassandra_namespace\"}, cassandra_cluster)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(cassandra_storage_load_bytes{cassandra_cluster=\"$cassandra_cluster\"}, cassandra_node)"
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"${instance}:9500\"}"
    }
   ]
  },
  {
   "title": "Coonections current",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cassandra_client_native_connections{cassandra_node=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Nodes in quorum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_endpoint_active{cassandra_node=~\"$instance\",cassandra_cluster=~\"$cassandra_cluster\"})"
    }
   ]
  },
  {
   "title": "Blocked Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_thread_pool_blocked_tasks_total{cassandra_node=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Pending compactions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_table_estimated_pending_compactions{cassandra_node=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Unavailable exceptions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cassandra_client_request_unavailable_exceptions_total{operation=~\"read|write\",cassandra_node=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Timeout exceptions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cassandra_client_request_timeouts_total{operation=~\"write|read\",cassandra_node=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_native_connections{cassandra_node=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Connection timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_endpoint_connection_timeouts_total{cassandra_node=~\"$instance\"}[$interval])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "DIsk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Top10 tables by size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(cassandra_table_disk_space_bytes{keyspace=~\".+\",cassandra_node=~\"$instance\"}) by (keyspace,columnfamily) > 0)",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Total disk usage $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_load_bytes{cassandra_node=~\"$instance\"}",
     "legendFormat": "Total disk usage"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Pool used $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_jvm_memory_pool_used_bytes{cassandra_node=\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "Duration R/W", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "ClientRead avg duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_request_latency_seconds{cassandra_node=\"$instance\",operation=\"read\"}",
     "legendFormat": "{{consistency}}"
    }
   ]
  },
  {
   "title": "ClientWrite avg duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_request_latency_seconds{cassandra_node=\"$instance\",operation=\"write\"}>0",
     "legendFormat": "{{consistency}}"
    }
   ]
  },
  {
   "title": "Coordinator level stats (data can be R/W using other nodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Writes / sec latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_client_request_latency_seconds_count{cassandra_node=\"$instance\",operation=~\"write.*\"}[$interval]) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Reads / sec latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_client_request_latency_seconds_count{cassandra_node=\"$instance\",operation=~\"read.*\"}[$interval])",
     "legendFormat": "{{consistency}}"
    }
   ]
  },
  {
   "title": "Avg write latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_request_latency_seconds{cassandra_node=\"$instance\",operation=~\"write.*\"} > 0",
     "legendFormat": "{{consistency}}"
    }
   ]
  },
  {
   "title": "Avg read latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_mean{cassandra_node=\"$instance\",type=~\"Read.*\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "95thPercentile write latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_95thpercentile{cassandra_node=\"$instance\",type=~\"Write.*\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "95thPercentile read latency $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_latency_95thpercentile{cassandra_node=\"$instance\",type=~\"Read.*\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Bytes compacted $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_bytes_compacted_total{cassandra_node=~\"$instance\"}[$interval])",
     "legendFormat": "Bytes compacted"
    }
   ]
  },
  {
   "title": "Completed compactions tasks $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_completed_tasks_total{cassandra_node=~\"$instance\"}[$interval])",
     "legendFormat": "Compactions completed"
    }
   ]
  },
  {
   "title": "Completed tasks count $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_completed_total{cassandra_node=~\"$instance\"}[$interval])",
     "legendFormat": "Completed tasks"
    }
   ]
  },
  { "title": "Thread pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Completed tasks / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_thread_pool_completed_tasks_total{cassandra_node=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Active tasks $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_thread_pool_active_tasks{cassandra_node=~\"$instance\"} > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Total blocked tasks / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_thread_pool_blocked_tasks_total{cassandra_node=~\"$instance\"}[$interval])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Currently blocked tasks $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_thread_pool_blocked_tasks{cassandra_node=~\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "Key cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Cache requests / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_cache_requests_total{cassandra_node=\"$instance\"}[$interval])",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_cache_capacity_bytes{cassandra_node=\"$instance\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache hits / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_cache_hits_total{cassandra_node=\"$instance\"}[$interval])",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache entries $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_cache_entries{cassandra_node=\"$instance\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  { "title": "Memtables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Top10 memtables by table size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(cassandra_table_memtable_live_bytes{keyspace=~\".+\",cassandra_node=~\"$instance\"}) by (keyspace,columnfamily) > 0)",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Memtables columns count $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_memtable_columns{keyspace=~\".+\",cassandra_node=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  { "title": "Snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Snapshots size $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_snapshots_size_bytes_total{keyspace=~\".+\",cassandra_node=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  }
 ]
}