{
 "title": "cpu, memory by namespace",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (75%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile by (namespace) (0.75, sum by (namespace) (rate(container_cpu_usage_seconds_total{}[$__rate_interval])) or count (avg_over_time(kube_controller_pod{}[$__rate_interval])) by (namespace) * 0 )",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Usage (75%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile by (namespace) (0.75, sum by (namespace) (avg_over_time(container_memory_working_set_bytes:without_kmem{}[$__rate_interval])) or count (avg_over_time(kube_controller_pod{}[$__rate_interval])) by (namespace) * 0 )",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "CPU Usage (50%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile by (namespace) (0.5, sum by (namespace) (rate(container_cpu_usage_seconds_total{}[$__rate_interval])) or count (avg_over_time(kube_controller_pod{}[$__rate_interval])) by (namespace) * 0 )",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Usage (50%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile by (namespace) (0.50, sum by (namespace) (avg_over_time(container_memory_working_set_bytes:without_kmem{}[$__rate_interval])) or count (avg_over_time(kube_controller_pod{}[$__rate_interval])) by (namespace) * 0 )",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}