{
 "title": "Kafka",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kafka_burrow_partition_lag,instance)"
    }
   },
   {
    "name": "instance_orig",
    "query": {
     "query": "label_values(kafka_burrow_partition_lag{instance=~\"$instance.*\"},instance)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_burrow_partition_lag{instance=\"$instance_orig\"},topic)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(kafka_burrow_partition_lag{topic=\"$topic\", instance=\"$instance_orig\"}, group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "In-Sync Replicas",
   "type": "stat",
   "description": "acks=0 The producer never waits for an ack from the broker when the ack value is set to 0. No guarantee can be made that the broker has received the message. The producer doesn’t try to send the record again since the producer never knows that the record was lost. This setting provides lower latency and higher throughput at the cost of much higher risk of message loss.\n\nacks=1 When setting the ack value to 1, the producer gets an ack after the leader has received the record. The leader will write the record to its log but will respond without awaiting a full acknowledgment from all followers. The message will be lost only if the leader fails immediately after acknowledging the record, but before the followers have replicated it. This setting is the middle ground for latency, throughput, and durability. It is slower but more durable than acks=0.\n\nacks=all Setting the ack value to all means that the producer gets an ack when all in-sync replicas have received the record. The leader will wait for the full set of in-sync replicas to acknowledge the record. This means that it takes a longer time to send a message with ack value all, but it gives the strongest message durability.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_cluster_partition_insyncreplicascount{topic=\"$topic\", instance=~\"$instance.*\"}",
     "legendFormat": "partition {{partition}}"
    }
   ]
  },
  {
   "title": "New messages per sec in topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"$topic\"}[1m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Broker topic bytes in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"$topic\"}[1m]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Broker topic bytes out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"$topic\"}[1m]))",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "$group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "group" },
  {
   "title": "Lag on reading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_burrow_partition_lag{topic=\"$topic\", instance=\"$instance_orig\", group=~\"$group\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "kafka_burrow_partition_lag{topic=\"$topic\", instance=\"$instance_orig\", group=~\"$group\"}",
     "legendFormat": "Partition - {{partition}}"
    }
   ]
  },
  {
   "title": "Lag on reading",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "max by (partition) (kafka_burrow_partition_current_offset{topic=\"$topic\", group=~\"$group\", instance=\"$instance_orig\"})",
     "legendFormat": "Current offset - {{partition}}"
    },
    {
     "expr": "max by (partition) (kafka_burrow_partition_max_offset{topic=\"$topic\", group=~\"$group\", instance=\"$instance_orig\"})",
     "legendFormat": "Max offset - {{partition}}"
    }
   ]
  }
 ]
}