{
 "title": "Monitoring Camunda",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(camunda_instance_count, service)"
    }
   },
   {
    "name": "process_definition_key",
    "label": "Process",
    "query": {
     "query": "label_values(camunda_instance_count{service=\"$service\"}, process_definition_key)"
    }
   },
   {
    "name": "activity_id",
    "label": "Delegat",
    "query": {
     "query": "label_values(camunda_instance_count{service=\"$service\",process_definition_key=~\"$process_definition_key\"}, activity_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Delegate instances",
   "type": "timeseries",
   "description": "Количество инстансов на делегате для последней версии процесса",
   "gridPos": { "h": 14, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(activity_id)(camunda_instance_count{service=~'$service', namespace=\"payment-sre-exporter\",process_definition_key=~'$process_definition_key',activity_id=~'$activity_id'})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Open Incidents",
   "type": "stat",
   "description": "Количество инцидентов на всех делегатах для последней версии процесса",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(camunda_incident_count{service=~'$service',namespace=\"payment-sre-exporter\",process_definition_key=~'$process_definition_key',activity_id=~'$activity_id'})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Running Process Instances",
   "type": "stat",
   "description": "Количество инстансов на всех делегатах для последней версии процесса",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(camunda_instance_count{service=~'$service',namespace=\"payment-sre-exporter\",process_definition_key=~'$process_definition_key',activity_id=~'$activity_id'})"
    }
   ]
  },
  {
   "title": "Delegate incident",
   "type": "timeseries",
   "description": "Количество инцидентов на делегате для последней версии процесса",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": " sum by(activity_id)(camunda_incident_count{service=~'$service',namespace=\"payment-sre-exporter\",process_definition_key=~'$process_definition_key',activity_id=~'$activity_id'}) > 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}