{
 "title": "Node.js Kafka producer",
 "description": "Dashboard for analyzing individual endpoints' performance using metric http_server_requests",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(nodejs_version_info, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Messages Count [10m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[10m]))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Messages Count [1h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1h]))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Response Time [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (irate(kafka_producer_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1m])) / sum by (topic) (irate(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(kafka_producer_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(kafka_producer_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1m])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Response Time [10m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (irate(kafka_producer_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[10m])) / sum by (topic) (irate(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[10m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(kafka_producer_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[10m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(kafka_producer_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[10m])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Response Time [10m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (irate(kafka_producer_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1h])) / sum by (topic) (irate(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1h]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(kafka_producer_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1h])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(kafka_producer_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1h])))",
     "legendFormat": "p90"
    }
   ]
  },
  { "title": "Response Statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Response Status Ratio [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (status) (increase(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[5m])) / scalar(sum by (service) (increase(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[5m])))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Status Ratio [1h]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (status) (increase(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1h])) / scalar(sum by (service) (increase(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[1h])))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Statuses [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sort_desc(sum by (status) (increase(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\"}[$__range]) > 0))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Exception Types [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sort_desc(sum(increase(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\", status!~\"2..|3..\"}[$__range]) > 0) by (status))",
     "legendFormat": "{{ exception }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "(4xx / 5xx Status) Count [5m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\", status=~\"4..|5..\"}[5m]))",
     "legendFormat": "[{{ status }}] {{ exception }}"
    }
   ]
  },
  {
   "title": "(4xx / 5xx Status) Count [1h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(kafka_producer_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", topic=\"$topic\", status=~\"4..|5..\"}[1h]))",
     "legendFormat": "[{{ status }}] {{ exception }}"
    }
   ]
  }
 ]
}