{
 "title": "Node.js HTTP CLIENT REQUEST/RESPONSE",
 "description": "Dashboard for analyzing individual endpoints' performance using metric http_client_requests",
 "tags": [ "Node.js" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(nodejs_version_info, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   },
   {
    "name": "url",
    "label": "URL",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\"}, url)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", url=\"$url\"}, method)"
    }
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|UNKNOWN|/camunda/.*|ROOT|REDIRECTION|root|NOT_FOUND|/webjars/.*"
   }
  ]
 },
 "panels": [
  { "title": "Request Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, url) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1m]))",
     "legendFormat": "{{ method }} {{ url }}"
    }
   ]
  },
  {
   "title": "Request Count [10m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, url) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[10m]))",
     "legendFormat": "{{ method }} {{ url }}"
    }
   ]
  },
  {
   "title": "Request Count [1h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, url) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1h]))",
     "legendFormat": "{{ method }} {{ url }}"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Response Time [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (method, url) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1m])) / sum by (method, url) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(http_client_requests_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(http_client_requests_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1m])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Response Time [10m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (method, url) (increase(http_client_requests_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[10m])) / sum by (method, url) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[10m]))",
     "legendFormat": "{{ method }} {{ url }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(http_client_requests_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[10m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(http_client_requests_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[10m])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Response Time [1h]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (method, url) (increase(http_client_requests_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1h])) / sum by (method, url) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1h]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(http_client_requests_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1h])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(http_client_requests_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1h])))",
     "legendFormat": "p90"
    }
   ]
  },
  { "title": "Response Statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Response Status Ratio [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[5m])) / scalar(sum by (service) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[5m])))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Status Ratio [1h]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1h])) / scalar(sum by (service) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[1h])))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Statuses [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sort_desc(sum by (status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\"}[$__range]) > 0))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Exception Types [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\", status!~\"2..|3..\"}[$__range]) > 0) by (status))",
     "legendFormat": "{{ exception }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "(4xx / 5xx Status + Exception) Count [5m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\", status=~'4..|5..'}[5m]))",
     "legendFormat": "[{{ status }}] {{ exception }}"
    }
   ]
  },
  {
   "title": "(4xx / 5xx Status + Exception) Count [1h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status, exception) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", url=\"$url\", method=\"$method\", status=~'4..|5..'}[1h]))",
     "legendFormat": "[{{ status }}] {{ exception }}"
    }
   ]
  }
 ]
}