{
 "title": "APM - SLI",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result((group by (namespace) (jvm_classes_loaded_classes) OR group by (namespace) (nodejs_version_info)))"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "query_result((group by (service) (jvm_classes_loaded_classes{namespace=\"$namespace\"}) OR group by (service) (nodejs_version_info{namespace=\"$namespace\"})))"
    }
   },
   {
    "name": "uri",
    "label": "Uri",
    "query": {
     "query": "query_result(group by (uri) (http_server_requests_seconds_sum{namespace=\"$namespace\",service=\"$app\"}) OR group by (path) (http_requests_sum{namespace=\"$namespace\",service=\"$app\"}))"
    }
   },
   {
    "name": "rate",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "SLI/SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Status is",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", uri=~\"$uri\", outcome!=\"SERVER_ERROR\"})/sum(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", uri=~\"$uri\"})",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "sum(http_requests_count{namespace=\"$namespace\", service=\"$app\", path=~\"$uri\", outcome!=\"SERVER_ERROR\"})/sum(http_requests_count{namespace=\"$namespace\", service=\"$app\", path=~\"$uri\"})"
    },
    {}
   ]
  },
  {
   "title": "SLI",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_count{namespace=\"$namespace\", service=\"$app\", uri=~\"$uri\", outcome!=\"SERVER_ERROR\"})/sum(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", uri=~\"$uri\"})"
    },
    {
     "expr": "sum(http_requests_count{namespace=\"$namespace\", service=\"$app\", path=~\"$uri\", outcome!=\"SERVER_ERROR\"})/sum(http_requests_count{namespace=\"$namespace\", service=\"$app\", path=~\"$uri\"})"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "namespace" },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(http_server_requests_seconds_sum{exception=\"None\",namespace=\"$namespace\",service=\"$app\",uri=~\"$uri\"}[$rate])) / sum by (method, uri) (rate(http_server_requests_seconds_count{exception=\"None\",namespace=\"$namespace\",service=\"$app\",uri=~\"$uri\"}[$rate]))"
    },
    {
     "expr": "sum by (method, path) (rate(http_requests_sum{namespace=\"$namespace\",service=\"$app\",path=~\"$uri\"}[$rate])) / sum by (method, path) (rate(http_requests_count{namespace=\"$namespace\",service=\"$app\",path=~\"$uri\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Latency p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\r\n          0.99,\r\n          sum by (uri,le,method)(\r\n            rate(http_server_requests_seconds_bucket{exception=\"None\",namespace=\"$namespace\",service=\"$app\",uri=~\"$uri\"}[$rate])\r\n          )\r\n        )"
    },
    {
     "expr": "histogram_quantile (\r\n          0.99,\r\n          sum by (path,le,method)(\r\n             rate(http_requests_bucket{namespace=\"$namespace\",service=\"$app\",path=~\"$uri\"}[$rate])\r\n          )\r\n        )"
    }
   ]
  },
  {
   "title": "Latency p50",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile (\r\n          0.50,\r\n          sum by (uri,le,method)(\r\n            rate(http_server_requests_seconds_bucket{exception=\"None\",namespace=\"$namespace\",service=\"$app\",uri=~\"$uri\"}[$rate])\r\n          )\r\n        )"
    },
    {
     "expr": "histogram_quantile (\r\n          0.50,\r\n          sum by (path,le,method)(\r\n             rate(http_requests_bucket{namespace=\"$namespace\",service=\"$app\",path=~\"$uri\"}[$rate])\r\n          )\r\n        )"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": " sum by (uri,method)(\r\n            rate(http_server_requests_seconds_bucket{exception=\"None\",namespace=\"$namespace\",service=\"$app\",uri=~\"$uri\"}[$rate])\r\n          )"
    },
    {
     "expr": "sum by (path,method)(\r\n             rate(http_requests_bucket{namespace=\"$namespace\",service=\"$app\",path=~\"$uri\"}[$rate])\r\n          )"
    }
   ]
  },
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (uri,method) (rate(http_server_requests_seconds_count{exception=\"None\",namespace=\"$namespace\",service=\"$app\",uri=~\"$uri\"}[$rate]))",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum by (path,method) (rate(http_requests_count{namespace=\"$namespace\",service=\"$app\",path=~\"$uri\"}[$rate]))"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 36 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (uri,method) (rate(http_server_requests_seconds_count{exception=\"None\",namespace=\"$namespace\",service=\"$app\",uri=~\"$uri\",status=\"5XX\"}[$rate]))",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum by (path,method) (rate(http_requests_count{namespace=\"$namespace\",service=\"$app\",path=~\"$uri\",status=\"5XX\"}[$rate]))"
    }
   ]
  }
 ]
}