{
 "title": "Calculator contour gRPC-services",
 "tags": [ "calculator" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Time frame",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "method_name",
    "label": "Method name",
    "query": {
     "query": "label_values(grpc_server_handled_total{grpc_service=\"$service\"} ,grpc_method) "
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(grpc_server_handled_total,grpc_service) "
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "0.99,0.95,0.90,0.75,0.5" }
  ]
 },
 "panels": [
  {
   "title": "$method_name gRPC request rates by code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(grpc_code)(irate(grpc_server_handled_total{grpc_service=\"$service\", grpc_method=\"$method_name\"}[$interval]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "gRPC requests rate over methods",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(grpc_method)(irate(grpc_server_handled_total{grpc_service=\"$service\"}[$interval]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "$method_name method handling time percentiles",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\", grpc_service=\"$service\", grpc_method=\"$method_name\"}[$interval])) by (grpc_method,le)\n)",
     "legendFormat": "99%-tile"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\", grpc_service=\"$service\", grpc_method=\"$method_name\"}[$interval])) by (grpc_method,le)\n)",
     "legendFormat": "95%-tile"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\", grpc_service=\"$service\", grpc_method=\"$method_name\"}[$interval])) by (grpc_method,le)\n)",
     "legendFormat": "90%-tile"
    },
    {
     "expr": "histogram_quantile(0.75, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\", grpc_service=\"$service\", grpc_method=\"$method_name\"}[$interval])) by (grpc_method,le)\n)",
     "legendFormat": "75%-tile"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\", grpc_service=\"$service\", grpc_method=\"$method_name\"}[$interval])) by (grpc_method,le)\n)",
     "legendFormat": "50%-tile"
    }
   ]
  },
  {
   "title": "$percentile-percentile handling time over methods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(${percentile}, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\", grpc_service=\"$service\"}[$interval])) by (grpc_method,le)\n)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  }
 ]
}