{
 "title": "Camunda Monitoring",
 "description": "Camunda Monitoring exposed by dedicated plugin",
 "tags": [ "camunda" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(camunda_active_incidents, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(camunda_active_incidents{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "engineName",
    "label": "Engine",
    "query": {
     "query": "label_values(camunda_active_incidents{namespace=\"$namespace\", service=\"$app\"}, engineName)"
    }
   },
   {
    "name": "window",
    "label": "Window",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Process Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Process Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_process_instances{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Active Process Instances per window",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(camunda_active_process_instances{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}[$window])",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Completed Process Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_completed_process_instances{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Completed Process Instances per window",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(camunda_completed_process_instances{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}[$window])",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  { "title": "Incidents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Process Incidents",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (processName) (camunda_active_process_incidents{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"} > 0)",
     "legendFormat": "{{ processName }}"
    }
   ]
  },
  {
   "title": "Active Incidents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_incidents{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "camunda_active_incidents"
    }
   ]
  },
  {
   "title": "Active Incidents per window",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(camunda_active_incidents{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}[$window])",
     "legendFormat": "camunda_active_incidents"
    }
   ]
  },
  {
   "title": "Active Incidents by processName per window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 26 },
   "targets": [
    {
     "expr": "sum by (processName)(delta(camunda_active_process_incidents{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}[$window]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Definitions and Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Active Process Definitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_process_definitions{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_deployments{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  { "title": "Timers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Executable Timer Jobs",
   "type": "graph",
   "description": "Timers that are ready to be executed (past due date)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_executable_timer_jobs{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Timer Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_timer_jobs{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  { "title": "User Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Active User Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_user_tasks{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Executable Jobs",
   "type": "graph",
   "description": "Jobs ready to be executed (past due date)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_executable_jobs{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Message Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_message_jobs{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  { "title": "External Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Active External Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_external_tasks{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Active Locked External Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_locked_external_tasks{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Active Not Locked External Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_not_locked_external_tasks{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  { "title": "Event Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Active Message Event Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_message_event_subscriptions{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Active Signal Event Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_signal_event_subscriptions{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Active Compensate Event Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_compensate_event_subscriptions{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Active Conditional Event Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_conditional_event_subscriptions{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "User Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_user_count{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  { "title": "Tenants", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Tenant Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_tenant_count{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  }
 ]
}