{
 "title": "Communication worker",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "span", "query": "5m, 30m, 1h, 2h, 6h, 1d, 3d" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(process_start_time_seconds{service=\"oms-communications-worker\"},namespace)"
    }
   },
   { "name": "worker", "query": "email,sms" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=\"oms-communications-worker\", namespace=\"$namespace\"}[5m]))\n / \n sum(rate(process_cpu_seconds_total{service=\"oms-communications-worker\", namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Comm Brick error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(event_code)(\n    irate(\n        oms_communications_worker_comm_brick_count{service=\"oms-communications-worker\", namespace=\"$namespace\", worker=~\"$worker\", status!~\"200|201\"}[$span]\n    )\n)"
    }
   ]
  },
  {
   "title": "Camunda topik error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(event_code)(\n    irate(\n        oms_communications_worker_camunda_topic_count{service=\"oms-communications-worker\", namespace=\"$namespace\", worker=~\"$worker\", status=\"fail\"}[$span]\n    )\n)"
    }
   ]
  },
  {
   "title": "HTTP API error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(event_code, path)(\n    irate(\n        oms_communications_worker_http_api_count{service=\"oms-communications-worker\", namespace=\"$namespace\", status_code!=\"200|201\"}[$span]\n    )\n)"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{service=\"oms-communications-worker\", namespace=\"$namespace\"}[2m]) * 100"
    }
   ]
  },
  {
   "title": "RSS memoty",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"oms-communications-worker\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Event Loop lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{service=\"oms-communications-worker\", namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (\n    rate(\n        oms_communications_worker_http_api_count{service=\"oms-communications-worker\", namespace=\"$namespace\"}[$span]\n    )\n) by(event_code, path)"
    }
   ]
  },
  {
   "title": "API Request time, p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum(\n        rate(\n            oms_communications_worker_http_api_bucket{service=\"oms-communications-worker\", namespace=\"$namespace\"}[$span]\n        )\n    ) by (event_code, path, le)\n)"
    }
   ]
  },
  {
   "title": "Max average handling time by method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n  rate(oms_communications_worker_http_api_sum{service=\"oms-communications-worker\", namespace=\"$namespace\"}[5m]) /\n  rate(oms_communications_worker_http_api_count{service=\"oms-communications-worker\", namespace=\"$namespace\"}[5m])\n) by (event_code, method, path, status_code)"
    }
   ]
  },
  { "title": "Camunda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Topic processing time, p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum (\n        rate(\n            oms_communications_worker_camunda_topic_bucket{service=\"oms-communications-worker\", namespace=\"$namespace\", worker=~\"$worker\"}[$span]\n        )\n    )  by (event_code, le)\n)"
    }
   ]
  },
  {
   "title": "Topic processing rate, p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    irate(\n        oms_communications_worker_camunda_topic_count{service=\"oms-communications-worker\", namespace=\"$namespace\", worker=~\"$worker\"}[$span]\n    )\n) by (event_code)"
    }
   ]
  },
  { "title": "Comm Brick Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (\n    irate(\n        oms_communications_worker_comm_brick_count{service=\"oms-communications-worker\", namespace=\"$namespace\", worker=~\"$worker\"}[$span]\n    )\n) by(event_code)"
    }
   ]
  },
  {
   "title": "Request time, p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n        rate(\n            oms_communications_worker_comm_brick_bucket{service=\"oms-communications-worker\", namespace=\"$namespace\", worker=~\"$worker\"}[$span]\n        )\n    ) by (event_code, le)\n)"
    }
   ]
  }
 ]
}