{
 "title": "Date recalculation service",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "span", "query": "5m, 30m, 1h, 2h, 6h, 1d, 3d" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", service=\"date-recalculation-service\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=\"mp-operations-date-recalculation-service-metrics\", namespace=\"$namespace\"}[5m]))\n / \n sum(rate(process_cpu_seconds_total{service=\"mp-operations-date-recalculation-service-metrics\", namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{service=\"mp-operations-date-recalculation-service-metrics\", namespace=\"$namespace\"}[2m]) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"mp-operations-date-recalculation-service-metrics\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Event Loop lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{service=\"mp-operations-date-recalculation-service-metrics\", namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "Internal metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Перенос даты отгрузки/доставки отправления",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "increase(data_recalculation_task_failed{namespace=\"$namespace\"}[$span])",
     "legendFormat": "Ошибки переноса"
    },
    {
     "expr": "increase(data_recalculation_task_success{namespace=\"$namespace\"}[$span])",
     "legendFormat": "Успешные переносы"
    }
   ]
  },
  {
   "title": "Процент ошибок",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(data_recalculation_task_failed{namespace=\"$namespace\"}[$span])/rate(data_recalculation_task_total{namespace=\"$namespace\"}[$span])) * 100",
     "legendFormat": "Ошибки переноса"
    }
   ]
  }
 ]
}