{
 "title": "Distribution of orders Emergency mod ATP",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(client_error_total, namespace)"
    }
   },
   { "name": "service", "label": "Service", "query": "atp" },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Percentage of Default responses All Request",
   "type": "timeseries",
   "description": "Процентное соотношение общего количество дефолтных случаев на общее количество запросов к сервису",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum (increase(client_error_total{namespace=\"$namespace\", service=\"$service\"}[5m]))\n/\n    sum (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", uri!~\"$excluded_urls\"}[5m]))\n) * 100",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Percentage of Default responses Client / All Request",
   "type": "timeseries",
   "description": "Процентное соотношение дефолтных случаев по клиенту на общее количество запросов к этому клиенту",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (client_name) (increase(client_error_total{namespace=\"$namespace\", service=\"$service\"}[5m]))\n    / on() group_left()\n    sum (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", uri!~\"$excluded_urls\"}[5m]))\n) * 100",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Default responses",
   "type": "piechart",
   "description": "Количество случаев, в результате которых был вызван дефолтный ответ по клиенту",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(client_error_total{namespace=\"$namespace\", service=\"$service\"}[$__range]) > 0) by (client_name))"
    }
   ]
  },
  {
   "title": "Default responses",
   "type": "timeseries",
   "description": "Количество случаев, в результате которых был вызван дефолтный ответ по клиенту",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by(service, client_name) (delta(client_error_total{namespace=\"$namespace\", service=\"$service\"}[5m])) >= 0",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Total default responses[range]",
   "type": "stat",
   "description": "Общее количество дефолтных ответов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(client_error_total{namespace=\"$namespace\", service=\"$service\"}[$__range]) > 0)"
    }
   ]
  },
  {
   "title": "Total Requests[range]",
   "type": "stat",
   "description": "Общее количество запросов к сервису ATP",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", uri!~\"$excluded_urls\"}[$__range]) > 0)"
    }
   ]
  }
 ]
}