{
 "title": "Kafka Dashboard",
 "description": "Общее доска по сервисам",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(kafka_burrow_partition_lag{namespace=\"infra-monitoring\"}, group)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "query_result(group by (topic) (kafka_burrow_partition_lag{group=~\"$group\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Topic LAG",
   "type": "graph",
   "description": "$group",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_burrow_partition_lag{group=~\"$group\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "MSG/S Rate topic",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_burrow_partition_current_offset{group=~\"$group\",topic=~\"$topic\"}[5m]))"
    }
   ]
  },
  {
   "title": "Partition lag",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (partition,topic) (kafka_burrow_partition_lag{group=~\"$group\",topic=~\"$topic\"})"
    }
   ]
  }
 ]
}