{
 "title": "Logistic Calculator - Delivery Parcels Method",
 "tags": [ "calculator" ],
 "time": { "from": "now-6h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(grpc_server_handled_total{grpc_service=\"mp.operations.logisticcalculator.v1.CalculationService\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "99% percentile of handling time with 10m window",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\", grpc_service=\"mp.operations.logisticcalculator.v1.CalculationService\", grpc_method=\"DeliveryParcels\", namespace=~\"$namespace\"}[10m])) by (le)\n)"
    }
   ]
  },
  {
   "title": "Max average handling time with 10m window",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(rate(grpc_server_handling_seconds_sum{grpc_type=\"unary\", grpc_method=\"DeliveryParcels\", grpc_service=\"mp.operations.logisticcalculator.v1.CalculationService\", namespace=~\"$namespace\"}[10m]) / rate(grpc_server_handling_seconds_count{grpc_type=\"unary\", grpc_method=\"DeliveryParcels\", grpc_service=\"mp.operations.logisticcalculator.v1.CalculationService\", namespace=~\"$namespace\"}[10m])) by (grpc_method) * 1000",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC responses rate by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\", grpc_service=\"mp.operations.logisticcalculator.v1.CalculationService\",grpc_method=\"DeliveryParcels\", namespace=~\"$namespace\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  { "title": "Errors graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "gRPC errors percentage by code for last 10m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\", grpc_service=\"mp.operations.logisticcalculator.v1.CalculationService\",grpc_method=\"DeliveryParcels\", grpc_code=\"DeadlineExceeded\", namespace=~\"$namespace\"}[10m])) / sum(rate(grpc_server_handled_total{grpc_type=\"unary\", grpc_service=\"mp.operations.logisticcalculator.v1.CalculationService\",grpc_method=\"DeliveryParcels\", grpc_code=\"OK\", namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "Deadline Exceeded"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\", grpc_service=\"mp.operations.logisticcalculator.v1.CalculationService\",grpc_method=\"DeliveryParcels\", grpc_code=\"Unavailable\", namespace=~\"$namespace\"}[10m])) / sum(rate(grpc_server_handled_total{grpc_type=\"unary\", grpc_service=\"mp.operations.logisticcalculator.v1.CalculationService\",grpc_method=\"DeliveryParcels\", namespace=~\"$namespace\", grpc_code=\"OK\"}[10m]))",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Parcels error percentage for last 10m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(deliveryParcelsErrorsCounter{namespace=~\"$namespace\"}[10m])) / sum(rate(calculator_handled_delivery_parcels_total{namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "Parcel error percentage"
    },
    {
     "expr": "sum(rate(calculator_handled_delivery_parcels_total{namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "Handled parcels rate"
    }
   ]
  },
  {
   "title": "Parcels default price percentage for last 10m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(deliveryParcelsDefaultPriceCounter{namespace=~\"$namespace\"}[10m])) / sum(rate(calculator_handled_delivery_parcels_total{namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "Parcel default price percentage"
    },
    {
     "expr": "sum(rate(calculator_handled_delivery_parcels_total{namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "Handled parcels rate"
    }
   ]
  },
  {
   "title": "Errors count by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(deliveryParcelsErrorsCounter{namespace=~\"$namespace\"}) by(errorCode)",
     "legendFormat": "Code: {{errorCode}}"
    }
   ]
  },
  {
   "title": "default price increase counts by consumer geo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(consumerGeoId, merchantId)(increase(deliveryParcelsDefaultPriceCounter{namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "Geo: {{consumerGeoId}} Merchant: {{merchantId}}"
    }
   ]
  },
  {
   "title": "default price increase counts by consumer geo and delivery type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(consumerGeoId, deliveryType)(increase(deliveryParcelsDefaultPriceCounter{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Geo: {{consumerGeoId}} {{deliveryType}}"
    }
   ]
  },
  {
   "title": "default price increase counts by merchant Id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(merchantId)(increase(deliveryParcelsDefaultPriceCounter{namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "Merchant ID: {{merchantId}}"
    }
   ]
  },
  {
   "title": "error counts increase by merchant and geo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(merchantId, consumerGeoId)(increase(deliveryParcelsErrorsCounter{namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "Merchant: {{merchantId}} Geo: {{consumerGeoId}} "
    }
   ]
  },
  {
   "title": "error counts increase by merchant Id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(merchantId)(increase(deliveryParcelsErrorsCounter{namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "Merchant ID: {{merchantId}}"
    }
   ]
  },
  {
   "title": "error counts increase by consumer geo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deliveryParcelsErrorsCounter{namespace=~\"$namespace\"}[$interval]))by(consumerGeoId)",
     "legendFormat": "Geo: {{consumerGeoId}}"
    }
   ]
  },
  {
   "title": " not supported delivery settings error counts by merchant and geo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(merchantId, consumerGeoId)(increase(deliveryParcelsErrorsCounter{errorMessage=\"Not supported delivery settings\", namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "Merchant: {{merchantId}} Geo: {{consumerGeoId}} "
    }
   ]
  },
  {
   "title": "error counts increase by error message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(errorMessage)(increase(deliveryParcelsErrorsCounter{namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "{{errorMessage}}"
    }
   ]
  },
  {
   "title": "Moscow error counts increase by error message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(errorMessage)(increase(deliveryParcelsErrorsCounter{consumerGeoId=\"1252472\", namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "{{errorMessage}}"
    }
   ]
  },
  {
   "title": "Saint-Petersburg error counts increase by error message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(errorMessage)(increase(deliveryParcelsErrorsCounter{consumerGeoId=\"1263287\", namespace=~\"$namespace\"}[$interval]))",
     "legendFormat": "{{errorMessage}}"
    }
   ]
  },
  {
   "title": "Errors bars",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top of default price counts by merchant and geo",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "topk(3, sum by(merchantId, consumerGeoId)(deliveryParcelsDefaultPriceCounter))",
       "legendFormat": "Merchant: {{merchantId}} Geo: {{consumerGeoId}} "
      }
     ]
    },
    {
     "title": "Top of default price counts by consumer geo and delivery type",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 7, "x": 10, "y": 28 },
     "targets": [
      {
       "expr": "topk(3, sum by(consumerGeoId, deliveryType)(deliveryParcelsDefaultPriceCounter))",
       "legendFormat": "Geo: {{consumerGeoId}} {{deliveryType}}"
      }
     ]
    },
    {
     "title": "Top of default price counts by merchant Id",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 28 },
     "targets": [
      {
       "expr": "topk(3, sum by(merchantId)(deliveryParcelsDefaultPriceCounter))",
       "legendFormat": "Merchant ID: {{merchantId}}"
      }
     ]
    },
    {
     "title": "Top of error counts by merchant and geo",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "topk(3, sum by(merchantId, consumerGeoId)(deliveryParcelsErrorsCounter))",
       "legendFormat": "Merchant: {{merchantId}} Geo: {{consumerGeoId}} "
      }
     ]
    },
    {
     "title": "Top of error counts by consumer geo",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 38 },
     "targets": [
      {
       "expr": "topk(3, sum by(consumerGeoId)(deliveryParcelsErrorsCounter))",
       "legendFormat": "Geo: {{consumerGeoId}}"
      }
     ]
    },
    {
     "title": "Top of error counts by merchant Id",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 38 },
     "targets": [
      {
       "expr": "topk(3, sum by(merchantId)(deliveryParcelsErrorsCounter))",
       "legendFormat": "Merchant ID: {{merchantId}}"
      }
     ]
    },
    {
     "title": "Top 10 errors count by error code",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "topk(10, sum by(errorCode)(deliveryParcelsErrorsCounter))",
       "legendFormat": "Error code: {{errorCode}}"
      }
     ]
    },
    {
     "title": "Top 10 error counts by error message",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 46 },
     "targets": [
      {
       "expr": "topk(10, sum by(errorMessage)(deliveryParcelsErrorsCounter))",
       "legendFormat": "{{errorMessage}}"
      }
     ]
    },
    {
     "title": "Top of not supported delivery settings error counts by merchant and geo",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "topk(3, sum by(merchantId, consumerGeoId)(deliveryParcelsErrorsCounter{errorMessage=\"Not supported delivery settings\"}))",
       "legendFormat": "Merchant: {{merchantId}} Geo: {{consumerGeoId}} "
      }
     ]
    }
   ]
  }
 ]
}