{
 "title": "Merchant Orders",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "span",
    "query": "2m, 5m, 30m, 1h, 2h, 6h, 1d, 3d"
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Up Status By Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "camunda",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/mo-camunda\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "gui-legacy",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/gui-legacy\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "storage-service",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/storage-service\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "camunda-workers",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/camunda-workers\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "file-generator",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/file-generator\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "gui-backend-legacy",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/gui-backend-legacy\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "camunda-api",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/camunda-api\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "public-api",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/public-api\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "file-manager",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/file-manager\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "mks",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/mks\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Camunda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Current External Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "camunda_active_external_tasks{namespace=\"$namespace\", service=\"camunda-monitoring\", engineName=\"default\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Responses %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"mo-camunda\"}[$span]), \"status_group\", \"${1}xx\", \"status\", \"([0-9])..\")) by (status_group)\n  / scalar(sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"mo-camunda\"}[$span]))) > 0",
     "legendFormat": "{{ status_group }}"
    }
   ]
  },
  {
   "title": "Active Process Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camunda_active_process_instances{namespace=\"$namespace\", service=\"camunda-monitoring\", engineName=\"default\"}",
     "legendFormat": "Key: {{process_definition_key}}"
    }
   ]
  },
  {
   "title": "Current Incidents Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (processName) (camunda_active_process_incidents{namespace=\"$namespace\", service=\"camunda-monitoring\", engineName=\"default\"} > 0)",
     "legendFormat": "{{activity_name}}"
    }
   ]
  },
  { "title": "GUI Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    grpc_server_handled_total{service=\"gui-backend-legacy\",grpc_type=\"unary\", namespace=~\"$namespace\"}[$span]\r\n  )\r\n) by (grpc_service, grpc_code)",
     "legendFormat": "{{grpc_service}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95,\r\n    sum(\r\n        rate(\r\n            grpc_server_handling_seconds_bucket{service=\"gui-backend-legacy\", grpc_type=\"unary\", namespace=~\"$namespace\"}[$span]\r\n        )\r\n    ) by (grpc_service, grpc_method, le)\r\n)",
     "legendFormat": "{{grpc_service}} {{grpc_method}}"
    }
   ]
  },
  { "title": "Public API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\",  namespace=~\"$namespace\", service=\"public-api\"}[$span]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\",  namespace=~\"$namespace\", service=\"public-api\"}[$span])) by (ingress, service, service_port) > 0",
     "legendFormat": "$legend_format"
    }
   ]
  },
  {
   "title": "Responses %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"public-api\"}[$span]), \"status_group\", \"${1}xx\", \"status\", \"([0-9])..\")) by (status_group)\n  / scalar(sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"public-api\"}[$span]))) > 0",
     "legendFormat": "{{ status_group }}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\",  namespace=~\"$namespace\", service=\"public-api\", status=~\"5..\"}[$span]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"public-api\", status=~\"5..\"}[$span])) by (ingress, service, service_port) > 0",
     "legendFormat": "$legend_format"
    }
   ]
  },
  { "title": "Camunda API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\",  namespace=~\"$namespace\", service=\"camunda-api\"}[$span]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\",  namespace=~\"$namespace\", service=\"camunda-api\"}[$span])) by (ingress, service, service_port) > 0",
     "legendFormat": "$legend_format"
    }
   ]
  },
  {
   "title": "Responses %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"camunda-api\"}[$span]), \"status_group\", \"${1}xx\", \"status\", \"([0-9])..\")) by (status_group)\n  / scalar(sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"camunda-api\"}[$span]))) > 0",
     "legendFormat": "{{ status_group }}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"camunda-api\", status=~\"5..\"}[$span]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"camunda-api\", status=~\"5..\"}[$span])) by (ingress, service, service_port) > 0",
     "legendFormat": "$legend_format"
    }
   ]
  },
  { "title": "Storage Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"storage-service\"}[$span]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"storage-service\"}[$span])) by (ingress, service, service_port) > 0",
     "legendFormat": "$legend_format"
    }
   ]
  },
  {
   "title": "Responses %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"storage-service\"}[$span]), \"status_group\", \"${1}xx\", \"status\", \"([0-9])..\")) by (status_group)\n  / scalar(sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"storage-service\"}[$span]))) > 0",
     "legendFormat": "{{ status_group }}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\",  namespace=~\"$namespace\", service=\"storage-service\", status=~\"5..\"}[$span]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"storage-service\", status=~\"5..\"}[$span])) by (ingress, service, service_port) > 0",
     "legendFormat": "$legend_format"
    }
   ]
  },
  { "title": "File Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\",  service=\"file-manager\"}[$span]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress=~\".*\", service=\"file-manager\"}[$span])) by (ingress, service, service_port) > 0",
     "legendFormat": "$legend_format"
    }
   ]
  },
  {
   "title": "Responses %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"file-manager\"}[$span]), \"status_group\", \"${1}xx\", \"status\", \"([0-9])..\")) by (status_group)\n  / scalar(sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"file-manager\"}[$span]))) > 0",
     "legendFormat": "{{ status_group }}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\",  namespace=~\"$namespace\", service=\"file-manager\", status=~\"5..\"}[$span]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", service=\"file-manager\", status=~\"5..\"}[$span])) by (ingress, service, service_port) > 0",
     "legendFormat": "$legend_format"
    }
   ]
  },
  {
   "title": "Acceptance Report",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(acceptance_report_returned_counter{service=\"file-manager\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Barcode Sticker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(barcode_sticker_returned_counter{service=\"file-manager\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Acceptance Report Barcode Stickers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(acceptance_report_barcode_stickers_returned_counter{service=\"file-manager\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Product List",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(product_list_returned_counter{service=\"file-manager\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Selected Product List",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(selected_product_list_returned_counter{service=\"file-manager\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Selected Barcode Stickers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(selected_barcode_stickers_returned_counter{service=\"file-manager\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Selected Acceptance Reports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(selected_acceptance_report_returned_counter{service=\"file-manager\", namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "MKS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Kafka Reader Result",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_reader_message_success{service=~\"mks\", namespace=~\"$namespace\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(kafka_reader_message_failed{service=~\"mks\", namespace=~\"$namespace\"})",
     "legendFormat": "failed"
    }
   ]
  },
  { "title": "File Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Success Generations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (document_type)(success_generation{service=\"file-generator\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Generations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (document_type)(failed_generation{service=\"file-generator\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Acceptance Report",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "success_generation{service=~\"file-generator\", namespace=~\"$namespace\", document_type=\"acceptanceReport\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Barcode Sticker",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "success_generation{service=~\"file-generator\", namespace=~\"$namespace\", document_type=\"barcodeSticker\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Acceptance Report Barcode Stickers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "success_generation{service=~\"file-generator\", namespace=~\"$namespace\", document_type=\"acceptanceReportBarcodeStickers\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Product List",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "success_generation{service=~\"file-generator\", namespace=~\"$namespace\", document_type=\"productList\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Selected Product List",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "success_generation{service=~\"file-generator\", namespace=~\"$namespace\", document_type=\"selectedProductLists\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Selected Barcode Stickers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "success_generation{service=~\"file-generator\", namespace=~\"$namespace\", document_type=\"selectedBarcodeStickers\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Selected Acceptance Reports",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "success_generation{service=~\"file-generator\", namespace=~\"$namespace\", document_type=\"selectedAcceptanceReports\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P95 Generation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(generation_duration_bucket{service=~\"file-generator\", namespace=~\"$namespace\"}[$span])) by (le, document_type))",
     "legendFormat": "{{document_type}}"
    }
   ]
  },
  {
   "title": "P50 Generation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(generation_duration_bucket{service=~\"file-generator\", namespace=~\"$namespace\"}[$span])) by (le, document_type))",
     "legendFormat": "{{document_type}}"
    }
   ]
  }
 ]
}