{
 "title": "Promise calculator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(adapter_timestamp_delta_accessibility_seconds_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Время от поступления данных поставщиков до расчета Accessibility в PC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (taskType) (irate(external_timestamp_delta_accessibility_seconds_sum{namespace=\"$namespace\", service=\"pcalc-holder\"}[1m])) / sum by (taskType) (irate(external_timestamp_delta_accessibility_seconds_count{namespace=\"$namespace\", service=\"pcalc-holder\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время от обработки данных поставщиков до расчета Accessibility в PC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (taskType) (irate(adapter_timestamp_delta_accessibility_seconds_sum{namespace=\"$namespace\", service=\"pcalc-holder\"}[1m])) / sum by (taskType) (irate(adapter_timestamp_delta_accessibility_seconds_count{namespace=\"$namespace\", service=\"pcalc-holder\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время от поступления данных поставщиков до расчета Lead Time в PC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (taskType) (irate(external_timestamp_delta_lead_time_seconds_sum{namespace=\"$namespace\", service=\"pcalc-holder\"}[1m])) / sum by (taskType) (irate(external_timestamp_delta_lead_time_seconds_count{namespace=\"$namespace\", service=\"pcalc-holder\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время от обработки данных поставщиков до расчета Lead Time в PC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (taskType) (irate(adapter_timestamp_delta_lead_time_seconds_sum{namespace=\"$namespace\", service=\"pcalc-holder\"}[1m])) / sum by (taskType) (irate(adapter_timestamp_delta_lead_time_seconds_count{namespace=\"$namespace\", service=\"pcalc-holder\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время от поступления данных поставщиков до расчета Seller Stock в PC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (taskType) (irate(external_timestamp_delta_seller_stock_seconds_sum{namespace=\"$namespace\", service=\"pcalc-stock\"}[1m])) / sum by (taskType) (irate(external_timestamp_delta_seller_stock_seconds_count{namespace=\"$namespace\", service=\"pcalc-stock\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время от обработки данных поставщиков до расчета Seller Stock PC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (taskType) (irate(adapter_timestamp_delta_seller_stock_seconds_sum{namespace=\"$namespace\", service=\"pcalc-stock\"}[1m])) / sum by (taskType) (irate(adapter_timestamp_delta_seller_stock_seconds_count{namespace=\"$namespace\", service=\"pcalc-stock\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}