{
 "title": "rom integrations",
 "time": { "from": "2025-02-27T21:19:49.895Z", "to": "2025-02-27T23:39:01.895Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(process_start_time_seconds{service=\"rms-import-service\"},namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kafka_total_messages_count{namespace=\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "increase(kafka_total_messages_count {namespace=\"$namespace\", service=\"$service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "increase(kafka_failed_message_count {namespace=\"$namespace\", service=\"$service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{namespace=\"$namespace\", service=\"$service\"}[1m]) / 60",
     "legendFormat": "full cpu"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}