{
 "title": "Services Platform APIs",
 "tags": [
  "spring",
  "prometheus",
  "api"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=\"$application\"}, namespace)"
    }
   },
   { "name": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "method",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{ namespace=\"$namespace\", application=\"$application\"}, method)"
    }
   },
   {
    "name": "uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{ namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"/v[0|1]/.*\"}, uri)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Microservice Inputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statuses Percentage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{ namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"}[$__rate_interval])) by (status)",
     "legendFormat": "status {{status}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Client Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\", outcome=\"CLIENT_ERROR\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Server Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\", outcome=\"SERVER_ERROR\"}[$__range]))"
    }
   ]
  },
  {
   "title": "RPS by uri",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri =~ \"$uri\"}[$__rate_interval])) by (method, uri)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency by uri",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", namespace=\"$namespace\", method=~\"$method\", uri =~ \"$uri\"}[$__rate_interval])) by (method,uri) / sum(rate(http_server_requests_seconds_count{application=\"$application\", namespace=\"$namespace\", method=~\"$method\", uri =~ \"$uri\"}[$__rate_interval])) by (method,uri)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  { "title": "Microservice Outputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Statuses Percentage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{application=\"$application\", namespace=\"$namespace\", method=~\"$method\", uri=~\"$uri\"}[$__rate_interval])) by (status)",
     "legendFormat": "status {{status}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", uri=~\"$uri\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Server Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", uri=~\"$uri\", outcome=\"SERVER_ERROR\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Client Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", uri=~\"$uri\", outcome=\"CLIENT_ERROR\"}[$__range]))"
    }
   ]
  },
  {
   "title": "RPS by uri",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{ namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri =~ \"$uri\"}[$__rate_interval])) by (method, uri)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency by uri",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{application=\"$application\",  namespace=\"$namespace\", uri =~ \"$uri\"}[$__rate_interval])) by (method,uri) / sum(rate(http_client_requests_seconds_count{application=\"$application\",  namespace=\"$namespace\", uri =~ \"$uri\"}[$__rate_interval])) by (method,uri)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}