{
 "title": "Camunda-pdm",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Env",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, namespace)"
    }
   },
   { "name": "processId", "label": "Process", "query": { "query": "label_values(processId)" } },
   {
    "name": "taskId",
    "label": "Task",
    "query": {
     "query": "label_values(camunda_activity_seconds_count{namespace=\"$namespace\",  processId=\"$processId\"}, activityId)"
    }
   },
   {
    "name": "endEvent",
    "label": "End event",
    "query": {
     "query": "label_values(camunda_process_seconds_count{processId=~\"$processId\"}, endActivityId)"
    }
   },
   { "name": "derivativeGap", "label": "Derivative time interval", "query": "1m,2m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Completed processes count [$derivativeGap]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (processId, endActivityId) (increase(camunda_process_seconds_count{namespace=\"$namespace\", processId=~\"$processId\"}[$derivativeGap]))",
     "legendFormat": "{{endActivityId}}"
    }
   ]
  },
  {
   "title": "Process execution time [$derivativeGap]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (processId, endActivityId) (irate(camunda_process_seconds_sum{namespace=\"$namespace\", processId=~\"$processId\"}[$derivativeGap])) / sum by (processId, endActivityId) (irate(camunda_process_seconds_count{namespace=\"$namespace\", processId=~\"$processId\"}[$derivativeGap]))",
     "legendFormat": "{{endActivityId}}"
    }
   ]
  },
  {
   "title": "Process duration distribution - $endEvent",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "repeat": "endEvent",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(camunda_process_seconds_bucket{namespace=\"$namespace\", processId=~\"$processId\", endActivityId=~\"$endEvent\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Process end events",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (processId, endActivityId) (increase(camunda_process_seconds_count{namespace=\"$namespace\", processId=~\"$processId\"}[$__range]))",
     "legendFormat": "{{endActivityId}}"
    }
   ]
  },
  {
   "title": "PTM_B2C Fiscalization time [$derivativeGap] ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(camunda_activity_time_between_seconds_sum{namespace=\"$namespace\",endActivity=\"sendReceiptRegistrationSuccess\",startActivity=\"registerReceipt\"}[$derivativeGap]) / irate(camunda_activity_time_between_seconds_count{namespace=\"$namespace\",endActivity=\"sendReceiptRegistrationSuccess\",startActivity=\"registerReceipt\"}[$derivativeGap])",
     "legendFormat": "Fiscalization time (s)"
    }
   ]
  },
  {
   "title": "PTM_B2C Fiscalization time distribution",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(camunda_activity_time_between_seconds_bucket{endActivity=\"sendReceiptRegistrationSuccess\",startActivity=\"registerReceipt\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Incidents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Incidents count [$derivativeGap]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (activityId) (increase(camunda_incident_created_total{namespace=\"$namespace\", processId=~\"$processId\"}[$derivativeGap]))",
     "legendFormat": "{{activityId}}"
    }
   ]
  },
  {
   "title": "Incident types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (processId, activityId) (increase(camunda_incident_created_total{namespace=\"$namespace\", processId=~\"$processId\"}[$__range]))",
     "legendFormat": "{{activityId}}"
    }
   ]
  },
  { "title": "Task details - $taskId", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }, "repeat": "taskId" },
  {
   "title": "Task execution time [$derivativeGap]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (activityId) (irate(camunda_activity_seconds_sum{namespace=\"$namespace\", processId=~\"$processId\", activityId=~\"$taskId\"}[$derivativeGap])) / sum by (activityId) (irate(camunda_activity_seconds_count{namespace=\"$namespace\", processId=~\"$processId\", activityId=~\"$taskId\"}[$derivativeGap]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task execution time distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(camunda_activity_seconds_bucket{namespace=\"$namespace\", processId=~\"$processId\", activityId=\"$taskId\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time since process execution start [$derivativeGap]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (activityId) (irate(camunda_process_till_activity_seconds_sum{namespace=\"$namespace\", processId=~\"$processId\", activityId=~\"$taskId\"}[$derivativeGap])) / sum by (activityId) (irate(camunda_process_till_activity_seconds_count{namespace=\"$namespace\", processId=~\"$processId\", activityId=~\"$taskId\"}[$derivativeGap]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time since process execution start distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(camunda_process_till_activity_seconds_bucket{namespace=\"$namespace\", processId=~\"$processId\", activityId=\"$taskId\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}