{
 "title": "High level Sloth SLOs",
 "description": "A high level view of all Sloth SLOs",
 "tags": [
  "service levels",
  "sli",
  "slo",
  "sloth"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "min_burning_rate", "label": "Min Burning rate", "query": "1" },
   {
    "name": "domain",
    "query": {
     "query": "label_values(slo:objective:ratio, domain)"
    }
   },
   {
    "name": "product",
    "query": {
     "query": "label_values(slo:objective:ratio{domain=\"$domain\"}, product)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(slo:objective:ratio{domain=\"$domain\", product=~\"$product\"}, sloth_service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(sloth_slo_info{product=~'$product'}) by (sloth_service))",
     "legendFormat": "Services"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sloth_slo_info{product=~'$product',sloth_slo!~'ingress.*'})",
     "legendFormat": "SLOs"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sloth_slo_info{product=~'$product', sloth_slo=~\"ingress.*\"})",
     "legendFormat": "SLOs ingress"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(slo:current_burn_rate:ratio{product=~'$product'})",
     "legendFormat": "Avg burn rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{sloth_id!=\"\",sloth_severity=\"ticket\",product=~'$product'}) OR on() vector(0)",
     "legendFormat": "Warning alerts"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{sloth_id!=\"\",sloth_severity=\"page\",product=~'$product'}) OR on() vector(0)",
     "legendFormat": "Critical alerts"
    }
   ]
  },
  { "title": "Problem detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Warning alerts",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(product,alertname,sloth_service)(ALERTS{sloth_id!=\"\",sloth_severity=\"ticket\",product=~'$product'})",
     "legendFormat": "Critical alerts"
    }
   ]
  },
  {
   "title": "Critical alerts",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(product,alertname,sloth_service)(ALERTS{sloth_id!=\"\",sloth_severity=\"page\",product=~'$product'})",
     "legendFormat": "Critical alerts"
    }
   ]
  },
  {
   "title": "Current exceeded burning rate SLOs ",
   "type": "table",
   "description": "The SLOs that currently are burning more error budget that then available",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{product=~'$product',sloth_service=~'$service'} > ${min_burning_rate}"
    }
   ]
  },
  {
   "title": "SLOs burn rate state timeline for real problem",
   "type": "state-timeline",
   "description": "Shows SLOs  burning rate state  for real problem",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{product=~'$product',sloth_service=~'$service'} > 0",
     "legendFormat": "{{sloth_service}}/{{sloth_slo}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "All burning rate (Filtered >${min_burning_rate}x)",
   "type": "timeseries",
   "description": "The burning rate of the all the Service SLOs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{product=~'$product',sloth_service=~'$service'} > ${min_burning_rate}",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  },
  {
   "title": "SLOs burn rate state timeline",
   "type": "state-timeline",
   "description": "Shows all the SLOs at the same time burning rate state",
   "gridPos": { "h": 19, "w": 15, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{product=~'$product',sloth_service=~'$service'}",
     "legendFormat": "{{sloth_service}}/{{sloth_slo}}"
    }
   ]
  },
  {
   "title": "Budget remaining 30 day window",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:period_error_budget_remaining:ratio{product=~'$product',sloth_service=~'$service'}",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  }
 ]
}