{
 "title": "Spring Cloud Stream (RabbitMQ)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(spring_integration_send_seconds_count, namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(spring_integration_send_seconds_count{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "queue",
    "label": "queue",
    "query": {
     "query": "label_values(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$service\"}, name)"
    }
   },
   { "name": "time_range", "label": "time range", "query": "1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Message Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$service\", name=~\"$queue\"}[$time_range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (irate(spring_integration_send_seconds_sum{namespace=\"$namespace\", service=\"$service\", name =~\"$queue\", result=\"success\"}[$time_range])) /  sum by (name) (irate(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$service\", name=~\"$queue\", result=\"success\"}[$time_range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$service\", name=~\"$queue\", result!=\"success\"}[$time_range]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}