{
 "title": "NiFi Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Queued Items",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nifi_amount_items_queued{service=\"nifi-exporter-external\"}",
     "legendFormat": "{{exported_instance}} ({{component_name}})"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(nifi_amount_threads_active[$__rate_interval])",
     "legendFormat": "{{exported_instance}} ({{component_name}})"
    }
   ]
  },
  { "title": "JVM Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "GC Runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(nifi_jvm_gc_runs [$__rate_interval])",
     "legendFormat": "{{exported_instance}}: {{gc_name}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(nifi_jvm_gc_time[$__rate_interval])",
     "legendFormat": "{{exported_instance}}: {{gc_name}}"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "nifi_jvm_heap_usage * 100", "legendFormat": "{{exported_instance}}" }
   ]
  }
 ]
}