{
 "title": "ClickHouse / Proxy",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(request_duration_seconds, namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(go_info{job=~\"chproxy.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "label_values(request_sum_total{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\"},user)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(host_health{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\"},cluster)"
    }
   },
   {
    "name": "cluster_user",
    "query": {
     "query": "label_values(request_sum_total{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\", cluster=~\"$cluster\"},cluster_user)"
    }
   },
   {
    "name": "cluster_node",
    "label": "Node",
    "query": {
     "query": "label_values(request_sum_total{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\", cluster=~\"$cluster\"},cluster_node)"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_sum_total{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}[$period])) ",
     "legendFormat": "request_sum"
    },
    {
     "expr": "sum(rate(request_success_total{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}[$period])) ",
     "legendFormat": "request_success"
    }
   ]
  },
  {
   "title": "Request duration [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(request_duration_seconds{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}) by (user, quantile)",
     "legendFormat": "{{user}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Status codes [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(status_codes_total{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster=~\"$cluster\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}[$period])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Summary request duration [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "60*sum(rate(request_duration_seconds_sum{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}[$period]) ) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Concurrent queries by users [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  concurrent_queries{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}) \nby (cluster_user)",
     "legendFormat": "cu-{{cluster_user}}"
    },
    {
     "expr": "sum(\n  concurrent_queries{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}) \nby (user)",
     "legendFormat": "u-{{user}}"
    }
   ]
  },
  {
   "title": "Body size rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(request_body_bytes_total{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}[$period]))\n",
     "legendFormat": "request"
    },
    {
     "expr": "sum(rate(response_body_bytes_total{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}[$period]))\n",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": "Limit Excess [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    concurrent_limit_excess_total{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster=~\"$cluster\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}[$period])) \nby (cluster_node)",
     "legendFormat": "{{cluster_node}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Cache hit rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cache_hits_total{user=~\"$user\",cluster=~\"$cluster\",cluster_user=~\"$cluster_user\",job=\"$job\",instance=~\"$instance\"}[$period])) by (cache) / (\n  sum(rate(cache_hits_total{user=~\"$user\",cluster=~\"$cluster\",cluster_user=~\"$cluster_user\",job=\"$job\",instance=~\"$instance\"}[$period])) by (cache) +\n  sum(rate(cache_miss_total{user=~\"$user\",cluster=~\"$cluster\",cluster_user=~\"$cluster_user\",job=\"$job\",instance=~\"$instance\"}[$period])) by (cache)\n)",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cached response duration [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(cached_response_duration_seconds{user=~\"$user\",cluster=~\"$cluster\",cluster_user=~\"$cluster_user\",job=~\"$job\",namespace=~\"$namespace\", instance=~\"$instance\"}) by (cache, quantile)",
     "legendFormat": "{{cache}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Cache size [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cache_size{job=~\"$job\",namespace=~\"$namespace\", instance=~\"$instance\"}) by (cache)",
     "legendFormat": "{{cache}} size"
    }
   ]
  },
  {
   "title": "Cache items [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cache_items{job=~\"$job\",namespace=~\"$namespace\", instance=~\"$instance\"}) by (cache)",
     "legendFormat": "{{cache}} items"
    }
   ]
  },
  {
   "title": "Cluster \"$cluster\" state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "repeat": "cluster"
  },
  {
   "title": "$cluster_node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 45 },
   "repeat": "cluster_node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(host_health{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",cluster=~\"$cluster\",cluster_node=~\"$cluster_node\"})",
     "legendFormat": "{{cluster_node}}"
    }
   ]
  },
  {
   "title": "Cluster \"$cluster\" host distirbution [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster_node)  (increase(request_sum_total{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}[$period]))",
     "legendFormat": "{{cluster_node}}"
    }
   ]
  },
  {
   "title": "Cluster \"$cluster\" concurrent queries by node [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  concurrent_queries{job=~\"$job\",namespace=~\"$namespace\",instance=~\"$instance\",user=~\"$user\",cluster=~\"$cluster\", cluster_user=~\"$cluster_user\",cluster_node=~\"$cluster_node\"}) \nby (cluster_node)",
     "legendFormat": "{{cluster_node}}"
    }
   ]
  }
 ]
}