{
 "title": "Databases",
 "description": "Dashboard for spring boot 2 services. Displays standard spring metrics along with important data from kubernetes.",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(spring_data_repository_invocations_seconds_count, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(spring_data_repository_invocations_seconds_count{namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(spring_data_repository_invocations_seconds_count{namespace=\"$namespace\", container=\"$container\"}, pod)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\"}, pool)"
    }
   },
   {
    "name": "spring_data_repository_name",
    "label": "Spring Repository Name",
    "query": {
     "query": "label_values(spring_data_repository_invocations_seconds_count{namespace=\"$namespace\", container=\"$container\"}, repository)"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Spring Data Repositories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Method Invocation Rate  - $spring_data_repository_name [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "repeat": "spring_data_repository_name",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (method) (irate(spring_data_repository_invocations_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", repository=\"$spring_data_repository_name\"}[$period]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Method Execution Time - $spring_data_repository_name [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "repeat": "spring_data_repository_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method) (irate(spring_data_repository_invocations_seconds_sum{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", repository=\"$spring_data_repository_name\"}[$period])) / sum by (method) (irate(spring_data_repository_invocations_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", repository=\"$spring_data_repository_name\"}[$period]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Method Exception Count [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (repository, method) (increase(spring_data_repository_invocations_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", exception!=\"None\"}[$period]))",
     "legendFormat": "{{ repository }}.{{ method }}"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations Rate [$period]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (command) (irate(mongodb_driver_commands_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\"}[$period]))",
       "legendFormat": "{{ command }}"
      }
     ]
    },
    {
     "title": "Operations Execution Time [$period]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (command) (irate(mongodb_driver_commands_seconds_sum{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\"}[$period])) / sum by (command) (irate(mongodb_driver_commands_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\"}[$period]))",
       "legendFormat": "{{ command }}"
      }
     ]
    },
    {
     "title": "Connections [$period]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (mongodb_driver_pool_size{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\"})-sum (mongodb_driver_pool_checkedout{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\"})",
       "legendFormat": "Idle"
      },
      {
       "expr": "sum (mongodb_driver_pool_checkedout{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum (mongodb_driver_pool_waitqueuesize{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\"})",
       "legendFormat": "Pending"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari Connection Pool - $hikaricp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "repeat": "hikaricp",
   "collapsed": true,
   "panels": [
    {
     "title": "Connections [$period]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_idle{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", pool=~\"$hikaricp\"})",
       "legendFormat": "Idle"
      },
      {
       "expr": "sum(hikaricp_connections_active{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", pool=~\"$hikaricp\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(hikaricp_connections_pending{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", pool=~\"$hikaricp\"})",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Creation Time [$period]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_creation_seconds_sum{namespace=\"$namespace\", container=\"$container\", pool=~\"$hikaricp\"}[$period]) / increase(hikaricp_connections_creation_seconds_count{namespace=\"$namespace\", container=\"$container\", pool=~\"$hikaricp\"}[$period])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Connection Usage Time [$period]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_usage_seconds_sum{namespace=\"$namespace\", container=\"$container\", pool=~\"$hikaricp\"}[$period]) / increase(hikaricp_connections_usage_seconds_count{namespace=\"$namespace\", container=\"$container\", pool=~\"$hikaricp\"}[$period])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Connection Timeouts [$period]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_timeout_total{namespace=\"$namespace\", container=\"$container\", pool=~\"$hikaricp\"}[$period])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Connection Acquire Time [$period]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_acquire_seconds_sum{namespace=\"$namespace\", container=\"$container\", pool=~\"$hikaricp\"}[$period]) / increase(hikaricp_connections_acquire_seconds_count{namespace=\"$namespace\", container=\"$container\", pool=~\"$hikaricp\"}[$period])",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}