{
 "title": "Spring / HTTP / Client",
 "description": "Dashboard for spring boot 2 services. Displays standard spring metrics along with important data from kubernetes.",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_client_requests_seconds_count, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\"}, pod)"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\"}, uri)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\"}[$period])) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Succeed (2xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"SUCCESS\"}[$period])) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Dropped (No response)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"UNKNOWN\"}[$period])) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Client Errors (4xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"CLIENT_ERROR\"}[$period])) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Server Errors (5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"SERVER_ERROR\"}[$period])) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Requests Rate [$period]",
   "type": "timeseries",
   "description": "Including cancelled",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\"}[$period]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Response Time [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", status!=\"CLIENT_ERROR\"}[$period])) / sum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", status!=\"CLIENT_ERROR\"}[$period]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "piechart",
   "description": "Including cancelled",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\"}[$__range]) > 0) by (method, uri)",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Response Statuses",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\"}[$__range]) > 0) by (status))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Correctness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Response Groups [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"SUCCESS\"}[$period])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\"}[$period])) by (service))",
     "legendFormat": "2xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"CLIENT_ERROR\"}[$period])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\"}[$period])) by (service))",
     "legendFormat": "4xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"SERVER_ERROR\"}[$period])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\"}[$period])) by (service))",
     "legendFormat": "5xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"UNKNOWN\"}[$period])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\"}[$period])) by (service))",
     "legendFormat": "None",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Statuses [$period]",
   "type": "timeseries",
   "description": "Including IO_ERROR",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\"}[$period])) by (status) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\"}[$period])) by (service))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Errors by Endpoint",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome!=\"SUCCESS\"}[$__range]) > 0) by (method, uri))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Dropped Responses by (method, path, status) [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by (method, uri, status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"UNKNOWN\"}[$period]))",
     "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
    }
   ]
  },
  {
   "title": "Response Status 4xx by (method, path, status) [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (method, uri, status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"CLIENT_ERROR\"}[$period]))",
     "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
    }
   ]
  },
  {
   "title": "Response Status 5xx by (method, path, status) [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by (method, uri, status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri=~\"$endpoint\", outcome=\"SERVER_ERROR\"}[$period]))",
     "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
    }
   ]
  }
 ]
}