{
 "title": "Spring / HTTP / Server",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{uri!~\"$excluded_urls\"}, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=\"$namespace\", uri!~\"$excluded_urls\"}, container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", uri!~\"$excluded_urls\"}, pod)"
    }
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$period])) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Succeed (2xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"SUCCESS\"}[$period])) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Client Errors (4xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"CLIENT_ERROR\"}[$period])) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Server Errors (5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"SERVER_ERROR\"}[$period])) or vector(0)",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Request Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", container=\"$container\", uri!~\"$excluded_urls\"}[$period]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Response Time [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", container=\"$container\", exception=\"none\", uri!~\"$excluded_urls\"}[$period])) / sum by (method, uri) (irate(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", container=\"$container\", exception=\"none\", uri!~\"$excluded_urls\"}[$period]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Response Status Groups 2xx / 4xx / 5xx [$period]",
   "type": "timeseries",
   "description": "Actually, query works with 'outcome' attribute: [SUCCESS, CLIENT_ERROR, SERVER_ERROR]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"SUCCESS\"}[$period])) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$period])) by (container))",
     "legendFormat": "2xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"CLIENT_ERROR\"}[$period])) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$period])) by (container))",
     "legendFormat": "4xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"SERVER_ERROR\"}[$period])) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$period])) by (container))",
     "legendFormat": "5xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Statuses [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$period])) by (status) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$period])) by (container))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Status 4xx by (method, path, status) [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri, status) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", outcome=\"CLIENT_ERROR\", uri!~\"$excluded_urls\"}[$period]))",
     "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
    }
   ]
  },
  {
   "title": "Response Status 5xx by (method, path, status) [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri, status) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", outcome=\"SERVER_ERROR\", uri!~\"$excluded_urls\"}[$period]))",
     "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
    }
   ]
  },
  {
   "title": "Response Status Error % by (method, path) [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", uri!~\"$excluded_urls\", outcome!=\"SUCCESS\"}[$period])) by (method, uri) / (sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", uri!~\"$excluded_urls\"}[$period])) by (method, uri) > 0)",
     "legendFormat": "{{ method }} {{ uri }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Exceptions [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!=\"none\"}[$period])) by (exception)",
     "legendFormat": "{{ exception }}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$__range]) > 0) by (method, uri))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Response Statuses",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$__range]) > 0) by (status))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Exceptions by endpoint",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!=\"none\"}[$__range]) > 0) by (method, uri))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Exception Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!=\"none\"}[$__range]) > 0) by (exception))",
     "legendFormat": "{{ exception }}"
    }
   ]
  }
 ]
}