{
 "title": "Spring Cloud Kafka / Producer",
 "description": "spring-kafka metrics",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_producer_topic_record_send_rate, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kafka_producer_topic_record_send_rate{namespace=~\"$namespace\"}, container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kafka_producer_topic_record_send_rate{namespace=~\"$namespace\",container=~\"$container\"}, pod)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_producer_topic_record_send_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"}, topic)"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Message Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Send Messages Rate  [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_topic_record_send_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", topic=~\"$topic\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Send Errors Rate  [$period]",
   "type": "timeseries",
   "description": "The average per-second number of record sends that resulted in errors for a topic ",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_topic_record_error_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", topic=~\"$topic\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Topic Byte Rate  [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_topic_byte_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", topic=~\"$topic\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Send Retries Rate  [$period]",
   "type": "timeseries",
   "description": "The average per-second number of retried record sends for a topic ",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_topic_record_retry_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", topic=~\"$topic\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  { "title": "Global Connection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Active Connections [$period]",
   "type": "timeseries",
   "description": "The current number of active connections. ",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_connection_count{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Created Connections [$period]",
   "type": "timeseries",
   "description": "The total number of new connections established ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_connection_creation_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Closed Connections [$period]",
   "type": "timeseries",
   "description": "The total number of connections closed ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_connection_close_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "IO ratio [$period]",
   "type": "timeseries",
   "description": "The fraction of time the I/O thread spent doing I/O ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_io_ratio{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "IO Wait Ratio [$period]",
   "type": "timeseries",
   "description": "The fraction of time the I/O thread spent waiting ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_io_wait_ratio{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "IO Time [$period]",
   "type": "timeseries",
   "description": "The average length of time for I/O per select call in nanoseconds. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_io_time_ns_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "IO Wait Time [$period]",
   "type": "timeseries",
   "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_io_wait_time_ns_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  { "title": "Broker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Incoming Bytes Rate [$period]",
   "type": "timeseries",
   "description": "The number of bytes read off all sockets per second ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_incoming_byte_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing Bytes Rate [$period]",
   "type": "timeseries",
   "description": "The number of outgoing bytes sent to all servers per second ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_outgoing_byte_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Node Request Rate [$period]",
   "type": "timeseries",
   "description": "The number of requests sent per second ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic, node_id) (\n  label_replace(\n    kafka_producer_node_request_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}} | {{node_id}}"
    }
   ]
  },
  {
   "title": "Request Size [$period]",
   "type": "timeseries",
   "description": "The average size of requests sent. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_request_size_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Request Rate [$period]",
   "type": "timeseries",
   "description": "The number of requests sent per second ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_request_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Response Rate [$period]",
   "type": "timeseries",
   "description": "The number of responses received per second ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_response_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Select Rate [$period]",
   "type": "timeseries",
   "description": "The number of times the I/O layer checked for new I/O to perform per second ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_select_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  { "title": "Batch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Average Batch Size [$period]",
   "type": "timeseries",
   "description": "The average number of bytes sent per partition per-request. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_batch_size_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Max Batch Size [$period]",
   "type": "timeseries",
   "description": "The max number of bytes sent per partition per-request. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_batch_size_max{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Batch Split Rate [$period]",
   "type": "timeseries",
   "description": "The average number of batch splits per second ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_batch_split_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Flush Time [$period]",
   "type": "timeseries",
   "description": "Total time producer has spent in flush in nanoseconds. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    increase(kafka_producer_flush_time_ns_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"}[$period]),\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Average Record Queue Time [$period]",
   "type": "timeseries",
   "description": "The average time in ms record batches spent in the send buffer. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_record_queue_time_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  { "title": "Buffer metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Available Buffer Bytes [$period]",
   "type": "timeseries",
   "description": "The total amount of buffer memory that is not being used (either unallocated or in the free list). ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_buffer_available_bytes{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Buffer Total Bytes [$period]",
   "type": "timeseries",
   "description": "The maximum amount of buffer memory the client can use (whether or not it is currently used). ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_buffer_total_bytes{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Buffer Exhausted Rate [$period]",
   "type": "timeseries",
   "description": "The average per-second number of record sends that are dropped due to buffer exhaustion ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_buffer_exhausted_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Bufferpool Wait Time [$period]",
   "type": "timeseries",
   "description": "The total time in nanoseconds an appender waits for space allocation. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    increase(kafka_producer_bufferpool_wait_time_ns_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"}[$period]),\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Bufferpool Wait Ratio [$period]",
   "type": "timeseries",
   "description": "The fraction of time an appender waits for space allocation. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\n  label_replace(\n    kafka_producer_bufferpool_wait_ratio{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.producer..*\"},\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.producer\\\\..+\"\n  )\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  }
 ]
}