{
 "title": "Spring Cloud Kafka / Consumer",
 "description": "spring-kafka metrics",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_lead, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_lead{namespace=~\"$namespace\"}, container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_lead{namespace=~\"$namespace\",container=~\"$container\"}, pod)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_lead{namespace=~\"$namespace\",container=~\"$container\",pod=~\"$pod\"}, topic)"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Commit Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_commit_latency_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"} > 0)"
    }
   ]
  },
  {
   "title": "Total Lag ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_commit_latency_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"})"
    }
   ]
  },
  {
   "title": "Commit Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_commit_rate{namespace=~\"$namespace\", container=~\"$container\", spring_id=~\"$topic.consumer..*\"})"
    }
   ]
  },
  {
   "title": "Join Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_join_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"})"
    }
   ]
  },
  { "title": "Fetch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Consumption Lag [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (kafka_consumer_fetch_manager_records_lag{ namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", topic=~\"$topic\"})",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Consumed Bytes Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (irate(kafka_consumer_fetch_manager_bytes_consumed_rate{ namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", topic=~\"$topic\"}[$period]))",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Latency [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_fetch_manager_fetch_latency_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Throttle [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_fetch_manager_fetch_throttle_time_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_fetch_manager_fetch_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Messages per Request [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (kafka_consumer_fetch_manager_records_per_request_avg{ namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", topic=~\"$topic\"})",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Records Lead [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (kafka_consumer_fetch_manager_records_lead{ namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", topic=~\"$topic\"})",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  { "title": "Consumer Group Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Assigned Partitions Per Instance [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_assigned_partitions{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Commit Latency [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_commit_latency_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Commit Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_commit_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Join Time [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_join_time_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)\r\n",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Join Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_join_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Last Heartbeat Ago [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_last_heartbeat_seconds_ago{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Heartbeat Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_heartbeat_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Sync Time [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_sync_time_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Sync Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_sync_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Last Rebalance Ago [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_last_rebalance_seconds_ago{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Rebalance Latency [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_rebalance_latency_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Rebalance Total [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_rebalance_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Rebalance Failed [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_failed_rebalance_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)\r\n",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Rebalance Rate per Hour [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ops/h" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_rebalance_rate_per_hour{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Coordinator Failed Rebalance Rate per Hour [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ops/h" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_failed_rebalance_rate_per_hour{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Partition Assigned Latency [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_partition_assigned_latency_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Partition Revoked Latency [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_coordinator_partition_revoked_latency_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  { "title": "Global Connection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "Created Connections [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_connection_creation_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Closed Connections [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_connection_close_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "IO Ratio [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_io_ratio{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "IO Wait Ratio [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_io_wait_ratio{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "IO Time [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_io_time_ns_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "IO Wait Time [$period]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_io_wait_time_ns_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Select Rate [$period]",
   "type": "timeseries",
   "description": "Number of times the I/O layer checked for new I/O to perform per second.\n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_select_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  { "title": "Per-Broker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  {
   "title": "Incoming Bytes Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_incoming_byte_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing Bytes Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_outgoing_byte_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Node Request Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_node_request_rate{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Request Size [$period]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_request_size_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  { "title": "Poll metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 } },
  {
   "title": "Time Between Poll [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "min by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_time_between_poll_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Last Poll Ago [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_last_poll_seconds_ago{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Poll Idle Time [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (container, topic) (\r\n  label_replace(\r\n    kafka_consumer_poll_idle_ratio_avg{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", spring_id=~\"$topic.consumer..*\"},\r\n    \"topic\", \"$1\", \"spring_id\", \"(.+)\\\\.consumer\\\\..+\"\r\n  )\r\n)",
     "legendFormat": "{{container}} | {{topic}}"
    }
   ]
  }
 ]
}