{
 "title": "Grafana Loki / Logs",
 "description": "Dashboard for spring boot 2 services. Displays standard spring metrics along with important data from kubernetes.",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(logback_events_total, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(logback_events_total{namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(logback_events_total{namespace=\"$namespace\", container=~\"$container\"}, pod)"
    }
   },
   { "name": "log_level", "label": "Log Level", "query": "TRACE,DEBUG,INFO,WARN,ERROR" },
   { "name": "message_contains", "label": "Message Contains" },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TRACE, DEBUG, INFO [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", level=\"trace\"}[$period]))",
     "legendFormat": "TRACE"
    },
    {
     "expr": "sum(increase(logback_events_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", level=\"debug\"}[$period]))",
     "legendFormat": "DEBUG"
    },
    {
     "expr": "sum(increase(logback_events_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", level=\"info\"}[$period]))",
     "legendFormat": "INFO"
    }
   ]
  },
  {
   "title": "WARN [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", level=\"warn\"}[$period]))",
     "legendFormat": "WARN"
    }
   ]
  },
  {
   "title": "ERROR [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(logback_events_total{namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\", level=\"error\"}[$period]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last 2000 Log Lines",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", container=~\"$container\", pod=~\"$pod\"} | json | level =~ \"$log_level\" | message =~ \"[\\\\s\\\\w\\\\W]*$message_contains[\\\\s\\\\w\\\\W]*\" | line_format \"{{.message}}\"",
     "maxLines": 2000
    }
   ]
  }
 ]
}