{
 "title": "DGTW NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "path",
    "query": {
     "query": "label_values(http_server_requests_seconds_bucket{service=\"domain-map-ui\", url!=\"/metrics/\"},url)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(nodejs_version_info,pod)"
    }
   },
   {
    "name": "status_code",
    "label": "status_code",
    "query": {
     "query": "label_values(http_server_requests_seconds_bucket,status)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   {
    "name": "api_url",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{url!=\"/metrics/\", service!=\"domain-map-ui\"},url)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BFF Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{service=\"domain-map-ui\", status=~\"$status_code\", url=~\"$path\", url!=\"/\"}[5m]) / rate(http_server_requests_seconds_count{service=\"domain-map-ui\", status=~\"$status_code\", url=~\"$path\"}[5m])",
     "legendFormat": "{{status}} - {{url}} - {{pod}}"
    }
   ]
  },
  {
   "title": "API Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{pod=~\"$pod\", status=~\"200\", url=~\"$api_url\", url!=\"/probe/healthz/\", url!=\"/probe/readiness/\", service!=\"domain-map-ui\", url!=\"/\"}[5m]) / rate(http_server_requests_seconds_count{pod=~\"$pod\", status=~\"200\", url=~\"$api_url\"}[5m])",
     "legendFormat": "{{status}} - {{pod}} - {{url}}  "
    }
   ]
  },
  {
   "title": "BFF Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(path, status, pod, url) (irate(http_server_requests_seconds_count{service=\"domain-map-ui\", status=\"200\", url!=\"/metrics/\"}[1m]))",
     "legendFormat": "{{status}} - {{pod}} - {{url}}  "
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "Active Handler - {{pod}}"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "Active Request - {{pod}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\",pod=~\"$pod\"}[2m]) * 100",
     "legendFormat": "User CPU - {{pod}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\",pod=~\"$pod\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{pod}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "External Memory - {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{pod=~\"$pod\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  }
 ]
}