{
 "title": "bpms-ved",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "5** statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_overall_responses_total{job=\"nginx-ingress-controller\", controller=~\".*\", app=~\".*\", node=~\".*\", namespace=~\"bpmsved-prod\", ingress=~\".*\", service=~\".*\", service_port=~\".*\", vhost=~\".*\", location=~\".*\", content_kind=~\".*\", status=~\"5..\"}[$__rate_interval])) by (status)\n  / scalar(sum(rate(ingress_nginx_overall_responses_total{job=\"nginx-ingress-controller\", controller=~\".*\", app=~\".*\", node=~\".*\", namespace=~\"bpmsved-prod\", ingress=~\".*\", service=~\".*\", service_port=~\".*\", vhost=~\".*\", location=~\".*\", content_kind=~\".*\", status=~\"5..\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_overall_upstream_response_seconds_sum{job=\"nginx-ingress-controller\", controller=~\".*\", app=~\".*\", node=~\".*\", namespace=~\"bpmsved-prod\", ingress=~\".*\", service=~\".*\", service_port=~\".*\", vhost=~\".*\", location=~\".*\", content_kind=~\".*\"}[$__rate_interval])) by (namespace)\n  / sum(rate(ingress_nginx_overall_upstream_response_seconds_count{job=\"nginx-ingress-controller\", controller=~\".*\", app=~\".*\", node=~\".*\", namespace=~\"bpmsved-prod\", ingress=~\".*\", service=~\".*\", service_port=~\".*\", vhost=~\".*\", location=~\".*\", content_kind=~\".*\"}[$__rate_interval])) by (namespace) > 0"
    }
   ]
  },
  {
   "title": "Error queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, durable, queue, vhost, policy) (rabbitmq_queue_messages{namespace=~\"bpmsved-prod\", pod=~\"rabbitmq-exporter-77b4b7f9d5-6wgfp\", vhost=~\"/\",\nqueue=~\"error\\\\.lmru\\\\.bpms\\\\.ved\\\\.shipment-creation-queue|error\\\\.lmru\\\\.bpms\\\\.ved\\\\.order-import-queue|error\\\\.lmru\\\\.bpms\\\\.ved\\\\.dictionary-update-queue|error\\\\.lmru\\\\.bpms\\\\.ved\\\\.camunda-start-process-queue|error\\\\.lmru\\\\.bpms\\\\.ved\\\\.shipment-start-queue|error\\\\.lmru\\\\.bpms\\\\.ved\\\\.upload-file-processing-queue|error\\\\.lmru\\\\.bpms\\\\.ved\\\\.task-creation-queue|error\\\\.lmru\\\\.bpms\\\\.ved\\\\.task-completion-queue|error\\\\.lmru\\\\.bpms\\\\.ved\\\\.package-making-queue|error\\\\.lmru\\\\.bpms\\\\.ved\\\\.process-instance-completion-queue\"})\n\n\n\n"
    }
   ]
  },
  {
   "title": "CPU_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=\"authentication-proxy-cc785dc7b-f56vx\", namespace=\"bpmsved-prod\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}