{
 "title": "Dostovernost-GS",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "All Corrections",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_correction_result_total{container=\"python\", delta=\"eq 0\"}[$__interval]))",
     "legendFormat": "delta = 0"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_result_total{container=\"python\", delta=\"less 0\"}[$__interval]))",
     "legendFormat": "delta < 0"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_result_total{container=\"python\", delta=\"more 0\"}[$__interval]))",
     "legendFormat": "delta > 0"
    }
   ]
  },
  {
   "title": "ML",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_correction_ml_total{container=\"python\", delta=\"eq 0\"}[$__interval]))",
     "legendFormat": "delta = 0"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_ml_total{container=\"python\", delta=\"less 0\"}[$__interval]))",
     "legendFormat": "delta < 0"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_ml_total{container=\"python\", delta=\"more 0\"}[$__interval]))",
     "legendFormat": "delta > 0"
    }
   ]
  },
  {
   "title": "Expo",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_correction_expo_total{container=\"python\", delta=\"eq 0\"}[$__interval]))",
     "legendFormat": "delta = 0"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_expo_total{container=\"python\", delta=\"less 0\"}[$__interval]))",
     "legendFormat": "delta < 0"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_expo_total{container=\"python\", delta=\"more 0\"}[$__interval]))",
     "legendFormat": "delta > 0"
    }
   ]
  },
  {
   "title": "FNL",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_correction_fnl_total{container=\"python\", delta=\"eq 0\"}[$__interval]))",
     "legendFormat": "delta = 0"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_fnl_total{container=\"python\", delta=\"less 0\"}[$__interval]))",
     "legendFormat": "delta < 0"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_fnl_total{container=\"python\", delta=\"more 0\"}[$__interval]))",
     "legendFormat": "delta > 0"
    }
   ]
  },
  {
   "title": "Risky stock",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_correction_risky_stock_total{container=\"python\", delta=\"eq 0\"}[$__interval]))",
     "legendFormat": "delta = 0"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_risky_stock_total{container=\"python\", delta=\"less 0\"}[$__interval]))",
     "legendFormat": "delta < 0"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_risky_stock_total{container=\"python\", delta=\"more 0\"}[$__interval]))",
     "legendFormat": "delta > 0"
    }
   ]
  },
  {
   "title": "Corrections sending",
   "type": "grafana-piechart-panel",
   "description": "Correction is not sent if its value is the same as current value in the system",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_send_to_kafka_to_stockreping_total{container=\"python\"}[$__interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_result_total{container=\"python\"}[$__interval])) - sum(delta(dostovernost_gs_send_to_kafka_to_stockreping_total{container=\"python\"}[$__interval]))",
     "legendFormat": "Wasn't sent"
    }
   ]
  },
  {
   "title": "Processing result",
   "type": "grafana-piechart-panel",
   "description": "Stock Repo messages processing result",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_kafka_stock_receiving_total{container=\"python\", result=\"failure\"}[$__interval]))",
     "legendFormat": "StockRepo message receiving error"
    },
    {
     "expr": "sum(delta(dostovernost_gs_kafka_stock_receiving_total{container=\"python\", result=\"success\"}[$__interval])) - sum(delta(dostovernost_gs_mongo_requests_total{container=\"python\"}[$__interval]))",
     "legendFormat": "Not in allowed stores"
    },
    {
     "expr": "sum(delta(dostovernost_gs_mongo_requests_total{container=\"python\", result=\"failure\"}[$__interval]))",
     "legendFormat": "Features receiving error"
    },
    {
     "expr": "sum(delta(dostovernost_gs_mongo_requests_total{container=\"python\", result=\"success\"}[$__interval])) - sum(delta(dostovernost_gs_correction_result_total{container=\"python\"}[$__interval]))",
     "legendFormat": "Business rules error"
    },
    {
     "expr": "sum(delta(dostovernost_gs_send_to_kafka_to_stockreping_total{container=\"python\", result=\"success\"}[$__interval]))",
     "legendFormat": "Was sent to StockRepo"
    },
    {
     "expr": "sum(delta(dostovernost_gs_correction_result_total{container=\"python\"}[$__interval])) - sum(delta(dostovernost_gs_send_to_kafka_to_stockreping_total{container=\"python\"}[$__interval]))",
     "legendFormat": "Sending skipped"
    },
    {
     "expr": "sum(delta(dostovernost_gs_send_to_kafka_to_stockreping_total{container=\"python\", result=\"failure\"}[$__interval]))",
     "legendFormat": "StockRepo message sending error"
    }
   ]
  },
  {
   "title": "StockRepo msg receiving",
   "type": "grafana-piechart-panel",
   "description": "Stock Repo messages receiving and parsing",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_kafka_stock_receiving_total{container=\"python\", result=\"failure\"}[$__interval]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(delta(dostovernost_gs_kafka_stock_receiving_total{container=\"python\", result=\"success\"}[$__interval]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Features from Mongo",
   "type": "grafana-piechart-panel",
   "description": "Features from Mongo receiving and parsing",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_mongo_requests_total{container=\"python\", result=\"success\"}[$__interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(delta(dostovernost_gs_mongo_requests_total{container=\"python\", result=\"failure\"}[$__interval]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Sending to DTM",
   "type": "grafana-piechart-panel",
   "description": "Messages to DTM sending",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_send_to_kafka_dtming_total{container=\"python\", result=\"success\"}[$__interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(delta(dostovernost_gs_send_to_kafka_dtming_total{container=\"python\", result=\"failure\"}[$__interval]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Sending to StockRepo",
   "type": "grafana-piechart-panel",
   "description": "Messages to SR sending",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_send_to_kafka_to_stockreping_total{container=\"python\", result=\"success\"}[$__interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(delta(dostovernost_gs_send_to_kafka_to_stockreping_total{container=\"python\", result=\"failure\"}[$__interval]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Avg(1h) RPS  + Sum by Pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dostovernost_gs_message_processing_seconds_count{container=\"python\"}[1h]))"
    }
   ]
  },
  {
   "title": "Last message received - MIN",
   "type": "stat",
   "description": "Minimum time since last message received by pods",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "min(time() - dostovernost_gs_message_last_ts{container=\"python\"})",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Last message received - MAX",
   "type": "stat",
   "description": "Maximum time since last message received by pods",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(time() - dostovernost_gs_message_last_ts{container=\"python\"})",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Errors distribution",
   "type": "grafana-piechart-panel",
   "description": "Errors distribution by types",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_gs_app_errors_total{container=\"python\", typ=\"factory\"}[$__interval]))",
     "legendFormat": "FactoryError"
    },
    {
     "expr": "sum(delta(dostovernost_gs_app_errors_total{container=\"python\", typ=\"repository\"}[$__interval]))",
     "legendFormat": "RepositoryError"
    },
    {
     "expr": "sum(delta(dostovernost_gs_app_errors_total{container=\"python\", typ=\"rules\"}[$__interval]))",
     "legendFormat": "BusinessRulesError"
    },
    {
     "expr": "sum(delta(dostovernost_gs_app_errors_total{container=\"python\", typ=\"undefined\"}[$__interval]))",
     "legendFormat": "UndefinedError"
    }
   ]
  },
  {
   "title": "RPS [Avg(1h)]  + Sum by Pod",
   "type": "gauge",
   "description": "Average input RPS over selected time period",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dostovernost_gs_message_processing_seconds_count{container=\"python\"}[1h]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "RPS [Current]  + Sum by Pod",
   "type": "gauge",
   "description": "Current input RPS ",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dostovernost_gs_message_processing_seconds_count{container=\"python\"}[1m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Average Response Time [1h] + Avg by Pod",
   "type": "gauge",
   "description": "Average response time",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1000* avg(rate(dostovernost_gs_message_processing_seconds_sum{container=\"python\"}[1h]) / rate(dostovernost_gs_message_processing_seconds_count{container=\"python\"}[1h]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Pods Restarts",
   "type": "graph",
   "description": "Number of pods restarts",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Restarts" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"dostovernost\", pod=~\"dostovernost-guaranteed-stock-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(consumer_group_lag{container=\"python\", cluster=\"stockrepo-gs\", group=\"grnstock-group-full-stock\"})"
    }
   ]
  }
 ]
}