{
 "title": "Dostovernost-SRS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Count of responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starlette_responses_total{service=\"dostovernost-srs-api-peresort\"}[1h])",
     "legendFormat": "{{method}}{{path_template}}{{status_code}}"
    }
   ]
  },
  {
   "title": "Count requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starlette_requests_total{service=\"dostovernost-srs-api-peresort\"}[1h])",
     "legendFormat": "{{method}}{{path_template}}"
    }
   ]
  },
  {
   "title": "RPS [Current]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_processing_time_seconds_count{path_template!=\"/metrics\", service=\"dostovernost-srs-api-peresort\"}[5m]))"
    }
   ]
  },
  {
   "title": "RPS [Avg]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_processing_time_seconds_count{path_template!=\"/metrics\", service=\"dostovernost-srs-api-peresort\"}[1h]))"
    }
   ]
  },
  {
   "title": "Usage by pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (kube_controller_pod{controller=\"deploy/dostovernost-srs-api-peresort\"}  * on (pod)  sum by (pod) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", namespace=\"dostovernost\"}[1h])))"
    }
   ]
  },
  {
   "title": "Time of response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starlette_requests_processing_time_seconds_sum{service=\"dostovernost-srs-api-peresort\"}[5m]) / increase(starlette_requests_processing_time_seconds_count{service=\"dostovernost-srs-api-peresort\"}[5m])",
     "legendFormat": "{{method}}{{path_template}}"
    }
   ]
  },
  {
   "title": "Size of graph in api",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dostovernost_srs_api_size_of_graph{container=\"python\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "StockApi status_code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(dostovernost_srs_api_StockRepApi_total{container=\"python\",pod=~\"dostovernost-srs-api-peresort.*\",status_code=\"404\"}[$__interval]))",
     "legendFormat": "404"
    },
    {
     "expr": "sum(delta(dostovernost_srs_api_StockRepApi_total{container=\"python\",pod=~\"dostovernost-srs-api-peresort.*\",status_code=\"200\"}[$__interval]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(delta(dostovernost_srs_api_StockRepApi_total{container=\"python\",pod=~\"dostovernost-srs-api-peresort.*\",status_code=\"500\"}[$__interval]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(delta(dostovernost_srs_api_StockRepApi_total{container=\"python\",pod=~\"dostovernost-srs-api-peresort.*\",status_code!~\"404|200|500\"}[$__interval]))",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Time of build graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dostovernost_srs_cron_time_process_sum",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"dostovernost-srs-api-peresort.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Size of graph in cron",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dostovernost_srs_cron_size_of_graph",
     "legendFormat": "{{exported_job}}"
    }
   ]
  }
 ]
}