{
 "title": "Qrator Metrics Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "QratorDomain",
    "query": {
     "query": "label_values(qrator_rps_total,domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Codes Stats",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (domain) (qrator_rps_blocked_total{domain=~\"$QratorDomain\"}) / sum by (domain) (qrator_rps_total{domain=~\"$QratorDomain\"}) * 100",
     "legendFormat": "blocked"
    },
    {
     "expr": "sum by (domain) (qrator_rps_4xx_total{domain=~\"$QratorDomain\"}) / sum by (domain) (qrator_rps_total{domain=~\"$QratorDomain\"}) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (domain) (qrator_rps_5xx_total{domain=~\"$QratorDomain\"}) / sum by (domain) (qrator_rps_total{domain=~\"$QratorDomain\"}) * 100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Qrator Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (domain,id) (qrator_rps_total{domain=~\"$QratorDomain\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Qrator 4XX RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (domain,id) (qrator_rps_4xx_total{domain=~\"$QratorDomain\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Qrator 5XX RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (domain,id,status) (qrator_rps_5xx_total{domain=~\"$QratorDomain\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (domain,id) (qrator_rps_5xx_total{domain=~\"$QratorDomain\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Qrator Blocked RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (domain,id,status) (qrator_rps_blocked_total{domain=~\"$QratorDomain\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (domain,id) (qrator_rps_blocked_total{domain=~\"$QratorDomain\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}