{
 "title": "Inbound Adapter Tasks",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(task_queue_count, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(task_queue_count{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(task_queue_count{namespace=\"$namespace\", service=\"$app\"}, pod)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(task_queue_count{namespace=\"$namespace\", service=\"$app\"}, pod)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(task_queue_count{namespace=\"$namespace\", service=\"$app\"}, type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task Queue Count $type",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (service, type) (task_queue_count{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\"})",
     "legendFormat": "$type AVG by app"
    }
   ]
  },
  {
   "title": "Task Processed Total Result",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(increase(task_processed_total{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\"}[$__range])\r\n> 0) by (result, type))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Task  Processed Total Increase [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (type, result) (increase(task_processed_total{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\"}[5m]))",
     "legendFormat": "{{type}} {{result}}"
    }
   ]
  },
  {
   "title": "Task Queue Count by Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Queue Count $type",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 22 },
     "repeat": "type",
     "targets": [
      {
       "expr": "avg by (service, type) (task_queue_count{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\"})",
       "legendFormat": "$type AVG by app"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Queue Count by Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Queue Count $pod",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
     "repeat": "pod",
     "targets": [
      {
       "expr": "avg by (service, type) (task_queue_count{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\"})",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Processed Total Increase by Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task  Processed Total [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "repeat": "pod",
     "targets": [
      {
       "expr": "sum by (app) (increase(task_processed_total{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\"}[5m]))",
       "legendFormat": "$type  SUM by app"
      }
     ]
    },
    {
     "title": "Task Processed Total Result $pod",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
     "repeat": "pod",
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sort_desc(sum(increase(task_processed_total{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\"}[$__range])\r\n> 0) by (result))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Processed Total Increase by Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task  Processed Total Increase [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "repeat": "type",
     "targets": [
      {
       "expr": "sum by (app) (increase(task_processed_total{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\"}[5m]))",
       "legendFormat": "$type  SUM by app"
      }
     ]
    },
    {
     "title": "Task Processed Total Result $type",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
     "repeat": "type",
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sort_desc(sum(increase(task_processed_total{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\"}[$__range])\r\n> 0) by (result))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Processed Total Increase by Result",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task  Processed Total Increase SUCCESS [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum by (app) (increase(task_processed_total{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\", result=\"SUCCESS\"}[5m]))",
       "legendFormat": "$type  SUM by app"
      }
     ]
    },
    {
     "title": "Task  Processed Total Increase ERROR",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum by (app) (increase(task_processed_total{namespace=~\"$namespace\",service=~\"$app\",pod=~\"$pod\", type=~\"$type\", result=\"ERROR\"}[$__range]))"
      }
     ]
    }
   ]
  }
 ]
}