{
 "title": "Camunda External Tasks",
 "time": { "from": "2024-08-23T08:37:32.607Z", "to": "2024-08-23T20:37:32.607Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(camunda_external_task_process_result_total, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(camunda_external_task_complete_failure_total {namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values( camunda_external_task_process_time_seconds_count{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(camunda_external_task_process_time_seconds_count{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\"}, job)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(camunda_external_task_process_time_seconds_count{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\", job=~\"$job\"}, topic)"
    }
   },
   {
    "name": "process",
    "label": "Process",
    "query": {
     "query": "label_values(camunda_external_task_process_time_seconds_count{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\", topic=~\"$topic\", job=~\"$job\"}, process)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "External Task Complete Failure Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "camunda_external_task_complete_failure_total{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\", job=~\"$job\", topic=~\"$topic\", process=~\"$process\"}"
    }
   ]
  },
  {
   "title": "Process time second count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "camunda_external_task_process_time_seconds_count{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\", job=~\"$job\", topic=~\"$topic\", process=~\"$process\"}"
    }
   ]
  },
  {
   "title": "External Task Result Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "camunda_external_task_process_result_total{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\", job=~\"$job\", topic=~\"$topic\", process=~\"$process\"}"
    }
   ]
  },
  {
   "title": "Process time second count by Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process time second count $process",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
     "repeat": "process",
     "targets": [
      {
       "expr": "camunda_external_task_process_time_seconds_count{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\", job=~\"$job\", topic=~\"$topic\", process=~\"$process\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "External task result total by Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "External Task Result Total $process",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "repeat": "process",
     "targets": [
      {
       "expr": "camunda_external_task_process_result_total{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\", job=~\"$job\", topic=~\"$topic\", process=~\"$process\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "External Task Complete Failure Total by Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "External Task Complete Failure Total $process",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
     "repeat": "process",
     "targets": [
      {
       "expr": "camunda_external_task_complete_failure_total{namespace=~\"$namespace\", service=~\"$service\", pod=~\"$pod\", job=~\"$job\", topic=~\"$topic\", process=~\"$process\"}"
      }
     ]
    }
   ]
  }
 ]
}