{
 "title": "Node JS + K8S Info",
 "description": "Dashboard for spring boot 2 services. Displays standard spring metrics along with important data from kubernetes.",
 "tags": [
  "nodejs",
  "kubernetes"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nodejs_version_info, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\", service=\"$app\"}, pod)"
    }
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/_healthz.*|/_readiness.*|/metrics|"
   }
  ]
 },
 "panels": [
  { "title": "HTTP Server I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method,path) (increase(http_requests_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "{{ method }} {{ path }}"
    },
    {
     "expr": "sum by (service) (increase(http_requests_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "total (press shift + left click to hide)"
    }
   ]
  },
  {
   "title": "Response Time [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path) (irate(http_requests_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[1m])) / sum by (method, path) (irate(http_requests_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Response Status Groups 2xx / 4xx / 5xx [5m]",
   "type": "graph",
   "description": "Actually, query works with 'outcome' attribute: [SUCCESS, CLIENT_ERROR, SERVER_ERROR]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\", status=\"2XX\"}[5m])) / scalar(sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "2xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\", status=\"4XX\"}[5m])) / scalar(sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "4xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\", status=\"5XX\"}[5m])) / scalar(sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "5xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Statuses [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[5m])) by (status) / scalar(sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Status 4xx by (method, path, status) [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path, status) (increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=\"4XX\", path!~\"$excluded_urls\"}[5m]))",
     "legendFormat": "{{ method }} {{ path }} [{{ status }}]"
    }
   ]
  },
  {
   "title": "Response Status 5xx by (method, path, status) [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path, status) (increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=\"5XX\", path!~\"$excluded_urls\"}[5m]))",
     "legendFormat": "{{ method }} {{ path }} [{{ status }}]"
    }
   ]
  },
  {
   "title": "Response Status Error % by (method, path) [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\", status!=\"2XX\"}[5m])) by (method, path) / (sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[5m])) by (method, path) > 0)",
     "legendFormat": "{{ method }} {{ path }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Request Count [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[$__range]) > 0) by (method, path))",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Total Requests [selected range]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[$__range]) > 0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Response Statuses [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[$__range]) > 0) by (status))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Kubernetes Pods Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Uptime - $pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 47 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time () - process_start_time_seconds{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "(\n  min by (pod) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Running\"}[$__rate_interval])\n  ) == 1\n) * 0",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Pending\"}[$__rate_interval])\n  ) == 1\n) * 1",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Unknown\"}[$__rate_interval])\n  ) == 1\n) * 2",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Failed\"}[$__rate_interval])\n  ) == 1\n) * 3",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Succeeded\"}[$__rate_interval])\n  ) == 1\n) * 4",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod) (\n    kube_controller_pod{node=~\"$node\", namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min by (pod) (min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n  ) == 0\n) + 5",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Restarts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}[$__rate_interval])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n) > 0",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum (\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}[$__rate_interval])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"}[$__rate_interval]))\n)",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\", namespace=\"$namespace\"}[$__rate_interval]))\n)",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", container=\"$app\"})",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Ingress Important Statuses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "503 (probably all backends not available) [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"503\"}[5m])) by (service)",
       "legendFormat": "{{ service }}"
      },
      {
       "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"503\"}[5m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "499 (client disconnected due to its timeout) [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"499\"}[5m])) by (service)",
       "legendFormat": "{{ service }}"
      },
      {
       "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"499\"}[5m]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Probes - healthz / readiness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Healthcheck Response Time [5m] - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
     "repeat": "pod",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (method, path) (irate(http_requests_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", status=\"2XX\", path=~\"/(_readiness|_healthz)\"}[5m]) / irate(http_requests_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", status=\"2XX\", path=~\"/(_readiness|_healthz)\"}[5m]))",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "Healthcheck Response Statuses 4xx/5xx by (method, path, status, pod) [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (method, path, status, pod) (increase(http_requests_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"2XX\", path=~\"/(_readiness|_healthz)\"}[5m]))",
       "legendFormat": "{{ method }} {{ path }} [{{ status }}] - {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage - $pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 73 },
     "repeat": "pod",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_user_seconds_total{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}[2m]) * 100",
       "legendFormat": "User CPU Usage"
      },
      {
       "expr": "irate(process_cpu_system_seconds_total{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}[2m]) * 100",
       "legendFormat": "System CPU Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 81 },
     "repeat": "pod",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (process_resident_memory_bytes{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Process Memory"
      },
      {
       "expr": "sum by (pod) (nodejs_heap_size_total_bytes{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Heap Total"
      },
      {
       "expr": "sum by (pod) (nodejs_heap_size_used_bytes{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Heap Used"
      },
      {
       "expr": "sum by (pod) (nodejs_external_memory_bytes{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "External Memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc (Eventloop latency, Used File Descriptors, Active Handlers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eventloop Latency - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 88 },
     "repeat": "pod",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "last"
      },
      {
       "expr": "nodejs_eventloop_lag_p99_seconds{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "p99"
      },
      {
       "expr": "nodejs_eventloop_lag_p50_seconds{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Used File Descriptors - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 94 },
     "repeat": "pod",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_open_fds {pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"} / process_max_fds{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Active Handlers - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 100 },
     "repeat": "pod",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nodejs_active_handles_total {pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "{{ pod }} active handlers"
      }
     ]
    }
   ]
  }
 ]
}