{
 "title": "Support Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(camunda_active_incidents, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(camunda_active_incidents{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "group",
    "label": "group",
    "query": {
     "query": "label_values(kafka_burrow_partition_lag, group)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "query_result(group by (topic) (kafka_burrow_partition_lag{group=~\"$group\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " Active Process Instances $app",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app) (camunda_active_process_instances{namespace=~\"$namespace\",service=~\"$app\"})",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Kafka Topic LAG $group",
   "type": "graph",
   "description": "$group",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_burrow_partition_lag{group=~\"$group\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Active Incidents $app",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app) (camunda_active_incidents{namespace=~\"$namespace\",service=~\"$app\"})",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Kafka MSG/S Rate topic $group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_burrow_partition_current_offset{group=~\"$group\",topic=~\"$topic\"}[5m]))"
    }
   ]
  },
  {
   "title": "Camunda Completed Process Instances $app",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app) (camunda_completed_process_instances{namespace=~\"$namespace\",service=~\"$app\"})",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Kafka Partition lag $group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (partition,topic) (kafka_burrow_partition_lag{group=~\"$group\",topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Active Process Instances by Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "repeat": "app",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_process_instances{namespace=\"$namespace\", service=\"$app\", engineName=\"default\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Active Incidents by Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "$app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
     "repeat": "app",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_incidents{namespace=\"$namespace\", service=\"$app\", engineName=\"default\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Completed Process Instances by Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "$app",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
     "repeat": "app",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_completed_process_instances{namespace=\"$namespace\", service=\"$app\", engineName=\"default\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  }
 ]
}