{
 "title": "WMS // Receivit // Camunda external task",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result((group by (namespace) (jvm_classes_loaded_classes) OR group by (namespace) (nodejs_version_info)))"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "query_result((group by (service) (jvm_classes_loaded_classes{namespace=\"$namespace\"}) OR group by (service) (nodejs_version_info{namespace=\"$namespace\"})))"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "10, 20, 25, 50, 60, 70, 75, 80, 85, 90, 95, 99"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(camunda_external_task_duration_sum,topicName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Время выполнения [$__interval]",
     "type": "timeseries",
     "description": "Фильтрация по topic не выполняется",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(camunda_external_task_duration_bucket{namespace=\"$namespace\",service=\"$app\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(camunda_external_task_duration_bucket{namespace=\"$namespace\",service=\"$app\"}[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "sum (rate(camunda_external_task_duration_sum{namespace=\"$namespace\",service=~\"$app\"} [$__rate_interval])) / sum (rate(camunda_external_task_duration_count{namespace=\"$namespace\",service=~\"$app\"} [$__rate_interval]))",
       "legendFormat": "AVG"
      }
     ]
    },
    {
     "title": "Процент ошибочных [$__interval]",
     "type": "timeseries",
     "description": "Фильтрация по топик не выполняется",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum (increase(camunda_external_task_duration_count{namespace=\"$namespace\", service=\"$app\", status!=\"SUCCESS\"}[$__rate_interval])) by (topicName) / sum(increase(camunda_external_task_duration_count{namespace=\"$namespace\", service=\"$app\"}[$__rate_interval])) by (topicName)",
       "legendFormat": "{{topicName}}"
      }
     ]
    },
    {
     "title": "Количество [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (topicName) (increase(camunda_external_task_duration_count{namespace=\"$namespace\", service=\"$app\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Количество в разрезе статуса [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status)(increase(camunda_external_task_duration_count{namespace=\"$namespace\",service=\"$app\"}[$__rate_interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Сводная по времени и количеству",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Сводный по количеству и времени выполнения [$__interval][P${percentile}]",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (topicName)(increase(camunda_external_task_duration_count{namespace=\"$namespace\",service=\"$app\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(${percentile} / 100, sum by(topicName, le) (rate(camunda_external_task_duration_bucket{namespace=\"$namespace\",service=~\"$app\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(${percentile} / 100, sum by(topicName, le) (rate(camunda_external_task_duration_bucket{namespace=\"$namespace\",service=~\"$app\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "$topic Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "topic",
   "collapsed": true,
   "panels": [
    {
     "title": "Время выполнения [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(topicName, le) (rate(camunda_external_task_duration_bucket{namespace=\"$namespace\",service=~\"$app\",topicName=\"$topic\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(topicName, le) (rate(camunda_external_task_duration_bucket{namespace=\"$namespace\",service=~\"$app\",topicName=\"$topic\"}[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "sum by (topicName) (rate(camunda_external_task_duration_sum{namespace=\"$namespace\",service=~\"$app\",topicName=~\"$topic\"} [$__rate_interval])) / sum by (topicName) (rate(camunda_external_task_duration_count{namespace=\"$namespace\",service=~\"$app\",topicName=\"$topic\"} [$__rate_interval]))",
       "legendFormat": "AVG"
      }
     ]
    },
    {
     "title": "Количество [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (topicName)(increase(camunda_external_task_duration_count{namespace=\"$namespace\",service=\"$app\", topicName=\"$topic\"}[$__rate_interval])) > 0",
       "legendFormat": "value"
      }
     ]
    },
    {
     "title": "Количество в разрезе статуса [$__interval]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status)(increase(camunda_external_task_duration_count{namespace=\"$namespace\",service=\"$app\", topicName=\"$topic\"}[$__rate_interval])) > 0",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  }
 ]
}