{
 "title": "Local OPUS dashboard (aggregated)",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot,)",
 "tags": [
  "main",
  "micrometer"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(up, namespace)" } },
   {
    "name": "service",
    "label": "Application",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"$service\"}, uri)"
    }
   },
   {
    "name": "clientName",
    "label": "Client",
    "query": {
     "query": "label_values(http_client_requests_seconds{service=~\"$service\"},clientName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"$path\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or sum(increase(http_server_requests_seconds_count{service=\"$service\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "200 HTTP response (count)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"$path\", status=~\"2..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or sum(increase(http_server_requests_seconds_count{status=~\"2..\", service=\"$service\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "500 HTTP response (count)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"$path\", status=~\"5..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or sum(increase(http_server_requests_seconds_count{status=~\"5..\", service=\"$service\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "500 HTTP response (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  (sum(increase(http_server_requests_seconds_count{uri=\"$path\", status=~\"5..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or vector(0))\n    /\n  sum(increase(http_server_requests_seconds_count{uri=\"$path\", service=\"$service\", namespace=\"$namespace\"}[$__range]))\n)\n  or\n(\n  (sum(increase(http_server_requests_seconds_count{status=~\"5..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or vector(0))\n    /\n  sum(increase(http_server_requests_seconds_count{service=\"$service\", namespace=\"$namespace\"}[$__range]))\n)"
    }
   ]
  },
  {
   "title": "400 HTTP response (count)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"$path\", status=~\"4..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or sum(increase(http_server_requests_seconds_count{status=~\"4..\", service=\"$service\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "400 HTTP response (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  (sum(increase(http_server_requests_seconds_count{uri=\"$path\", status=~\"4..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or vector(0))\n    /\n  sum(increase(http_server_requests_seconds_count{uri=\"$path\", service=\"$service\", namespace=\"$namespace\"}[$__range]))\n)\n  or\n(\n  (sum(increase(http_server_requests_seconds_count{status=~\"4..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or vector(0))\n    /\n  sum(increase(http_server_requests_seconds_count{service=\"$service\", namespace=\"$namespace\"}[$__range]))\n)"
    }
   ]
  },
  {
   "title": "Average API response $path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (quantile, status) (http_server_requests_seconds{uri=~\"$path\", service=\"$service\", namespace=\"$namespace\", exception=\"None\"})",
     "legendFormat": "{{status}} {{quantile}}"
    },
    {
     "expr": "avg by (quantile, status, exception) (http_server_requests_seconds{uri=~\"$path\", exception!=\"None\", service=\"$service\", namespace=\"$namespace\", quantile=\"0.95\"})",
     "legendFormat": "{{status}} {{exception}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Requests per second $path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"$path\", service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "$path"
    }
   ]
  },
  { "title": "Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Offer Orchestrator alert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg (http_server_requests_seconds{namespace=\"opus_eureka_prod\",method=\"POST\",status=\"200\",uri=\"/product/extended\",quantile=\"0.95\"})"
    }
   ]
  },
  {
   "title": "HTTP Client Percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request per second $clientName",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "repeat": "clientName",
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "(sum by (service, uri, clientName) (rate(http_client_requests_seconds_count{clientName=~\"$clientName\", namespace=\"$namespace\", service=\"$service\"}[1m])))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "API response $clientName",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "repeat": "clientName",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg by (service, clientName, quantile, uri, status) (http_client_requests_seconds{namespace=\"$namespace\", service=\"$service\", clientName=~\"$clientName\", outcome=\"SUCCESS\"})",
       "legendFormat": "{{uri}} {{status}} {{quantile}}"
      },
      {
       "expr": "avg by (service, clientName, quantile, uri, status) (http_client_requests_seconds{namespace=\"$namespace\", service=\"$service\", clientName=~\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"})",
       "legendFormat": "{{uri}} {{status}} {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}