{
 "title": "Offer-Repository",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values({service=\"$service\", namespace=\"$namespace\"},topic)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values({namespace=\"$namespace\", service=\"$service\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consume lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag {namespace=\"$namespace\", service=\"$service\", topic=\"$topic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consume rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_consumed_rate {namespace=\"$namespace\", service=\"$service\", topic=\"$topic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consume latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_manager_fetch_latency_avg {namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(kafka_producer_record_send_rate{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Время выполнения", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "OS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (entity, method)(rate(os_method_execution_time_seconds_sum{namespace=\"$namespace\", method=\"consume\", class=\"ru.lm.offerrepository.os.message.OfferUpdatesListener\"}[5m])) / sum by (entity, method)(rate(os_method_execution_time_seconds_count{namespace=\"$namespace\", method=\"consume\", class=\"ru.lm.offerrepository.os.message.OfferUpdatesListener\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (entity, method)(rate(oss_method_execution_time_seconds_sum{namespace=\"$namespace\", method=\"consume\", class=\"ru.lm.offerrepository.oss.message.OisiaListener\"}[5m])) / sum by (entity, method)(rate(oss_method_execution_time_seconds_count{namespace=\"$namespace\", method=\"consume\", class=\"ru.lm.offerrepository.oss.message.OisiaListener\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ORM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (entity, method)(rate(orm_method_execution_time_seconds_sum{namespace=\"$namespace\", method=\"consume\", class=\"ru.lm.offerrepository.orm.message.oria.OfferOrSalabilityUpdatesConsumer\"}[5m])) / sum by (entity, method)(rate(orm_method_execution_time_seconds_count{namespace=\"$namespace\", method=\"consume\", class=\"ru.lm.offerrepository.orm.message.oria.OfferOrSalabilityUpdatesConsumer\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap ($pod)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "Committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap ($pod)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total ($pod)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  }
 ]
}