{
 "title": "Mongo overview v1",
 "description": "Should display mongodb overview for telegraf 1.5",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "label_values(env)" },
   {
    "name": "host",
    "query": "label_values(mongodb_inserts_per_sec{env=\"$env\"},host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current master",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_inserts_per_sec{state=\"PRIMARY\", env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Mongo Oplog",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "exec_mongoext_timeDiff{env=\"$env\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mongoext",
     "select": [
      [
       { "params": [ "timeDiff" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Writes Queue to Master",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_active_writes{env=\"$env\", state=\"PRIMARY\"}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_active_reads{env=\"$env\"}",
     "legendFormat": "Reads: {{host}}"
    }
   ]
  },
  {
   "title": "mongo operations $host",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 7 },
   "repeat": "host",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "commands_per_sec $tag_host",
     "expr": "mongodb_inserts_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inserts ",
     "measurement": "mongodb",
     "query": "SELECT mean(\"commands_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "commands_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "deletes_per_sec $tag_host",
     "expr": "mongodb_queries_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Queries ",
     "measurement": "mongodb",
     "query": "SELECT mean(\"deletes_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "deletes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "flushes_per_sec $tag_host",
     "expr": "mongodb_updates_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Updates",
     "measurement": "mongodb",
     "query": "SELECT mean(\"flushes_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "flushes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "getmores_per_sec $tag_host",
     "expr": "mongodb_commands_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Commands",
     "measurement": "mongodb",
     "query": "SELECT mean(\"getmores_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "getmores_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "inserts_per_sec $tag_host",
     "expr": "mongodb_flushes_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Flushes",
     "measurement": "mongodb",
     "query": "SELECT mean(\"inserts_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "inserts_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "queries_per_sec $tag_host",
     "expr": "mongodb_getmores_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Getmores",
     "measurement": "mongodb",
     "query": "SELECT mean(\"queries_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "queries_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    },
    {
     "alias": "updates_per_sec $tag_host",
     "expr": "mongodb_deletes_per_sec{env=\"$env\", host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deletes",
     "measurement": "mongodb",
     "query": "SELECT mean(\"queries_per_sec\") FROM \"mongodb\" WHERE \"hostname\" = '127.0.0.1:27017' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "updates_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" }
     ]
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_open_connections{env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}