{
 "title": "Pimento job execution monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job_type", "query": { "query": "label_values(jobType)" } }
  ]
 },
 "panels": [
  {
   "title": "$job_type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "repeat": "job_type",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (jobType) (round(increase(job_count{jobType=\"$job_type\"}[$__range])))",
     "legendFormat": "current range"
    },
    {
     "expr": "max by (jobType) (round(increase(job_count{jobType=\"$job_type\"}[1h])))",
     "legendFormat": "1h"
    },
    {
     "expr": "max by (jobType) (round(increase(job_count{jobType=\"$job_type\"}[24h])))",
     "legendFormat": "24h"
    },
    {
     "expr": "max by (jobType) (round(increase(job_count{jobType=\"$job_type\"}[5d])))",
     "legendFormat": "5d"
    }
   ]
  },
  { "title": "Executed jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Execution time 99p",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, jobType) (rate(job_processing_time_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution time avg",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(jobType) (rate(job_processing_time_sum[$__range]))\r\n/ \r\nsum by(jobType)(rate(job_processing_time_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job total count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (jobType) (increase(job_processing_time_count[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}