{
 "title": "QA  perf monitor",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "microservice",
    "label": "Microservice name",
    "query": "select distinct microservice from publication_tests"
   },
   {
    "name": "app_version",
    "label": "Application version",
    "query": "select distinct application_version from publication_tests where microservice = '$microservice'"
   },
   {
    "name": "api",
    "label": "Api",
    "query": "select distinct api from publication_tests where microservice = '$microservice'"
   },
   {
    "name": "base_url",
    "label": "Base URL",
    "query": "select distinct base_url from publication_tests where microservice = '$microservice'"
   },
   { "name": "filtered", "label": "Result filter", "query": "true,false" },
   {
    "name": "simulation",
    "label": "Simulation Name",
    "query": "SELECT simulation FROM microservice_to_simulation WHERE microservice = '$microservice'"
   }
  ]
 },
 "panels": [
  {
   "title": "Результаты $microservice",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT rps, p50, p75, p95, p99, errors, start_time, warming, duration, (extract(epoch from start_time at time zone 'UTC'))*1000 as from, (45+extract(epoch from start_time at time zone 'UTC') + duration + warming)*1000 as to,\n       replace(test_params, '\\n', ' ') as params, application_replicas, application_version, api, base_url,comment, dependencies\nfrom publication_tests where microservice = '$microservice' and (filtered in ($filtered)) and (api in ($api)) and (application_version in ($app_version)) and (base_url in ($base_url)) and $__timeFilter(start_time) limit 20"
    }
   ]
  },
  {
   "title": "Responses per second",
   "type": "graph",
   "description": "Number of responses per second. NOT requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "OK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\" FROM \"gatling\" WHERE \"status\"='ok' AND \"request\"='allRequests' AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "KO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\" FROM \"gatling\" WHERE \"status\"='ko' AND \"request\"='allRequests' AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\" FROM \"gatling\" WHERE \"status\"='all' AND \"request\"='allRequests' AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "50 percentiles",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"percentiles50\" FROM \"gatling\" WHERE $timeFilter AND \"request\"='allRequests' AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "75 percentiles",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"percentiles75\" FROM \"gatling\" WHERE $timeFilter AND \"request\"='allRequests' AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "95 percentiles",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"percentiles95\" FROM \"gatling\" WHERE $timeFilter AND \"request\"='allRequests' AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "99 percentiles",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"percentiles99\" FROM \"gatling\" WHERE $timeFilter AND \"request\"='allRequests' AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"max\" FROM \"gatling\" WHERE $timeFilter AND \"request\"='allRequests' AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Responses per second for $api",
   "type": "graph",
   "description": "Number of responses per second. NOT requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "KO $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\" FROM \"gatling\" WHERE \"status\"='ko' AND \"request\"=~/$api$/ AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "all $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\" FROM \"gatling\" WHERE \"status\"='all' AND \"request\"=~/$api$/ AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response time for $api",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "50 percentiles $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"percentiles50\" FROM \"gatling\" WHERE $timeFilter AND \"request\"=~/$api$/ AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "75 percentiles $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"percentiles75\" FROM \"gatling\" WHERE $timeFilter AND \"request\"=~/$api$/ AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "95 percentiles $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"percentiles95\" FROM \"gatling\" WHERE $timeFilter AND \"request\"=~/$api$/ AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "99 percentiles $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"percentiles99\" FROM \"gatling\" WHERE $timeFilter AND \"request\"=~/$api$/ AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"max\" FROM \"gatling\" WHERE $timeFilter AND \"request\"=~/$api$/ AND $timeFilter AND \"simulation\"='$simulation' GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}