{
 "title": "QCMS Statistic",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(jvm_info, namespace)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Http requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri, status)(max_over_time(http_server_requests_seconds_count{namespace=\"$Namespace\", uri!~\".*/actuator/.*\"}[$interval]) - min_over_time(http_server_requests_seconds_count{namespace=\"$Namespace\", uri!~\".*/actuator/.*\"}[$interval]))",
     "legendFormat": "{{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Kafka consumers lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (topic, service) (kafka_consumer_fetch_manager_records_lag{namespace=~\"$Namespace\"})",
     "legendFormat": "{{service}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Created Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (service)(max_over_time(qas_action_created_counter_total{namespace=\"$Namespace\"}[$interval]) - min_over_time(qas_action_created_counter_total{namespace=\"$Namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Created/Updated Products",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (service)(max_over_time(pqms_product_created_counter_total{namespace=\"$Namespace\"}[$interval]) - min_over_time(pqms_product_created_counter_total{namespace=\"$Namespace\"}[$interval]))",
     "legendFormat": "Created"
    },
    {
     "expr": "sum by (service)(max_over_time(pqms_product_updated_counter_total{namespace=\"$Namespace\"}[$interval]) - min_over_time(pqms_product_updated_counter_total{namespace=\"$Namespace\"}[$interval]))",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "Async tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (service)(max_over_time(pqms_product_async_tasks_in_process_gauge{namespace=\"$Namespace\"}[$interval]) - min_over_time(pqms_product_async_tasks_in_process_gauge{namespace=\"$Namespace\"}[$interval]))",
     "legendFormat": "batch-update"
    },
    {
     "expr": "sum by (service)(max_over_time(pqms_send_status_tasks_in_process_gauge{namespace=\"$Namespace\"}[$interval]) - min_over_time(pqms_send_status_tasks_in_process_gauge{namespace=\"$Namespace\"}[$interval]))",
     "legendFormat": "Send status"
    },
    {
     "expr": "sum by (service)(max_over_time(pqms_update_qm_tasks_in_process_gauge{namespace=\"$Namespace\"}[$interval]) - min_over_time(pqms_update_qm_tasks_in_process_gauge{namespace=\"$Namespace\"}[$interval]))",
     "legendFormat": "Update QM Data"
    },
    {
     "expr": "sum by (service)(max_over_time(pqms_transfer_async_tasks_in_process_gauge{namespace=\"$Namespace\"}[$interval]) - min_over_time(pqms_transfer_async_tasks_in_process_gauge{namespace=\"$Namespace\"}[$interval]))",
     "legendFormat": " Async transfer"
    }
   ]
  },
  {
   "title": "Integration errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by (service)(max_over_time(pqms_product_error_counter_total{namespace=\"$Namespace\"}[$interval]) - min_over_time(pqms_product_error_counter_total{namespace=\"$Namespace\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Import nomenclatures errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by (service)(max_over_time(rqrms_import_nomenclature_error_counter_total{namespace=\"$Namespace\"}[$interval]) - min_over_time(rqrms_import_nomenclature_error_counter_total{namespace=\"$Namespace\"}[$interval]))",
     "legendFormat": "RQRMS Import errors"
    }
   ]
  }
 ]
}