{
 "title": "QCMS (http-metrics)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "window",
    "label": "window",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "service", "label": "service", "query": { "query": "label_values(service)" } },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "AVG response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AVG response time (by http_url)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_sum{service=~\"$service\",namespace=\"$namespace\", uri!~\".*/(actuator|swagger|api-docs).*\"}[$window])) by (uri) / sum(rate(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\", uri!~\".*/(actuator|swagger|api-docs).*\"}[$window])) by (uri)) * 1000"
    }
   ]
  },
  {
   "title": "AVG response time (total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_sum{service=~\"$service\",namespace=\"$namespace\",uri!~\".*/(actuator|swagger|api-docs).*\"}[$window])) / sum(rate(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\",uri!~\".*/(actuator|swagger|api-docs).*\"}[$window]))) * 1000"
    }
   ]
  },
  { "title": "Total requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total requests (by service)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\", uri!~\".*/(actuator|swagger|api-docs).*\"}[$window]))"
    }
   ]
  },
  {
   "title": "Total requests (total) by pod",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\", uri!~\".*/(actuator|swagger|api-docs).*\"}[$window])) by (pod)"
    }
   ]
  },
  { "title": "Success requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Success requests (by http_url)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\", uri!~\".*/(actuator|swagger|api-docs).*\", status=~\"(2|3)..\"}[$window])) by (uri)"
    }
   ]
  },
  {
   "title": "Success requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\", uri!~\".*/(actuator|swagger|api-docs).*\",status=~\"(2|3)..\"}[$window])) by (pod)"
    }
   ]
  },
  {
   "title": "Errors requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors requests (by http_url)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\", uri!~\".*/(actuator|swagger|api-docs).*\", status=~\"(4|5)..\"}[$window])) by (uri)"
      }
     ]
    },
    {
     "title": "Errors requests (total)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\", uri!~\".*/(actuator|swagger|api-docs).*\", status=~\"(4|5)..\"}[$window]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming requests",
     "type": "table",
     "gridPos": { "h": 12, "w": 20, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sum(increase(http_requests_latency_count{service=~\"$service\",namespace=\"$namespace\"}[$__range])) by (http_request_url) > 0 or vector(0)"
      },
      {
       "expr": "sum(increase(http_requests_latency_sum{service=~\"$service\",namespace=\"$namespace\"}[$__range])) by (http_request_url) \n/ sum(increase(http_requests_latency_count{service=~\"$service\",namespace=\"$namespace\"}[$__range])) by (http_request_url) > 0"
      },
      {
       "expr": "((sum(increase(http_requests_errors_total{service=~\"$service\",namespace=\"$namespace\",namespace=\"$namespace\"}[$__range])) by (http_request_url) or vector(0))\n/ sum(increase(http_requests_latency_count{service=~\"$service\",namespace=\"$namespace\",namespace=\"$namespace\"}[$__range])) by (http_request_url) > 0) * 100"
      }
     ]
    },
    {
     "title": "Success \\ Errors Request",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 2, "x": 20, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\",status=~\"(2|3)..\"}[$__range]))"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\", status=~\"(4|5)..\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Success Requests",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\",status=~\"(2|3)..\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Errors Requests",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 22, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{service=~\"$service\",namespace=\"$namespace\",status=~\"(4|5)..\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing client requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outgoing requests (by api_client)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_total{service=~\"$service\",namespace=\"$namespace\"}[$window])) by (api_client)"
      }
     ]
    },
    {
     "title": "Outgoing requests (total)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_total{service=~\"$service\",namespace=\"$namespace\"}[$window]))"
      }
     ]
    },
    {
     "title": "Outgoing requests (by target_name)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_total{service=~\"$service\",namespace=\"$namespace\"}[$window])) by (target_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Success outgoing client requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success outgoing requests (by api_client)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_success_total{service=~\"$service\",namespace=\"$namespace\"}[$window])) by (api_client)"
      }
     ]
    },
    {
     "title": "Success outgoing requests (total  - by api_client)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_success_total{service=~\"$service\",namespace=\"$namespace\"}[$window])) by (api_client)"
      }
     ]
    },
    {
     "title": "Success outgoing requests (by target_name)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_success_total{service=~\"$service\",namespace=\"$namespace\"}[$window])) by (target_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Failed outgoing client requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed outgoing requests (by api_client)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_errors_total{service=~\"$service\",namespace=\"$namespace\"}[$window])) by (api_client)"
      }
     ]
    },
    {
     "title": "Failed outgoing requests (total)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_errors_total{service=~\"$service\",namespace=\"$namespace\"}[$window]))"
      }
     ]
    },
    {
     "title": "Failed outgoing requests (by target_name)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_errors_total{service=~\"$service\",namespace=\"$namespace\"}[$window])) by (target_name)"
      }
     ]
    }
   ]
  }
 ]
}