{
 "title": "Image validator dashboard",
 "description": "Dashboard for Image Validator (Python)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(up, namespace)" } },
   {
    "name": "service",
    "label": "Application",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of images to check",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(validator_python_requests_count_total{service=\"$service\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Number of Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(validator_python_errors_total{service=\"$service\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Number of marked images",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(validator_python_images_blocked_count_total{service=\"$service\", namespace=\"$namespace\", pod=\"$pod\"}[$__range]))",
     "legendFormat": "{{method_name}}"
    }
   ]
  },
  {
   "title": "Python Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_info{service=\"$service\", namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{service=\"$service\", namespace=\"$namespace\", pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "Average time per image [95th percentile]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method_name) (rate(validator_python_avg_time_per_action_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[$__rate_interval])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RAM usage [Mbs]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "validator_python_ram_usage_mbs{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{method_name}}"
    }
   ]
  },
  {
   "title": "CPU usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "validator_python_cpu_usage_percent{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{method_name}}"
    }
   ]
  }
 ]
}