{
 "title": "FastAPI services aggregated",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(up, namespace)" } },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{service=~\"$service\"}, handler)"
    }
   },
   {
    "name": "service",
    "label": "Application",
    "query": "search-product-scoring, search-product-scoring-a, search-related-search, search-product-cart-recommendations"
   }
  ]
 },
 "panels": [
  { "title": "Common panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "requests per minute (all paths)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status, method) (increase(http_requests_total{service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_request_duration_seconds_count{handler=\"$path\", service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{service=\"$service\", handler=\"$path\"}[1m])/rate(http_request_duration_seconds_count{service=\"$service\", handler=\"$path\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{ method}} {{ handler }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler=\"$path\", status!=\"2xx\", service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Request duration [ms] - p50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{service=\"$service\", handler=\"$path\", namespace=\"$namespace\"}[1m])) * 1000",
     "legendFormat": "{{ method}} {{ handler }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{service=\"$service\", handler=\"$path\", namespace=\"$namespace\"}[1m])) * 1000",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Related Search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Empty Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(empty_result_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Default Region Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(default_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  { "title": "Product Cart Recommendations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Recommendations Requested Histogram sum",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "recommendations_requested_histogram_sum{namespace=\"recsys-prod\",service=\"search-product-cart-recommendations\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Recommendations Responsed Histogram sum",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "recommendations_responsed_histogram_sum{namespace=\"recsys-prod\",service=\"search-product-cart-recommendations\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Recommendations Requested Histogram buckets",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "recommendations_requested_histogram_bucket{namespace=\"recsys-prod\",service=\"search-product-cart-recommendations\"}",
     "legendFormat": "le={{le}}, reason={{reason}}"
    }
   ]
  },
  {
   "title": "Recommendations Responsed Histogram buckets",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "recommendations_responsed_histogram_bucket{namespace=\"recsys-prod\",service=\"search-product-cart-recommendations\"}",
     "legendFormat": "le={{le}}, reason={{reason}}"
    }
   ]
  },
  {
   "title": "Recommendation Types Counter",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "recommendation_types_counter_total{namespace=\"recsys-prod\",service=\"search-product-cart-recommendations\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}