{
 "title": "Monitoring by instance",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot,) by instances",
 "tags": [
  "main",
  "micrometer"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(up, namespace)" },
   {
    "name": "service",
    "label": "Application",
    "query": "label_values(up{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(up{namespace=\"$namespace\", service=\"$service\"}, pod)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\"},id)"
   },
   {
    "name": "path",
    "label": "Path",
    "query": "label_values(http_server_requests_seconds_count{pod=~\"$pod\"}, uri)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(method_execution_time_seconds{service=\"$service\"}, method)"
   },
   {
    "name": "clientName",
    "label": "client",
    "query": "label_values(http_client_requests_seconds{pod=\"$pod\"}, clientName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{pod=\"$pod\"}*1000"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"nonheap\"})"
      }
     ]
    },
    {
     "title": "$path",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds{pod=\"$pod\", uri=\"$path\", exception=\"none\"}",
       "legendFormat": "{{uri}},  {{quantile}}"
      },
      {
       "expr": "http_server_requests_seconds{pod=\"$pod\", uri=\"$path\", exception!=\"none\", quantile=\"0.95\"}",
       "legendFormat": "{{uri}},  {{quantile}} {{exception}}"
      }
     ]
    },
    {
     "title": "Average requests per second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{pod=\"$pod\"}[1m]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum by (uri) (rate(http_server_requests_seconds_count{pod=\"$pod\", uri=\"$path\"}[1m]))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Average Error Response Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "increase(http_server_requests_seconds_count{pod=\"$pod\", status=~\"5..\"}[1m])/2",
       "legendFormat": "{{exception}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{pod=\"$pod\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod=\"$pod\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod=\"$pod\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{pod=\"$pod\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{pod=\"$pod\"}",
       "legendFormat": "JVM"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{pod=\"$pod\"}",
       "legendFormat": "system-1m"
      },
      {},
      {
       "expr": "system_cpu_count{pod=\"$pod\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{pod=\"$pod\"} or jvm_threads_live_threads{pod=\"$pod\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon{pod=\"$pod\"} or jvm_threads_daemon_threads{pod=\"$pod\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak{pod=\"$pod\"} or jvm_threads_peak_threads{pod=\"$pod\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{pod=\"$pod\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{pod=\"$pod\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "legendFormat": "used" },
      {
       "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "legendFormat": "used" },
      {
       "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "legendFormat": "used" },
      {
       "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_max_bytes{pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari CP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection size",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(hikaricp_connections{pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_active{pod=\"$pod\"}",
       "legendFormat": "Count of active {{pool}}"
      },
      {
       "expr": "hikaricp_connections_idle{pod=\"$pod\"}",
       "legendFormat": "Count of ilde {{pool}}"
      },
      {
       "expr": "hikaricp_connections_pending{pod=\"$pod\"}",
       "legendFormat": "Count of pending {{pool}}"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(hikaricp_connections_timeout_total{pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Acquire Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_acquire_seconds_sum{pod=\"$pod\"} / hikaricp_connections_acquire_seconds_count{pod=\"$pod\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connection Creation Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_creation_seconds_sum{pod=\"$pod\"} / hikaricp_connections_creation_seconds_count{pod=\"$pod\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connection Usage Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_sum{pod=\"$pod\"} / hikaricp_connections_usage_seconds_count{pod=\"$pod\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{pod=\"$pod\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{pod=\"$pod\"}[30s])/rate(jvm_gc_pause_seconds_count{pod=\"$pod\"}[30s])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{pod=\"$pod\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{pod=\"$pod\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{pod=\"$pod\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{pod=\"$pod\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{pod=\"$pod\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{pod=\"$pod\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{pod=\"$pod\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{pod=\"$pod\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{pod=\"$pod\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  { "title": "Method execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "repeat": "method",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "method_execution_time_seconds{pod=\"$pod\", method=\"$method\", exception=\"none\"}",
     "legendFormat": "{{class}} {{quantile}}"
    },
    {
     "expr": "method_execution_time_seconds{pod=\"$pod\", method=\"$method\", exception!=\"none\", quantile=\"0.95\"}",
     "legendFormat": "{{exception}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "$method rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "repeat": "method",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(method_execution_time_seconds_count{pod=\"$pod\", method=\"$method\", exception=\"none\"}[1m])",
     "legendFormat": "{{class}}"
    },
    {
     "expr": "rate(method_execution_time_seconds_count{pod=\"$pod\", method=\"$method\", exception!=\"none\", quantile=\"0.95\"}[1m])",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  { "title": "HTTP Client Percentiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$clientName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "repeat": "clientName",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    },
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    }
   ]
  },
  {
   "title": "$clientName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    },
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    }
   ]
  },
  {
   "title": "$clientName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    },
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    }
   ]
  },
  {
   "title": "$clientName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    },
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    }
   ]
  },
  {
   "title": "$clientName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    },
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    }
   ]
  },
  {
   "title": "$clientName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    },
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    }
   ]
  },
  {
   "title": "$clientName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    },
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    }
   ]
  },
  {
   "title": "$clientName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    },
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    }
   ]
  },
  {
   "title": "$clientName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    },
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    }
   ]
  },
  {
   "title": "$clientName",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome=\"SUCCESS\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    },
    {
     "expr": "http_client_requests_seconds{pod=\"$pod\", clientName=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"}",
     "legendFormat": "{{quantile}}, code={{status}}, {{uri}}"
    }
   ]
  }
 ]
}