{
 "title": "Tempo custom",
 "tags": [ "tempo" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Кластер",
    "query": {
     "query": "label_values(tempo_build_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tempo_build_info{cluster=~'$cluster'}, namespace)"
    }
   },
   {
    "name": "component",
    "query": {
     "query": "{job=~\"$namespace.*\"}"
    }
   },
   {
    "name": "route",
    "query": {
     "query": " {job=~\".*$component\"}"
    }
   },
   {
    "name": "container",
    "query": {
     "query": " {job=~\".*$component\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "tempodb_blocklist_tenant_index_errors_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service,tenant) (tempodb_blocklist_tenant_index_errors_total{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "tempo_ingester_flush_failed_retries_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service) (increase(tempo_ingester_flush_failed_retries_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Полученные span на distributor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(tempo_distributor_spans_received_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by(service) (rate(tempo_distributor_spans_received_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Созданные трейсы на ingestors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(tempo_ingester_traces_created_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by(service) (rate(tempo_ingester_traces_created_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Общее", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Ошибки по компонентам",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (increase(tempo_request_duration_seconds_count{cluster=~\"$cluster\", status_code=~\"4.*|error|5.*\",endpoint!~\"http-metrics\"}[1m])) > 0 or on() vector(0)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Общее количество трассировок",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(container) (tempo_ingester_live_traces{namespace=\"$namespace\",cluster=\"$cluster\"})",
     "legendFormat": "Количество"
    }
   ]
  },
  {
   "title": "Spans в секунду",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_receiver_accepted_spans{cluster=~\"$cluster\", job=~\"($namespace)/distributor\"}[$__interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(tempo_receiver_refused_spans{cluster=~\"$cluster\", job=~\"($namespace)/distributor\"}[$__interval]))",
     "legendFormat": "refused"
    }
   ]
  },
  {
   "title": "Не обработанные данные",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(tempo_discarded_spans_total{namespace=\"$namespace\"}[$__interval])) or on() vector(0)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Общее количество объектов",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by(container,status) (tempodb_backend_objects_total{namespace=\"otel-grafana-tempo\"})",
     "legendFormat": "{{container}} - {{status}}"
    }
   ]
  },
  {
   "title": "Полученные данные",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(service) (rate(tempo_distributor_bytes_received_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memcache $component QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(method,status_code) (rate(tempo_memcache_request_duration_seconds_count{cluster=\"$cluster\",job=~\".*$component\"}[$__rate_interval]))",
       "legendFormat": "{{status_code}} - {{method}}"
      }
     ]
    },
    {
     "title": "Memcache $component Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tempo_memcache_request_duration_seconds_bucket{cluster=\"yc-obs-traces-stage\", job=\"otel-grafana-tempo/querier\",method=~\"Memcache.Get|Memcache.GetMulti\"}[$__interval])) by (le)) * 1e3",
       "legendFormat": "{{status_code}} - {{method}}"
      }
     ]
    }
   ]
  },
  { "title": "Запросы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Latency $component by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\",job=~\"$namespace.*$component\",route=~\"$route\"}[$__rate_interval])) by (le,pod, route)) * 1e3 > 0",
     "legendFormat": "{{pod}} - {{route}}"
    }
   ]
  },
  {
   "title": "Latency $component by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tempo_request_duration_seconds_bucket{cluster=\"$cluster\",job=~\".*$component\",route=~\"$route\"}[$__rate_interval])) by (le,method, route)) * 1e3 > 0",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "QPS - $component ALL",
   "type": "timeseries",
   "description": "Запросы в секунду по статусам",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status,route) (\n  label_replace(label_replace(rate(tempo_request_duration_seconds_count{cluster=~\"$cluster\", job=~\".*$component\", route=~\"$route\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\")) > 0\n",
     "legendFormat": "{{status}} - {{route}}"
    }
   ]
  },
  {
   "title": "QPS - $component - 2XX",
   "type": "timeseries",
   "description": "Запросы в секунду по статусам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code,route) (rate(tempo_request_duration_seconds_count{cluster=~\"$cluster\", job=~\".*$component\", route=~\"$route\",status_code=~\"2.*|success\"}[$__rate_interval])) >0 or on() vector(0)\n",
     "legendFormat": "{{status_code}} - {{route}}"
    }
   ]
  },
  {
   "title": "QPS - $component - 4XX",
   "type": "timeseries",
   "description": "Запросы в секунду по статусам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code,route) (rate(tempo_request_duration_seconds_count{cluster=~\"$cluster\", job=~\".*$component\", route=~\"$route\",status_code=~\"4.*|error|5.*\"}[$__rate_interval])) >0 or on() vector(0)\n",
     "legendFormat": "{{status_code}} - {{route}}"
    }
   ]
  },
  {
   "title": "Логи",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Логи",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "{namespace=\"obs-grafana-tempo\",pod_labels_app_kubernetes_io_component=\"$component\"}"
      }
     ]
    }
   ]
  },
  { "title": "Инфра", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "CPU $component",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{node=~\".*$cluster.*\", namespace=~\"$namespace\",container=~\"$container\"}[$__interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_cpu_quota{node=~\".*$cluster.*\", namespace=~\"$namespace\",container=~\"$container\"} / container_spec_cpu_period{node=~\".*$cluster.*\", namespace=~\"$namespace\",container=~\"$container\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{node=~\".*$cluster.*\", namespace=~\"$namespace\",container=~\"$container\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (workingset) $component",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{node=~\".*$cluster.*\", namespace=~\"$namespace\",container=~\"$container\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(container_spec_memory_limit_bytes{node=~\".*$cluster.*\", namespace=~\"$namespace\",container=~\"$container\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{node=~\".*$cluster.*\", namespace=~\"$namespace\",container=~\"$container\", resource=\"memory\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse) $component",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", job=~\"($namespace)/$component\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network in|out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\".*$container.*\"}[$__interval]))",
     "legendFormat": "{{pod}} - in"
    },
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\".*$container.*\"}[$__interval]))",
     "legendFormat": "{{pod}} - out"
    }
   ]
  },
  {
   "title": "Запись на диск",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate(container_fs_writes_bytes_total{pod=~\".*$component.*\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Чтение с диска",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate(container_fs_reads_bytes_total{pod=~\".*$component.*\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}