{
 "title": "HTTP statistic (UI)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(request_server_duration_ms, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(request_server_duration_ms{namespace=\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "BFF -> LOPUS (Request)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_server_duration_ms_count{namespace=\"$Namespace\", service=\"$Service\"}[1m]))",
     "legendFormat": "SUCCESS"
    }
   ]
  },
  {
   "title": "BFF -> LOPUS (Response)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(response_server_duration_ms_count{namespace=\"$Namespace\", service=\"$Service\"}[1m]))",
     "legendFormat": "SUCCESS"
    }
   ]
  },
  {
   "title": "LOPUS -> ? (Request)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_client_duration_ms_count{namespace=\"$Namespace\", service=\"$Service\"}[1m]))",
     "legendFormat": "SUCCESS"
    }
   ]
  },
  {
   "title": "BFF -> ElasticSearch (Request)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_elastic_duration_ms_count{namespace=\"$Namespace\", service=\"$Service\"}[1m]))",
     "legendFormat": "SUCCESS"
    }
   ]
  },
  { "title": "BFF -> LOPUS (Request)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (service, quantile) (request_server_duration_ms{namespace=\"$Namespace\", service=~\"$Service\"})",
     "legendFormat": "{{service}} ({{quantile}})"
    }
   ]
  },
  {
   "title": "Uri - Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (path) (rate(request_server_duration_ms_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Uri - Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(request_server_duration_ms_sum{namespace=\"$Namespace\", service=~\"$Service\"}[1m])) / scalar(sum(rate(request_server_duration_ms_sum{namespace=\"$Namespace\", service=~\"$Service\"}[1m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (path) (increase(request_server_duration_ms_count{namespace=~\"$Namespace\", service=~\"$Service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "BFF -> LOPUS (Response)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (service, quantile) (response_server_duration_ms{namespace=\"$Namespace\", service=~\"$Service\"})",
     "legendFormat": "{{service}} ({{quantile}})"
    }
   ]
  },
  {
   "title": "Uri - Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (path) (rate(response_server_duration_ms_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Uri - Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(response_server_duration_ms_sum{namespace=\"$Namespace\", service=~\"$Service\"}[1m])) / scalar(sum(rate(response_server_duration_ms_sum{namespace=\"$Namespace\", service=~\"$Service\"}[1m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by (path) (increase(response_server_duration_ms_count{namespace=~\"$Namespace\", service=~\"$Service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BFF -> ElasticSearch (Request)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "request_elastic_duration_ms{namespace=\"$Namespace\", service=~\"$Service\"}",
       "legendFormat": "{{pod}} ({{quantile}})"
      }
     ]
    },
    {
     "title": "Uri - Method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "rate(request_elastic_duration_ms_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}