{
 "title": "Spring Kafka (Consumer)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_lead, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_lead{namespace=\"$Namespace\"}, service)"
    }
   },
   {
    "name": "Topic",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_lead{namespace=\"$Namespace\", service=\"$Service\"}, topic)"
    }
   },
   {
    "name": "ClientID",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_lead{namespace=\"$Namespace\", service=\"$Service\", topic=\"$Topic\"}, client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Сommit latency ($ClientID)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "ClientID",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_commit_latency_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=\"$ClientID\"})"
    }
   ]
  },
  {
   "title": "Total lag ($ClientID)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "repeat": "ClientID",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag{namespace=\"$Namespace\", service=\"$Service\", client_id=\"$СlientID\"})"
    }
   ]
  },
  {
   "title": "Commit rate ($ClientID)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "repeat": "ClientID",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_commit_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=\"$ClientID\"})"
    }
   ]
  },
  {
   "title": "Join rate ($ClientID)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "repeat": "ClientID",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_join_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=\"$ClientID\"})"
    }
   ]
  },
  {
   "title": "Fetch Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumption lag",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_fetch_manager_records_lag{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumed bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_fetch_manager_bytes_consumed_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_fetch_manager_fetch_latency_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch throttle",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_fetch_manager_fetch_throttle_time_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_fetch_manager_fetch_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Records per request",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_fetch_manager_records_per_request_avg{namespace=\"$Namespace\", service=\"$Service\", topic=\"$Topic\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Group Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Assigned partitions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_coordinator_assigned_partitions{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Commit latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_coordinator_commit_latency_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_coordinator_commit_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Commit ({{client_id}})"
      },
      {
       "expr": "sum by (client_id) (kafka_consumer_coordinator_join_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Join ({{client_id}})"
      },
      {
       "expr": "sum by (client_id) (kafka_consumer_coordinator_heartbeat_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Heartbeat ({{client_id}})"
      },
      {
       "expr": "sum by (client_id) (kafka_consumer_coordinator_sync_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Sync ({{client_id}})"
      }
     ]
    },
    {
     "title": "Join time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_coordinator_join_time_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Last heartbeat ago",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_coordinator_last_heartbeat_seconds_ago{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Sync time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_coordinator_sync_time_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Rebalance latency ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_coordinator_rebalance_latency_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Rebalance count ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (client_id) (increase(kafka_consumer_coordinator_rebalance_total{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"}[5m]))",
       "legendFormat": "Current ({{client_id}})"
      },
      {
       "expr": "sum by (client_id) (increase(kafka_consumer_coordinator_failed_rebalance_total{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"}[5m]))",
       "legendFormat": "Failed ({{client_id}})"
      }
     ]
    },
    {
     "title": "Rebalance rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_coordinator_rebalance_rate_per_hour{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Current ({{client_id}})"
      }
     ]
    },
    {
     "title": "Partition assigned/revoked latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_coordinator_partition_assigned_latency_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Assigned ({{client_id}})"
      },
      {
       "expr": "avg by (client_id) (kafka_consumer_coordinator_partition_revoked_latency_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Revoked ({{client_id}})"
      }
     ]
    },
    {
     "title": "Last rebalance ago",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_coordinator_last_rebalance_seconds_ago{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Global Connection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_connection_count_total{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Total ({{client_id}})"
      },
      {
       "expr": "sum by (client_id) (kafka_consumer_connection_creation_total{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Create ({{client_id}})"
      },
      {
       "expr": "sum by (client_id) (kafka_consumer_connection_close_total{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Close ({{client_id}})"
      }
     ]
    },
    {
     "title": "IO ratio",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_io_ratio{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "IO wait ratio",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_io_wait_ratio{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "IO wait time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_io_wait_time_ns_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "IO time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_io_time_ns_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Select rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_select_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per-Broker Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request/Response",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_node_request_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Request {{client_id}}"
      },
      {
       "expr": "sum by (client_id) (kafka_consumer_node_response_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Response {{client_id}}"
      }
     ]
    },
    {
     "title": "Request size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_request_size_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Incoming/Outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (client_id) (kafka_consumer_incoming_byte_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Incoming ({{client_id}})"
      },
      {
       "expr": "sum by (client_id) (kafka_consumer_outgoing_byte_rate{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "Outgoing ({{client_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Poll metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time between poll ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_time_between_poll_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Last poll ago",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_last_poll_seconds_ago{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Poll idle time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (client_id) (kafka_consumer_poll_idle_ratio_avg{namespace=\"$Namespace\", service=\"$Service\", client_id=~\"$ClientID\"})",
       "legendFormat": "{{client_id}}"
      }
     ]
    }
   ]
  }
 ]
}