{
 "title": "Almaz business",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Shop",
    "query": {
     "query": "label_values(incorrect_product_weight_1810,location_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "The Product Has No Price ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(the_product_has_no_price_percentage{location_id=\"$location\"})",
     "legendFormat": "{{location_id}}"
    }
   ]
  },
  {
   "title": "Orders were not created in RMS",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(orders_were_not_created_in_RMS_values{location_id=\"$location\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incorrect Product Weight ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(incorrect_product_weight_1810{location_id=\"$location\"})",
     "legendFormat": "{{location_id}}"
    }
   ]
  },
  {
   "title": "The Product Has No Price  (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(the_product_has_no_price_percentage{location_id=\"$location\"})",
     "legendFormat": "{{location_id}}"
    }
   ]
  },
  {
   "title": "Orders were not created in RMS (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(orders_were_not_created_in_RMS_values{location_id=\"$location\"})",
     "legendFormat": "{{location_id}}"
    }
   ]
  },
  {
   "title": "Incorrect Product Weight (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(incorrect_product_weight_1810{location_id=\"$location\"})",
     "legendFormat": "{{location_id}}"
    }
   ]
  }
 ]
}