{
 "title": "Airflow",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(airflow_up, job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(airflow_up{job=~\".*${host}.*\"}, instance)"
    }
   },
   {
    "name": "dag",
    "query": {
     "query": "label_values(airflow_dag_run_state{instance=~\"${instance}:9112\"}, dag)"
    }
   },
   {
    "name": "nodeexpport",
    "query": {
     "query": "label_values(node_uname_info{instance=~\"$instance:(.*)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker online",
   "type": "stat",
   "description": "The time the task spent waiting at the celery worker to be executed",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flower_worker_online{instance=\"${instance}:5555\"}"
    }
   ]
  },
  {
   "title": "Active DAGs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(airflow_dag_active{instance=~\"${instance}:9112\"})",
     "legendFormat": "Active DAGs"
    }
   ]
  },
  {
   "title": "Running DAGs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(airflow_dag_run_state{state=\"running\", instance=\"${instance}:9112\"})",
     "legendFormat": "Active DAGs"
    }
   ]
  },
  {
   "title": "Executor queued tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_executor_queued_tasks{instance=\"${instance}:9102\"}",
     "legendFormat": "Active DAGs"
    }
   ]
  },
  {
   "title": "Worker number of currently executing tasks",
   "type": "timeseries",
   "description": "Number of tasks currently executing at a worker",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "flower_worker_number_of_currently_executing_tasks{instance=\"${instance}:5555\"}",
     "legendFormat": "currently executing tasks"
    }
   ]
  },
  {
   "title": " Time the task spent waiting at the celery worker",
   "type": "timeseries",
   "description": "The time the task spent waiting at the celery worker to be executed.",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "flower_worker_prefetched_tasks{instance=\"${instance}:5555\"}",
     "legendFormat": " Time the task spent waiting at the celery worker"
    }
   ]
  },
  {
   "title": "Events total",
   "type": "timeseries",
   "description": "Number of events",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 7 },
   "targets": [
    {
     "expr": "rate(flower_events_total{instance=\"${instance}:5555\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Task runtime by time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(flower_task_runtime_seconds_bucket{instance=\"${instance}:5555\"}[$__rate_interval])",
     "legendFormat": "time - {{le}}"
    }
   ]
  },
  {
   "title": "task prefetch time",
   "type": "timeseries",
   "description": "The time the task spent waiting at the celery worker to be executed.",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "rate(flower_task_prefetch_time_seconds{instance=\"${instance}:5555\"}[$__rate_interval])",
     "legendFormat": "The time the task spent waiting"
    }
   ]
  },
  {
   "title": "Task runtime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 15 },
   "targets": [
    {
     "expr": "increase(flower_task_runtime_seconds_created{instance=\"${instance}:5555\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"${instance}:${nodeexpport}\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"${instance}:${nodeexpport}\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"${instance}:${nodeexpport}\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"${instance}:${nodeexpport}\"} * 100) / node_memory_MemTotal_bytes{instance=~\"${instance}:${nodeexpport}\"})"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Used Data FS",
   "type": "gauge",
   "description": "Used Data FS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host/data\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host/data\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"${instance}:${nodeexpport}\"}) /  count(count(node_cpu_seconds_total{instance=~\"${instance}:${nodeexpport}\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"${instance}:${nodeexpport}\"}) /  count(count(node_cpu_seconds_total{instance=~\"${instance}:${nodeexpport}\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"${instance}:${nodeexpport}\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance}:${nodeexpport}\"}"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Total DataFS",
   "type": "stat",
   "description": "Total DataFS",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host/data\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "stat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"${instance}:${nodeexpport}\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"${instance}:${nodeexpport}\"} - node_boot_time_seconds{instance=~\"${instance}:${nodeexpport}\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"${instance}:${nodeexpport}\"}[10m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance}:${nodeexpport}\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance}:${nodeexpport}\"} - node_memory_MemFree_bytes{instance=~\"${instance}:${nodeexpport}\"} - (node_memory_Cached_bytes{instance=~\"${instance}:${nodeexpport}\"} + node_memory_Buffers_bytes{instance=~\"${instance}:${nodeexpport}\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"${instance}:${nodeexpport}\"} + node_memory_Buffers_bytes{instance=~\"${instance}:${nodeexpport}\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"${instance}:${nodeexpport}\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"${instance}:${nodeexpport}\"} - node_memory_SwapFree_bytes{instance=~\"${instance}:${nodeexpport}\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Container info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running containers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(rate(container_last_seen{name=~\".+\", instance=\"${instance}:18080\"}[5m]))"
      }
     ]
    },
    {
     "title": "CPU Usage per Container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",instance=\"${instance}:18080\"}[5m])) by (name) * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage per Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{name=~\".+\",instance=\"${instance}:18080\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Swap per Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_swap{name=~\".+\",instance=\"${instance}:18080\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Received Network Traffic per Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\", instance=\"${instance}:18080\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic per Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\",instance=\"${instance}:18080\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slots default pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_default_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_default_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_default_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots booking pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_booking_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_booking_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_booking_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots clickhouse pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_clickhouse_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_clickhouse_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_clickhouse_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots data_quality pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_data_quality_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_data_quality_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_data_quality_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots data_quality pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_data_quality_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_data_quality_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_data_quality_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots delete_artmags pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_delete_artmags_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_delete_artmags_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_delete_artmags_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots eligibility pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_eligibility_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_eligibility_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_eligibility_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots new_replenishment pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_new_replenishment_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_new_replenishment_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_new_replenishment_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots new_replenishment dev pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_new_replenishment_pool_dev{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_new_replenishment_pool_dev{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_new_replenishment_pool_dev{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots new_replenishment preprod pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_new_replenishment_pool_preprod{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_new_replenishment_pool_preprod{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_new_replenishment_pool_preprod{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots new_replenishment prod pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_new_replenishment_pool_prod{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_new_replenishment_pool_prod{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_new_replenishment_pool_prod{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots rms pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_rms_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_rms_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_rms_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots ruptures pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_ruptures_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_ruptures_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_ruptures_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots solution_reporter pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_solution_reporter_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_solution_reporter_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_solution_reporter_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots stock_repository_mariadb pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 26 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_stock_repository_mariadb_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_stock_repository_mariadb_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_stock_repository_mariadb_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Slots stock_repository_mariadb_preprod pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 26 },
     "targets": [
      {
       "expr": "airflow_pool_open_slots_stock_repository_mariadb_preprod_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "open"
      },
      {
       "expr": "airflow_pool_starving_tasks_stock_repository_mariadb_preprod_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "starving"
      },
      {
       "expr": "airflow_pool_used_slots_stock_repository_mariadb_preprod_pool{instance=\"${instance}:9102\"}",
       "legendFormat": "used"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task instance created",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "increase(airflow_task_instance_created_BashOperator{instance=\"${instance}:9102\"}[$__rate_interval])",
       "legendFormat": "BashOperator"
      },
      {
       "expr": "increase(airflow_task_instance_created_BigQueryOperator{instance=\"${instance}:9102\"}[$__rate_interval])",
       "legendFormat": "BigQueryOperator"
      },
      {
       "expr": "increase(airflow_task_instance_created_BigQueryTableDeleteOperator{instance=\"${instance}:9102\"}[$__rate_interval])",
       "legendFormat": "BigQueryTableDeleteOperator"
      },
      {
       "expr": "increase(airflow_task_instance_created_PythonOperator{instance=\"${instance}:9102\"}[$__rate_interval])",
       "legendFormat": "PythonOperator"
      },
      {
       "expr": "increase(airflow_task_instance_created_PythonOperator{instance=\"${instance}:9102\"}[$__rate_interval])",
       "legendFormat": "ClickHouseOperator"
      },
      {
       "expr": "increase(airflow_task_instance_created_PostgresOperator{instance=\"${instance}:9102\"}[$__rate_interval])",
       "legendFormat": "PostgresOperator"
      },
      {
       "expr": "increase(airflow_task_instance_created_BranchPythonOperator{instance=\"${instance}:9102\"}[$__rate_interval])",
       "legendFormat": "BranchPythonOperator"
      },
      {
       "expr": "increase(airflow_task_instance_created_MySqlOperator{instance=\"${instance}:9102\"}[$__rate_interval])",
       "legendFormat": "MySqlOperator"
      },
      {
       "expr": "increase(airflow_task_instance_created_DummyOperator{instance=\"${instance}:9102\"}[$__rate_interval])",
       "legendFormat": "DummyOperator"
      }
     ]
    },
    {
     "title": "Executor queued tasks",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "airflow_executor_queued_tasks{instance=\"${instance}:9102\"}",
       "legendFormat": "Executor queued tasks"
      }
     ]
    },
    {
     "title": "Executor open slots",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 12 },
     "targets": [
      {
       "expr": "airflow_executor_open_slots{instance=\"${instance}:9102\"}",
       "legendFormat": "Executor open slots"
      }
     ]
    },
    {
     "title": "Executor running tasks",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 14, "y": 12 },
     "targets": [
      {
       "expr": "airflow_executor_running_tasks{instance=\"${instance}:9102\"}",
       "legendFormat": "Executor running tasks"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "scheduler tasks running",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "airflow_scheduler_tasks_running{instance=\"${instance}:9102\"}",
       "legendFormat": "scheduler tasks running"
      }
     ]
    },
    {
     "title": "scheduler killed externally",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 4 },
     "targets": [
      {
       "expr": "rate(airflow_scheduler_tasks_killed_externally{instance=\"${instance}:9102\"}[$__rate_interval])",
       "legendFormat": "scheduler killed externally"
      }
     ]
    },
    {
     "title": "scheduler tasks starving",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 14, "y": 4 },
     "targets": [
      {
       "expr": "airflow_scheduler_tasks_starving{instance=\"${instance}:9102\"}",
       "legendFormat": "scheduler tasks starving"
      }
     ]
    },
    {
     "title": "scheduler tasks pending",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "airflow_scheduler_tasks_pending{instance=\"${instance}:9102\"}",
       "legendFormat": "scheduler tasks pending"
      }
     ]
    }
   ]
  },
  {
   "title": "DAGs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dags run state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "airflow_dag_run_state{dag=~\"${dag}\", instance=\"${instance}:9112\"}",
       "legendFormat": "{{ dag }}  -  {{ state }}"
      }
     ]
    },
    {
     "title": "Dags state - Failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate(airflow_dag_run_state{state=\"failed\",instance=\"${instance}:9112\"}[$__rate_interval]))",
       "legendFormat": "Failed dags"
      }
     ]
    },
    {
     "title": "Dags state - Running",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(airflow_dag_run_state{state=\"running\",instance=\"${instance}:9112\"})",
       "legendFormat": "Running dags"
      }
     ]
    }
   ]
  }
 ]
}