{
 "title": "kafka",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,5m,10m,20m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kafka_burrow_partition_lag{}, namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info{namespace=\"${namespace}\"},job)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{job=~\"$job\"}))"
    }
   },
   {
    "name": "consumergroupid",
    "query": {
     "query": "label_values(kafka_burrow_partition_lag{namespace=\"${namespace}\"}, group)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(prometheus_kafka_cert_expire{namespace=\"${namespace}\"},host)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_burrow_partition_lag{namespace=\"${namespace}\",group=~\"${consumergroupid}\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cert expire day - ${host}",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(prometheus_kafka_cert_expire{host=~\"$host\"})/86400",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Under Replicated",
     "type": "stat",
     "description": "Number of under-replicated partitions (| ISR | < | all replicas |). Alert if value is greater than 0.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_replicamanager_underreplicatedpartitions{namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Offline Partitions",
     "type": "stat",
     "description": "Number of partitions that don't have an active leader and are hence not writable or readable. Alert if value is greater than 0.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Controller",
     "type": "stat",
     "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Follower Fetch",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", request=\"FetchFollower\", quantile=\"0.50\"})"
      }
     ]
    },
    {
     "title": "Consumer Fetch",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", request=\"FetchConsumer\", quantile=\"0.50\"})"
      }
     ]
    },
    {
     "title": "Produce Request",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", request=\"Produce\", quantile=\"0.50\"})"
      }
     ]
    },
    {
     "title": "Partition Total ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_burrow_partition_status{namespace=\"$namespace\",topic=~\"$topic\"})"
      }
     ]
    },
    {
     "title": "Partition status OK",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_burrow_partition_status{namespace=\"$namespace\",topic=~\"$topic\"}==2)"
      }
     ]
    },
    {
     "title": "Partition Warning Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_burrow_partition_status{namespace=\"$namespace\",topic=~\"$topic\"}==3)"
      }
     ]
    },
    {
     "title": "Partition Error Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_burrow_partition_status{namespace=\"$namespace\",topic=~\"$topic\"}==4)"
      }
     ]
    },
    {
     "title": "Partition Stop Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_burrow_partition_status{namespace=\"$namespace\",topic=~\"$topic\"}==5)"
      }
     ]
    },
    {
     "title": "Partition REWIND Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_burrow_partition_status{namespace=\"$namespace\",topic=~\"$topic\"}==7)"
      }
     ]
    },
    {
     "title": "Partition STALL Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_burrow_partition_status{namespace=\"$namespace\",topic=~\"$topic\"}==6)"
      }
     ]
    },
    {
     "title": "In Sync Replicas Count",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(kafka_cluster_partition_insyncreplicascount{namespace=\"$namespace\", topic=~\"$topic\"}) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Clean / Unclean leader election rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_controller_controllerstats_leaderelectionrateandtimems{namespace=\"$namespace\", quantile=\"0.50\"}",
       "legendFormat": "{{hostname}} - clean leader election"
      }
     ]
    },
    {
     "title": "Kafka Broker - Outgoing Byte Per Sec",
     "type": "graph",
     "description": "Byte out rate to clients",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"$namespace\", topic=\"\"}[1m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Follower Fetch p99",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", request=\"FetchFollower\", quantile=\"0.99\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Purgatory Size",
     "type": "graph",
     "description": "https://www.confluent.io/blog/apache-kafka-purgatory-hierarchical-timing-wheels/",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_delayedoperationpurgatory_purgatorysize{namespace=\"$namespace\"}) by (delayedOperation)",
       "legendFormat": "{{delayedOperation}}"
      }
     ]
    },
    {
     "title": "Follower Fetch p50",
     "type": "graph",
     "description": "Total time in ms to serve fetch follower request",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", request=\"FetchFollower\", quantile=\"0.50\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Kafka Network  - Total Time per Produce request",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", request=\"Produce\", quantile=\"0.50\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Kafka Network  - FetchConsumer Request Total Time",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", request=\"FetchConsumer\", quantile=\"0.50\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ISR Shrinks Per Sec",
     "type": "graph",
     "description": "Rate at which the pool of in-sync replicas (ISRs) shrinks/expands",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_replicamanager_isrexpands_total{namespace=\"$namespace\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Kafka Broker - Incoming Byte Per Sec",
     "type": "graph",
     "description": "Byte in rate to Kafka",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$namespace\", topic=\"\"}[1m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Kafka Network  - FetchConsumer Request Total Time",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_totaltimems{namespace=\"$namespace\", request=\"FetchConsumer\", quantile=\"0.50\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "All Node Overview [Job: $namaspace, Total: $total]",
   "type": "table",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=~\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_Buffers_bytes{job=~\"$job\"}+\nnode_memory_Cached_bytes{job=~\"$job\"}) / node_memory_MemTotal_bytes{job=~\"$job\"} * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"$job\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"$job\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$job：Overall total 5m load & average CPU used%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Total 5m load" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\", mode='system'})",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "sum(node_load5{job=~\"$job\"})",
     "legendFormat": "Total 5m load"
    },
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "Overall average used%"
    }
   ]
  },
  {
   "title": "$job：Overall total memory & average memory used%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\"} - node_memory_MemAvailable_bytes{job=~\"$job\"})",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=~\"$job\"} - node_memory_MemAvailable_bytes{job=~\"$job\"}) / sum(node_memory_MemTotal_bytes{job=~\"$job\"}))*100",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  {
   "title": "$job：Overall total disk & average disk used%",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "Total" }
   ],
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "Overall Average Used%"
    }
   ]
  },
  {
   "title": "Consumer info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read message per instance [1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(burrow_kafka_topic_partition_offset{topic=~\"${topic}\"}[1m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Read message per topic and partition [1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(burrow_kafka_topic_partition_offset{topic=~\"${topic}\"}[1m])) by (topic, partition)",
       "legendFormat": "{{ topic }} - partition {{ partition }}"
      }
     ]
    },
    {
     "title": "Read message per topic and consumer group [1m]",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(burrow_kafka_consumer_current_offset{topic=~\"${topic}\"}[1m])) by (topic, consumer_group)",
       "legendFormat": "{{ topic }} - {{ consumer_group }}"
      }
     ]
    },
    {
     "title": "Consumer Group Lag",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "max(sum(kafka_burrow_partition_lag{group=~\"${consumergroupid}\",topic=~\"${topic}\"}) by (group, topic, instance)) by (group,topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Consumer lag ",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(sum(kafka_burrow_partition_lag{group=~\"${consumergroupid}\",topic=~\"${topic}\"}) by (group, topic, instance)) by (group,topic)",
       "legendFormat": "{{group}} - {{topic}}"
      }
     ]
    },
    {
     "title": "Consumer lag by partition",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(sum(kafka_burrow_partition_lag{group=~\"${consumergroupid}\",topic=~\"${topic}\"}) by (group, topic, instance)) by (group,topic)",
       "legendFormat": "{{group}} - {{topic}} - {{partition}}"
      }
     ]
    },
    {
     "title": "Consumer Group Offsets",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum(kafka_burrow_partition_current_offset{group=~\"${consumergroupid}\",topic=~\"${topic}\"}) by (group,partition,topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topic info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Messages",
     "type": "stat",
     "description": "Since last restart of Kafka",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Total Messages Per Topic",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$namespace\", topic=~\"$topic\"}) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Topic - Incoming Byte Per Sec",
     "type": "graph",
     "description": "Byte in rate to Kafka",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$namespace\", topic!=\"\"}[1m])) by (topic)",
       "legendFormat": "{{ topic }}"
      }
     ]
    },
    {
     "title": "Topic - Outgoing Byte Per Sec",
     "type": "graph",
     "description": "Byte out rate to clients",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"$namespace\", topic!=\"\"}[1m])) by (topic)",
       "legendFormat": "{{ topic }}"
      }
     ]
    },
    {
     "title": "Message In Topic Total",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$namespace\"}[1m])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Messages In broker [1m]",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$namespace\", topic=\"\"}[1m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Messages in topic - $topic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 37 },
     "repeat": "topic",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"${namespace}\", topic=~\"${topic}\"}[1m])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Connector - Navision",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Navision connect offset last message lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "min(time() - label_replace(kafka_connect_last_message{connector_name=~\".*NAV.*\"}, \"name\", \"$1\", \"connector_name\", \".*(NAV-STORE-[0-9]*).*\")) by (name)",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "min(time() - label_replace(kafka_connect_last_message{connector_name=~\".*navision.*\"}, \"name\", \"$1\", \"connector_name\", \".*(navision-prod-store[0-9]*).*\")) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Connect Worker Connector Count",
     "type": "table-old",
     "description": "The number of connectors run in this worker.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_connector_count{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Connect Task Count",
     "type": "table-old",
     "description": "The number of tasks run in this worker.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_task_count{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Burrow Status Partitions",
     "type": "table-old",
     "description": "https://github.com/linkedin/Burrow/wiki/Consumer-Lag-Evaluation-Rules",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "kafka_burrow_partition_status{namespace=\"$namespace\"}",
       "legendFormat": "{{group}} - {{partition}} - {{topic}} - {{hostname}}"
      }
     ]
    },
    {
     "title": "Burrow Status Consumer",
     "type": "table-old",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "kafka_burrow_status{namespace=\"$namespace\"}",
       "legendFormat": "{{group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka connect worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Connect Worker Connector Tasks Count",
     "type": "graph",
     "description": "The number of tasks run in this worker.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_task_count{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Connect Worker Connector Startup Attempt",
     "type": "graph",
     "description": "The total number of connector startups that this worker has attempted.\n",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_task_startup_attempts_total{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Connect Worker Connector Startup Success Total",
     "type": "graph",
     "description": "The total number of connector starts that succeeded.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_task_startup_success_total{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Connect Worker Connector Startup Success Percentage",
     "type": "graph",
     "description": "The average percentage of this worker's connectors starts that succeeded.\n",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_connector_startup_success_percentage{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Connect Worker Connector Startup Failure Total",
     "type": "graph",
     "description": "The total number of connector starts that failed.\n",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_task_startup_failure_total{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Connect Worker Connector Startup Failure Percentage",
     "type": "graph",
     "description": "The average percentage of this worker's connectors starts that failed.\n",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_connector_startup_failure_percentage{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Connect Task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Connect Tasks Startup Success Total",
     "type": "graph",
     "description": "The total number of task starts that succeeded.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_task_startup_success_total{namespace=\"$namespace\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Kafka Connect Tasks Startup Failure Total",
     "type": "graph",
     "description": "The total number of task starts that failed.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_task_startup_failure_total{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Connect Tasks Startup Success Percentage",
     "type": "graph",
     "description": "The average percentage of this worker's tasks starts that succeeded.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_task_startup_success_percentage{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Connect Worker Tasks Startup Failure Percentage",
     "type": "graph",
     "description": "The average percentage of this worker's tasks starts that failed.\n",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_metrics_task_startup_failure_percentage{namespace=\"$namespace\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quroum",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(zookeeper_quorumsize{namespace=\"$namespace\"}) by (namespace)"
      }
     ]
    },
    {
     "title": "Zookeeper leader ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 3, "y": 5 },
     "targets": [
      {
       "expr": "zookeeper_leader{namespace=\"$namespace\"}",
       "legendFormat": "{{ instance }} - replicaid {{ replicaid }}"
      }
     ]
    }
   ]
  }
 ]
}