{
 "title": "MariaDB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mysql_global_status_wsrep_local_state{namespace=\"$namespace\"}, instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mysql_galera_variables_info{namespace=\"$namespace\", instance=~\"$instance\"}, wsrep_cluster_name)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(mysql_galera_variables_info{namespace=\"$namespace\", wsrep_cluster_name =\"$cluster\"}, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(mysql_up{}, namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info{namespace=\"${namespace}\"},job)"
    }
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{job=~\"$job\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "DB Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MariaDB Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_version_info" }
   ]
  },
  {
   "title": "MariaDB Uptime (days)",
   "type": "stat",
   "description": "**MySQL Uptime**\\n\\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round (mysql_uptime / 3600 / 24 )",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "MariaDB status service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round (mysql_up{project=\"cfp\"})",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "gauge",
   "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Global Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_exporter_collector_duration_seconds{collector=\"collect.global_status\",namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Events Statements",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_exporter_collector_duration_seconds{collector=\"collect.perf_schema.eventsstatements\",namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "graph",
   "description": "***System Memory***: Total Memory for the system.\\\n***InnoDB Buffer Pool Data***: InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.\\\n***TokuDB Cache Size***: Similar in function to the InnoDB Buffer Pool,  TokuDB will allocate 50% of the installed RAM for its own cache.\\\n***Key Buffer Size***: Index blocks for MYISAM tables are buffered and are shared by all threads. key_buffer_size is the size of the buffer used for index blocks.\\\n***Adaptive Hash Index Size***: When InnoDB notices that some index values are being accessed very frequently, it builds a hash index for them in memory on top of B-Tree indexes.\\\n ***Query Cache Size***: The query cache stores the text of a SELECT statement together with the corresponding result that was sent to the client. The query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time.\\\n***InnoDB Dictionary Size***: The data dictionary is InnoDB ‘s internal catalog of tables. InnoDB stores the data dictionary on disk, and loads entries into memory while the server is running.\\\n***InnoDB Log Buffer Size***: The MySQL InnoDB log buffer allows transactions to run without having to write the log to disk before the transactions commit.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{namespace=\"$namespace\"}",
     "legendFormat": "System Memory - {{instance}}"
    },
    {
     "expr": "mysql_global_status_innodb_page_size{namespace=\"$namespace\"} * on (instance) mysql_global_status_buffer_pool_pages{namespace=\"$namespace\",state=\"data\"}",
     "legendFormat": "InnoDB Buffer Pool Data - {{instance}}"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{namespace=\"$namespace\"}",
     "legendFormat": "InnoDB Log Buffer Size - {{instance}}"
    },
    {
     "expr": "mysql_global_variables_innodb_additional_mem_pool_size{enamespace=\"$namespace\"}",
     "legendFormat": "InnoDB Additional Memory Pool Size - {{instance}}"
    },
    {
     "expr": "mysql_global_status_innodb_mem_dictionary{namespace=\"$namespace\"}",
     "legendFormat": "InnoDB Dictionary Size - {{instance}}"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{namespace=\"$namespace\"}",
     "legendFormat": "Key Buffer Size - {{instance}}"
    },
    {
     "expr": "mysql_global_variables_query_cache_size{namespace=\"$namespace\"}",
     "legendFormat": "Query Cache Size - {{instance}}"
    },
    {
     "expr": "mysql_global_status_innodb_mem_adaptive_hash{namespace=\"$namespace\"}",
     "legendFormat": "Adaptive Hash Index Size - {{instance}}"
    },
    {
     "expr": "mysql_global_variables_tokudb_cache_size{namespace=\"$namespace\"}",
     "legendFormat": "TokuDB Cache Size - {{instance}}"
    }
   ]
  },
  {
   "title": "Table I/O waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_exporter_collector_duration_seconds{collector=\"collect.perf_schema.tableiowaits\",namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Node Overview [Job: $namaspace, Total: $total]",
     "type": "table",
     "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_uname_info{job=~\"$job\"} - 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "node_load5{job=~\"$job\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "(node_memory_Buffers_bytes{job=~\"$job\"}+\nnode_memory_Cached_bytes{job=~\"$job\"}) / node_memory_MemTotal_bytes{job=~\"$job\"} * 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "max((node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\"}[$interval])) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\"}[$interval])) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "node_netstat_Tcp_CurrEstab{job=~\"$job\"} - 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "node_sockstat_TCP_tw{job=~\"$job\"} - 0",
       "legendFormat": "TIME_WAIT"
      },
      {
       "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\"}[$interval])*8) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\"}[$interval])*8) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$job：Overall total 5m load & average CPU used%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "Total 5m load" }
     ],
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{job=~\"$job\", mode='system'})",
       "legendFormat": "CPU Cores"
      },
      {
       "expr": "sum(node_load5{job=~\"$job\"})",
       "legendFormat": "Total 5m load"
      },
      {
       "expr": "avg(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
       "legendFormat": "Overall average used%"
      }
     ]
    },
    {
     "title": "$job：Overall total memory & average memory used%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "bytes", "label": "Total" }
     ],
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\"} - node_memory_MemAvailable_bytes{job=~\"$job\"})",
       "legendFormat": "Total Used"
      },
      {
       "expr": "(sum(node_memory_MemTotal_bytes{job=~\"$job\"} - node_memory_MemAvailable_bytes{job=~\"$job\"}) / sum(node_memory_MemTotal_bytes{job=~\"$job\"}))*100",
       "legendFormat": "Overall Average Used%"
      }
     ]
    },
    {
     "title": "$job：Overall total disk & average disk used%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "bytes", "label": "Total" }
     ],
     "targets": [
      {
       "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
       "legendFormat": "Total Used"
      },
      {
       "expr": "(sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
       "legendFormat": "Overall Average Used%"
      }
     ]
    }
   ]
  },
  {
   "title": "Galera Cluster info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Galera Cluster Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_wsrep_cluster_size{namespace=\"cfp-stock-repository--prod\",service=\"p-mariadb-innodb-exporter\",server=\"127.0.0.1:3306\",wsrep_cluster_state_uuid=\"4f7a9e29-dbb4-11ea-9ff8-6e6bb30e25fa\",wsrep_evs_state=\"OPERATIONAL\",wsrep_incoming_addresses=\"10.220.12.134:3306,10.220.12.133:3306,10.220.12.132:3306\"}"
      }
     ]
    },
    {
     "title": "Member State $instance",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
     "repeat": "instance",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_wsrep_connected{wsrep_cluster_status=~\"Disconnected|Primary\",instance=~\".*:9216\"}"
      }
     ]
    },
    {
     "title": "Cluster Member State $instance",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
     "repeat": "instance",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_wsrep_local_state{instance=~\".*:9216\"}"
      }
     ]
    },
    {
     "title": "Cluster Member State $instance",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
     "repeat": "instance",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_wsrep_connected{instance=~\".*:9216\"}"
      }
     ]
    },
    {
     "title": "Ready to Accept Queries ${instance}",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_status_wsrep_ready{namespace=\"$namespace\", instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "mysql_wsrep_ready $instance",
     "type": "stat",
     "description": "Server is ready to accept queries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
     "repeat": "instance",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_wsrep_ready{instance=~\".*:9216\"}"
      }
     ]
    },
    {
     "title": "gcache Size $host",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 31 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_galera_gcache_size_bytes{namespace=\"$namespace\", instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Galera Replication Latency",
     "type": "graph",
     "description": "Shows figures for the replication latency on group communication. It measures latency from the time point when a message is sent out to the time point when a message is received. As replication is a group operation, this essentially gives you the slowest ACK and longest RTT in the cluster.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max_over_time(mysql_global_status_wsrep_evs_repl_latency{namespace=\"$namespace\", instance=~\"$host\", aggregator=\"Maximum\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_evs_repl_latency{namespace=\"$namespace\", instance=~\"$host\", aggregator=\"Maximum\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      },
      {
       "expr": "avg_over_time(mysql_global_status_wsrep_evs_repl_latency{namespace=\"$namespace\", instance=~\"$host\", aggregator=\"Standard Deviation\"}[$interval]) or\navg_over_time(mysql_global_status_wsrep_evs_repl_latency{namespace=\"$namespace\", instance=~\"$host\", aggregator=\"Standard Deviation\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      },
      {
       "expr": "avg_over_time(mysql_global_status_wsrep_evs_repl_latency{namespace=\"$namespace\", instance=~\"$host\", aggregator=\"Average\"}[$interval]) or\navg_over_time(mysql_global_status_wsrep_evs_repl_latency{namespace=\"$namespace\", instance=~\"$host\", aggregator=\"Average\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      },
      {
       "expr": "min_over_time(mysql_global_status_wsrep_evs_repl_latency{namespace=\"$namespace\", instance=~\"$host\", aggregator=\"Minimum\"}[$interval]) or\nmin_over_time(mysql_global_status_wsrep_evs_repl_latency{namespace=\"$namespace\", instance=~\"$host\", aggregator=\"Minimum\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      }
     ]
    },
    {
     "title": "Galera Replication Queues",
     "type": "graph",
     "description": "Shows the length of receive and send queues.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_local_recv_queue{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_local_recv_queue{namespace=\"$namespace\", instance=~\"$host\"}[5m])",
       "legendFormat": "Receive Queue"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_local_send_queue{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_local_send_queue{namespace=\"$namespace\", instance=~\"$host\"}[5m])",
       "legendFormat": "Send Queue"
      }
     ]
    },
    {
     "title": "Galera Cluster Size",
     "type": "graph",
     "description": "Shows the number of members currently connected to the cluster.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_cluster_size{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_cluster_size{namespace=\"$namespace\", instance=~\"$host\"}[5m])",
       "legendFormat": "Size"
      }
     ]
    },
    {
     "title": "Galera Flow Control",
     "type": "graph",
     "description": "Shows the number of FC_PAUSE events sent/received. They are sent by a node when its replication queue gets too full. If a node is sending out FC messages it indicates a problem.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_flow_control_recv{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_recv{instance=~\"$host\"}[5m])",
       "legendFormat": "FC Messages Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_flow_control_sent{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_sent{instance=~\"$host\"}[5m])",
       "legendFormat": "FC Messages Sent"
      },
      {
       "calculatedInterval": "2m",
       "expr": "(rate(mysql_global_status_wsrep_flow_control_paused_ns{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_paused_ns{instance=~\"$host\"}[5m]))/1000000000",
       "legendFormat": "Paused due to Flow Control"
      }
     ]
    },
    {
     "title": "Galera Parallelization Efficiency",
     "type": "graph",
     "description": "Shows the average distances between highest and lowest seqno that are concurrently applied, committed and can be possibly applied in parallel (potential degree of parallelization).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_apply_window{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_apply_window{namespace=\"$namespace\", instance=~\"$host\"}[5m])",
       "legendFormat": "Apply Window"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_commit_window{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_commit_window{namespace=\"$namespace\", instance=~\"$host\"}[5m])",
       "legendFormat": "Commit Window"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_cert_deps_distance{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_cert_deps_distance{namespace=\"$namespace\", instance=~\"$host\"}[5m])",
       "legendFormat": "Cert Deps Distance"
      }
     ]
    },
    {
     "title": "Galera Writing Conflicts",
     "type": "graph",
     "description": "Shows the number of local transactions being committed on this node that failed certification (some other node had a commit that conflicted with ours) – client received deadlock error on commit and also the number of local transactions in flight on this node that were aborted because they locked something an applier thread needed – deadlock error anywhere in an open transaction. Spikes in the graph may indicate writing to the same table potentially the same rows from 2 nodes.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_local_cert_failures{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_local_cert_failures{instance=~\"$host\"}[5m])",
       "legendFormat": "Local Cert Failures"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_local_bf_aborts{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_local_bf_aborts{instance=~\"$host\"}[5m])",
       "legendFormat": "Local Bf Aborts"
      }
     ]
    },
    {
     "title": "Available Downtime before SST Required",
     "type": "graph",
     "description": "Shows for how long the node can be taken out of the cluster before SST is required. SST is a full state transfer method.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_galera_gcache_size_bytes{namespace=\"$namespace\", instance=~\"$host\"} /\n(rate(mysql_global_status_wsrep_replicated_bytes{namespace=\"$namespace\", instance=~\"$host\"}[1h])+rate(mysql_global_status_wsrep_received_bytes{namespace=\"$namespace\", instance=~\"$host\"}[1h]))",
       "legendFormat": "Time (1h avg)"
      },
      {
       "expr": "mysql_galera_gcache_size_bytes{namespace=\"$namespace\", instance=~\"$host\"} /\n((rate(mysql_global_status_wsrep_replicated_bytes{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{namespace=\"$namespace\", instance=~\"$host\"}[5m])) + \n(rate(mysql_global_status_wsrep_received_bytes{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{namespace=\"$namespace\", instance=~\"$host\"}[5m])))",
       "legendFormat": "Time (Instant)"
      }
     ]
    },
    {
     "title": "Galera Writeset Count",
     "type": "graph",
     "description": "Shows the count of transactions received from the cluster (any other node) and replicated to the cluster (from this node).",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_received{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_received{instance=~\"$host\"}[5m])",
       "legendFormat": "Transactions Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_replicated{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_replicated{instance=~\"$host\"}[5m])",
       "legendFormat": "Transactions Replicated"
      }
     ]
    },
    {
     "title": "Galera Writeset Size",
     "type": "graph",
     "description": "Shows the average transaction size received/replicated.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_received_bytes{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) / rate(mysql_global_status_wsrep_received{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{namespace=\"$namespace\", instance=~\"$host\"}[5m]) / irate(mysql_global_status_wsrep_received{namespace=\"$namespace\", instance=~\"$host\"}[5m])",
       "legendFormat": "Incoming Transaction Size"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_replicated_bytes{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) / rate(mysql_global_status_wsrep_replicated{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{namespace=\"$namespace\", instance=~\"$host\"}[5m]) / irate(mysql_global_status_wsrep_replicated{namespace=\"$namespace\", instance=~\"$host\"}[5m])",
       "legendFormat": "Replicating Transaction Size"
      }
     ]
    },
    {
     "title": "Galera Writeset Traffic",
     "type": "graph",
     "description": "Shows the bytes of data received from the cluster (any other node) and replicated to the cluster (from this node).",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_received_bytes{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{namespace=\"$namespace\", instance=~\"$host\"}[5m])",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_replicated_bytes{namespace=\"$namespace\", instance=~\"$host\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{namespace=\"$namespace\", instance=~\"$host\"}[5m])",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "Galera Network Usage Hourly",
     "type": "graph",
     "description": "Shows the bytes of data received from the cluster (any other node) and replicated to the cluster (from this node).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_wsrep_received_bytes{namespace=\"$namespace\", instance=~\"$host\"}[1h])",
       "legendFormat": "Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_wsrep_replicated_bytes{namespace=\"$namespace\", instance=~\"$host\"}[1h])",
       "legendFormat": "Replicated"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries/Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mysql_global_status_queries{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_queries{namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{total}}"
      }
     ]
    },
    {
     "title": "Current QPS",
     "type": "graph",
     "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "rate(mysql_global_status_queries{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_queries{namespace=\"$namespace\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Top Command Counters",
     "type": "graph",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5, rate(mysql_global_status_commands_total{namespace=\"$namespace\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{namespace=\"$namespace\"}[5m])>0)",
       "legendFormat": "Com_{{ command }} - {{instance}}"
      }
     ]
    },
    {
     "title": "Top Command Counters Hourly",
     "type": "graph",
     "description": "**Top Command Counters Hourly**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5, increase(mysql_global_status_commands_total{namespace=\"$namespace\"}[1h])>0)",
       "legendFormat": "Com_{{ command }} - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Slow Queries",
     "type": "graph",
     "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_slow_queries{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_slow_queries{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Slow Queries - {{instance}}"
      }
     ]
    },
    {
     "title": "InnoDB Transactions",
     "type": "graph",
     "description": "**Innodb Transactions** \n\nInnoDB is an MVCC storage engine, which means you can start a transaction and continue to see a consistent snapshot \neven as the data changes. This is implemented by keeping old versions of rows as they are modified.\n\nThe InnoDB History List is the undo logs which are used to store these modifications. They are a fundamental part of InnoDB’s transactional architecture.\n\nIf history length is rising regularly, do not let open connections linger for a long period as this can affect the performance of InnoDB considerably. It is also a good idea to look for long running queries in PMM's Query Analytics.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_max_trx_id{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_max_trx_id{instance=\"$host\"}[5m])",
       "legendFormat": "InnoDB Transactions"
      },
      {
       "calculatedInterval": "2m",
       "expr": "(max_over_time(mysql_global_status_innodb_history_list_length{instance=\"$host\"}[$interval]) or \nmax_over_time(mysql_global_status_innodb_history_list_length{instance=\"$host\"}[5m])) or \n(max_over_time(mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len{instance=\"$host\"}[$interval]) or \nmax_over_time(mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len{instance=\"$host\"}[5m]))",
       "legendFormat": "History Length"
      }
     ]
    },
    {
     "title": "Total inserts|updates",
     "type": "graph",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(topk(5, rate(mysql_global_status_commands_total{namespace=\"$namespace\", command=~\"insert|update\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{namespace=\"$namespace\", command=~\"insert|update\"}[5m])>0))",
       "legendFormat": "Com_{{ command }} - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Select Types",
     "type": "graph",
     "description": "**MySQL Select Types**\n\nAs with most relational databases, selecting based on indexes is more efficient than scanning an entire table's data. Here we see the counters for selects not done with indexes.\n\n* ***Select Scan*** is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.\n* ***Select Range*** is how many queries used a range scan, which means MySQL scanned all rows in a given range.\n* ***Select Full Join*** is the number of joins that are not joined on an index, this is usually a huge performance hit.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_select_full_join{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_select_full_join{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Select Full Join - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_select_full_range_join{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_select_full_range_join{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Select Full Range Join - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_select_range{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_select_range{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Select Range - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_select_range_check{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_select_range_check{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Select Range Check - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_select_scan{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_select_scan{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Select Scan - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Transaction Handlers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_handlers_total{namespace=\"$namespace\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{namespace=\"$namespace\", handler=~\"commit|rollback|savepoint.*|prepare\"}[5m])",
       "legendFormat": "{{ handler }} - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Handlers",
     "type": "graph",
     "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_handlers_total{namespace=\"$namespace\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{namespace=\"$namespace\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
       "legendFormat": "{{ handler }} - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Questions",
     "type": "graph",
     "description": "**MySQL Questions**\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_questions{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_questions{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Questions -{{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Sorts",
     "type": "graph",
     "description": "**MySQL Sorts**\n\nDue to a query's structure, order, or other requirements, MySQL sorts the rows before returning them. For example, if a table is ordered 1 to 10 but you want the results reversed, MySQL then has to sort the rows to return 10 to 1.\n\nThis graph also shows when sorts had to scan a whole table or a given range of a table in order to return the results and which could not have been sorted via an index.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_rows{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_sort_rows{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Sort Rows - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_range{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_sort_range{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Sort Range - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_merge_passes{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_sort_merge_passes{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Sort Merge Passes - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_scan{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_sort_scan{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Sort Scan - {{instance}}"
      }
     ]
    },
    {
     "title": "InnoDB Row Operations",
     "type": "graph",
     "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\"}[5m])",
       "legendFormat": "Rows {{ operation }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Connections",
     "type": "graph",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max(max_over_time(mysql_global_status_threads_connected{namespace=\"$namespace\"}[$interval])  or mysql_global_status_threads_connected{namespace=\"$namespace\"} )",
       "legendFormat": "Connections-{{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_max_used_connections{namespace=\"$namespace\"}",
       "legendFormat": "Max Used Connections-{{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_max_connections{namespace=\"$namespace\"}",
       "legendFormat": "Max Connections-{{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Client Thread Activity",
     "type": "graph",
     "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Threads" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_threads_connected{namespace=\"$namespace\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Peak Threads Connected - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_threads_running{namespace=\"$namespace\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Peak Threads Running - {{instance}}"
      },
      {
       "expr": "avg_over_time(mysql_global_status_threads_running{namespace=\"$namespace\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Avg Threads Running - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Aborted Connections",
     "type": "graph",
     "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_aborted_connects{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_aborted_connects{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Aborted Connects (attempts) - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_aborted_clients{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_aborted_clients{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Aborted Clients (timeout) - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Table Locks",
     "type": "graph",
     "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_table_locks_immediate{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_table_locks_immediate{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Table Locks Immediate - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_table_locks_waited{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_table_locks_waited{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Table Locks Waited - {{instance}}"
      }
     ]
    },
    {
     "title": "InnoDB Row Lock Time",
     "type": "graph",
     "description": "**InnoDB Row Lock Time**\n\nWhen data is locked, then that means that another ***session can NOT update that data until the lock*** is released (which unlocks the data and allows other users to update that data). Locks are usually released by either a ROLLBACK or COMMIT SQL statement.\n\nInnoDB implements standard row-level locking where there are two types of locks, [shared (S) locks](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_shared_lock) and [exclusive (X) locks](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_exclusive_lock).\n\n* A [shared (S) lock](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_shared_lock) permits the transaction that holds the lock to read a row.\n* An [exclusive (X) lock](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_exclusive_lock) permits the transaction that holds the lock to update or delete a row.\n\n_Average Row Lock Wait Time_ is the row lock wait time divided by the number of row locks.\\\n_Row Lock Waits_ are how many times a transaction waited on a row lock per second.\\\n_Row Lock Wait Load_ is a rolling 5 minute average of Row Lock Waits.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_row_lock_waits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_lock_waits{instance=\"$host\"}[5m])",
       "legendFormat": "Row Lock Waits"
      },
      {
       "expr": "rate(mysql_global_status_innodb_row_lock_time{instance=\"$host\"}[$interval])/1000 or irate(mysql_global_status_innodb_row_lock_time{instance=\"$host\"}[5m])/1000",
       "legendFormat": "Row Lock Wait Load"
      },
      {
       "expr": "rate(mysql_global_status_innodb_row_lock_time{instance=\"$host\"}[$interval])/rate(mysql_global_status_innodb_row_lock_waits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_lock_time{instance=\"$host\"}[5m])/irate(mysql_global_status_innodb_row_lock_waits{instance=\"$host\"}[5m])",
       "legendFormat": "Avg Row Lock Wait Time"
      }
     ]
    },
    {
     "title": "InnoDB Deadlocks",
     "type": "graph",
     "description": "**InnoDB Deadlocks**\n\nA deadlock in MySQL happens when two or more transactions mutually hold and request for locks, creating a cycle of dependencies. In a transaction system, deadlocks are a fact of life and not completely avoidable. InnoDB automatically detects transaction deadlocks, rollbacks a transaction immediately and returns an error.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(rate(mysql_global_status_innodb_deadlocks{instance=\"$host\"}[$interval]) or rate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{instance=\"$host\"}[$interval])) or (irate(mysql_global_status_innodb_deadlocks{instance=\"$host\"}[5m]) or irate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{instance=\"$host\"}[5m]))",
       "legendFormat": "Deadlocks"
      }
     ]
    },
    {
     "title": "Locks by schemas (second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum(mysql_perf_schema_sql_lock_waits_seconds_total) by (name,operation)",
       "legendFormat": "{{ name }} - {{ operation }}"
      }
     ]
    },
    {
     "title": "IO waits  by schemas (second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "increase(mysql_perf_schema_index_io_waits_seconds_total[1m])",
       "legendFormat": "{{schema}} - {{name}} - {{operation}}"
      }
     ]
    },
    {
     "title": "External locks waits  by schemas (second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "increase(mysql_perf_schema_external_lock_waits_seconds_total[1m])",
       "legendFormat": "{{schema}} - {{name}} - {{operation}}"
      }
     ]
    },
    {
     "title": "SQL locks waits  by schemas (second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "increase(mysql_perf_schema_sql_lock_waits_seconds_total[1m])",
       "legendFormat": "{{schema}} - {{name}} - {{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Input/Output",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB I/O",
     "type": "graph",
     "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_data_reads{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{instance=\"$host\"}[5m])",
       "legendFormat": "Data Reads"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_data_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{instance=\"$host\"}[5m])",
       "legendFormat": "Data Writes"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_data_fsyncs{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_fsyncs{instance=\"$host\"}[5m])",
       "legendFormat": "Data Fsyncs"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_log_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_log_writes{instance=\"$host\"}[5m])",
       "legendFormat": "Log Writes"
      }
     ]
    },
    {
     "title": "Innodb Read-Ahead",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=\"$host\"}[5m])",
       "legendFormat": "Pages Fetched by Linear Read Ahead "
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=\"$host\"}[5m])",
       "legendFormat": "Paged Fetched by Random Read Ahead"
      },
      {
       "expr": "rate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{instance=\"$host\"}[5m])",
       "legendFormat": "Paged Fetched by Read Ahead but Never Accessed"
      },
      {
       "expr": "(rate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{instance=\"$host\"}[5m])) / ((rate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=\"$host\"}[5m])) + (rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=\"$host\"}[5m])))",
       "legendFormat": "Read Ahead Waste Percent"
      },
      {
       "expr": "((rate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{instance=\"$host\"}[5m]))+(rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{instance=\"$host\"}[5m])))/(rate(mysql_global_status_innodb_pages_read{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_read{instance=\"$host\"}[5m])\n)",
       "legendFormat": "Percent of IO Caused by Read Ahead"
      }
     ]
    }
   ]
  },
  {
   "title": "Open files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Open Files",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_open_files{namespace=\"$namespace\"}",
       "legendFormat": "Open Files - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_open_files_limit{namespace=\"$namespace\"}",
       "legendFormat": "Open Files Limit - {{instance}}"
      },
      {
       "expr": "mysql_global_status_innodb_num_open_files{namespace=\"$namespace\"}",
       "legendFormat": "InnoDB Open Files - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL File Openings",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_opened_files{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_opened_files{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Openings - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Open Tables",
     "type": "graph",
     "description": "**MySQL Open Tables**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_open_tables{namespace=\"$namespace\"}",
       "legendFormat": "Open Tables - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_table_open_cache{namespace=\"$namespace\"}",
       "legendFormat": "Table Open Cache - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Temporary Objects",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_created_tmp_tables{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_created_tmp_tables{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Created Tmp Tables - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_created_tmp_disk_tables{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_created_tmp_disk_tables{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Created Tmp Disk Tables - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_created_tmp_files{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_created_tmp_files{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Created Tmp Files - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Innodb Logging Performance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_os_log_written{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_written{instance=\"$host\"}[5m])",
       "legendFormat": "Data Written to Logs"
      },
      {
       "calculatedInterval": "2m",
       "expr": "(mysql_global_variables_innodb_log_files_in_group{instance=\"$host\"} * mysql_global_variables_innodb_log_file_size{instance=\"$host\"})/(rate(mysql_global_status_innodb_os_log_written{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_written{instance=\"$host\"}[5m]))",
       "legendFormat": "Time to Use Redo Log Space "
      },
      {
       "expr": "(mysql_global_variables_innodb_log_buffer_size{instance=\"$host\"})/(rate(mysql_global_status_innodb_os_log_written{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_written{instance=\"$host\"}[5m]))",
       "legendFormat": "Time to Use In-Memory Log Buffer"
      }
     ]
    },
    {
     "title": "InnoDB Log File Usage Hourly",
     "type": "graph",
     "description": "**InnoDB Log File Usage Hourly**\n\nAlong with the buffer pool size, `innodb_log_file_size` is the most important setting when we are working with InnoDB. This graph shows how much data was written to InnoDB's redo logs over each hour. When the InnoDB log files are full, InnoDB needs to flush the modified pages from memory to disk.\n\nThe rules of the thumb is to keep one hour of traffic in those logs and let the checkpointing perform its work as smooth as possible. If you don't do this, InnoDB will do synchronous flushing at the worst possible time, ie when you are busiest.\n\nThis graph can help guide you in setting the correct `innodb_log_file_size`.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_innodb_os_log_written{instance=\"$host\"}[1h])",
       "legendFormat": "Data Written"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_innodb_log_files_in_group{instance=\"$host\"} * mysql_global_variables_innodb_log_file_size{instance=\"$host\"}",
       "legendFormat": "Total Size of InnoDB Log Files"
      }
     ]
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Network Usage Hourly",
     "type": "graph",
     "description": "**MySQL Network Usage Hourly**\n\nHere we can see how much network traffic is generated by MySQL per hour. You can use the bar graph to compare data sent by MySQL and data received by MySQL.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_bytes_received{namespace=\"$namespace\"}[1h])",
       "legendFormat": "Received - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_bytes_sent{namespace=\"$namespace\"}[1h])",
       "legendFormat": "Sent - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Network Traffic",
     "type": "graph",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_received{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_bytes_received{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Inbound-{{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_sent{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_bytes_sent{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Outbound-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers/Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB Buffer Pool Pages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_buffer_pool_pages{instance=\"$host\", state=~\"free|data|misc\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_pages_created{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_created{instance=\"$host\"}[5m])",
       "legendFormat": "Pages Created"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_pages_read{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_read{instance=\"$host\"}[5m])",
       "legendFormat": "Pages Read"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_pages_written{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_written{instance=\"$host\"}[5m])",
       "legendFormat": "Pages Written"
      }
     ]
    },
    {
     "title": "InnoDB Change Buffer Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_ibuf_merges{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merges{instance=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{instance=\"$host\"}[5m])",
       "legendFormat": "Merges"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_ibuf_merged_inserts{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_inserts{instance=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{instance=\"$host\"}[5m])",
       "legendFormat": "Merged Inserts"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_ibuf_merged_deletes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_deletes{instance=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{instance=\"$host\"}[5m])",
       "legendFormat": "Merged Deletes"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_ibuf_merged_delete_marks{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_delete_marks{instance=\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{instance=\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{instance=\"$host\"}[5m])",
       "legendFormat": "Merged Delete Marks"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Content",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_innodb_buffer_pool_bytes_data{instance=\"$host\"}",
       "legendFormat": "Data Total"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_innodb_buffer_pool_bytes_dirty{instance=\"$host\"}",
       "legendFormat": "Data Dirty"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Pages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_buffer_pool_pages{instance=\"$host\", state=~\"free|data|misc\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[5m])",
       "legendFormat": "Read Requests"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_buffer_pool_write_requests{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{instance=\"$host\"}[5m])",
       "legendFormat": "Write Requests"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_innodb_buffer_pool_reads{instance=\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_reads{instance=\"$host\"}[5m]) ",
       "legendFormat": "Disk Reads"
      }
     ]
    },
    {
     "title": "MySQL Table Definition Cache",
     "type": "graph",
     "description": "**MySQL Table Definition Cache**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_open_table_definitions{namespace=\"$namespace\"}",
       "legendFormat": "Open Table Definitions - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_table_definition_cache{namespace=\"$namespace\"}",
       "legendFormat": "Table Definitions Cache Size - {{instance}}"
      },
      {
       "expr": "rate(mysql_global_status_opened_table_definitions{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_opened_table_definitions{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Opened Table Definitions - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Thread Cache",
     "type": "graph",
     "description": "**MySQL Thread Cache**\n\nThe thread_cache_size variable sets how many threads the server should cache to reuse. When a client disconnects, the client's threads are put in the cache if the cache is not full. It is autosized in MySQL 5.6.8 and above (capped to 100). Requests for threads are satisfied by reusing threads taken from the cache if possible, and only when the cache is empty is a new thread created.\n\n* *Threads_created*: The number of threads created to handle connections.\n* *Threads_cached*: The number of threads in the thread cache.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_thread_cache_size{namespace=\"$namespace\"}",
       "legendFormat": "Thread Cache Size -{{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_threads_cached{namespace=\"$namespace\"}",
       "legendFormat": "Threads Cached - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_threads_created{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_threads_created{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Threads Created -{{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Query Cache Memory",
     "type": "graph",
     "description": "**MySQL Query Cache Memory**\n\nThe query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time. This serialization is true not only for SELECTs, but also for INSERT/UPDATE/DELETE.\n\nThis also means that the larger the `query_cache_size` is set to, the slower those operations become. In concurrent environments, the MySQL Query Cache quickly becomes a contention point, decreasing performance. MariaDB and AWS Aurora have done work to try and eliminate the query cache contention in their flavors of MySQL, while MySQL 8.0 has eliminated the query cache feature.\n\nThe recommended settings for most environments is to set:\n  ``query_cache_type=0``\n  ``query_cache_size=0``\n\nNote that while you can dynamically change these values, to completely remove the contention point you have to restart the database.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_qcache_free_memory{namespace=\"$namespace\"}",
       "legendFormat": "Free Memory - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_query_cache_size{namespace=\"$namespace\"}",
       "legendFormat": "Query Cache Size - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Query Cache Activity",
     "type": "graph",
     "description": "**MySQL Query Cache Activity**\n\nThe query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time. This serialization is true not only for SELECTs, but also for INSERT/UPDATE/DELETE.\n\nThis also means that the larger the `query_cache_size` is set to, the slower those operations become. In concurrent environments, the MySQL Query Cache quickly becomes a contention point, decreasing performance. MariaDB and AWS Aurora have done work to try and eliminate the query cache contention in their flavors of MySQL, while MySQL 8.0 has eliminated the query cache feature.\n\nThe recommended settings for most environments is to set:\n``query_cache_type=0``\n``query_cache_size=0``\n\nNote that while you can dynamically change these values, to completely remove the contention point you have to restart the database.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_qcache_hits{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_qcache_hits{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Hits - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_qcache_inserts{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_qcache_inserts{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Inserts - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_qcache_not_cached{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_qcache_not_cached{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Not Cached - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_qcache_lowmem_prunes{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_qcache_lowmem_prunes{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Prunes - {{instance}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_qcache_queries_in_cache{namespace=\"$namespace\"}",
       "legendFormat": "Queries in Cache - {{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Table Open Cache Status",
     "type": "graph",
     "description": "**MySQL Table Open Cache Status**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_opened_tables{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_opened_tables{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Openings - {{instance}}"
      },
      {
       "expr": "rate(mysql_global_status_table_open_cache_hits{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Hits - {{instance}}"
      },
      {
       "expr": "rate(mysql_global_status_table_open_cache_misses{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Misses - {{instance}}"
      },
      {
       "expr": "(rate(mysql_global_status_table_open_cache_hits{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{namespace=\"$namespace\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{namespace=\"$namespace\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{namespace=\"$namespace\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{namespace=\"$namespace\"}[5m])))",
       "legendFormat": "Table Open Cache Hit Ratio - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statements count total",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "topk(10,rate((mysql_perf_schema_events_statements_total[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Statements by query time [seconds]",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "topk(10,rate((mysql_perf_schema_events_statements_seconds_total[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Statements No index used ",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "topk(10,rate((mysql_perf_schema_events_statements_no_index_used_total[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      { "expr": "database_size_mb", "legendFormat": "{{ Database }}" }
     ]
    },
    {
     "title": "Table Size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 7, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      { "expr": "tables_size_mb", "legendFormat": "{{Database}} - {{Table}}" }
     ]
    },
    {
     "title": "Index Size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 15, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "index_size_mb",
       "legendFormat": "{{database_name}} - {{table_name}} - {{index_name}}"
      }
     ]
    }
   ]
  }
 ]
}