{
 "title": "Synapse Workspace / Workspace",
 "tags": [
  "Synapse",
  "Spark"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(metrics_executor_totalDuration_seconds_total{}, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Header", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Application Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(spark_info{service=\"$service\"}) by (application_id)) or vector(0)"
    }
   ]
  },
  {
   "title": "Current Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_memoryUsed_bytes{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Current Total Cores",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(metrics_executor_totalCores{service=\"$service\"}))",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  { "title": "Spark Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Active Spark pools",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\nmax_over_time(\n   max(spark_info{service=\"$service\"}) by (service)\n   [$__range:2m]\n)\n   ,\"info\", \"Manage\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "Total Running CPU Cores",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "yaxes": [
    { "format": "cpu" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_totalCores{service=\"$service\"})",
     "legendFormat": "Total Cores"
    }
   ]
  }
 ]
}