{
 "title": "Spark Application",
 "tags": [
  "Spark",
  "Research"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(metrics_executor_totalDuration_seconds_total{}, service)"
    }
   },
   {
    "name": "application_id",
    "label": "Application ID",
    "query": {
     "query": "label_values(metrics_executor_totalDuration_seconds_total{service=\"$service\"}, application_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Executors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count(metrics_executor_memoryUsed_bytes{service=\"$service\", executor_id!=\"driver\", application_id=\"$application_id\"})\n  by (service, executor_id))\nby (service)",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Storage Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_memoryUsed_bytes{service=\"$service\", executor_id!=\"driver\", application_id=\"$application_id\"}) by (service, application_id)\n/\nsum(metrics_executor_maxMemory_bytes{service=\"$service\",executor_id!=\"driver\", application_id=\"$application_id\"}) by (service, application_id)"
    }
   ]
  },
  {
   "title": "Driver Storage Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(metrics_executor_memoryUsed_bytes{service=\"$service\", executor_id=\"driver\", application_id=\"$application_id\"}) by (service, application_id)\n/ \nmax(metrics_executor_maxMemory_bytes{service=\"$service\", executor_id=\"driver\", application_id=\"$application_id\"}) by (service, application_id)"
    }
   ]
  },
  {
   "title": "Max Executor GC time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(metrics_executor_totalGCTime_seconds_total{service=\"$service\", application_id=\"$application_id\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total GC time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalGCTime_seconds_total{service=\"$service\", application_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": "Max Tasks on Executor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(metrics_executor_activeTasks{service=\"$service\", application_id=\"$application_id\"})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_failedTasks_total{service=\"$service\", executor_id!=\"driver\"})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_completedTasks_total{service=\"$service\", executor_id!=\"driver\", application_id=\"$application_id\"})"
    }
   ]
  },
  { "title": "Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Application Executors Current Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  max(metrics_executor_totalDuration_seconds_total{service=\"$service\", application_id=\"$application_id\"})\r\n  by (application_id, application_name, executor_id)[$__range:1m]\r\n)"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Tasks Time per Executor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(metrics_executor_totalDuration_seconds_total{service=\"$service\", application_id=\"$application_id\"}) by (executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_memoryUsed_bytes{service=\"$service\", application_id=\"$application_id\"}",
     "legendFormat": "[{{name}}] executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor JVM Off-Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_JVMOffHeapMemory_bytes{service=\"$service\", application_id=\"$application_id\"}",
     "legendFormat": "[{{name}}] executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor JVM Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_JVMHeapMemory_bytes{service=\"$service\", application_id=\"$application_id\"}",
     "legendFormat": "[{{name}}] executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Duration / Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(metrics_executor_totalDuration_seconds_total{service=\"$service\",  application_id=\"$application_id\", executor_id!=\"driver\"}[2m])) \nby (service, application_name)",
     "legendFormat": "[{{name}}]"
    }
   ]
  },
  {
   "title": "Executor GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_totalGCTime_seconds_total{service=\"$service\", application_id=\"$application_id\"}[1m])",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Active Tasks per Executor",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_activeTasks{service=\"$service\", application_id=\"$application_id\"}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_totalShuffleRead_bytes_total{service=\"$service\", application_id=\"$application_id\"}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_totalShuffleWrite_bytes_total{service=\"$service\", application_id=\"$application_id\"}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Input Bytes/Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_totalInputBytes_bytes_total{service=\"$service\", application_id=\"$application_id\"}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Shuffle IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metrics_executor_totalShuffleWrite_bytes_total{service=\"$service\", application_id=\"$application_id\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(spark_executor_totalShuffleRead_bytes_total{workspace_name=\"$workspace_name\", spark_pool_name=\"$spark_pool_name\", application_id=\"$application_id\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}