{
 "title": "Camunda Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(camunda_active_process_instance_count, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(camunda_active_process_instance_count{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "process",
    "query": {
     "query": "label_values(camunda_active_process_instance_count{namespace=~\"$namespace\"}, process_definition_key)"
    }
   },
   {
    "name": "process_with_active_tokens",
    "query": {
     "query": "label_values(camunda_active_tokens_activity_count{namespace=~\"$namespace\"}, process_definition_key)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Opened incidents",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "camunda_open_incidents_runtime_count{engine_name=\"default\",namespace=\"$namespace\",pod=\"$pod\"}  "
    }
   ]
  },
  {
   "title": "Active timers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "camunda_active_timer_job_count{engine_name=\"default\",namespace=\"$namespace\",pod=\"$pod\"}  "
    }
   ]
  },
  {
   "title": "Activity Instance Start/End Rate per 10 mins",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(camunda_metric_job_execution_rejected{engine_name=\"default\",namespace=\"$namespace\",pod=\"$pod\"}[20m])",
     "legendFormat": "Execution Rejections"
    },
    {
     "expr": "rate(camunda_metric_activity_instance_start{namespace=\"$namespace\",pod=\"$pod\"}[20m])",
     "legendFormat": "Instance Start"
    },
    {
     "expr": "rate(camunda_metric_activity_instance_end{namespace=\"$namespace\",pod=\"$pod\"}[20m])",
     "legendFormat": "Instance End"
    }
   ]
  },
  { "title": "Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$process_with_active_tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "repeat": "process_with_active_tokens",
   "targets": [
    {
     "expr": "camunda_active_tokens_activity_count { engine_name=\"default\", namespace=\"$namespace\", pod=\"$pod\", process_definition_key = \"$process_with_active_tokens\" }",
     "legendFormat": "{{activity_id}}"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "$process",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "repeat": "process",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camunda_active_process_instance_count{process_definition_key = \"$process\", engine_name=\"default\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Activity Instance Start (Flow Node Instances)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(camunda_metric_activity_instance_start{namespace=\"$namespace\",pod=\"$pod\"}[$__range])"
      }
     ]
    },
    {
     "title": "Activity Instance End",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(camunda_metric_activity_instance_end{namespace=\"$namespace\",pod=\"$pod\"}[$__range])"
      }
     ]
    },
    {
     "title": "Jobs Successful Executed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(camunda_metric_job_successful{namespace=\"$namespace\",pod=\"$pod\"}[$__range])"
      }
     ]
    },
    {
     "title": "job_failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 11, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "camunda_metric_job_failed{engine_name=\"default\",namespace=\"$namespace\",pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Job Acquisition Attempts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(camunda_metric_job_acquisition_attempt{namespace=\"$namespace\",pod=\"$pod\"}[$__range])"
      }
     ]
    },
    {
     "title": "Jobs Successfully Acquired",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(camunda_metric_job_acquired_success{namespace=\"$namespace\",pod=\"$pod\"}[$__range])"
      }
     ]
    },
    {
     "title": "Job Acquire Failure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(camunda_metric_job_acquired_failure{namespace=\"$namespace\",pod=\"$pod\"}[$__range])"
      }
     ]
    },
    {
     "title": "Delta Jobs Failed to Execute",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(camunda_metric_job_failed{namespace=\"$namespace\",pod=\"$pod\"}[$__range])"
      }
     ]
    },
    {
     "title": "Jobs Locked (Exclusive)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "delta(camunda_metric_job_locked_exclusive{namespace=\"$namespace\",pod=\"$pod\"}[$__range])"
      }
     ]
    },
    {
     "title": "Job Execution Rejected",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "delta(camunda_metric_job_execution_rejected{namespace=\"$namespace\",pod=\"$pod\"}[$__range])"
      }
     ]
    }
   ]
  }
 ]
}