{
 "title": "Spring Boot + K8S Info",
 "description": "Dashboard for spring boot 2 services. Displays standard spring metrics along with important data from kubernetes.",
 "tags": [
  "java",
  "kubernetes",
  "spring boot"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$app\"}, pod)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{pod=~\"$pod\"}, pool)"
    }
   },
   {
    "name": "spring_data_repository_name",
    "label": "Spring Repository Name",
    "query": {
     "query": "label_values(spring_data_repository_invocations_seconds_count{namespace=\"$namespace\", service=\"$app\"}, repository)"
    }
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   },
   {
    "name": "heap_part",
    "label": "Heap Part",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}, id)"
    }
   },
   {
    "name": "excluded_stream_channels",
    "query": ".*errorLogger|errorChannel|.*\\.errors(\\.bridge)?|unknown"
   }
  ]
 },
 "panels": [
  { "title": "HTTP Server I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", uri!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "{{ method }} {{ uri }}"
    },
    {
     "expr": "sum by (service) (increase(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", uri!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "total (press shift + left click to hide)"
    }
   ]
  },
  {
   "title": "Response Time [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", exception=\"None\", uri!~\"$excluded_urls\"}[1m])) / sum by (method, uri) (irate(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", exception=\"None\", uri!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Response Status Groups 2xx / 4xx / 5xx [5m]",
   "type": "graph",
   "description": "Actually, query works with 'outcome' attribute: [SUCCESS, CLIENT_ERROR, SERVER_ERROR]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"SUCCESS\"}[5m])) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "2xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"CLIENT_ERROR\"}[5m])) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "4xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"SERVER_ERROR\"}[5m])) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "5xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Statuses [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (status) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Status 4xx by (method, path, status) [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri, status) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"CLIENT_ERROR\", uri!~\"$excluded_urls\"}[5m]))",
     "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
    }
   ]
  },
  {
   "title": "Response Status 5xx by (method, path, status) [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri, status) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"SERVER_ERROR\", uri!~\"$excluded_urls\"}[5m]))",
     "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
    }
   ]
  },
  {
   "title": "Response Status Error % by (method, path) [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", uri!~\"$excluded_urls\", outcome!=\"SUCCESS\"}[5m])) by (method, uri) / (sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", uri!~\"$excluded_urls\"}[5m])) by (method, uri) > 0)",
     "legendFormat": "{{ method }} {{ uri }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Exceptions [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!=\"None\"}[5m])) by (exception)",
     "legendFormat": "{{ exception }}"
    }
   ]
  },
  {
   "title": "Request Count [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$__range]) > 0) by (method, uri))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Total Requests [selected range]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$__range]) > 0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Response Statuses [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$__range]) > 0) by (status))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Exceptions by endpoint [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!=\"None\"}[$__range]) > 0) by (method, uri))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Total Exceptions [selected range]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!=\"None\"}[$__range]) > 0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Exception Types [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!=\"None\"}[$__range]) > 0) by (exception))",
     "legendFormat": "{{ exception }}"
    }
   ]
  },
  {
   "title": "HTTP Client I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count [1m]",
     "type": "graph",
     "description": "Including cancelled",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (method, uri) (increase(http_client_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "{{ method }} {{ uri }}"
      },
      {
       "expr": "sum by (service) (increase(http_client_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "total (press shift + left click to hide)"
      }
     ]
    },
    {
     "title": "Response Time [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", status!=\"CLIENT_ERROR\"}[1m])) / sum by (method, uri) (irate(http_client_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", status!=\"CLIENT_ERROR\"}[1m]))",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Response Status Groups 2xx / 4xx / 5xx / IO_ERROR [5m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"SUCCESS\"}[5m])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
       "legendFormat": "2xx",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"CLIENT_ERROR\"}[5m])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
       "legendFormat": "4xx",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"SERVER_ERROR\"}[5m])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
       "legendFormat": "5xx",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=\"IO_ERROR\"}[5m])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
       "legendFormat": "IO_ERROR",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Response Statuses [5m]",
     "type": "graph",
     "description": "Including IO_ERROR",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (status) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
       "legendFormat": "{{ status }}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Response Status 4xx by (method, path, status) [5m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (method, uri, status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"CLIENT_ERROR\"}[5m]))",
       "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
      }
     ]
    },
    {
     "title": "Response Status 5xx by (method, path, status) [5m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (method, uri, status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"SERVER_ERROR\"}[5m]))",
       "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
      }
     ]
    },
    {
     "title": "Request Count [selected range]",
     "type": "grafana-piechart-panel",
     "description": "Including cancelled",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[$__range]) > 0) by (method, uri))",
       "legendFormat": "{{ method }} {{ uri }}"
      }
     ]
    },
    {
     "title": "Total Requests [selected range]",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[$__range]) > 0)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Response Statuses [selected range]",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[$__range]) > 0) by (status))",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Errors by endpoint [selected range]",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=~\"4..|5..|IO_ERROR\"}[$__range]) > 0) by (method, uri))",
       "legendFormat": "{{ method }} {{ uri }}"
      }
     ]
    },
    {
     "title": "Total Errors [selected range]",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=~\"4..|5..|IO_ERROR\"}[$__range]) > 0)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Response Error Statuses [selected range]",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=~\"4..|5..|IO_ERROR\"}[$__range]) > 0) by (status))",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "TRACE, DEBUG, INFO [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"info\"}[5m]))",
     "legendFormat": "INFO",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"debug\"}[5m]))",
     "legendFormat": "DEBUG",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"trace\"}[5m]))",
     "legendFormat": "TRACE",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN, ERROR [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"warn\"}[5m]))",
     "legendFormat": "WARN",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"error\"}[5m]))",
     "legendFormat": "ERROR",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN by pod [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"warn\"}[5m]))",
     "legendFormat": "{{ pod }}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR by pod [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"error\"}[5m]))",
     "legendFormat": "{{ pod }}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Spring Cloud Stream (RabbitMQ / Kafka)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Rate [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!~\"$excluded_stream_channels\"}[1m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Timings [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (irate(spring_integration_send_seconds_sum{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!~\"$excluded_stream_channels\", result=\"success\"}[1m])) /  sum by (name) (irate(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!~\"$excluded_stream_channels\", result=\"success\"}[1m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Errors [5m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!=\"unknown\", result!=\"success\"}[5m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Kafka Consumer Offsets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (topic) (spring_cloud_stream_binder_kafka_offset{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "{{ topic }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Data Repositories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Method Invocation Count  - $spring_data_repository_name [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
     "repeat": "spring_data_repository_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (increase(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m]))",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "sum by (service) (increase(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m]))",
       "legendFormat": "total (press shift + left click to hide)"
      }
     ]
    },
    {
     "title": "Method Execution Time - $spring_data_repository_name [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
     "repeat": "spring_data_repository_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (irate(spring_data_repository_invocations_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m])) / sum by (method) (irate(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Method Exception Count  [5m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (repository, method) (increase(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", exception!=\"None\"}[5m]))",
       "legendFormat": "{{ repository }}.{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Cache Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 138 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (cache) (cache_size{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "{{ cache }}"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 138 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", result=\"hit\"}[5m])) by (cache) / sum(increase(cache_gets_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])) by (cache)",
       "legendFormat": "{{ cache }}"
      }
     ]
    },
    {
     "title": "Average Cache Puts [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (cache) ( \n  increase(cache_puts_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])\n)",
       "legendFormat": "{{ cache }}"
      }
     ]
    },
    {
     "title": "Average Cache Evictions [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (cache) ( \n  increase(cache_evictions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])\n)",
       "legendFormat": "{{ cache }}"
      }
     ]
    }
   ]
  },
  { "title": "Kubernetes Pods Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Uptime - $pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 74 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "(\n  min by (pod) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Running\"}[$__rate_interval])\n  ) == 1\n) * 0",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Pending\"}[$__rate_interval])\n  ) == 1\n) * 1",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Unknown\"}[$__rate_interval])\n  ) == 1\n) * 2",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Failed\"}[$__rate_interval])\n  ) == 1\n) * 3",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Succeeded\"}[$__rate_interval])\n  ) == 1\n) * 4",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod) (\n    kube_controller_pod{node=~\"$node\", namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min by (pod) (min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n  ) == 0\n) + 5",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods Restarts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}[$__rate_interval])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n) > 0",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum (\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}[$__rate_interval])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Kubernetes Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"}[$__rate_interval]))\n)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\", namespace=\"$namespace\"}[$__rate_interval]))\n)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", container=\"$app\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Kubernetes Ingress Important Statuses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 }
  },
  {
   "title": "503 (probably all backends not available) [5m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"503\"}[5m])) by (service)",
     "legendFormat": "{{ service }}"
    },
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"503\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "499 (client disconnected due to its timeout) [5m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"499\"}[5m])) by (service)",
     "legendFormat": "{{ service }}"
    },
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"499\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "HTTP Actuator - health / info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actuator Response Time [5m] - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 102 },
     "repeat": "pod",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", outcome=\"SUCCESS\", uri=~\"/actuator/(info|health)\"}[5m]) / irate(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", outcome=\"SUCCESS\", uri=~\"/actuator/(info|health)\"}[5m]))",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Actuator Response Statuses 4xx/5xx by (method, path, status, pod) [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (method, uri, status, pod) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome!=\"SUCCESS\", uri=~\"/actuator/(info|health)\"}[5m]))",
       "legendFormat": "{{ method }} {{ uri }} [{{ status }}] - {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Memory Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
     "repeat": "pod",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (area) (jvm_memory_used_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum by (area) (jvm_memory_committed_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum by (area) (jvm_memory_max_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Non-heap - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 107 },
     "repeat": "pod",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (area) (jvm_memory_used_bytes{area=\"nonheap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum by (area) (jvm_memory_committed_bytes{area=\"nonheap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Commited"
      }
     ]
    },
    {
     "title": "JVM Byte Buffers - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 113 },
     "repeat": "pod",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (id) (jvm_buffer_memory_used_bytes{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}) > 0",
       "legendFormat": "Used - {{ id }}"
      },
      {
       "expr": "sum by (id) (jvm_buffer_total_capacity_bytes{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}) > 0",
       "legendFormat": "Total Capacity - {{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Memory Details by Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap - $heap_part - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 218 },
     "repeat": "heap_part",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"$heap_part\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{area=\"heap\", id=\"$heap_part\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_memory_max_bytes{area=\"heap\", id=\"$heap_part\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Non-heap - Compressed Class Space - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 224 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"nonheap\", id=\"Compressed Class Space\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{area=\"nonheap\", id=\"Compressed Class Space\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Committed"
      }
     ]
    },
    {
     "title": "JVM Non-heap - Code Cache - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 224 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"nonheap\", id=~\"Code.*Cache\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{area=\"nonheap\", id=~\"Code.*Cache\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_memory_max_bytes{area=\"nonheap\", id=~\"Code.*Cache\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Non-heap - Metaspace - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 224 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"nonheap\", id=\"Metaspace\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{area=\"nonheap\", id=\"Metaspace\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Committed"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - CPU / Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage - $pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 190 },
     "repeat": "pod",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "Load Average - $pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 197 },
     "repeat": "pod",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "CPU Core Size"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 231 },
     "repeat": "pod",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 237 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations Count [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 167 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (command) (increase(mongodb_driver_commands_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "{{ command }}"
      },
      {
       "expr": "sum by (service) (increase(mongodb_driver_commands_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "total (press shift + left click to hide)"
      }
     ]
    },
    {
     "title": "Operations Execution Time [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 174 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (command) (irate(mongodb_driver_commands_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m])) / sum by (command) (irate(mongodb_driver_commands_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "{{ command }}"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB Connection Pool On Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Pool - size on $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_driver_pool_size{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "{{ server_address }}"
      }
     ]
    },
    {
     "title": "Connection Pool - in use on $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_driver_pool_checkedout{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "{{ server_address }}"
      }
     ]
    },
    {
     "title": "Wait queue size on $pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_driver_pool_waitqueuesize{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "{{ server_address }}"
      }
     ]
    }
   ]
  },
  {
   "title": "HikariCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 169 },
     "repeat": "pod",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_idle{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\", pool=~\"$hikaricp\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_active{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\", pool=~\"$hikaricp\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_pending{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\", pool=~\"$hikaricp\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Acquire Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 181 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_acquire_seconds_sum{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Connection Usage Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 181 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_sum{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Connection Creation Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 187 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_creation_seconds_sum{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Connection Timeout Count (Average)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (service) (hikaricp_connections_timeout_total{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\"})"
      }
     ]
    },
    {
     "title": "Connections Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (service) (hikaricp_connections{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 219 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tomcat_sessions_active_current_sessions{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}