{
 "title": "Spring Boot and libs",
 "description": "Dashboard for spring boot",
 "tags": [
  "java",
  "kubernetes",
  "spring boot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$app\"}, pod)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{pod=~\"$pod\"}, pool)"
    }
   },
   {
    "name": "spring_data_repository_name",
    "label": "Spring Repository Name",
    "query": {
     "query": "label_values(spring_data_repository_invocations_seconds_count{namespace=\"$namespace\", service=\"$app\"}, repository)"
    }
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   },
   {
    "name": "heap_part",
    "label": "Heap Part",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}, id)"
    }
   },
   {
    "name": "excluded_stream_channels",
    "query": ".*errorLogger|errorChannel|.*\\.errors(\\.bridge)?|unknown"
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state, name)"
    }
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": {
     "query": "label_values(resilience4j_retry_calls_total, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kameleoon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kameleoon Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(kameleoon_variation_counter_total{service=\"$app\", namespace=\"$namespace\"}[1m])) by (kameleoon_variation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kameleoon Valid Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(kameleoon_valid_channel_counter_total{service=\"$app\", namespace=\"$namespace\"}[1m])) by (kameleoon_valid_channel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kameleeon Visitor Code Status",
   "type": "timeseries",
   "description": "The graph shows whether client and backend kameleeon visitor codes match each other",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(kameleoon_visitor_code_matching_counter_total{service=\"$app\", namespace=\"$namespace\"}[1m])) by (match)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "TRACE, DEBUG, INFO [5m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"info\"}[5m]))",
       "legendFormat": "INFO",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      },
      {
       "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"debug\"}[5m]))",
       "legendFormat": "DEBUG",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      },
      {
       "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"trace\"}[5m]))",
       "legendFormat": "TRACE",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN, ERROR [5m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"warn\"}[5m]))",
       "legendFormat": "WARN",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      },
      {
       "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"error\"}[5m]))",
       "legendFormat": "ERROR",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN by pod [5m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"warn\"}[5m]))",
       "legendFormat": "{{ pod }}",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR by pod [5m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"error\"}[5m]))",
       "legendFormat": "{{ pod }}",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Cloud Stream (RabbitMQ / Kafka)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Rate [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!~\"$excluded_stream_channels\"}[1m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Timings [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (irate(spring_integration_send_seconds_sum{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!~\"$excluded_stream_channels\", result=\"success\"}[1m])) /  sum by (name) (irate(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!~\"$excluded_stream_channels\", result=\"success\"}[1m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Errors [5m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!=\"unknown\", result!=\"success\"}[5m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Kafka Consumer Offsets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (topic) (spring_cloud_stream_binder_kafka_offset{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "{{ topic }}"
      }
     ]
    },
    {
     "title": "Number of closed CircuitBreaker",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(resilience4j_circuitbreaker_state{state=\"closed\"})"
      }
     ]
    },
    {
     "title": "Number of open CircuitBreaker",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(resilience4j_circuitbreaker_state{state=~\"open|forced_open\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Data Repositories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Method Invocation Count  - $spring_data_repository_name [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "repeat": "spring_data_repository_name",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (increase(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m]))",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "sum by (service) (increase(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m]))",
       "legendFormat": "total (press shift + left click to hide)"
      }
     ]
    },
    {
     "title": "Method Execution Time - $spring_data_repository_name [1m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "repeat": "spring_data_repository_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (irate(spring_data_repository_invocations_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m])) / sum by (method) (irate(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Method Exception Count  [5m]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (repository, method) (increase(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", exception!=\"none\"}[5m]))",
       "legendFormat": "{{ repository }}.{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Cache Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (cache) (cache_size{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "{{ cache }}"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", result=\"hit\"}[5m])) by (cache) / sum(increase(cache_gets_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])) by (cache)",
       "legendFormat": "{{ cache }}"
      }
     ]
    },
    {
     "title": "Average Cache Puts [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (cache) ( \n  increase(cache_puts_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])\n)",
       "legendFormat": "{{ cache }}"
      }
     ]
    },
    {
     "title": "Average Cache Evictions [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (cache) ( \n  increase(cache_evictions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])\n)",
       "legendFormat": "{{ cache }}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Actuator - health / info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actuator Response Time [5m] - $pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "repeat": "pod",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", outcome=\"SUCCESS\", uri=~\"/actuator/(info|health)\"}[5m]) / irate(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", outcome=\"SUCCESS\", uri=~\"/actuator/(info|health)\"}[5m]))",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Actuator Response Statuses 4xx/5xx by (method, path, status, pod) [5m]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (method, uri, status, pod) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome!=\"SUCCESS\", uri=~\"/actuator/(info|health)\"}[5m]))",
       "legendFormat": "{{ method }} {{ uri }} [{{ status }}] - {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Summary - CircuitBreaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of closed CircuitBreaker",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(resilience4j_circuitbreaker_state{state=\"closed\"})"
      }
     ]
    },
    {
     "title": "Number of open CircuitBreaker",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(resilience4j_circuitbreaker_state{state=~\"open|forced_open\"})"
      }
     ]
    },
    {
     "title": "CircuitBreaker States",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Number" }
     ],
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_state{pod=~\"$pod\"}",
       "legendFormat": "{{ name }}: {{ state }}"
      }
     ]
    },
    {
     "title": "Number of half_open CircuitBreaker",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(resilience4j_circuitbreaker_state{state=\"half_open\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "CircuitBreaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "circuitbreaker_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Failure Rate: $circuitbreaker_name",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_failure_rate{pod=~\"$pod\",name=~\"$circuitbreaker_name\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Call rate: $circuitbreaker_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Calls/sec" }
     ],
     "targets": [
      {
       "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{pod=~\"$pod\",name=~\"$circuitbreaker_name\"}[1m])",
       "legendFormat": "{{ kind }} "
      },
      {
       "expr": "rate(resilience4j_circuitbreaker_calls_total{pod=~\"$pod\",name=~\"$circuitbreaker_name\"}[1m])",
       "legendFormat": "{{ kind  }} "
      }
     ]
    },
    {
     "title": "Buffered calls: $circuitbreaker_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Number" }
     ],
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_buffered_calls{pod=~\"$pod\",name=~\"$circuitbreaker_name\"}",
       "legendFormat": "{{ kind }}"
      },
      {
       "expr": "resilience4j_circuitbreaker_max_buffered_calls{pod=~\"$pod\",name=~\"$circuitbreaker_name\"}",
       "legendFormat": "maximum"
      }
     ]
    },
    {
     "title": "Call duration percentiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "s", "label": "Average duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{pod=~\"$pod\", name=~\"$circuitbreaker_name\"}[1m])) by (le))",
       "legendFormat": "90th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=~\"$application\", instance=~\"$instance\", name=~\"$circuitbreaker_name\"}[1m])) by (le))",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.98, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{pod=~\"$pod\", name=~\"$circuitbreaker_name\"}[1m])) by (le))",
       "legendFormat": "98th Percentile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{pod=~\"$pod\", name=~\"$circuitbreaker_name\"}[1m])) by (le))",
       "legendFormat": "Median"
      }
     ]
    },
    {
     "title": "Average call durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "s", "label": "Average duration" }
     ],
     "targets": [
      {
       "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{pod=~\"$pod\",name=~\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{pod=~\"$pod\",name=~\"$circuitbreaker_name\"}[1m])",
       "legendFormat": "{{ kind }}"
      },
      {
       "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{pod=~\"$pod\",name=~\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{pod=~\"$pod\",name=~\"$circuitbreaker_name\"}[1m]))",
       "legendFormat": "total "
      }
     ]
    }
   ]
  },
  {
   "title": "Retry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "retry_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Rate retryable calls: $retry_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Number of calls" }
     ],
     "targets": [
      {
       "expr": "rate(resilience4j_retry_calls_total{pod=~\"$pod\",name=~\"$retry_name\",}[1m])",
       "legendFormat": "{{ kind }}"
      }
     ]
    }
   ]
  }
 ]
}