{
 "title": "Service",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(http_server_requests_seconds, namespace)"
   },
   {
    "name": "Service",
    "query": "label_values(http_server_requests_seconds{namespace=\"$Namespace\"}, service)"
   },
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "UriTemplate", "query": "/api.*,/.*" }
  ]
 },
 "panels": [
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", uri=~\"$UriTemplate\"}[$Interval]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Request info",
   "type": "table",
   "gridPos": { "h": 27, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", uri=~\"$UriTemplate\"}[$__range]))"
    },
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", uri=~\"$UriTemplate\", status=~\"2..\"}[$__range])) / sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", uri=~\"$UriTemplate\"}[$__range])) > 0"
    },
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", uri=~\"$UriTemplate\", status=~\"4..\"}[$__range])) / sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", uri=~\"$UriTemplate\"}[$__range])) > 0"
    },
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", uri=~\"$UriTemplate\", status=~\"5..\"}[$__range])) / sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", uri=~\"$UriTemplate\"}[$__range])) > 0"
    }
   ]
  },
  {
   "title": "Request average time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds{namespace=\"$Namespace\", service=\"$Service\", uri=~\"$UriTemplate\", quantile=\"0.95\"}) by (method, uri) > 0",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Request status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", uri=~\"$UriTemplate\"}[$Interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}