{
 "title": "Acquiring Reconcillation",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Sended transactions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service, topic) (increase(kafka_producer_topic_record_send_total{namespace=\"billing-prod\", service=\"acq-rc-tx-importer\", topic=\"acquiringservices-prod-system-int-payment-acquiringreconciliation-v1\"}[5m]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by (service) (increase(kafka_processed_messages{service=\"repobanktx\", status=\"success\"}[5m]))",
     "legendFormat": "RepoFactory: {{label_name}}"
    }
   ]
  },
  {
   "title": "Corrupted Files Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(service) (increase(corrupted_files_count_total[1h]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Corrupted Transactions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(service) (increase(corrupted_transactions_count_total[1h]))",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}