{
 "title": "Alive statistic",
 "time": { "from": "2024-12-12T00:07:36.371Z", "to": "2024-12-12T12:07:36.371Z" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Incident Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum by (processName, service) (camunda_incident_count{namespace=\"$namespace\"}))/ (count by (processName, service) (camunda_incident_count{namespace=\"$namespace\"}))",
     "legendFormat": "{{service}} | {{ processName }}"
    }
   ]
  },
  {
   "title": "Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (processName, service) (camunda_instance_count{namespace=\"$namespace\"}) / (count by (processName, service) (camunda_instance_count{namespace=\"$namespace\"}))",
     "legendFormat": "{{service}} | {{ processName }}"
    }
   ]
  },
  {
   "title": "Number of Log Errors",
   "type": "timeseries",
   "description": "Number of errors by service",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service) (idelta(logback_events_total{namespace=\"$namespace\", level=\"error\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod)(jvm_memory_used_bytes{namespace=\"$namespace\", area=\"heap\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kakfa Consumer lags",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(sum by(instance, group, topic)(kafka_burrow_partition_lag{group=~\".*billing-group.*prod.*|.*phtt-group.*|.*acquiringrecon-group.*|b2bm-group.*\"})) by (group, topic)",
     "legendFormat": "{{topic}} | {{ group }}"
    }
   ]
  },
  {
   "title": "Time live",
   "type": "stat",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Memory Usage per Instance",
   "type": "table-old",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "(sum by (pod) (jvm_memory_used_bytes{ namespace=\"$namespace\", area=\"heap\"}))*100/(sum by (pod) (jvm_memory_max_bytes{namespace=\"$namespace\", area=\"heap\"})) ",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Load Average by CPU Core",
   "type": "table-old",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (pod) (system_load_average_1m{namespace=\"$namespace\"}*100/system_cpu_count{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}