{
 "title": "AS-SP business metrics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Received transition objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task-in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(idelta(billing_task_in_processed_count{namespace = \"$namespace\", service=~\"as-sp-task-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "PROCESSED"
    },
    {
     "expr": "sum(idelta(billing_task_in_skipped_count{namespace = \"$namespace\", service=~\"as-sp-task-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SKIPPED"
    },
    {
     "expr": "sum(idelta(billing_task_in_dlt_count{namespace = \"$namespace\", service=~\"as-sp-task-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DLT"
    }
   ]
  },
  {
   "title": "Receipt-in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(idelta(billing_receipt_in_processed_count{namespace = \"$namespace\", service=~\"as-sp-receipt-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "PROCESSED"
    },
    {
     "expr": "sum(idelta(billing_receipt_in_skipped_count{namespace = \"$namespace\", service=~\"as-sp-receipt-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SKIPPED"
    },
    {
     "expr": "sum(idelta(billing_receipt_in_dlt_count{namespace = \"$namespace\", service=~\"as-sp-receipt-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DLT"
    }
   ]
  },
  {
   "title": "Reconciliation-in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(idelta(billing_reconciliation_in_received_count{namespace = \"$namespace\", service=~\"as-sp-reconciliation-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    }
   ]
  },
  {
   "title": "Command-in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(idelta(billing_command_in_processed_count{namespace = \"$namespace\", service=~\"as-sp-report-command-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "PROCESSED"
    },
    {
     "expr": "sum(idelta(billing_command_in_dlt_count{namespace = \"$namespace\", service=~\"as-sp-report-command-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DLT"
    }
   ]
  },
  {
   "title": "Edic-status-in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_edic_status_in_received_status_count{namespace = \"$namespace\", service=~\"as-sp-report-edic-status-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "PROCESSED"
    },
    {
     "expr": "sum(idelta(billing_report_edic_status_in_send_dlt_status_count{namespace = \"$namespace\", service=~\"as-sp-report-edic-status-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DLT"
    }
   ]
  },
  {
   "title": "Contract-in",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_sp_contract_in_received_contract_count{namespace = \"$namespace\", service=~\"as-sp-contract-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_as_sp_contract_in_send_contract_count{namespace = \"$namespace\", service=~\"as-sp-contract-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "PROCESSED"
    },
    {
     "expr": "sum(idelta(billing_as_sp_contract_in_send_to_dlt_contract_count{namespace = \"$namespace\", service=~\"as-sp-contract-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DLT"
    }
   ]
  },
  { "title": "Sent transition objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Report-out",
   "type": "timeseries",
   "description": "Количество полученных и отправленных отчётов",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_out_received_report_for_sp_count{namespace = \"$namespace\", service=~\"as-sp-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED FOR SP"
    },
    {
     "expr": "sum(idelta(billing_report_out_processed_report_to_sp_count{namespace = \"$namespace\", service=~\"as-sp-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SEND TO SP"
    },
    {
     "expr": "sum(idelta(billing_report_out_processed_report_to_hands_ru_count{namespace = \"$namespace\", service=~\"as-sp-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SEND TO HANDS.RU"
    },
    {
     "expr": "sum(idelta(billing_report_out_received_report_for_dp_count{namespace = \"$namespace\", service=~\"as-sp-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED FOR DP"
    },
    {
     "expr": "sum(idelta(billing_report_out_received_report_from_history_count{namespace = \"$namespace\", service=~\"as-sp-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED FROM HISTORY"
    },
    {
     "expr": "sum(idelta(billing_report_out_processed_report_to_data_platform_count{namespace = \"$namespace\", service=~\"as-sp-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SEND TO DP"
    }
   ]
  },
  {
   "title": "Report-edic-out",
   "type": "timeseries",
   "description": "Количество отчётов полученных перекладывателем и  отправленных в EDI-Сonnector",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_edic_out_received_report_count{namespace = \"$namespace\", service=~\"as-sp-report-edic-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_report_edic_out_send_report_count{namespace = \"$namespace\", service=~\"as-sp-report-edic-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SEND"
    },
    {
     "expr": "sum(idelta(billing_report_edic_out_send_to_dlt_report_count{namespace = \"$namespace\", service=~\"as-sp-report-edic-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SEND TO DLT"
    }
   ]
  },
  { "title": "Received contracts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Commission-manager",
   "type": "timeseries",
   "description": "Количество сохранённых и обновлённых правил комиссии(контрактов)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(idelta(billing_commission_manager_saved_or_updated_contract{namespace = \"$namespace\", service=~\"as-sp-commission-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SAVED OR UPDATE"
    }
   ]
  },
  {
   "title": "Contract-manager",
   "type": "timeseries",
   "description": "Количество сохранённых, обновленных и пропущенных из-за дублирования контрактов",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(idelta(billing_contract_manager_saved_contracts{namespace = \"$namespace\", service=~\"as-sp-contract-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SAVED"
    },
    {
     "expr": "sum(idelta(billing_contract_manager_updated_contracts{namespace = \"$namespace\", service=~\"as-sp-contract-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(idelta(billing_contract_manager_duplicated_contracts{namespace = \"$namespace\", service=~\"as-sp-contract-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DUPLICATED"
    },
    {
     "expr": "sum(idelta(billing_contract_manager_saved_edm_contract{namespace = \"$namespace\", service=~\"as-sp-contract-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SAVED EDM ATTRIBUTE"
    }
   ]
  },
  {
   "title": "Report-scheduler",
   "type": "timeseries",
   "description": "Количество сохранённых, обновлённых и пропущенных контрактов",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_scheduler_saved_and_updated_contracts{namespace = \"$namespace\", service=~\"as-sp-report-scheduler.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SAVED OR UPDATE"
    },
    {
     "expr": "sum(idelta(billing_report_scheduler_skipped_contracts{namespace = \"$namespace\", service=~\"as-sp-report-scheduler.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SKIPPED"
    }
   ]
  },
  { "title": "Agent report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Agent report data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_sp_task_received_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "TASK"
    },
    {
     "expr": "sum(idelta(billing_report_manager_receipt_received_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIPT"
    },
    {
     "expr": "sum(idelta(billing_report_manager_sp_reconciliation_received_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECONCILIATION"
    }
   ]
  },
  {
   "title": "Agent report commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_compile_received_command_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPILE"
    },
    {
     "expr": "sum(idelta(billing_report_manager_approve_received_command_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "APPROVE"
    },
    {
     "expr": "sum(idelta(billing_report_manager_for_payment_received_command_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FOR PAYMENT"
    }
   ]
  },
  {
   "title": "COMPILE commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_compile_received_command_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPLETED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FAILED"
    }
   ]
  },
  {
   "title": " Generated agent reports in DRAFT status",
   "type": "timeseries",
   "description": "Количество сгенерированных отчётов в статусе DRAFT",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_generated_agent_report_draft_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DRAFT"
    }
   ]
  },
  {
   "title": "PROCESSING to COMPLETED transition time COMPILE command",
   "type": "timeseries",
   "description": "Время перевода COMPILE команды из PROCESSING в COMPLETED. Так же эту метрику можно считать временем генерации отчёта.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "PROCESSING to FAILED transition time COMPILE command",
   "type": "timeseries",
   "description": "Время перевода COMPILE команды из PROCESSING в FAILED.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "APPROVE commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_approve_received_command_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPLETED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FAILED"
    }
   ]
  },
  {
   "title": " Generated agent reports in APPROVED status",
   "type": "timeseries",
   "description": "Количество сгенерированных отчётов в статусе APPROVED",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_generated_agent_report_approved_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "APPROVED"
    }
   ]
  },
  {
   "title": "PROCESSING to COMPLETED transition time APPROVE command",
   "type": "timeseries",
   "description": "Время перевода APPROVE команды из PROCESSING в COMPLETED. Так же эту метрику можно считать временем генерации отчёта.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "PROCESSING to FAILED transition time APPROVE command",
   "type": "timeseries",
   "description": "Время перевода APPROVE команды из PROCESSING в FAILED.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "FOR PAYMENT commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_for_payment_received_command_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPLETED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FAILED"
    }
   ]
  },
  {
   "title": " Generated agent reports in FOR_PAYMENT status",
   "type": "timeseries",
   "description": "Количество сгенерированных отчётов в статусе FOR_PAYMENT",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_generated_agent_report_for_payment_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FOR_PAYMENT"
    }
   ]
  },
  {
   "title": "PROCESSING to COMPLETED transition time FOR_PAYMENT command",
   "type": "timeseries",
   "description": "Время перевода FOR_PAYMENT команды из PROCESSING в COMPLETED. Так же эту метрику можно считать временем генерации отчёта.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "PROCESSING to FAILED transition time FOR_PAYMENT command",
   "type": "timeseries",
   "description": "Время перевода FOR_PAYMENT команды из PROCESSING в FAILED. Так же эту метрику можно считать временем генерации отчёта.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": " Generated agent reports by approvalType",
   "type": "timeseries",
   "description": "Количество сгенерированных отчётов по типу подтверждения",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_generated_agent_report_manual_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "MANUAL"
    },
    {
     "expr": "sum(idelta(billing_report_manager_generated_agent_report_auto_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "AUTO"
    }
   ]
  },
  {
   "title": "Printing form generation time",
   "type": "timeseries",
   "description": "Время генерации печатной формы, с момента получения отчёта и до момента когда его можно получить по ссылке из s3",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "sum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"0.1\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 0.1s"
    },
    {
     "expr": "(sum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"0.3\"}[$__rate_interval])) - \r\nsum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"0.1\"}[$__rate_interval]))) >= 0",
     "legendFormat": "0.1-0.3s"
    },
    {
     "expr": "(sum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"1.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"0.5\"}[$__rate_interval]))) >= 0",
     "legendFormat": "0.5-1s"
    },
    {
     "expr": "(sum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"1.5\"}[$__rate_interval])) - \r\nsum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"1.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-1.5s"
    },
    {
     "expr": "(sum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"5.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"1.5\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1.5-5s"
    },
    {
     "expr": "(sum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"10.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"5.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-10s"
    },
    {
     "expr": "(sum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"54.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-54s"
    },
    {
     "expr": "(sum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_print_form_manager_proccessing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", le=\"54.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "54s+"
    }
   ]
  },
  {
   "title": "Incidents in camunda",
   "type": "timeseries",
   "description": "Количество сгенерированных отчётов по типу подтверждения",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum by (processName) (camunda_incident_count{service=~\"as-sp-report-manager.*\", namespace=\"$namespace\"}))",
     "legendFormat": "{{processName}}"
    }
   ]
  },
  { "title": "Revenue report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Revenue COMPILE commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_revenue_compile_received_command_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPILE"
    }
   ]
  },
  {
   "title": " Generated REVENUE reports",
   "type": "timeseries",
   "description": "Количество сгенерированных revenue отчётов",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_generated_revenue_report_count{namespace = \"$namespace\", service=~\"as-sp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPILE"
    }
   ]
  },
  {
   "title": "Time of successful creation of the REVENUE report",
   "type": "timeseries",
   "description": "Время успешного выполнения команды на генерацию отчёта REVENUE ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_successfully_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "Time of unsuccessful creation of the REVENUE report",
   "type": "timeseries",
   "description": "Время неудачного выполнения команды на генерацию отчёта REVENUE ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_report_manager_processing_revenue_failed_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  { "title": "Contracts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Contracts count ",
   "type": "stat",
   "description": "Общее количество контрактов в contract-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": " sum(billing_contract_manager_total_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"}) / count by (app) (billing_contract_manager_total_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"})",
     "legendFormat": "Total contracts:"
    },
    {
     "expr": " sum(billing_contract_manager_total_edm_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"}) / count by (app) (billing_contract_manager_total_edm_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"})",
     "legendFormat": "EDM Contracts:"
    }
   ]
  },
  {
   "title": "Contracts by approval type",
   "type": "piechart",
   "description": "Общее количество контрактов по типу подтверждения",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": " sum(billing_contract_manager_total_auto_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"}) / count by (app) (billing_contract_manager_total_auto_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"})",
     "legendFormat": "AUTO"
    },
    {
     "expr": " sum(billing_contract_manager_total_manual_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"}) / count by (app) (billing_contract_manager_total_manual_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"})",
     "legendFormat": "MANUAL"
    }
   ]
  },
  {
   "title": "Contracts by period",
   "type": "piechart",
   "description": "Общее количество контрактов по периоду генерации в report-scheduler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": " sum(billing_report_scheduler_contracts_with_schedule_once_week{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"}) / count by (app) (billing_report_scheduler_contracts_with_schedule_once_week{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"})",
     "legendFormat": "ONCE_WEEK"
    },
    {
     "expr": " sum(billing_report_scheduler_contracts_with_schedule_twice_month{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"}) / count by (app) (billing_report_scheduler_contracts_with_schedule_twice_month{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"})",
     "legendFormat": "TWICE_MONTH"
    },
    {
     "expr": " sum(billing_report_scheduler_contracts_with_schedule_once_month{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"}) / count by (app) (billing_report_scheduler_contracts_with_schedule_once_month{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"})",
     "legendFormat": "ONCE_MONTH"
    },
    {
     "expr": " sum(billing_report_scheduler_contracts_with_schedule_daily{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"}) / count by (app) (billing_report_scheduler_contracts_with_schedule_daily{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"})",
     "legendFormat": "DAILY"
    }
   ]
  },
  {
   "title": "Commands by period",
   "type": "piechart",
   "description": "Количество команд, которые должны отправиться в определённый период времени.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": " sum(billing_report_scheduler_contracts_by_store_with_schedule_once_week{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"}) / count by (app) (billing_report_scheduler_contracts_by_store_with_schedule_once_week{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"})",
     "legendFormat": "ONCE_WEEK"
    },
    {
     "expr": " sum(billing_report_scheduler_contracts_by_store_with_schedule_twice_month{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"}) / count by (app) (billing_report_scheduler_contracts_by_store_with_schedule_twice_month{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"})",
     "legendFormat": "TWICE_MONTH"
    },
    {
     "expr": " sum(billing_report_scheduler_contracts_by_store_with_schedule_once_month{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"}) / count by (app) (billing_report_scheduler_contracts_by_store_with_schedule_once_month{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"})",
     "legendFormat": "ONCE_MONTH"
    },
    {
     "expr": " sum(billing_report_scheduler_contracts_by_store_with_schedule_daily{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"}) / count by (app) (billing_report_scheduler_contracts_by_store_with_schedule_daily{namespace=\"$namespace\", service=~\"as-sp-report-scheduler.*\"})",
     "legendFormat": "DAILY"
    }
   ]
  },
  {
   "title": "Share of EDM contracts ",
   "type": "gauge",
   "description": "Общее количество контрактов по периоду генерации в report-scheduler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": " sum(billing_contract_manager_total_edm_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"} / billing_contract_manager_total_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"}) / count by (app) (billing_contract_manager_total_edm_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"} / billing_contract_manager_total_contracts{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\"})",
     "legendFormat": "Contracts"
    }
   ]
  },
  { "title": "HTTP statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "Cost-center-manager api response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"cost-center-manager.*\", uri=~\"/v1.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"cost-center-manager.*\", uri=~\"/v1.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Cost-center-manager api errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"cost-center-manager.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Contract-manager api response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\", uri=~\"/v1.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\", uri=~\"/v1.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Contract-manager api errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-sp-contract-manager.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Commission-manager api response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-sp-commission-manager.*\", uri=~\"/v1.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-sp-commission-manager.*\", uri=~\"/v1.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Commission-manager api errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-sp-commission-manager.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Report-manager to Commission-manager api response",
   "type": "timeseries",
   "description": "Время ответа commission-manager при вызове из report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", uri=~\"/v1/commissions.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", uri=~\"/v1/commissions.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Report-manager to Commission-manager api errors",
   "type": "timeseries",
   "description": "Время ошибочного ответа commission-manager при вызове из report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-sp-report-manager.*\" ,  uri=~\"/v1/commissions.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Report-manager to Contract-manager api response",
   "type": "timeseries",
   "description": "Время ответа contract-manager при вызове из report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", uri=~\"/v1/contracts.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-sp-report-manager.*\", uri=~\"/v1/contracts.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Report-manager to Contract-manager api errors",
   "type": "timeseries",
   "description": "Время ошибочного ответа contract-manager при вызове из report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-sp-report-manager.*\",  uri=~\"/v1/contracts.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Print-form-manager api response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", uri=~\"/v1.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", uri=~\"/v1.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Print-form-manager api errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Cloud-print api response",
   "type": "timeseries",
   "description": "Время ответа cloud-print при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", uri=~\"/cloud-print/v1/actions/.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", uri=~\"/cloud-print/v1/actions/.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Cloud-print api errors",
   "type": "timeseries",
   "description": "Время jошибочного ответа cloud-print при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", uri=~\"/cloud-print/v1/actions/.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0 ",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Print-form-manager to Cost-center-manager api response",
   "type": "timeseries",
   "description": "Время ответа cost-center-manager при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", uri=~\"/v1/cost-centers.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", uri=~\"/v1/cost-centers.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Print-form-manager to Cost-center-manager api errors",
   "type": "timeseries",
   "description": "Время ошибочного ответа cost-center-manager при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\", uri=~\"/v1/cost-centers.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0 ",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Print-form-manager to S3 upload file ",
   "type": "timeseries",
   "description": "Время загрузки отчёта в S3 при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
   "targets": [
    {
     "expr": "sum by (method, exception) (irate(billing_print_form_manager_s3_upload_request_seconds_count{namespace=\"$namespace\", service=~\"as-sp-print-form-manager.*\"}[$__rate_interval])) >= 0 ",
     "legendFormat": "{{method}} "
    }
   ]
  }
 ]
}