{
 "title": "EDI-Connector business metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Edic contracts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Received contracts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(idelta(billing_edic_contract_manager_received_contracts{namespace = \"$namespace\", service=~\"edic-contract-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_edic_contract_manager_saved_contracts{namespace = \"$namespace\", service=~\"edic-contract-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SAVED"
    }
   ]
  },
  {
   "title": "Contracts count",
   "type": "stat",
   "description": "Общее количество контрактов в edic-contract-manager",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(billing_edic_contract_manager_total_contracts{namespace = \"$namespace\", service=~\"edic-contract-manager.*\"}) / count by (app) (billing_edic_contract_manager_total_contracts{namespace = \"$namespace\", service=~\"edic-contract-manager.*\"})",
     "legendFormat": "Total contracts:"
    }
   ]
  },
  { "title": "Edic report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Received reports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(idelta(billing_edic_report_manager_received_report_count{namespace = \"$namespace\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_received_ucd_report_count{namespace = \"$namespace\"}[$__rate_interval])) >= 0",
     "legendFormat": "UCD"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_received_utd_report_count{namespace = \"$namespace\"}[$__rate_interval])) >= 0",
     "legendFormat": "UTD"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_received_empty_report_count{namespace = \"$namespace\"}[$__rate_interval])) >= 0",
     "legendFormat": "EMPTY"
    }
   ]
  },
  {
   "title": "PROCESSING to SUCCESS all documents",
   "type": "timeseries",
   "description": "Время подписания всех документов по отчёту. Измеряется в часах. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"3600.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 1h"
    },
    {
     "expr": "(sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"7200.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"3600.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2h"
    },
    {
     "expr": "(sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"14400.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"7200.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-4h"
    },
    {
     "expr": "(sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"21600.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"14400.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-6h"
    },
    {
     "expr": "(sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"28800.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"21600.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8h"
    },
    {
     "expr": "(sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"36000.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"28800.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-10h"
    },
    {
     "expr": "(sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"43200.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"36000.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-12h"
    },
    {
     "expr": "(sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"50400.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"43200.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-14h"
    },
    {
     "expr": "(sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"57600.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"50400.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "14-16h"
    },
    {
     "expr": "(sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"86400.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"57600.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "16-24h"
    },
    {
     "expr": "(sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_bucket{namespace=\"$namespace\", service=~\"edic-report-manager.*\", le=\"86400.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "24h+"
    }
   ]
  },
  {
   "title": "Signed documents",
   "type": "timeseries",
   "description": "Количество подписанных документов ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(idelta(billing_edic_report_manager_processing_to_success_all_document_metric_seconds_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SIGNED"
    }
   ]
  },
  {
   "title": "Edic request statuses",
   "type": "timeseries",
   "description": "Статусы отправленные в as-sp",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(idelta(billing_edic_report_manager_received_report_request_status_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_sent_report_request_status_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SENT"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_skipped_report_request_status_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SKIPPED"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_sent_to_dlt_report_request_status_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SENT TO DLT"
    }
   ]
  },
  { "title": "Edic request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Received request events",
   "type": "timeseries",
   "description": "Количество полученных событий запроса",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(idelta(billing_edic_report_manager_received_event_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_success_event_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_skipped_event_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SKIPPED"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_failed_event_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FAILED"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_sent_to_dlt_event_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SENT TO DLT"
    }
   ]
  },
  {
   "title": "Received failed request events",
   "type": "timeseries",
   "description": "Количество полученных неудачных событий запроса по типу.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(idelta(billing_edic_report_manager_transformation_failed_event_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "TRANSFORMATION"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_validation_failed_event_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "VALIDATION"
    },
    {
     "expr": "sum(idelta(billing_edic_report_manager_sending_provider_failed_event_count{namespace = \"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SENDING PROVIDER"
    }
   ]
  },
  { "title": "HTTP statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Сontract-manager api response",
   "type": "timeseries",
   "description": "Время ответа contract-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"edic-contract-manager.*\", uri=~\"/v1.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"edic-contract-manager.*\", uri=~\"/v1.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Сontract-manager api errors",
   "type": "timeseries",
   "description": "Время ошибочного ответа contract-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"edic-contract-manager.*\", status=~\"3..|4..|5..\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Report-manager to Сontract-manager api response",
   "type": "timeseries",
   "description": "Время ответа contract-manager при вызове из report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"edic-report-manager.*\", uri=~\"/v1/contracts.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"edic-report-manager.*\", uri=~\"/v1/contracts.*\"}[$__range]))",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "Report-manager to Сontract-manager api errors",
   "type": "timeseries",
   "description": "Время ошибочного ответа contract-manager при вызове из report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{ namespace=\"$namespace\", service=~\"edic-report-manager.*\",  uri=~\"/v1/contracts.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "Edic-report-manager to Edi api response",
   "type": "timeseries",
   "description": "Время ответа Edi платформы при вызове из edic-report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"edic-report-manager.*\", uri=~\"/partners/edi-exchange-platform/v2/requests.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"edic-report-manager.*\", uri=~\"/partners/edi-exchange-platform/v2/requests.*\"}[$__range]))",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "Edic-report-manager to Edi api errors",
   "type": "timeseries",
   "description": "Время ошибочного ответа Edi платформы при вызове из edic-report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{ namespace=\"$namespace\", service=~\"edic-report-manager.*\", uri=~\"/partners/edi-exchange-platform/v2/requests.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "Send request to EDI platform",
   "type": "timeseries",
   "description": "Количество отправленных запросов в EDI платформу",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(idelta(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"edic-report-manager.*\", uri=~\"/partners/edi-exchange-platform/v2/requests.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "S3 upload XML file",
   "type": "timeseries",
   "description": "Время загрузки отчёта в формате xml в s3. В миллисекундах.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum by (method, exception) (irate(billing_edic_report_manager_s3_upload_xml_request_metric_seconds_count{namespace=\"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0 ",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "S3 generate url for pdf",
   "type": "timeseries",
   "description": "Время генерации ссылки на отчёт в формате pdf. В миллисекундах.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum by (method, exception) (irate(billing_edic_report_manager_s3_get_pdf_url_metric_seconds_count{namespace=\"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0 ",
     "legendFormat": "Method: {{method}} - Exception: {{exception}}"
    }
   ]
  },
  {
   "title": "S3 generate url for xml",
   "type": "timeseries",
   "description": "Время генерации ссылки на отчёт в формате xml. В миллисекундах.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum by (method, exception) (irate(billing_edic_report_manager_s3_get_xml_url_metric_seconds_count{namespace=\"$namespace\", service=~\"edic-report-manager.*\"}[$__rate_interval])) >= 0 ",
     "legendFormat": "{{method}} "
    }
   ]
  }
 ]
}