{
 "title": "HTTP req/resp statistic",
 "description": "Dashboard for analyzing individual endpoints' performance using metric http_server_requests",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(jvm_classes_loaded_classes, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$service\"}, pod)"
   },
   {
    "name": "url",
    "label": "URL",
    "query": "label_values(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", uri!~\"$excluded_urls\"}, uri)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", uri=\"$url\"}, method)"
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|UNKNOWN|/camunda/.*|ROOT|REDIRECTION|root|NOT_FOUND|/webjars/.*"
   }
  ]
 },
 "panels": [
  { "title": "Request Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", uri=\"$url\", method=\"$method\"}[1m]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Request Count [10m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", uri=\"$url\", method=\"$method\"}[10m]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Request Count [1h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", uri=\"$url\", method=\"$method\"}[1h]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Response Time [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", exception=\"None\", uri=\"$url\", method=\"$method\"}[1m])) / sum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", exception=\"None\", uri=\"$url\", method=\"$method\"}[1m]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Response Time [10m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", exception=\"None\", uri=\"$url\", method=\"$method\"}[10m])) / sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", exception=\"None\", uri=\"$url\", method=\"$method\"}[10m]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Response Time [1h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", exception=\"None\", uri=\"$url\", method=\"$method\"}[1h])) / sum by (method, uri) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", exception=\"None\", uri=\"$url\", method=\"$method\"}[1h]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  { "title": "Response Statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Response Status Ratio [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (status) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", uri=\"$url\", method=\"$method\"}[5m])) / scalar(sum by (service) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", uri=\"$url\", method=\"$method\"}[5m])))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Status Ratio [1h]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (status) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", uri=\"$url\", method=\"$method\"}[1h])) / scalar(sum by (service) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", uri=\"$url\", method=\"$method\"}[1h])))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Statuses [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sort_desc(sum by (status) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", uri=\"$url\", method=\"$method\"}[$__range]) > 0))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Exception Types [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", uri=\"$url\", method=\"$method\", exception!=\"None\"}[$__range]) > 0) by (exception))",
     "legendFormat": "{{ exception }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "(4xx / 5xx Status + Exception) Count [5m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status, exception) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", outcome!=\"SUCCESS\", uri=\"$url\", method=\"$method\"}[5m]))",
     "legendFormat": "[{{ status }}] {{ exception }}"
    }
   ]
  },
  {
   "title": "(4xx / 5xx Status + Exception) Count [1h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status, exception) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", outcome!=\"SUCCESS\", uri=\"$url\", method=\"$method\"}[1h]))",
     "legendFormat": "[{{ status }}] {{ exception }}"
    }
   ]
  }
 ]
}