{
 "title": "Kafka consumers statistic",
 "description": "Kafka metrics depends on spring-kafka-metrics for consumers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, namespace)"
    }
   },
   {
    "name": "client_id",
    "label": "client_id",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_bytes_consumed_total{namespace=\"$namespace\"},client_id)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_bytes_consumed_total{namespace=\"$namespace\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "fetch latency",
     "type": "graph",
     "description": "The time taken for a fetch request.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "Avg - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_fetch_manager_fetch_latency_max{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "Max - {{client_id}}"
      }
     ]
    },
    {
     "title": "commit latency",
     "type": "graph",
     "description": "The time taken for a commit request",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_commit_latency_avg{namespace=\"$namespace\"}",
       "legendFormat": "Avg - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_commit_latency_max{namespace=\"$namespace\"}",
       "legendFormat": "Max - {{client_id}}"
      }
     ]
    },
    {
     "title": "Join latency",
     "type": "graph",
     "description": "The time taken for a group rejoin",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "kafka_consumer_coordinator_join_time_avg{namespace=\"$namespace\"}",
       "legendFormat": "avg - {{client_id}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "sync latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_sync_time_avg{namespace=\"$namespace\"}",
       "legendFormat": "Avg- {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_sync_time_max{namespace=\"$namespace\"}",
       "legendFormat": "Max - {{client_id}}"
      }
     ]
    },
    {
     "title": "Fetch throttle",
     "type": "graph",
     "description": "The average throttle time in ms",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_avg{namespace=\"$namespace\"}",
       "legendFormat": "Avg - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_max{namespace=\"$namespace\"}",
       "legendFormat": "Max - {{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heartbeat",
     "type": "graph",
     "description": "The time taken to receive a response to a heartbeat request",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_heartbeat_response_time_max{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "Max time - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_last_heartbeat_seconds_ago{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "Last heartbeat duration - {{client_id}}"
      }
     ]
    },
    {
     "title": "Commits",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_commit_rate{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "The number of commit calls per second - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_join_rate{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "The number of group joins per seconds - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_heartbeat_rate{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "The number of heartbeats per second\n - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_sync_rate{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "The number of group syncs per second - {{client_id}}"
      }
     ]
    },
    {
     "title": "Partitions",
     "type": "stat",
     "description": "The number of partitions currently assigned to this consumer",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "kafka_consumer_coordinator_assigned_partitions{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_connection_count_total{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "Total connections - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_connection_creation_total{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "Total created - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_connection_close_total{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "Total closed - {{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "lead records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_lead_avg{namespace=\"$namespace\", client_id=~\"$client_id\", topic=~\"$topic\"}",
       "legendFormat": "lead avg records - {{client_id}} - {{topic}}"
      },
      {
       "expr": "kafka_consumer_fetch_manager_records_lead_min{namespace=\"$namespace\", client_id=~\"$client_id\", topic=~\"$topic\"}",
       "legendFormat": "lead min records - {{client_id}} - {{topic}}"
      },
      {
       "expr": "kafka_consumer_fetch_manager_records_lead{namespace=\"$namespace\", client_id=~\"$client_id\", topic=~\"$topic\"}",
       "legendFormat": "lead records - {{client_id}} - {{topic}}"
      }
     ]
    },
    {
     "title": "Consumer lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_lag{namespace=\"$namespace\", client_id=~\"$client_id\", topic=~\"$topic\"}",
       "legendFormat": "Total lag - {{client_id}} - {{topic}}"
      },
      {
       "expr": "kafka_consumer_fetch_manager_records_lag_avg{namespace=\"$namespace\", client_id=~\"$client_id\", topic=~\"$topic\"}",
       "legendFormat": "Avg lag - {{client_id}} - {{topic}}"
      },
      {
       "expr": "kafka_consumer_fetch_manager_records_lag_max{namespace=\"$namespace\", client_id=~\"$client_id\", topic=~\"$topic\"}",
       "legendFormat": "Max lag - {{client_id}} - {{topic}}"
      }
     ]
    },
    {
     "title": "Total records consume",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{namespace=\"$namespace\", client_id=~\"$client_id\", topic=~\"$topic\"}",
       "legendFormat": "{{client_id}} - {{topic}}"
      }
     ]
    },
    {
     "title": "Total consumer requests",
     "type": "graph",
     "description": "The total number of times the I/O layer checked for new I/O to perform",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_select_total{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "I/O number checked for new I/O - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_fetch_manager_fetch_total{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "Total fetch requests - {{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_bytes_consumed_total{namespace=\"$namespace\", client_id=~\"$client_id\", topic=~\"$topic\"}",
       "legendFormat": "{{client_id}} - {{topic}}"
      }
     ]
    },
    {
     "title": "Records request",
     "type": "graph",
     "description": "The average number of records in each request for a topic",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_per_request_avg{namespace=\"$namespace\", client_id=~\"$client_id\", topic=~\"$topic\"}",
       "legendFormat": "{{client_id}} - {{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg time for waiting IO operations",
     "type": "graph",
     "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_io_wait_time_ns_avg{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "Avg time for waiting IO - {{client_id}}"
      }
     ]
    },
    {
     "title": "Avg time for IO",
     "type": "graph",
     "description": "The average length of time for I/O per select call in nanoseconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_io_time_ns_avg{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "IO Ratio",
     "type": "graph",
     "description": "The fraction of time the I/O thread spent doing I/O",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_io_ratio{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "io_ratio - {{client_id}}"
      }
     ]
    },
    {
     "title": "io_wait_ratio",
     "type": "graph",
     "description": "The fraction of time the I/O thread spent waiting",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_io_wait_ratio{namespace=\"$namespace\", client_id=~\"$client_id\"}",
       "legendFormat": "io_wait_ratio - {{client_id}}"
      }
     ]
    }
   ]
  }
 ]
}