{
 "title": "RAP product Metrics",
 "description": "Shows processing online, offline, marketplace, fedabc and out etl metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Статистика времени формирования Asset transfer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "99 перцентиль времени обработки платформой Rap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rap_asset_transfer_phtt_processing_time_seconds_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "PHTT"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rap_asset_transfer_ab_processing_time_seconds_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "FEDABC"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rap_asset_transfer_marketplace_processing_time_seconds_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "MARKETPLACE"
    }
   ]
  },
  {
   "title": "99 перцентиль полного времени обработки",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(full_asset_transfer_phtt_processing_time_seconds_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "PHTT"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(full_asset_transfer_ab_processing_time_seconds_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "FEDABC"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(full_asset_transfer_marketplace_processing_time_seconds_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "MARKETPLACE"
    }
   ]
  },
  {
   "title": "Обработка платформой RAP более 10 часов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(idelta(rap_asset_transfer_phtt_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"+Inf\"}[$__rate_interval])) - \nsum(idelta(rap_asset_transfer_phtt_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"35184.372088831\"}[$__rate_interval]))) >= 0",
     "legendFormat": "PHTT"
    },
    {
     "expr": "(sum(idelta(rap_asset_transfer_ab_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"+Inf\"}[$__rate_interval])) - \nsum(idelta(rap_asset_transfer_ab_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"35184.372088831\"}[$__rate_interval]))) >= 0",
     "legendFormat": "FEDABC"
    },
    {
     "expr": "(sum(idelta(rap_asset_transfer_marketplace_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"+Inf\"}[$__rate_interval])) - \nsum(idelta(rap_asset_transfer_marketplace_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"35184.372088831\"}[$__rate_interval]))) >= 0",
     "legendFormat": "MARKETPLACE"
    }
   ]
  },
  {
   "title": "Полная обработка более 10 часов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(idelta(full_asset_transfer_phtt_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"+Inf\"}[$__rate_interval])) - \nsum(idelta(full_asset_transfer_phtt_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"35184.372088831\"}[$__rate_interval]))) >= 0",
     "legendFormat": "PHTT"
    },
    {
     "expr": "(sum(idelta(full_asset_transfer_ab_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"+Inf\"}[$__rate_interval])) - \nsum(idelta(full_asset_transfer_ab_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"35184.372088831\"}[$__rate_interval]))) >= 0",
     "legendFormat": "FEDABC"
    },
    {
     "expr": "(sum(idelta(full_asset_transfer_marketplace_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"+Inf\"}[$__rate_interval])) - \nsum(idelta(full_asset_transfer_marketplace_processing_time_seconds_bucket{namespace=\"$namespace\", service=~\"rap-etl-transfer-out.*\", le=\"35184.372088831\"}[$__rate_interval]))) >= 0",
     "legendFormat": "MARKETPLACE"
    }
   ]
  },
  {
   "title": "Среднее времени обработки платформой Rap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(rap_asset_transfer_phtt_processing_time_seconds_sum{namespace=\"$namespace\"}[5m])) \n/\navg(rate(rap_asset_transfer_phtt_processing_time_seconds_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "PHTT"
    },
    {
     "expr": "avg(rate(rap_asset_transfer_ab_processing_time_seconds_sum[5m])) \n/\navg(rate(rap_asset_transfer_ab_processing_time_seconds_count[5m]))",
     "legendFormat": "FEDABC"
    },
    {
     "expr": "avg(rate(rap_asset_transfer_marketplace_processing_time_seconds_sum[5m])) \n/\navg(rate(rap_asset_transfer_marketplace_processing_time_seconds_count[5m]))",
     "legendFormat": "MARKETPLACE"
    }
   ]
  },
  {
   "title": "Среднее полное время обработки",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(full_asset_transfer_phtt_processing_time_seconds_sum{namespace=\"$namespace\"}[5m])) \n/\navg(rate(full_asset_transfer_phtt_processing_time_seconds_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "PHTT"
    },
    {
     "expr": "avg(rate(full_asset_transfer_ab_processing_time_seconds_sum[5m])) \n/\navg(rate(full_asset_transfer_ab_processing_time_seconds_count[5m]))",
     "legendFormat": "FEDABC"
    },
    {
     "expr": "avg(rate(full_asset_transfer_marketplace_processing_time_seconds_sum[5m])) \n/\navg(rate(full_asset_transfer_marketplace_processing_time_seconds_count[5m]))",
     "legendFormat": "MARKETPLACE"
    }
   ]
  },
  { "title": "Ошибки обработки", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Incident Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum by (processName, service) (camunda_incident_count{namespace=\"$namespace\", service=~\"rap.*\"}))/ (count by (processName, service) (camunda_incident_count{namespace=\"$namespace\", service=~\"rap.*\"}))",
     "legendFormat": "{{service}} | {{ processName }}"
    }
   ]
  },
  {
   "title": "Number of Log Errors",
   "type": "timeseries",
   "description": "Number of errors by service",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 23 },
   "targets": [
    {
     "expr": "sum by (service) (idelta(logback_events_total{namespace=\"$namespace\", service=~\"rap.*\", level=\"error\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Ошибки обработки чеков",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(idelta(solution_lines_is_empty_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "At least one solution don't have lines"
    },
    {
     "expr": "sum(idelta(document_type_is_not_order_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "At least one solution have not ORDER document type"
    },
    {
     "expr": "sum(idelta(more_than_one_delivery_line_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "At least one solution have more than one DELIVERY line"
    },
    {
     "expr": "sum(idelta(incorrect_line_type_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "At least one solution have lines different from PRODUCT or DELIVERY"
    },
    {
     "expr": "sum(idelta(more_than_one_solution_online_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "There are more than one solution with \"ONLINE\" type"
    },
    {
     "expr": "sum(idelta(different_solution_type_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "There are solutions with different types"
    },
    {
     "expr": "sum(idelta(different_point_of_origin_for_online_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Different pointOfOrigin values for solution with \"ONLINE\" type"
    },
    {
     "expr": "sum(idelta(missed_delivery_coordinates_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Delivery coordinates are missed in the solution"
    },
    {
     "expr": "sum(idelta(missed_payment_task_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "PaymentTask in the solution is null"
    },
    {
     "expr": "sum(idelta(not_valid_store_phtt_online_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Store isn't valid for phtt online"
    },
    {
     "expr": "sum(idelta(different_point_of_sale_and_origin_for_online_counter_total{service=\"rap-conductor\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Different pointOfOrigin and pointOfSale values for solution with \"ONLINE\" type"
    },
    {
     "expr": "sum(idelta(solution_not_found_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Solution not found"
    }
   ]
  },
  {
   "title": "Количество повторной обработки чеков без сформированной команды",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(delta(reprocessing_receipts_counter_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Ошибки обработки 1С Реализаций",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "sum(idelta(no_lines_counter_total{service=\"rap-conductor-ab\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "There are no lines for transfer!"
    },
    {
     "expr": "sum(idelta(empty_cluster_of_sale_counter_total{service=\"rap-conductor-ab\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Cluster of sale for transit sale is missed"
    },
    {
     "expr": "sum(idelta(deliver_line_in_transit_sale_counter_total{service=\"rap-conductor-ab\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Found delivery line for transit sale"
    },
    {
     "expr": "sum(idelta(more_than_one_delivery_counter_total{service=\"rap-conductor-ab\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "More than one delivery line"
    },
    {
     "expr": "sum(idelta(solution_not_found_error_counter_total{service=\"rap-conductor-ab\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Solution not found"
    }
   ]
  },
  {
   "title": "Ошибки обработки заказов MP",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "expr": "sum(idelta(delivery_not_found_counter_total{service=\"rap-conductor-mp\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Delivery not found"
    },
    {
     "expr": "sum(idelta(parcel_lines_is_empty_counter_total{service=\"rap-conductor-mp\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "There aren’t lines for turnover allocation in the parcel"
    },
    {
     "expr": "sum(idelta(messages_consumers_errors_count_total{service=\"rap-conductor-mp\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Ошибки чтения"
    }
   ]
  },
  { "title": "Статистика обработки данных", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Обработанные трансферы по типам",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_rap_etl_transfer_out_received_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Сумма"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_transfer_out_processed_ab_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "AB"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_transfer_out_processed_federal_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "FED"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_transfer_out_processed_c_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "C"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_transfer_out_processed_marketplace_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "MARKETPLACE"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_transfer_out_processed_online_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "ONLINE"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_transfer_out_processed_offline_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "OFFLINE"
    },
    {
     "expr": "sum(idelta(messages_consumers_errors_count_total{namespace=\"$namespace\", service=\"rap-etl-transfer-out\"}[$__rate_interval]))",
     "legendFormat": "Ошибки чтения"
    }
   ]
  },
  {
   "title": "Обработанные заказы",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_received_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Полученные"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_processed_online_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "ONLINE"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_processed_offline_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "OFFLINE"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_filtered_by_solution_lines_empty_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"Empty lines\""
    },
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_filtered_by_document_type_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"Document type is not order\""
    },
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_filtered_by_more_than_one_delivery_line_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"More than one delivery line\""
    },
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_filtered_by_incorrect_line_type_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"Incorrect line type\""
    },
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_filtered_by_not_valid_store_offline_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"Not valid store for offline\""
    },
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_filtered_by_not_valid_store_online_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"Not valid store for online\""
    },
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_filtered_by_different_point_of_origin_for_online_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"Different point of origin for online\""
    },
    {
     "expr": "sum(idelta(billing_rap_etl_solution_in_filtered_by_missed_delivery_coordinates_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"Missed delivery coordinates\""
    },
    {
     "expr": "sum by(service) (rate(messages_consumers_errors_count_total{namespace=\"$namespace\",service=\"rap-etl-solution-in\"}[$__rate_interval]))",
     "legendFormat": "Ошибки чтения"
    }
   ]
  },
  {
   "title": "Обработанные чеки",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_rap_etl_receipt_in_received_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Полученные"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_receipt_in_processed_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Успешно обработанные"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_receipt_in_filtered_by_not_valid_store_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"Not valid store\""
    },
    {
     "expr": "sum(idelta(messages_consumers_errors_count_total{namespace=\"$namespace\", service=\"rap-etl-receipt-in\"}[$__rate_interval]))",
     "legendFormat": "Ошибки чтения"
    }
   ]
  },
  {
   "title": "Обработанные 1С Реализации",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_rap_etl_1c_received_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Полученные"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_1c_processed_transit_c_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "TRANSIT C"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_1c_processed_transit_ab_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "TRANSIT AB"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_1c_processed_transit_fed_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "TRANSIT FED"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_1c_processed_not_transit_ab_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "NOT TRANSIT AB"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_1c_processed_not_transit_fed_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "NOT TRANSIT FED"
    },
    {
     "expr": "sum(idelta(messages_consumers_errors_count_total{service=\"rap-etl-1c\",namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Ошибки чтения"
    }
   ]
  },
  {
   "title": "Обработанные парселы",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_rap_etl_mp_parcel_in_received_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Полученные"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_mp_parcel_in_processed_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_mp_parcel_in_filtered_by_invalid_status_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"Invalid status\""
    },
    {
     "expr": "sum(idelta(billing_rap_etl_mp_parcel_in_filtered_by_incorrect_address_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Отфильтрованных \"Incorrect address\""
    },
    {
     "expr": "sum(idelta(messages_consumers_errors_count_total{namespace=\"$namespace\", service=\"rap-etl-mp-parcel-in\"}[$__rate_interval]))",
     "legendFormat": "Ошибки чтения"
    }
   ]
  },
  {
   "title": "Обработанные delivery",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_rap_etl_mp_delivery_in_received_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Полученные"
    },
    {
     "expr": "sum(idelta(billing_rap_etl_mp_delivery_in_processed_count_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(idelta(messages_consumers_errors_count_total{namespace=\"$namespace\", service=\"rap-etl-mp-delivery-in\"}[$__rate_interval]))",
     "legendFormat": "Ошибки чтения"
    }
   ]
  }
 ]
}