{
 "title": "RAP technical metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "RAPServices", "label": "RAP Services", "query": "rap.*" },
   {
    "name": "excluded_urls",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|UNKNOWN|/camunda/.*|ROOT|REDIRECTION|root|NOT_FOUND|/webjars/.*"
   }
  ]
 },
 "panels": [
  {
   "title": "rap-tariff-manager-http-responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{pod=~\"$RAPServices\", uri!~\"$excluded_urls\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Avg consumer lag per partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service, topic)(kafka_consumer_fetch_manager_records_lag{namespace=\"$namespace\", service=~\"$RAPServices\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka send records total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (increase(kafka_producer_topic_record_send_total{namespace=\"$namespace\", service=~\"$RAPServices\"}[5m]))",
     "legendFormat": "{{pod}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Kafka fetched records total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (increase(kafka_consumer_fetch_manager_records_consumed_total{namespace=\"$namespace\", service=~\"$RAPServices\"}[1m]))",
     "legendFormat": "{{pod}}: {{client-id}} - {{topic}}"
    }
   ]
  }
 ]
}