{
 "title": "HTTP statistic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, namespace)"
    }
   },
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## **This is an HTTP dashboard of your application's statistics. Select the namespace for your product.**\r\n#### **If you need a dashboard with cluster metrics, follow the [link](https://grafana-customer.apps.lmru.tech/d/Gec4gLhVz/cluster-metrics?orgId=1&refresh=30s)**."
   }
  },
  {
   "title": "$Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "repeat": "Service",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", status!~\"5..\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", status=~\"5..\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "$Service (IN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Request time (quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (service, quantile) (http_server_requests_seconds{namespace=\"$Namespace\", service=~\"$Service\", quantile=\"0.5\"}) OR histogram_quantile(0.5, sum by (le, service) (rate(http_server_requests_seconds_bucket{namespace=\"$Namespace\", service=\"$Service\"}[1m])))",
       "legendFormat": "{{service}} (0.5)"
      },
      {
       "expr": "avg by (service, quantile) (http_server_requests_seconds{namespace=\"$Namespace\", service=~\"$Service\", quantile=\"0.95\"}) OR histogram_quantile(0.95, sum by (le, service) (rate(http_server_requests_seconds_bucket{namespace=\"$Namespace\", service=\"$Service\"}[1m])))",
       "legendFormat": "{{service}} (0.95)"
      },
      {
       "expr": "avg by (service, quantile) (http_server_requests_seconds{namespace=\"$Namespace\", service=~\"$Service\", quantile=\"0.99\"}) OR histogram_quantile(0.99, sum by (le, service) (rate(http_server_requests_seconds_bucket{namespace=\"$Namespace\", service=\"$Service\"}[1m])))",
       "legendFormat": "{{service}} (0.99)"
      }
     ]
    },
    {
     "title": "Status / Method / Uri (requests)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum by (status, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m])) > 0",
       "legendFormat": "{{status}} {{method}} ({{uri}})"
      }
     ]
    },
    {
     "title": "Method / Uri (time)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (method, uri) (http_server_requests_seconds{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "{{status}} {{method}} ({{uri}})"
      }
     ]
    }
   ]
  },
  {
   "title": "$Service (OUT)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Request time (client)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (client_name, clientName) (rate(http_client_requests_seconds_sum{namespace=\"$Namespace\", service=~\"$Service\"}[1m])) / scalar(sum(rate(http_client_requests_seconds_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m])))",
       "legendFormat": "{{client_name}}{{clientName}}"
      }
     ]
    },
    {
     "title": "Status / Method / Uri",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (status, method, uri) (increase(http_client_requests_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\"}[1m])) > 0",
       "legendFormat": "{{status}} {{method}} ({{uri}})"
      }
     ]
    },
    {
     "title": "Method / Uri (time)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (rate(http_client_requests_seconds_sum{namespace=\"$Namespace\", service=~\"$Service\"}[1m])) / scalar(sum(rate(http_client_requests_seconds_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))) > 0",
       "legendFormat": "{{status}} {{method}} ({{uri}})"
      }
     ]
    }
   ]
  }
 ]
}