{
 "title": "HTTP statistic (detail)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds, namespace)"
    }
   },
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values(http_server_requests_seconds{namespace=\"$Namespace\"}, service)"
    }
   },
   {
    "name": "ClientName",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{namespace=\"$Namespace\", service=~\"$Service\"}, client_name)"
    }
   },
   {
    "name": "UriIncome",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=\"$Namespace\", service=~\"$Service\"}, uri)"
    }
   },
   {
    "name": "UriOutcome",
    "query": {
     "query": "label_values(http_client_requests_seconds_count{namespace=\"$Namespace\", service=~\"$Service\"}, uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## **This is an HTTP dashboard of your application's statistics. Select the namespace for your product.**\r\n#### **If you need a dashboard with cluster metrics, follow the [link](https://grafana-customer.apps.lmru.tech/d/Gec4gLhVz/cluster-metrics?orgId=1&refresh=30s)**."
   }
  },
  {
   "title": "$Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "repeat": "Service",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", status!~\"5..\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=\"$Service\", status=~\"5..\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "$Service (IN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Request time (quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (service, quantile) (http_server_requests_seconds{namespace=\"$Namespace\", service=~\"$Service\", quantile=\"0.5\"})",
       "legendFormat": "{{service}} ({{quantile}})"
      },
      {
       "expr": "avg by (service, quantile) (http_server_requests_seconds{namespace=\"$Namespace\", service=~\"$Service\", quantile=\"0.95\"})",
       "legendFormat": "{{service}} ({{quantile}})"
      },
      {
       "expr": "avg by (service, quantile) (http_server_requests_seconds{namespace=\"$Namespace\", service=~\"$Service\", quantile=\"0.99\"})",
       "legendFormat": "{{service}} ({{quantile}})"
      }
     ]
    },
    {
     "title": "Status / Method / Uri (requests)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum by (method, status, uri) (increase(http_server_requests_seconds_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m])) > 0",
       "legendFormat": "{{status}} {{method}} ({{uri}})"
      }
     ]
    },
    {
     "title": "Method / Uri (time)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (rate(http_server_requests_seconds_sum{namespace=~\"$Namespace\", service=~\"$Service\"}[1m])) / scalar(sum(rate(http_server_requests_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\"}[1m]))) > 0",
       "legendFormat": "{{method}} ({{uri}})"
      }
     ]
    }
   ]
  },
  {
   "title": "$Service (OUT)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Request time (client)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (client_name, clientName) (rate(http_client_requests_seconds_sum{namespace=~\"$Namespace\", service=~\"$Service\"}[1m])) / scalar(sum(rate(http_client_requests_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\"}[1m]))) > 0",
       "legendFormat": "{{client_name}}{{clientName}}"
      }
     ]
    },
    {
     "title": "Status / Method / Uri",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (status, method, uri) (increase(http_client_requests_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\"}[1m])) > 0",
       "legendFormat": "{{status}} {{method}} ({{uri}})"
      }
     ]
    },
    {
     "title": "Method / Uri (time)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (rate(http_client_requests_seconds_sum{namespace=~\"$Namespace\", service=~\"$Service\"}[1m])) / scalar(sum(rate(http_client_requests_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\"}[1m]))) > 0",
       "legendFormat": "{{status}} {{method}} ({{uri}})"
      }
     ]
    }
   ]
  },
  {
   "title": "$Service (IN/Quantile)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Request time (0,5 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (method, uri) (http_server_requests_seconds{namespace=\"$Namespace\", service=~\"$Service\", quantile=\"0.5\"})",
       "legendFormat": "{{method}} ({{uri}})"
      }
     ]
    },
    {
     "title": "Request time (0,95 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (method, uri) (http_server_requests_seconds{namespace=\"$Namespace\", service=~\"$Service\", quantile=\"0.95\"})",
       "legendFormat": "{{method}} ({{uri}})"
      }
     ]
    },
    {
     "title": "Request time (0,99 quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (method, uri) (http_server_requests_seconds{namespace=\"$Namespace\", service=~\"$Service\", quantile=\"0.99\"})",
       "legendFormat": "{{method}} ({{uri}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Incoming requests statistic by endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "$UriIncome",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "repeat": "UriIncome",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum by (status_group) (label_replace(rate(http_server_requests_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\", uri=~\"$UriIncome\"}[1m]), \"status_group\", \"${1}xx\", \"status\", \"([0-9])..\")) / scalar(sum(rate(http_server_requests_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\", uri=~\"$UriIncome\"}[1m]))) > 0",
       "legendFormat": "{{status_group}} {{method}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing requests statistic by clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "$ClientName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "repeat": "ClientName",
     "targets": [
      {
       "expr": "sum by (method, status, uri) (increase(http_client_requests_seconds_count{namespace=\"$Namespace\", service=~\"$Service\", client_name=~\"$ClientName\"}[1m])) > 0",
       "legendFormat": "{{status}} {{method}} ({{uri}})"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming requests",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (client_name, method, status, uri) (increase(http_server_requests_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\"}[$__range])) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outgoing requests",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (client_name, method, status, uri) (increase(http_client_requests_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\"}[$__range])) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}