{
 "title": "Cluster resources",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$Node\"}, namespace)"
    }
   },
   {
    "name": "NodeGroup",
    "query": {
     "query": "label_values(node_group_node_status, node_group)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_group_node_status{node_group=~\"$NodeGroup\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application node resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_group_node_status{node=~\"$Node\", status=\"UpToDate\"})"
    }
   ]
  },
  {
   "title": "CPU cores allocated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\"$Node\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU cores total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "RAM allocated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"$Node\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"}) / sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "RAM total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$Node\"})",
     "legendFormat": "Total Mem."
    }
   ]
  },
  {
   "title": "CPU cores request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "RAM request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$Node\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node=~\"$Node\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Average RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{node=~\"$Node\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"$Node\"})",
     "legendFormat": "Request"
    }
   ]
  },
  { "title": "Resources by node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_group_node_status{node=\"$Node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "$Node",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{node=\"$Node\", condition=\"Ready\", status=\"true\"}"
    }
   ]
  },
  {
   "title": "CPU allocated",
   "type": "stat",
   "description": "$Node",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=\"$Node\", resource=\"cpu\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"}) / sum(kube_node_status_allocatable{node=\"$Node\", resource=\"cpu\"}) * 100"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "$Node",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=\"$Node\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Request",
   "type": "stat",
   "description": "$Node",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=\"$Node\", resource=\"cpu\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "RAM allocated",
   "type": "stat",
   "description": "$Node",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=\"$Node\", resource=\"memory\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"}) / sum(kube_node_status_allocatable{node=\"$Node\", resource=\"memory\"}) * 100"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "$Node",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=\"$Node\", resource=\"memory\"})",
     "legendFormat": "Total Mem."
    }
   ]
  },
  {
   "title": "Request",
   "type": "stat",
   "description": "$Node",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=\"$Node\", resource=\"memory\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=\"$Node\"}[5m]))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{node=\"$Node\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Root usage",
   "type": "stat",
   "description": "$Node",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 15 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{mountpoint=\"/\", node=\"$Node\"} * 100 / node_filesystem_size_bytes{mountpoint=\"/\", node=\"$Node\"})"
    }
   ]
  },
  {
   "title": "Resources by namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Usage/Limits/Requests",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_info{namespace=~\"$Namespace\"})"
      },
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\"}[$__interval]))"
      },
      {
       "expr": "sum by (namespace) (kube_pod_container_resource_requests{namespace=~\"$Namespace\", resource=\"cpu\"})"
      },
      {
       "expr": "sum by (namespace) (kube_pod_container_resource_limits{namespace=~\"$Namespace\", resource=\"cpu\"})"
      },
      {
       "expr": "sum by (namespace) (container_memory_working_set_bytes{namespace=~\"$Namespace\"})"
      },
      {
       "expr": "sum by (namespace) (kube_pod_container_resource_requests{namespace=~\"$Namespace\", resource=\"memory\"})"
      },
      {
       "expr": "sum by (namespace) (kube_pod_container_resource_limits{namespace=~\"$Namespace\", resource=\"memory\"})"
      }
     ]
    }
   ]
  }
 ]
}