{
 "title": "MongoDB statistic",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(mongodb_driver_commands_seconds_count, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(mongodb_driver_commands_seconds_count{namespace=~\"$Namespace\"}, service)"
    }
   },
   {
    "name": "Status",
    "query": {
     "query": "label_values(mongodb_driver_commands_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\"}, status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service $Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Service" },
  {
   "title": "$Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "repeat": "Status",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_driver_commands_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\", status=~\"$Status\"}) * 100 / sum(mongodb_driver_commands_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\"})"
    }
   ]
  },
  {
   "title": "Driver commands time by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(mongodb_driver_commands_seconds_sum{namespace=~\"$Namespace\", service=~\"$Service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver commands time by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(mongodb_driver_commands_seconds_sum{namespace=~\"$Namespace\", service=~\"$Service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commands status by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service, status) (rate(mongodb_driver_commands_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\", status=~\"$Status\"}[1m]))",
     "legendFormat": "{{status}} ({{service}})"
    }
   ]
  },
  {
   "title": "Commands status by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod, status) (rate(mongodb_driver_commands_seconds_count{namespace=~\"$Namespace\", service=~\"$Service\", status=~\"$Status\"}[1m]))",
     "legendFormat": "{{status}} ({{pod}})"
    }
   ]
  }
 ]
}