{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kubernetes_build_info, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$node\"}, namespace)"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(kube_controller_pod{node=~\"$node\", namespace=~\"$namespace\"}, controller_name)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_controller_pod{node=~\"$node\", namespace=~\"$namespace\", controller_name=~\"$controller\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}[2m]) * 100",
     "legendFormat": "User CPU - {{ pod }}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{ pod }}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_max_seconds{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info{namespace=~\"$namespace\", service=~\"$controller.*\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{namespace=~\"$namespace\", service=~\"$controller.*\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sum CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (irate(process_cpu_user_seconds_total{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}[2m]) * 100)",
     "legendFormat": "User CPU"
    },
    {
     "expr": "sum(irate(process_cpu_system_seconds_total{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}[2m]) * 100)",
     "legendFormat": "Sys CPU"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}",
     "legendFormat": "Active Handler - {{ pod }}"
    },
    {
     "expr": "nodejs_active_requests_total{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}",
     "legendFormat": "Active Request - {{ pod }}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}",
     "legendFormat": "Process Memory - {{ pod }}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}",
     "legendFormat": "Heap Total - {{ pod }}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}",
     "legendFormat": "Heap Used - {{ pod }}"
    },
    {
     "expr": "nodejs_external_memory_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}",
     "legendFormat": "External Memory - {{ pod }}"
    }
   ]
  },
  {
   "title": "Sum Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"})",
     "legendFormat": "Process Memory "
    },
    {
     "expr": "sum(nodejs_heap_size_total_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"})",
     "legendFormat": "Heap Total"
    },
    {
     "expr": "sum(nodejs_heap_size_used_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"})",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "sum(nodejs_external_memory_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"})",
     "legendFormat": "External Memory"
    }
   ]
  },
  {
   "title": "Garbage collector duration seconds percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(kind) (histogram_quantile(0.99, rate(nodejs_gc_duration_seconds_bucket{namespace=~\"$namespace\", service=~\"$controller.*\"}[$__rate_interval])))",
     "legendFormat": "99p - {{ kind }}"
    },
    {
     "expr": "max by(kind) (histogram_quantile(0.95, rate(nodejs_gc_duration_seconds_bucket{namespace=~\"$namespace\", service=~\"$controller.*\"}[$__rate_interval])))",
     "legendFormat": "95p - {{ kind }}"
    },
    {
     "expr": "max by(kind) (histogram_quantile(0.90, rate(nodejs_gc_duration_seconds_bucket{namespace=\"$namespace\", service=~\"$controller.*\"}[$__rate_interval])))",
     "legendFormat": "50p - {{ kind }}"
    },
    {
     "expr": "max by(kind) (histogram_quantile(0.50, rate(nodejs_gc_duration_seconds_bucket{namespace=\"$namespace\", service=~\"$controller.*\"}[$__rate_interval])))",
     "legendFormat": "50p - {{ kind }}"
    }
   ]
  },
  {
   "title": "Garbage collector duration seconds by POD",
   "type": "timeseries",
   "description": "GC by POD",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(nodejs_gc_duration_seconds_bucket{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "95p - {{ kind }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}",
     "legendFormat": "Heap Total - {{ pod }} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}",
     "legendFormat": "Heap Used - {{ pod }} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{namespace=~\"$namespace\", service=~\"$controller.*\", pod=~\"$pod\"}",
     "legendFormat": "Heap Used - {{ pod }} - {{space}}"
    }
   ]
  }
 ]
}