{
 "title": "Carrier chooser",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(carriers_choice_requests_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\"},for_service) "
   },
   {
    "name": "namespace",
    "query": "label_values(carriers_choice_requests_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\"},namespace) "
   },
   {
    "name": "store",
    "query": "label_values(carriers_choice_requests_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\"},store_id) "
   },
   {
    "name": "carrier",
    "query": "label_values(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\"},carrier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Процент курьерской доставки за последние 12 часов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(carriers_courier_choice_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\"}[12h]))/sum(increase(carriers_choice_requests_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\"}[12h]))",
     "legendFormat": "Процент КК"
    },
    {
     "expr": "sum(increase(carriers_choice_requests_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\"}[12h]))",
     "legendFormat": "Всего доставок"
    }
   ]
  },
  {
   "title": "Количество запросов на расчет, шт",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(carriers_choice_requests_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\"}[$__interval]))",
     "legendFormat": "Кол-во запросов"
    }
   ]
  },
  {
   "title": "Ограничения доставки, шт",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"no_store\"}[$__range]))",
     "legendFormat": "Нет правил для магазина"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"current_day_delivery\"}[$__range]))",
     "legendFormat": "Доставка день в день"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"no_store_cutoff\"}[$__range]))",
     "legendFormat": "Для магазина не задано время cutoff"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"no_store_quota\"}[$__range]))",
     "legendFormat": "Закончилась квота магазина"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"geo\",carrier=~\"$carrier\"}[$__range]))",
     "legendFormat": "Ограничение географии доставки"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_max_height\",carrier=~\"$carrier\"}[$__range]))",
     "legendFormat": "Макс. высота"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_max_width\",carrier=~\"$carrier\"}[$__range]))",
     "legendFormat": "Макс. ширина"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_max_length\",carrier=~\"$carrier\"}[$__range]))",
     "legendFormat": "Макс. длина"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_max_volume\",carrier=~\"$carrier\"}[$__range]))",
     "legendFormat": "Макс. объем"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_max_weight\",carrier=~\"$carrier\"}[$__range]))",
     "legendFormat": "Макс. вес"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_total_sides_length\",carrier=~\"$carrier\"}[$__range]))",
     "legendFormat": "Сумма сторон"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"no_carrier_quota\",carrier=~\"$carrier\"}[$__range]))",
     "legendFormat": "Закончилась квота КК"
    }
   ]
  },
  {
   "title": "Средний процент ограничений доставки (за выбранный период)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"no_store\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Нет правил для магазина"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"current_day_delivery\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Доставка день в день"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"no_store_cutoff\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Для магазина не задано время cutoff"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"no_store_quota\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Закончилась квота магазина"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"geo\",carrier=~\"$carrier\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Ограничение географии доставки"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_max_height\",carrier=~\"$carrier\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Макс. высота"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_max_width\",carrier=~\"$carrier\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Макс. ширина"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_max_length\",carrier=~\"$carrier\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Макс. длина"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_max_volume\",carrier=~\"$carrier\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Макс. объем"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_max_weight\",carrier=~\"$carrier\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Макс. вес"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"dimensions_total_sides_length\",carrier=~\"$carrier\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Сумма сторон"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",restriction=\"no_carrier_quota\",carrier=~\"$carrier\"}[$__range])) / sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier|\"}[$__range]))",
     "legendFormat": "Закончилась квота КК"
    }
   ]
  },
  {
   "title": "Всего заказов, шт (без фильтра по курьеркам)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(carriers_choice_requests_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\"}[$__range]))",
     "legendFormat": "Всего заказов"
    },
    {
     "expr": "sum(increase(carriers_courier_choice_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\"}[$__range]))",
     "legendFormat": "Заказов в курьерку"
    }
   ]
  },
  {
   "title": "Превышения по весу",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier\",restriction=\"dimensions_max_weight\",exceeded=\"1\"}[$__range]))",
     "legendFormat": "⩽ 1 кг"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier\",restriction=\"dimensions_max_weight\",exceeded=\"3\"}[$__range]))",
     "legendFormat": "⩽ 3 кг"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier\",restriction=\"dimensions_max_weight\",exceeded=\"5\"}[$__range]))",
     "legendFormat": "⩽ 5 кг"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier\",restriction=\"dimensions_max_weight\",exceeded=\"10\"}[$__range]))",
     "legendFormat": "⩽ 10 кг"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier\",restriction=\"dimensions_max_weight\",exceeded=\"15\"}[$__range]))",
     "legendFormat": "⩽ 15 кг"
    },
    {
     "expr": "sum(increase(carriers_restrictions_total{job=\"custom-dnp-gagarin-carrier-chooser-metrics\",for_service=\"$service\",namespace=\"$namespace\",store_id=~\"$store\",carrier=~\"$carrier\",restriction=\"dimensions_max_weight\",exceeded=\"over\"}[$__range]))",
     "legendFormat": "> 15 кг"
    }
   ]
  }
 ]
}