{
 "title": "ALL IN ONE",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "atol",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"atol\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "CONDUCTOR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"conductor\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "CASH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"cash\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SIMULATION",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"simulation\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "ORCHESTRATOR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"orchestrator\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SBERBANK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"sberbank\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "UNIFIED-PAYMENT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"unified-payment\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "ITSM-INTERACTION",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"itsm-interaction\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "TASKS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"tasks\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "TP-NET-INTERACTION",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"tp-net-interaction\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "BILLING-INTERACTION",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"billing-interaction\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Memory Usage per Instance",
   "type": "table-old",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "(sum by (pod) (jvm_memory_used_bytes{ namespace=\"$namespace\", area=\"heap\"}))*100/(sum by (pod) (jvm_memory_max_bytes{namespace=\"$namespace\", area=\"heap\"})) ",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Load Average by CPU Core",
   "type": "table-old",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (pod) (system_load_average_1m{namespace=\"$namespace\"}*100/system_cpu_count{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "TASKS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{namespace=\"$namespace\", service=\"tasks\"}",
       "legendFormat": "{{instance}}: system CPU Usage"
      },
      {
       "expr": "process_cpu_usage{namespace=\"$namespace\", service=\"tasks\"}",
       "legendFormat": "{{instance}}: process CPU Usage"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{namespace=\"$namespace\", service=\"TASKS\"}",
       "legendFormat": "{{service}}: Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{namespace=\"$namespace\", service=\"TASKS\"}",
       "legendFormat": "{{service}}: CPU Core Size"
      }
     ]
    },
    {
     "title": "Heap Used",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(jvm_memory_used_bytes{namespace=\"$namespace\", app_name=\"TASKS\", area=\"heap\"})*100/(jvm_memory_max_bytes{namespace=\"$namespace\", app_name=\"TASKS\", area=\"heap\"})",
       "legendFormat": "{{instance}} {{id}}"
      }
     ]
    },
    {
     "title": "Nonheap Used",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(jvm_memory_used_bytes{area=\"nonheap\", namespace=\"$namespace\", app_name=\"TASKS\"})",
       "legendFormat": "USED {{instance}} {{id}}"
      },
      {
       "expr": "jvm_memory_max_bytes{area=\"nonheap\", namespace=\"$namespace\", app_name=\"TASKS\"}",
       "legendFormat": "MAX {{instance}} {{id}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{namespace=\"$namespace\", app_name=\"TASKS\"}",
       "legendFormat": "Daemon {{instance}}"
      },
      {
       "expr": "jvm_threads_live_threads{namespace=\"$namespace\", app_name=\"TASKS\"}",
       "legendFormat": "Live {{instance}}"
      },
      {
       "expr": "jvm_threads_peak_threads{namespace=\"$namespace\", app_name=\"TASKS\"}",
       "legendFormat": "Peak {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}