{
 "title": "Camunda metrics pb",
 "description": "Dashboard for analyzing individual endpoints' performance using metric http_server_requests",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, namespace)"
    }
   },
   {
    "name": "process",
    "query": {
     "query": "label_values(activity_count{namespace=\"$namespace\"}, process)"
    }
   },
   {
    "name": "activity_id",
    "query": {
     "query": "label_values(activity_count{namespace=\"$namespace\", process=\"$process\"}, activity_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "old processes are greater than 0",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(activity_count{namespace=\"$namespace\", definition_id=\"old\"}) by (process) > 0",
     "legendFormat": "__auto",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "latest processes are greater than 0",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(activity_count{namespace=\"$namespace\", definition_id=\"latest\"}) by (process) > 0",
     "legendFormat": "{{activity_id}}"
    }
   ]
  },
  {
   "title": "Instance Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (processName) (camunda_instance_count{namespace=\"$namespace\"})",
     "legendFormat": "{{ processName }}"
    }
   ]
  },
  {
   "title": "Incident Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (processName) (camunda_incident_count{namespace=\"$namespace\"})",
     "legendFormat": "{{ processName }}"
    }
   ]
  },
  {
   "title": "Human Task Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (processName)(camunda_human_task_count{namespace=\"$namespace\"})",
     "legendFormat": "{{ processName }}"
    }
   ]
  },
  {
   "title": "Job Executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (processName) (camunda_active_job_count{namespace=\"$namespace\"})",
     "legendFormat": "{{ processName }} (active)"
    },
    {
     "expr": "sum by (processName) (camunda_suspended_job_count{namespace=\"$namespace\"})",
     "legendFormat": "{{ processName }} (suspended)"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "old processes are greater than 0",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(activity_count{namespace=\"$namespace\", process=\"$process\", definition_id=\"old\"}) by (activity_id) > 0",
     "legendFormat": "__auto",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "latest processes are greater than 0",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "activity_count{namespace=\"$namespace\", process=\"$process\", definition_id=\"latest\"} > 0",
     "legendFormat": "{{activity_id}}"
    }
   ]
  },
  { "title": "Delegate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "$activity_id",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "activity_id",
   "targets": [
    {
     "expr": "sum(activity_count{namespace=\"$namespace\", process=\"$process\", activity_id=\"$activity_id\"}) by(definition_id)",
     "legendFormat": "{{activity_id}}"
    }
   ]
  }
 ]
}