{
 "title": "JVM Applications",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut) in K8s",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\",container=\"$container\"}, pod)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\", container=\"$container\",pod=\"$pod\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\", container=\"$container\",pod=\"$pod\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Rate [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}[$period]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", status=~\"5..\"}[$period]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_sum{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", status!~\"5..\"}[$period]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Utilisation [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "TOMCAT - BSY"
    },
    {
     "expr": "tomcat_threads_current_threads{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "TOMCAT - CUR"
    },
    {
     "expr": "tomcat_threads_config_max_threads{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "TOMCAT - MAX"
    },
    {
     "expr": "jetty_threads_busy{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "JETTY - BSY"
    },
    {
     "expr": "jetty_threads_current{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "JETTY - CUR"
    },
    {
     "expr": "jetty_threads_config_max{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "JETTY - MAX"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "JVM Heap [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Process Memory [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_memory_rss_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_swap_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_rss_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"} + process_memory_swap_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Load [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Log Events [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}[$period])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open_files{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "persistence_counts" },
  {
   "title": "$jvm_memory_pool_heap [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "$jvm_memory_pool_nonheap [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Collections [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}[$period])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}[$period])/irate(jvm_gc_pause_seconds_count{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}[$period])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}[$period])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}[$period])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "GC Overhead [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_gc_overhead_percent{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "GC %"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Classes loaded [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class Delta [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_classes_loaded_classes{namespace=\"$namespace\", container=\"$container\",pod=\"$pod\"}[$period])",
     "legendFormat": "delta"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Direct Buffers [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers [$period]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{namespace=\"$namespace\", container=\"$container\", pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "count"
    }
   ]
  }
 ]
}