{
 "title": "PaymentBrick - conversion",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "window", "label": "window", "query": "5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(channel)(increase(success_payments_total{service=~\"sberbank-interaction|brs-interaction\"}[$window])) \r\n/ sum by(channel)(increase(created_payment_instruments_total {service=~\"sberbank-interaction|brs-interaction\"}[$window] offset 5m))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(channel)(increase(success_payments_total{service=~\"sberbank-interaction|brs-interaction\", channel=\"MARKETPLACE\",}[$window])) \r\n/ sum by(channel)(increase(created_payment_instruments_total {service=~\"sberbank-interaction|brs-interaction\", channel=\"MARKETPLACE\"}[$window] offset 5m))",
     "legendFormat": "MARKETPLACE"
    },
    {
     "expr": "sum by(channel)(increase(success_payments_total{service=~\"sberbank-interaction|brs-interaction\", channel=\"SOLUTION\"}[$window])) \r\n/ sum by(channel)(increase(created_payment_instruments_total {service=~\"sberbank-interaction|brs-interaction\", channel=\"SOLUTION\"}[$window]))",
     "legendFormat": "SOLUTION"
    }
   ]
  },
  {
   "title": "Распределение времени оплаты(%)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(success_payments_seconds_bucket[$window]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Payment Instrument",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(paymentInstrument)(increase(success_payments_total{service=~\"sberbank-interaction|brs-interaction\"}[$window])) \r\n/ sum by(paymentInstrument)(increase(created_payment_instruments_total {service=~\"sberbank-interaction|brs-interaction\"}[$window] offset 5m))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Instrument",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(paymentInstrument)(increase(success_payments_total{service=~\"sberbank-interaction|brs-interaction\",paymentInstrument=\"BANK_CARD\"}[$window])) \r\n/ sum by(paymentInstrument)(increase(created_payment_instruments_total {service=~\"sberbank-interaction|brs-interaction\",paymentInstrument=\"BANK_CARD\"}[$window]  offset 5m))",
     "legendFormat": "BANK_CARD"
    }
   ]
  },
  {
   "title": "Распределение времени оплаты (кол-во)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(success_payments_seconds_bucket[$window]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}