{
 "title": "Spring Boot + K8S Info 2.0",
 "description": "Dashboard for spring boot services. Displays standard spring metrics, jvm metrics, important data from kubernetes. Grafana 10+. Up-to-date original version is here https://github.lmru.tech/adeo/lmru--sv-grafana-dashboards/",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$app\"}, pod)"
    }
   },
   {
    "name": "spring_data_repository_name",
    "label": "Spring Repository Name",
    "query": {
     "query": "label_values(spring_data_repository_invocations_seconds_count{namespace=\"$namespace\", service=\"$app\"}, repository)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}, pool)"
    }
   },
   {
    "name": "tomcat_thread_group",
    "label": "Tomcat",
    "query": {
     "query": "label_values(tomcat_threads_config_max_threads{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}, name)"
    }
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   },
   {
    "name": "heap_part",
    "label": "Heap Part",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}, id)"
    }
   },
   {
    "name": "spring_task_executor",
    "label": "Task Executor",
    "query": {
     "query": "label_values(executor_pool_max_threads{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}, name)"
    }
   },
   {
    "name": "kafka_topic_for_lag",
    "label": "Kafka Topic",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_lag{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}, topic)"
    }
   },
   {
    "name": "excluded_stream_channels",
    "query": ".*errorLogger|errorChannel|.*\\.errors(\\.bridge)?|unknown"
   }
  ]
 },
 "panels": [
  { "title": "HTTP Server I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (increase(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", uri!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "{{ method }} {{ uri }}"
    },
    {
     "expr": "sum by (service) (increase(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", uri!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "total (press shift + left click to hide)"
    }
   ]
  },
  {
   "title": "Response Time [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", exception=~\"[Nn]one\", uri!~\"$excluded_urls\"}[1m])) / sum by (method, uri) (irate(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", exception=~\"[Nn]one\", uri!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Response Status Groups 2xx / 4xx / 5xx [5m]",
   "type": "timeseries",
   "description": "Actually, query works with 'outcome' attribute: [SUCCESS, CLIENT_ERROR, SERVER_ERROR]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"SUCCESS\"}[5m])) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "2xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"CLIENT_ERROR\"}[5m])) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "4xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", outcome=\"SERVER_ERROR\"}[5m])) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "5xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Statuses [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (status) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Status 4xx by (method, path, status) [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method, uri, status) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"CLIENT_ERROR\", uri!~\"$excluded_urls\"}[5m]))",
     "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
    }
   ]
  },
  {
   "title": "Response Status 5xx by (method, path, status) [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method, uri, status) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"SERVER_ERROR\", uri!~\"$excluded_urls\"}[5m]))",
     "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
    }
   ]
  },
  {
   "title": "Response Status Error % by (method, path) [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", uri!~\"$excluded_urls\", outcome!=\"SUCCESS\"}[5m])) by (method, uri) / (sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", uri!~\"$excluded_urls\"}[5m])) by (method, uri) > 0)",
     "legendFormat": "{{ method }} {{ uri }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Exceptions [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!~\"[Nn]one\"}[5m])) by (exception)",
     "legendFormat": "{{ exception }}"
    }
   ]
  },
  {
   "title": "Request Count [selected range]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$__range]) > 0) by (method, uri))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Total Requests [selected range]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$__range]) > 0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Response Statuses [selected range]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[$__range]) > 0) by (status))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Exceptions by endpoint [selected range]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!~\"[Nn]one\"}[$__range]) > 0) by (method, uri))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Total Exceptions [selected range]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!~\"[Nn]one\"}[$__range]) > 0)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Exception Types [selected range]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\", exception!~\"[Nn]one\"}[$__range]) > 0) by (exception))",
     "legendFormat": "{{ exception }}"
    }
   ]
  },
  {
   "title": "HTTP Client I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count [1m]",
     "type": "timeseries",
     "description": "Including cancelled",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (increase(http_client_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "{{ method }} {{ uri }}"
      },
      {
       "expr": "sum by (service) (increase(http_client_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "total (press shift + left click to hide)"
      }
     ]
    },
    {
     "title": "Response Time [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", status!=\"CLIENT_ERROR\"}[1m])) / sum by (method, uri) (irate(http_client_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", status!=\"CLIENT_ERROR\"}[1m]))",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Response Status Groups 2xx / 4xx / 5xx / IO_ERROR [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"SUCCESS\"}[5m])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
       "legendFormat": "2xx",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"CLIENT_ERROR\"}[5m])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
       "legendFormat": "4xx",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"SERVER_ERROR\"}[5m])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
       "legendFormat": "5xx",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=\"IO_ERROR\"}[5m])) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
       "legendFormat": "IO_ERROR",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Response Statuses [5m]",
     "type": "timeseries",
     "description": "Including IO_ERROR",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (status) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
       "legendFormat": "{{ status }}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Response Status 4xx by (method, path, status) [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (method, uri, status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"CLIENT_ERROR\"}[5m]))",
       "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
      }
     ]
    },
    {
     "title": "Response Status 5xx by (method, path, status) [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (method, uri, status) (increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome=\"SERVER_ERROR\"}[5m]))",
       "legendFormat": "{{ method }} {{ uri }} [{{ status }}]"
      }
     ]
    },
    {
     "title": "Request Count [selected range]",
     "type": "piechart",
     "description": "Including cancelled",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[$__range]) > 0) by (method, uri))",
       "legendFormat": "{{ method }} {{ uri }}"
      }
     ]
    },
    {
     "title": "Total Requests [selected range]",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[$__range]) > 0)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Response Statuses [selected range]",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[$__range]) > 0) by (status))",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Errors by endpoint [selected range]",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=~\"4..|5..|IO_ERROR\"}[$__range]) > 0) by (method, uri))",
       "legendFormat": "{{ method }} {{ uri }}"
      }
     ]
    },
    {
     "title": "Total Errors [selected range]",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=~\"4..|5..|IO_ERROR\"}[$__range]) > 0)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Response Error Statuses [selected range]",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=~\"4..|5..|IO_ERROR\"}[$__range]) > 0) by (status))",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  { "title": "Kubernetes Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Pods Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "min by (pod) (\n  max(kube_controller_pod{namespace=\"$namespace\", controller_name=\"$app\"}) by(pod)\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods restarts",
   "type": "timeseries",
   "description": "The number of Pod restarts",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", controller_name=\"$app\", pod=~\"$pod\"}[$__rate_interval])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"}[$__rate_interval]))\n)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\", namespace=\"$namespace\"}[$__rate_interval]))\n)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", container=\"$app\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Uptime by Pod",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{namespace=\"$namespace\", service=\"$app\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Ingress Important Statuses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 }
  },
  {
   "title": "503 (probably all backends not available) [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"503\"}[5m])) by (service)",
     "legendFormat": "{{ service }}"
    },
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"503\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "499 (client disconnected due to its timeout) [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"499\"}[5m])) by (service)",
     "legendFormat": "{{ service }}"
    },
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", status=\"499\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "TRACE, DEBUG, INFO [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"info\"}[5m]))",
     "legendFormat": "INFO",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"debug\"}[5m]))",
     "legendFormat": "DEBUG",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"trace\"}[5m]))",
     "legendFormat": "TRACE",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN, ERROR [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"warn\"}[5m]))",
     "legendFormat": "WARN",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "sum by (service) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"error\"}[5m]))",
     "legendFormat": "ERROR",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN by pod [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"warn\"}[5m]))",
     "legendFormat": "{{ pod }}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR by pod [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(logback_events_total{namespace=\"$namespace\", service=\"$app\", level=\"error\"}[5m]))",
     "legendFormat": "{{ pod }}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Spring Cloud Stream (RabbitMQ / Kafka)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spring Integration - Message Rate [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!~\"$excluded_stream_channels\"}[1m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Spring Integration - Timings [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (name) (irate(spring_integration_send_seconds_sum{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!~\"$excluded_stream_channels\", result=\"success\"}[1m])) /  sum by (name) (irate(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!~\"$excluded_stream_channels\", result=\"success\"}[1m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Spring Integration - Errors [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name!=\"unknown\", result!=\"success\"}[5m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Kafka Consumer Offsets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (topic) (spring_cloud_stream_binder_kafka_offset{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "{{ topic }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Kafka Listener/Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Listener - Message Rate [1m]",
     "type": "timeseries",
     "description": "Как сделать, чтобы заработали новые метрики, смотри https://github.lmru.tech/adeo/lmru--sv-grafana-dashboards/issues/18#issuecomment-64709",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (messaging_source_name) (increase(spring_kafka_listener_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", messaging_operation=\"receive\",messaging_source_kind=\"topic\", messaging_system=\"kafka\"}[1m]))",
       "legendFormat": "{{ messaging_source_name }}"
      }
     ]
    },
    {
     "title": "Kafka Listener - Timings [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (messaging_source_name) (irate(spring_kafka_listener_seconds_sum{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", messaging_operation=\"receive\",messaging_source_kind=\"topic\", messaging_system=\"kafka\"}[1m])) /  sum by (messaging_source_name) (irate(spring_kafka_listener_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", messaging_operation=\"receive\",messaging_source_kind=\"topic\", messaging_system=\"kafka\"}[1m]))",
       "legendFormat": "{{ messaging_source_name }}"
      }
     ]
    },
    {
     "title": "Kafka Listener - Errors [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (error, messaging_source_name) (increase(spring_kafka_template_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", error!=\"none\", messaging_operation=\"receive\", messaging_source_kind=\"topic\", messaging_system=\"kafka\"}[1m]))",
       "legendFormat": "{{ error }} - {{ messaging_source_name }}"
      }
     ]
    },
    {
     "title": "Kafka Consumer Lag by Topic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (topic) (kafka_consumer_fetch_manager_records_lag{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kafka Consumer Lag Details - $kafka_topic_for_lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "repeat": "kafka_topic_for_lag",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (partition) (kafka_consumer_fetch_manager_records_lag{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", topic=\"$kafka_topic_for_lag\"})",
       "legendFormat": "partition {{ partition }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Kafka Template/Producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Template - Message Rate [1m]",
     "type": "timeseries",
     "description": "Как сделать, чтобы заработали новые метрики, смотри https://github.lmru.tech/adeo/lmru--sv-grafana-dashboards/issues/18#issuecomment-64709",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (messaging_destination_name, spring_kafka_template_name) (increase(spring_kafka_template_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", messaging_operation=\"publish\", messaging_destination_kind=\"topic\", messaging_system=\"kafka\"}[1m]))",
       "legendFormat": "{{ messaging_destination_name }} - {{ spring_kafka_template_name }}"
      }
     ]
    },
    {
     "title": "Kafka Template - Timings [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (messaging_destination_name, spring_kafka_template_name) (irate(spring_kafka_template_seconds_sum{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", messaging_operation=\"publish\", messaging_destination_kind=\"topic\", messaging_system=\"kafka\"}[1m])) / sum by (messaging_destination_name, spring_kafka_template_name) (irate(spring_kafka_template_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", messaging_operation=\"publish\", messaging_destination_kind=\"topic\", messaging_system=\"kafka\"}[1m]))\r\n",
       "legendFormat": "{{ messaging_destination_name }} - {{ spring_kafka_template_name }}"
      }
     ]
    },
    {
     "title": "Kafka Template - Errors [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (error, messaging_destination_name, spring_kafka_template_name) (increase(spring_kafka_template_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", error!=\"none\", messaging_operation=\"publish\", messaging_destination_kind=\"topic\", messaging_system=\"kafka\"}[1m]))\r\n",
       "legendFormat": "{{ error }} - {{ messaging_source_name }} - {{ spring_kafka_template_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Kafka Listener/Consumer (Old)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Listener - Message Rate [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (increase(spring_kafka_listener_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Kafka Listener - Timings [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (name) (irate(spring_kafka_listener_seconds_sum{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[1m])) /  sum by (name) (irate(spring_kafka_listener_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Kafka Listener - Errors [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (exception, name) (increase(spring_kafka_listener_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", result=\"failure\"}[1m]))",
       "legendFormat": "{{ exception }} - {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Data Repositories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Method Invocation Count  - $spring_data_repository_name [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "repeat": "spring_data_repository_name",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method) (increase(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m]))",
       "legendFormat": "{{ method }}"
      },
      {
       "expr": "sum by (service) (increase(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m]))",
       "legendFormat": "total (press shift + left click to hide)"
      }
     ]
    },
    {
     "title": "Method Execution Time - $spring_data_repository_name [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "repeat": "spring_data_repository_name",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method) (irate(spring_data_repository_invocations_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m])) / sum by (method) (irate(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", repository=\"$spring_data_repository_name\"}[1m]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Method Exception Count [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (repository, method, exception) (increase(spring_data_repository_invocations_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", exception!~\"[Nn]one\"}[5m]))",
       "legendFormat": "{{ repository }}.{{ method }} - {{ exception }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (cache) (cache_size{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "{{ cache }}"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio [5m]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(cache_gets_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", result=\"hit\"}[5m])) by (cache) / sum(increase(cache_gets_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])) by (cache)",
       "legendFormat": "{{ cache }}"
      }
     ]
    },
    {
     "title": "Average Cache Puts [5m]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (cache) ( \n  increase(cache_puts_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])\n)",
       "legendFormat": "{{ cache }}"
      }
     ]
    },
    {
     "title": "Average Cache Evictions [5m]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (cache) ( \n  increase(cache_evictions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])\n)",
       "legendFormat": "{{ cache }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool Executors by Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads in Pool - $spring_task_executor - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "repeat": "spring_task_executor",
     "targets": [
      {
       "expr": "executor_pool_core_threads{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$spring_task_executor\"}",
       "legendFormat": "Core Threads"
      },
      {
       "expr": "(vector(-1) and on() (executor_pool_max_threads{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$spring_task_executor\"} == 2147483647)) or on() executor_pool_max_threads{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$spring_task_executor\"}",
       "legendFormat": "Max Threads"
      },
      {
       "expr": "executor_active_threads{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$spring_task_executor\"}",
       "legendFormat": "Busy Threads"
      },
      {
       "expr": "executor_pool_size_threads{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$spring_task_executor\"}",
       "legendFormat": "Current Threads"
      }
     ]
    },
    {
     "title": "Task Queue - $spring_task_executor - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "repeat": "spring_task_executor",
     "targets": [
      {
       "expr": "executor_queued_tasks{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$spring_task_executor\"}",
       "legendFormat": "Queued Tasks"
      },
      {
       "expr": "(vector(-1) and on() (executor_queue_remaining_tasks{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$spring_task_executor\"} == 2147483647)) or on() executor_queue_remaining_tasks{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$spring_task_executor\"}",
       "legendFormat": "Remaining Queue Space"
      }
     ]
    },
    {
     "title": "Completed Tasks - $pod [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (increase(executor_completed_tasks_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Spring Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "@Scheduled Method Invocation Count [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (code_function) (increase(tasks_scheduled_execution_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "{{ code_function }}"
      },
      {
       "expr": "sum by (service) (increase(tasks_scheduled_execution_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "total (press shift + left click to hide)"
      }
     ]
    },
    {
     "title": "@Scheduled Method Execution Time [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (code_function) (irate(tasks_scheduled_execution_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m])) / sum by (code_function) (irate(tasks_scheduled_execution_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "{{ code_function }}"
      }
     ]
    },
    {
     "title": "Method Exception Count [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (code_function, exception) (increase(tasks_scheduled_execution_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", outcome=\"ERROR\"}[5m]))",
       "legendFormat": "{{ code_function }} - {{ exception }}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Actuator - health, info, prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "panels": [
    {
     "title": "Actuator Response Time [5m] - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", outcome=\"SUCCESS\", uri=~\"/actuator/(info|health|prometheus)\"}[5m]) / irate(http_server_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", outcome=\"SUCCESS\", uri=~\"/actuator/(info|health|prometheus)\"}[5m]))",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Actuator Response Statuses 4xx/5xx by (method, path, status, pod) [5m]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (method, uri, status, pod) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", outcome!=\"SUCCESS\", uri=~\"/actuator/(info|health|prometheus)\"}[5m]))",
       "legendFormat": "{{ method }} {{ uri }} [{{ status }}] - {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Memory Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (area) (jvm_memory_used_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum by (area) (jvm_memory_committed_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum by (area) (jvm_memory_max_bytes{area=\"heap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Non-heap - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (area) (jvm_memory_used_bytes{area=\"nonheap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum by (area) (jvm_memory_committed_bytes{area=\"nonheap\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Commited"
      }
     ]
    },
    {
     "title": "JVM Byte Buffers - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (id) (jvm_buffer_memory_used_bytes{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}) > 0",
       "legendFormat": "Used - {{ id }}"
      },
      {
       "expr": "sum by (id) (jvm_buffer_total_capacity_bytes{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}) > 0",
       "legendFormat": "Total Capacity - {{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Memory Details by Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap - $heap_part - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "repeat": "heap_part",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\", id=\"$heap_part\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{area=\"heap\", id=\"$heap_part\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_memory_max_bytes{area=\"heap\", id=\"$heap_part\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Non-heap - Code Cache - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"nonheap\", id=~\"Code.*Cache\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{area=\"nonheap\", id=~\"Code.*Cache\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "jvm_memory_max_bytes{area=\"nonheap\", id=~\"Code.*Cache\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Non-heap - Metaspace - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"nonheap\", id=\"Metaspace\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{area=\"nonheap\", id=\"Metaspace\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Committed"
      }
     ]
    },
    {
     "title": "JVM Non-heap - Compressed Class Space - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"nonheap\", id=\"Compressed Class Space\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{area=\"nonheap\", id=\"Compressed Class Space\", namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "Committed"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - CPU / Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_cpu_usage{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "Load Average - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "CPU Core Size"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{pod=\"$pod\", namespace=\"$namespace\", service=\"$app\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Thread States - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Garbage Collector by Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Overhead Percent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "jvm_gc_overhead{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "GC Events by Pod [1m] - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_pause_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{ cause }} - {{ action }}"
      }
     ]
    },
    {
     "title": "GC Pause Times [1m] - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[1m]) / irate(jvm_gc_pause_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{ cause }} - {{ action }}"
      }
     ]
    },
    {
     "title": "GC Concurrent Phase Times [1m] - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_concurrent_phase_time_seconds_sum{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[1m]) / irate(jvm_gc_concurrent_phase_time_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[1m])",
       "legendFormat": "{{ cause }} - {{ action }}"
      }
     ]
    },
    {
     "title": "GC Memory Flow [1m] - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_memory_allocated_bytes_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[1m])",
       "legendFormat": "Allocated"
      },
      {
       "expr": "increase(jvm_gc_memory_promoted_bytes_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[1m])",
       "legendFormat": "Promoted"
      }
     ]
    },
    {
     "title": "GC Data Size - $pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_gc_live_data_size_bytes{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_gc_max_data_size_bytes{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations Count [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (command) (increase(mongodb_driver_commands_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "{{ command }}"
      },
      {
       "expr": "sum by (service) (increase(mongodb_driver_commands_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "total (press shift + left click to hide)"
      }
     ]
    },
    {
     "title": "Operations Execution Time [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (command) (irate(mongodb_driver_commands_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m])) / sum by (command) (irate(mongodb_driver_commands_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "{{ command }}"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Pool - size on $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mongodb_driver_pool_size{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "{{ server_address }}"
      }
     ]
    },
    {
     "title": "Connection Pool - in use on $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mongodb_driver_pool_checkedout{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "{{ server_address }}"
      }
     ]
    },
    {
     "title": "Wait queue size on $pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mongodb_driver_pool_waitqueuesize{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"}",
       "legendFormat": "{{ server_address }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 112 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_idle{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\", pool=~\"$hikaricp\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_active{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\", pool=~\"$hikaricp\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_pending{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\", pool=~\"$hikaricp\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Creation Time [1m]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod) (irate(hikaricp_connections_creation_seconds_sum{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\", pod=~\"$pod\"} [1m])) / sum by (pod) (irate(hikaricp_connections_creation_seconds_count{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Connection Acquire Time [1m]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod) (irate(hikaricp_connections_acquire_seconds_sum{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\", pod=~\"$pod\"}[1m])) / sum by (pod) (irate(hikaricp_connections_acquire_seconds_count{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Connection Usage Time [1m]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod) (irate(hikaricp_connections_usage_seconds_sum{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\", pod=~\"$pod\"} [1m])) / sum by (pod) (irate(hikaricp_connections_usage_seconds_count{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\", pod=~\"$pod\"}[1m]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Connection Timeout Count [5m]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 6, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(hikaricp_connections_timeout_total{namespace=\"$namespace\", service=\"$app\", pool=~\"$hikaricp\", pod=~\"$pod\"}[5m]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JDBC Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "JDBC Connections - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 114 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name) (jdbc_connections_idle{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Idle - {{ name }}"
      },
      {
       "expr": "sum by (name) (jdbc_connections_active{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Active - {{ name }}"
      },
      {
       "expr": "sum by (name) (jdbc_connections_min{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Min - {{ name }}"
      },
      {
       "expr": "sum by (name) (jdbc_connections_max{namespace=\"$namespace\", service=\"$app\", pod=\"$pod\"})",
       "legendFormat": "Max - {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat by Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tomcat Threads - $tomcat_thread_group - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tomcat_threads_current_threads{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$tomcat_thread_group\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "tomcat_threads_busy_threads{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$tomcat_thread_group\"}",
       "legendFormat": "Busy"
      }
     ]
    },
    {
     "title": "Tomcat Connections - $tomcat_thread_group - $pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tomcat_connections_current_connections{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$tomcat_thread_group\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "tomcat_connections_keepalive_current_connections{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$tomcat_thread_group\"}",
       "legendFormat": "Keepalive Current"
      }
     ]
    },
    {
     "title": "Max Threads - $tomcat_thread_group",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 7, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (service) (tomcat_threads_config_max_threads{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$tomcat_thread_group\"})",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Max Connections - $tomcat_thread_group",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 12, "y": 60 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (service) (tomcat_connections_config_max_connections{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", name=\"$tomcat_thread_group\"})",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tomcat_sessions_active_current_sessions{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Execution Count [1m]",
     "type": "timeseries",
     "description": "Task scheduling library https://github.com/kagkarlsson/db-scheduler",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (task) (increase(dbscheduler_task_completions_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "{{ task }}"
      },
      {
       "expr": "sum(increase(dbscheduler_task_completions_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "total (press shift + left click to hide)"
      }
     ]
    },
    {
     "title": "Task Execution Time [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (task) (irate(dbscheduler_task_duration_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m])) / sum by (task) (irate(dbscheduler_task_duration_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"}[1m]))",
       "legendFormat": "{{ task }}"
      }
     ]
    },
    {
     "title": "Success/Error Ratio [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(dbscheduler_task_completions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", result=\"ok\"}[5m])) / scalar(sum(increase(dbscheduler_task_completions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])) by (service))",
       "legendFormat": "Success",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(dbscheduler_task_completions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", result=\"failed\"}[5m])) / scalar(sum(increase(dbscheduler_task_completions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[5m])) by (service))",
       "legendFormat": "Error",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Errors by Task [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(dbscheduler_task_completions_total{namespace=\"$namespace\", service=\"$app\", result=\"failed\"}[5m])) by (task)",
       "legendFormat": "{{ task }}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Execution Count by Task [selected range]",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(dbscheduler_task_completions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[$__range]) > 0) by (task))",
       "legendFormat": "{{ task }}"
      }
     ]
    },
    {
     "title": "Total Executions [selected range]",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dbscheduler_task_completions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[$__range]) > 0)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Execution Results [selected range]",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(dbscheduler_task_completions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\"}[$__range]) > 0) by (result))",
       "legendFormat": "{{ result }}"
      }
     ]
    },
    {
     "title": "Errors by Task [selected range]",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(dbscheduler_task_completions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", result=\"failed\"}[$__range]) > 0) by (task))",
       "legendFormat": "{{ task }}"
      }
     ]
    },
    {
     "title": "Total Errors [selected range]",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(dbscheduler_task_completions_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", result=\"failed\"}[$__range]) > 0)",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}