{
 "title": "K8S cluster (yandex-metrics)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(master_cpu_utilization_percent, cluster_id)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_cpu_total_cores{cluster_id=\"$Cluster\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster CPU utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "master_cpu_utilization_percent{cluster_id=\"$Cluster\"}",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Cluster RAM utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "master_memory_utilization_percent{cluster_id=\"$Cluster\"}",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (resource_id) (cpu_utilization{resource_id=~\"$Node\"}))",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "CPU utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (resource_id) (cpu_utilization{resource_id=~\"$Node\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "RAM utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_used_bytes{node=~\"$Node\"} * 100 / node_memory_total_bytes{node=~\"$Node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (resource_id) (network_received_bytes{resource_id=~\"$Node\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Network sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (resource_id) (network_sent_bytes{resource_id=~\"$Node\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "$Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "Node",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_cpu_total_cores{node=\"$Node\"}"
      }
     ]
    },
    {
     "title": "CPU Allocatable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_cpu_allocatable_cores{node=\"$Node\"}"
      }
     ]
    },
    {
     "title": "CPU utilization (%)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(cpu_utilization{resource_id=\"$Node\"})"
      }
     ]
    },
    {
     "title": "RAM total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_total_bytes{node=\"$Node\"}"
      }
     ]
    },
    {
     "title": "RAM allocatable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_allocatable_bytes{node=\"$Node\"}"
      }
     ]
    },
    {
     "title": "RAM usage",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_used_bytes{node=\"$Node\"}"
      }
     ]
    },
    {
     "title": "RAM utilization (%)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_used_bytes{node=\"$Node\"} * 100 / node_memory_total_bytes{node=\"$Node\"}"
      }
     ]
    },
    {
     "title": "Connection utilization (%)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "network_connections_quota_utilization{resource_id=\"$Node\"}"
      }
     ]
    }
   ]
  }
 ]
}