{
 "title": "Pods (yandex-metrics)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(container_cpu_core_usage_time, cluster_id)"
    }
   },
   {
    "name": "dam",
    "query": {
     "query": "label_values(container_cpu_core_usage_time{cluster_id=~\"$Cluster\"}, exported_pod)"
    }
   },
   {
    "name": "yandex",
    "query": {
     "query": "label_values(container_cpu_core_usage_time{cluster_id=~\"$Cluster\"}, exported_pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Count of pods (dam-media)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_core_usage_time{exported_pod=~\"$dam\"})"
    }
   ]
  },
  {
   "title": "Restarts of pods (dam-media)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(container_restart_count{exported_pod=~\"$dam\"}[1m]))"
    }
   ]
  },
  {
   "title": "Count of pods (yandex-storage)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_core_usage_time{exported_pod=~\"$yandex\"})"
    }
   ]
  },
  {
   "title": "Restarts of pods (yandex-storage)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(container_restart_count{exported_pod=~\"$yandex\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU average utilization (dam-media)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pod) (container_cpu_limit_utilization{exported_pod=~\"$dam\"})",
     "legendFormat": "Limit utilization"
    },
    {
     "expr": "avg by (pod) (container_cpu_request_utilization{exported_pod=~\"$dam\"})",
     "legendFormat": "Request utilization"
    }
   ]
  },
  {
   "title": "CPU average utilization (yandex-storage)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pod) (container_cpu_limit_utilization{exported_pod=~\"$yandex\"})",
     "legendFormat": "Limit utilization"
    },
    {
     "expr": "avg by (pod) (container_cpu_request_utilization{exported_pod=~\"$yandex\"})",
     "legendFormat": "Request utilization"
    }
   ]
  },
  {
   "title": "RAM Average utilization (dam-media)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pod) (container_memory_limit_utilization{exported_pod=~\"$dam\"})",
     "legendFormat": "Limit utilization"
    },
    {
     "expr": "avg by (pod) (container_memory_request_utilization{exported_pod=~\"$dam\"})",
     "legendFormat": "Request utilization"
    }
   ]
  },
  {
   "title": "RAM Average utilization (yandex-storage)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pod) (container_memory_limit_utilization{exported_pod=~\"$yandex\"})",
     "legendFormat": "Limit utilization"
    },
    {
     "expr": "avg by (pod) (container_memory_request_utilization{exported_pod=~\"$yandex\"})",
     "legendFormat": "Request utilization"
    }
   ]
  },
  {
   "title": "DAM-MEDIA Pods (CPU)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$dam",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
     "repeat": "dam",
     "targets": [
      {
       "expr": "container_cpu_limit_utilization{exported_pod=\"$dam\"}",
       "legendFormat": "Limit utilization"
      },
      {
       "expr": "container_cpu_request_utilization{exported_pod=\"$dam\"}",
       "legendFormat": "Request utilization"
      }
     ]
    }
   ]
  },
  {
   "title": "DAM-MEDIA Pods (RAM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "$dam",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
     "repeat": "dam",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "container_memory_limit_utilization{exported_pod=\"$dam\"}",
       "legendFormat": "Limit utilization"
      },
      {
       "expr": "container_memory_request_utilization{exported_pod=\"$dam\"}",
       "legendFormat": "Request utilization"
      }
     ]
    }
   ]
  },
  {
   "title": "YANDEX-STORAGE Pods (CPU)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "$yandex",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
     "repeat": "yandex",
     "targets": [
      {
       "expr": "container_cpu_limit_utilization{exported_pod=\"$yandex\"}",
       "legendFormat": "Limit utilization"
      },
      {
       "expr": "container_cpu_request_utilization{exported_pod=\"$yandex\"}",
       "legendFormat": "Request utilization"
      }
     ]
    }
   ]
  },
  {
   "title": "YANDEX-STORAGE Pods (RAM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "$yandex",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
     "repeat": "yandex",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "container_memory_limit_utilization{exported_pod=\"$yandex\"}",
       "legendFormat": "Limit utilization"
      },
      {
       "expr": "container_memory_request_utilization{exported_pod=\"$yandex\"}",
       "legendFormat": "Request utilization"
      }
     ]
    }
   ]
  }
 ]
}