{
 "title": "S3 (yandex-metrics)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Storage",
    "query": {
     "query": "label_values(space_usage, resource_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Storage (objects)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "repeat": "Storage",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(objects_count{resource_id=\"$Storage\"})"
    }
   ]
  },
  {
   "title": "$Storage (usage)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "repeat": "Storage",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "space_usage{resource_id=\"$Storage\", storage_type=\"All\"}"
    }
   ]
  },
  {
   "title": "$Storage (rps)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "repeat": "Storage",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rps{resource_id=\"$Storage\"})"
    }
   ]
  },
  {
   "title": "$Storage (download)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "repeat": "Storage",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traffic{bytes=\"BytesDownloaded\", resource_id=\"$Storage\"}"
    }
   ]
  },
  {
   "title": "$Storage (upload)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "repeat": "Storage",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traffic{bytes=\"BytesUploaded\", resource_id=\"$Storage\"}"
    }
   ]
  }
 ]
}