{
 "title": "APM - SLOs: Availability and Latency",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "span", "query": "5m, 30m, 1h, 2h, 6h, 1d, 3d" },
   { "name": "project", "query": "receiveit" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\".*$project.*\"}, namespace) "
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}, service) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SLO",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (ingress,location,namespace) (((kubernetes:ingress_location_namespace_[[project]]:errors_per_responses:ratio_rate[[span]]{ingress=~\"$service\",namespace=\"$namespace\"}*100 > on(ingress,location) kubernetes:error_[[project]]_slo:percent) *0 + 1)\r\nor\r\n(( kubernetes:ingress_location_namespace_[[project]]:request_latency_seconds:p90_rate[[span]]{namespace=\"$namespace\",ingress=~\"$service\"} >  ignoring(namespace, severity_level) group_left() kubernetes:latency_p90_[[project]]_slo:seconds) *0+1 )\r\nor\r\n(( kubernetes:ingress_location_namespace_[[project]]:request_latency_seconds:p99_rate[[span]]{namespace=\"$namespace\",ingress=~\"$service\"} >  ignoring(namespace, severity_level) group_left() kubernetes:latency_p99_[[project]]_slo:seconds) *0+1 ))\r\n#all \r\n# or (min by (ingress,location) (kubernetes:error_[[project]]_slo:percent{ingress=~\"$service\"} * 0 or (kubernetes:ingress_location_namespace_[[project]]:request_latency_seconds:p90_rate5m{ingress=~\"$service\"} * 0) or (kubernetes:ingress_location_namespace_[[project]]:request_latency_seconds:p90_rate5m{ingress=~\"$service\"} * 0))) ",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "SLO, overall ingresses, window $span",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * (sum by (ingress,location) (kubernetes:ingress_location_namespace_[[project]]:errors_per_responses:ratio_rate[[span]]{ingress=~\"$service\", namespace=\"$namespace\"} and kubernetes:ingress_location_namespace_[[project]]:errors_per_responses:ratio_rate3d{ingress=~\"$service\", namespace=\"$namespace\"})) \r\nOR \r\n(sum by (ingress,location)(min_over_time(kubernetes:ingress_location_namespace_[[project]]:errors_per_responses:ratio_rate3d{ingress=~\"$service\",namespace=\"$namespace\"}[30d])))\r\nOR \r\n(sum by (ingress,location)\r\n(min_over_time(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", ingress=~\"$service\"}[3d]))*0)\r\n)",
     "legendFormat": "{{ingress}}{{location}}"
    }
   ]
  },
  {
   "title": "Avg RPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (location)(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\", ingress=~\"$service\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "service",
   "collapsed": true,
   "panels": [
    {
     "title": "Errors over $span",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "kubernetes:error_inbound_slo:percent{ingress=\"$service\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "((max_over_time(kubernetes:ingress_location_namespace_[[project]]:errors_per_responses:ratio_rate[[span]]{ingress=\"$service\",  namespace=\"$namespace\"}[$__range])*100)\r\nOR min by (ingress,location,namespace) (min_over_time(ingress_nginx_detail_info{ingress=\"$service\", namespace=\"$namespace\"}[10d])*0))\r\n",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "Errors ratio over 5m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "kubernetes:ingress_location_namespace_inbound:errors_per_responses:ratio_rate5m{ingress=\"$service\"}*100",
       "legendFormat": "{{location}}"
      }
     ]
    },
    {
     "title": "P99 Latency Target max over $span",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "last_over_time(kubernetes:latency_p99_slo:seconds{service=\"$service\"}[$span])\r\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "max_over_time (histogram_quantile (\r\n          0.99,\r\n          sum by (le, ingress, location, namespace)(\r\n            rate(ingress_nginx_detail_upstream_response_seconds_bucket{namespace=\"$namespace\",ingress=\"$service\"}[$__rate_interval])\r\n          )\r\n        )[$__range:])"
      }
     ]
    },
    {
     "title": "P90 Latency Target max over $span",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "last_over_time(kubernetes:latency_p90_slo:seconds{service=\"$service\"}[$span])\r\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "max_over_time (histogram_quantile (\r\n          0.90,\r\n          sum by (le, ingress, location, namespace)(\r\n            rate(ingress_nginx_detail_upstream_response_seconds_bucket{namespace=\"$namespace\",ingress=\"$service\"}[$__rate_interval])\r\n          )\r\n        )[$__range:])"
      }
     ]
    },
    {
     "title": "Latency over 5m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (location) (kubernetes:ingress_location_namespace_[[project]]:request_latency_seconds:p90_rate5m{ingress=\"$service\",namespace=\"$namespace\"})",
       "legendFormat": "90th percentile  by {{ location }}"
      },
      {
       "expr": "sum by (location) (kubernetes:ingress_location_namespace_[[project]]:request_latency_seconds:p99_rate5m{ingress=\"$service\", namespace=\"$namespace\"})",
       "legendFormat": "99th percentile  by {{ location }}"
      }
     ]
    },
    {
     "title": "Avg RPS by location",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (location)(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\", ingress=\"$service\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ location }}"
      }
     ]
    }
   ]
  }
 ]
}