{
 "title": "Camunda Metrics",
 "description": "Camunda Metrics exposed by dedicated plugin",
 "tags": [ "camunda" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(camunda_active_incidents, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(camunda_active_incidents{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "engineName",
    "label": "Engine",
    "query": {
     "query": "label_values(camunda_active_incidents{namespace=\"$namespace\", service=\"$app\"}, engineName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Process Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_process_instances{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Completed Process Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_completed_process_instances{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  { "title": "Incidents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active Incidents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "camunda_active_incidents{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
     "legendFormat": "{{ engineName }}"
    }
   ]
  },
  {
   "title": "Active Process Incidents",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (processName) (camunda_active_process_incidents{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"} > 0)",
     "legendFormat": "{{ processName }}"
    }
   ]
  },
  {
   "title": "Process Definitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Process Definitions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_process_definitions{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Deployments",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_deployments{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Timers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executable Timer Jobs",
     "type": "graph",
     "description": "Timers that are ready to be executed (past due date)",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_executable_timer_jobs{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    },
    {
     "title": "Timer Jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_timer_jobs{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "User Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active User Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_user_tasks{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executable Jobs",
     "type": "graph",
     "description": "Jobs ready to be executed (past due date)",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_executable_jobs{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    },
    {
     "title": "Message Jobs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_message_jobs{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "External Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active External Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_external_tasks{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    },
    {
     "title": "Active Locked External Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_locked_external_tasks{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    },
    {
     "title": "Active Not Locked External Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_not_locked_external_tasks{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Message Event Subscriptions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_message_event_subscriptions{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    },
    {
     "title": "Active Signal Event Subscriptions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_signal_event_subscriptions{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    },
    {
     "title": "Active Compensate Event Subscriptions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_compensate_event_subscriptions{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    },
    {
     "title": "Active Conditional Event Subscriptions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_conditional_event_subscriptions{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_user_count{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tenants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tenant Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_tenant_count{namespace=\"$namespace\", service=\"$app\", engineName=\"$engineName\"}",
       "legendFormat": "{{ engineName }}"
      }
     ]
    }
   ]
  }
 ]
}