{
 "title": "perfDostovernost",
 "description": "Dashboard for spring boot services. Displays standard spring metrics, jvm metrics, important data from kubernetes. Grafana 10+. Up-to-date original version is here https://github.lmru.tech/adeo/lmru--sv-grafana-dashboards/",
 "time": { "from": "2025-01-17T06:05:44.242Z", "to": "2025-01-17T13:59:04.669Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_requests_total,namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(http_requests_total{namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_controller_pod{namespace=\"$namespace\", controller_name=\"$app\"},pod)"
    }
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(\n  http_requests_total{\n        service=~\"$app\"\n\n  }[$__range]\n))"
    }
   ]
  },
  {
   "title": "Max RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(\n\t\n\t    sum(rate(http_requests_total {\n\t            service=~\"$app\"\n        \n\t    }[1m]))\n\t\n)"
    }
   ]
  },
  {
   "title": "Max response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(\n\thistogram_quantile(1, \n\t    increase(http_request_duration_seconds_bucket {\n\t            service=~\"$app\"\n        \n\t    }[5m])\n\t)\n)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "P99, P95, P50 of response times",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n    sum(rate(\n        http_request_duration_seconds_bucket{\n            service=~\"$app\"            \n            }[1m]\n    )) by(le))",
     "legendFormat": "P99 {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.95, \n    sum(rate(\n        http_request_duration_seconds_bucket{\n            service=~\"$app\"            \n            }[1m]\n\n    )) by(le))",
     "legendFormat": "P95 {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.5, \n    sum(rate(\n        http_request_duration_seconds_bucket{\n            service=~\"$app\"            \n            }[1m]\n    )) by(le))",
     "legendFormat": "P50 {{handler}}"
    }
   ]
  },
  {
   "title": "Request Per Second (RPS) by app",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "\t    sum(rate(http_requests_total {\r\n\t            service=~\"$app\",   \r\n\t    }[1m]))",
     "legendFormat": "$app"
    }
   ]
  },
  {
   "title": "CLIENT AVAILABILITY (2xx/all)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_requests_total{\r\n        service=~\"$app\",\r\n        status=~\"2xx\"\r\n    }[1m]\r\n  )) / \r\nsum(\r\n  rate(\r\n    http_requests_total{\r\n        service=~\"$app\"      \r\n    }[1m]\r\n  ))*100",
     "legendFormat": "${app}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_inprogress{service=~\"$app\"}",
     "legendFormat": "HTTP Request In progress"
    }
   ]
  },
  {
   "title": "Response Statuses (all)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\", service=~\"$app\",status=~\"2..|3..|4..|5..\"}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response 5xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      http_requests_total{\n        status=\"5xx\",  \n        service=~\"$app\"      \n      }[5m]\n    )\n  ) by (service, handler, method)\n, 0.001)",
     "legendFormat": "{{service}}: {{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Responses 4xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      http_requests_total{\n        status=\"4xx\",\n        service=~\"$app\"      \n      }[5m]\n    )\n  ) by (service, handler, method)\n, 0.001)",
     "legendFormat": "{{service}}: {{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "CPU Usage % by app",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by(pod) (\r\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\r\n  * on (pod)\r\n  sum by(pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\", namespace=\"$namespace\"}[$__rate_interval]))\r\n)\r\n/\r\navg by(pod) (\r\n  kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", container=\"$app\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (MAX)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (\r\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\r\n  * on (pod)\r\n  sum by(pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\", namespace=\"$namespace\"}[$__rate_interval]))\r\n)",
     "legendFormat": "container_cpu_usage_seconds_total (cores)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"}[$__rate_interval]))\n)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Memory Usage (MAX)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=\"$app\"}) / 1048576",
     "legendFormat": "container_memory_working_set_bytese (MB)"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (app) / 1048576",
     "legendFormat": "container_network_receive_bytes_total (MB)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (app) / 1048576",
     "legendFormat": "container_network_transmit_bytes_total (MB)"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (app) / 1048576",
     "legendFormat": "container_network_receive_bytes_total (MB)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (app) / 1048576",
     "legendFormat": "container_network_transmit_bytes_total (MB)"
    }
   ]
  }
 ]
}