{
 "title": "PerfSCM",
 "description": "Dashboard for spring boot services. Displays standard spring metrics, jvm metrics, important data from kubernetes. Grafana 10+. Up-to-date original version is here https://github.lmru.tech/adeo/lmru--sv-grafana-dashboards/",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "scdp-whs-stockcounting-perf, \nscdp-whs-stockcounting-preprod"
   },
   {
    "name": "app",
    "label": "Application",
    "query": "inventory-backend, inventory-front"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_controller_pod{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Latency From All URI",
   "type": "timeseries",
   "description": "P99, P95, P50 of response times",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_sum{service=\"$app\"}[1m]) \r\n/ \r\nrate(http_client_requests_seconds_count{service=\"$app\"}[1m])",
     "legendFormat": "$app-{{uri}}"
    }
   ]
  },
  {
   "title": "Average Client Latency ",
   "type": "timeseries",
   "description": "P99, P95, P50 of response times",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{service=\"$app\"}[1m])) \r\n/ \r\nsum(rate(http_client_requests_seconds_count{service=\"$app\"}[1m]))",
     "legendFormat": "$app"
    }
   ]
  },
  {
   "title": "CLIENT AVAILABILITY (2xx/all)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status=\"200\"}[5m]))\r\n/\r\nsum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m]))\r\n*100",
     "legendFormat": "${app}"
    }
   ]
  },
  {
   "title": "Request Per Second (RPS) by app",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service) (rate(http_client_requests_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", status!=\"CLIENT_ERROR\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Statuses [5m] CLIENT",
   "type": "timeseries",
   "description": "Including IO_ERROR",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (status) / scalar(sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", status!=\"CLIENT_ERROR\"}[5m])) by (service))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Statuses [5m] SERVER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (status) / scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", uri!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "CPU Usage % by app",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by(pod) (\r\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\r\n  * on (pod)\r\n  sum by(pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\", namespace=\"$namespace\"}[$__rate_interval]))\r\n)\r\n/\r\navg by(pod) (\r\n  kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", container=\"$app\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (app)",
     "legendFormat": "container_cpu_usage_seconds_total (cores)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"}[$__rate_interval]))\n)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=\"$app\"}) / 1048576",
     "legendFormat": "container_memory_working_set_bytese (MB)"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (app) / 1048576",
     "legendFormat": "container_network_receive_bytes_total (MB)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (app) / 1048576",
     "legendFormat": "container_network_transmit_bytes_total (MB)"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (app) / 1048576",
     "legendFormat": "container_network_receive_bytes_total (MB)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (app) / 1048576",
     "legendFormat": "container_network_transmit_bytes_total (MB)"
    }
   ]
  }
 ]
}