{
 "title": "Rupture Autocreation",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=~\"scdp-whs-ruptures.*\"}, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"auto-creation\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$app\"}, pod)"
    }
   },
   { "name": "full_stock_topic", "query": "full_stock_information" },
   {
    "name": "capacity_topic",
    "query": "lmaddress-canonical-int-products-store-product-capacity-v1"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview ruptures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Ruptures To Create",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toCreate\"}) - sum by (pod) (autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toCreate-failed\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Ruptures To Delete",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toDelete\"}) - sum by (pod) (autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toDelete-failed\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAILED Offer Orchestrator Requests",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome!=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAILED Create Requests",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\", outcome!=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAILED Delete Requests",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\", outcome!=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Inner messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Added Messages",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_inner_message_produce_counter_total{pod=~\"$pod\", namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Added Messages by Route",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (route_type)(autocreation_inner_message_produce_counter_total{pod=~\"$pod\", namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Processed Messages",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_inner_message_consume_counter_total{pod=~\"$pod\", namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processed Messages by Route",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (route_type)(autocreation_inner_message_consume_counter_total{pod=~\"$pod\", namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Messages to Process",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max (autocreation_inner_message_statistics{pod=~\"$pod\", namespace=\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current Time Lag by Route",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 5, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (route_type) (autocreation_inner_message_time_lag {namespace=\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time since last Worker Run",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 13, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - max by (route_type) (autocreation_inner_message_worker_last_start_time {namespace=\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Unfrozen Message Count",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (route_type) (autocreation_inner_message_unfrozen_messages_counter_total {namespace=\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Count of added messages[1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (route_type) (increase(autocreation_inner_message_produce_counter_total{pod=~\"$pod\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Count of processed messages[1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (route_type) (increase(autocreation_inner_message_consume_counter_total{pod=~\"$pod\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Lag Per Period",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (route_type) (autocreation_inner_message_time_lag {namespace=\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unfrozen Message Count[1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(autocreation_inner_message_unfrozen_messages_counter_total{pod=~\"$pod\", namespace=\"$namespace\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message Count to Process",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (route_type) (autocreation_inner_message_statistics{pod=~\"$pod\", namespace=\"$namespace\", processing=\"false\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Stock Repo - full_stock_information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Total Consumed Batches",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Consumed Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$full_stock_topic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Lag Of Topic",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spring_cloud_stream_binder_kafka_offset {namespace=\"$namespace\", pod=~\"$pod\", topic=\"$full_stock_topic\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumed Messages Per Period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$full_stock_topic\"}[$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Minute Consumed Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$full_stock_topic\"}) - sum by (pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$full_stock_topic\"} offset 1m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Hour Consumed Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$full_stock_topic\"}) - sum by (pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$full_stock_topic\"} offset 1h)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 24 Hour Consumed Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$full_stock_topic\"}) - sum by (pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$full_stock_topic\"} offset 24h)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total StockRepo Kafka Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (spring_cloud_stream_binder_kafka_offset {namespace=\"$namespace\", pod=~\"$pod\", topic=\"$full_stock_topic\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Stock Repo Kafka lag",
   "type": "text",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 8 },
   "options": {
    "content": "# Stock Repo topic PROD\n[KAFKA LAG PROD](https://grafana-saa.apps.lmru.tech/d/gdi6l8vZz/stock-repository-kafka?orgId=1&from=now-24h&to=now)\n\n# Stock Repo topic DEV/TEST/PREPROD\n\n[KAFKA LAG DEV/TEST/PREPROD](https://grafana-saa-stage.apps.lmru.tech/d/gdi6l8vZz/stock-repository-kafka?orgId=1)"
   }
  },
  {
   "title": "Time Lag Per Period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (pod) (autocreation_consumed_time_lag {namespace=\"$namespace\", pod=~\"$pod\", topic=\"$full_stock_topic\"})",
     "legendFormat": "{{pod}} / partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Messages per Batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$full_stock_topic\"}) / sum by (pod) (spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Batches [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Batches [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Batches [1h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process time per batch [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(spring_kafka_listener_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"}[1m])) / sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process time per batch [10m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(spring_kafka_listener_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"}[10m])) / sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process time per batch [1h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(spring_kafka_listener_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"}[1h])) / sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)full(.*)\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages from StockRepo [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"filtered\"}[1m])",
     "legendFormat": "{{pod}} - messages from StockRepo"
    },
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"initial\"}[1m])",
     "legendFormat": "{{pod}} - Messages without topEM and locAttr values"
    },
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"WOProductData\"}[1m])",
     "legendFormat": "{{pod}} - Messages without product data"
    },
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"WOActions\"}[1m])",
     "legendFormat": "{{pod}} - Messages without actions"
    }
   ]
  },
  {
   "title": "Messages from StockRepo [10m]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"filtered\"}[10m])",
     "legendFormat": "{{pod}} - messages from StockRepo"
    },
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"initial\"}[10m])",
     "legendFormat": "{{pod}} - Messages without topEM and locAttr values"
    },
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"WOProductData\"}[10m])",
     "legendFormat": "{{pod}} - Messages without product data"
    },
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"WOActions\"}[10m])",
     "legendFormat": "{{pod}} - Messages without actions"
    }
   ]
  },
  {
   "title": "Messages from StockRepo [1h]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"filtered\"}[1h])",
     "legendFormat": "{{pod}} - messages from StockRepo"
    },
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"initial\"}[1h])",
     "legendFormat": "{{pod}} - Messages without topEM and locAttr values"
    },
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"WOProductData\"}[1h])",
     "legendFormat": "{{pod}} - Messages without product data"
    },
    {
     "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"WOActions\"}[1h])",
     "legendFormat": "{{pod}} - Messages without actions"
    }
   ]
  },
  {
   "title": "LM address - capacity topic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Consumed Batches",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Consumed Messages",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Lag Of Topic",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (spring_cloud_stream_binder_kafka_offset {namespace=\"$namespace\", pod=~\"$pod\", topic=\"$capacity_topic\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current Time Lag Of Topic",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (pod) (autocreation_consumed_time_lag {namespace=\"$namespace\", pod=~\"$pod\", topic=\"$capacity_topic\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Consumed Messages Per Period",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"}[$__range]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Last Minute Consumed Messages",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"}) - sum by (pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"} offset 1m)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Hour Consumed Messages",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"}) - sum by (pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"} offset 1h)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last 24 Hour Consumed Messages",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"}) - sum by (pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"} offset 24h)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Address capacity topic Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (spring_cloud_stream_binder_kafka_offset {namespace=\"$namespace\", pod=~\"$pod\", topic=\"$capacity_topic\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Lag Per Period",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod) (autocreation_consumed_time_lag {namespace=\"$namespace\", pod=~\"$pod\", topic=\"$capacity_topic\"})",
       "legendFormat": "{{pod}} / partition: {{partition}}"
      }
     ]
    },
    {
     "title": "Messages per Batch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "targets": [
      {
       "expr": "sum by (pod) (kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"}) / sum by (pod) (spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Batches [1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Batches [10m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"}[10m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Batches [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "targets": [
      {
       "expr": "sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process time per batch [1m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(spring_kafka_listener_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"}[1m])) / sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process time per batch [10m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(spring_kafka_listener_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"}[10m])) / sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"}[10m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process time per batch [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(spring_kafka_listener_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"}[1h])) / sum by (pod) (increase(spring_kafka_listener_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", name=~\"(.*)capacity(.*)\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Messages Address Capacity[1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 159 },
     "targets": [
      {
       "expr": "sum by(pod) (increase(kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Messages Address Capacity [10m]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 168 },
     "targets": [
      {
       "expr": "sum by(pod) (increase(kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"}[10m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Messages Address Capacity [1h]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 168 },
     "targets": [
      {
       "expr": "sum by(pod) (increase(kafka_consumer_fetch_manager_records_consumed_total{pod=~\"$pod\", namespace=\"$namespace\", topic=\"$capacity_topic\"}[1h]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Offer Orchestrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SUCCESS requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAILED requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome!=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Requests [10m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod, outcome, status) (autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome!=\"SUCCESS\"})",
       "legendFormat": "{{pod}} - {{outcome}} - {{status}}"
      }
     ]
    },
    {
     "title": "Requests [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Requests [10m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[10m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Requests [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1h])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Request [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_offerOrchestratorClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) / sum by (pod) (increase(autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Request [10m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_offerOrchestratorClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\"}[10m])) / sum by (pod) (increase(autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[10m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Request [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_offerOrchestratorClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\"}[1h])) / sum by (pod) (increase(autocreation_offerOrchestratorClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1h])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 165 },
     "options": {
      "content": "# OFFER ORCHESTRATOR THREAD POOL"
     }
    },
    {
     "title": "Offer Orchestrator Active Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "executor_active_threads{pod=~\"$pod\", namespace=\"$namespace\", name=\"offer_orchestrator_call_task_executor\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Offer Orchestrator Tasks In Queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "executor_queued_tasks{pod=~\"$pod\", namespace=\"$namespace\", name=\"offer_orchestrator_call_task_executor\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pool Size",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "executor_pool_size_threads{pod=~\"$pod\", namespace=\"$namespace\", name=\"offer_orchestrator_call_task_executor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max Pool Size",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "executor_pool_max_threads{pod=~\"$pod\", namespace=\"$namespace\", name=\"offer_orchestrator_call_task_executor\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Rupture Actions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (autocreation_ruptureClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SUCCESS requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_ruptureClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAILED requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_ruptureClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome!=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Requests [10m]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod, outcome, status) (autocreation_ruptureClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome!=\"SUCCESS\"})",
       "legendFormat": "{{pod}} - {{outcome}} - {{status}}"
      }
     ]
    },
    {
     "title": "Requests [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(autocreation_ruptureClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Requests [10m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(autocreation_ruptureClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[10m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Requests [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(autocreation_ruptureClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1h])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Request [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_ruptureClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) / sum by (pod) (increase(autocreation_ruptureClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Request [10m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_ruptureClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\"}[10m])) / sum by (pod) (increase(autocreation_ruptureClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[10m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Request [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_ruptureClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\"}[1h])) / sum by (pod) (increase(autocreation_ruptureClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1h])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Stock Repo REST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "TOTAL requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (autocreation_stockClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCCESS requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(autocreation_stockClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome=\"SUCCESS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAILED requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(autocreation_stockClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome!=\"SUCCESS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Requests [10m]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod, outcome, status) (autocreation_stockClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome!=\"SUCCESS\"})",
     "legendFormat": "{{pod}} - {{outcome}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(autocreation_stockClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time Per Request [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(autocreation_stockClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) / sum by (pod) (increase(autocreation_stockClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "LS Address REST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "TOTAL requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (autocreation_lsClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCCESS requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(autocreation_lsClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome=\"SUCCESS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAILED requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(autocreation_lsClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome!=\"SUCCESS\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Requests [10m]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod, outcome, status) (autocreation_lsClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", outcome!=\"SUCCESS\"})",
     "legendFormat": "{{pod}} - {{outcome}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(autocreation_lsClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time Per Request [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod) (increase(autocreation_lsClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) / sum by (pod) (increase(autocreation_lsClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\"}[1m])) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "BFF Messages To Create",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mesages To Create Ruptures",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toCreate\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "TOTAL requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SUCCESS requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\", outcome=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAILED requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\", outcome!=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod, outcome, status) (autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\", outcome!=\"SUCCESS\"})",
       "legendFormat": "{{pod}} - {{outcome}} - {{status}}"
      }
     ]
    },
    {
     "title": "Messages to Create [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toCreate\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Messages to Create [10m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toCreate\"}[10m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Messages to Create [1h]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
     "targets": [
      {
       "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toCreate\"}[1h])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 153 }, "options": { "content": "# REQUESTS" } },
    {
     "title": "Create Requests [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\"}[1m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Create Requests [10m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\"}[10m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Create Requests [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\"}[1h])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Create Request [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_BFFClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\"}[1m])) / sum by (pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\"}[1m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Create Request [10m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_BFFClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\"}[10m])) / sum by (pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\"}[10m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Create Request [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_BFFClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\"}[1h])) / sum by (pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures-autocalculation\"}[1h])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BFF Messages To Delete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages To Delete Ruptures",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toDelete\"}",
       "legendFormat": "{{pod}} - Total  requests"
      }
     ]
    },
    {
     "title": "TOTAL requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SUCCESS requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\", outcome=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAILED requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\", outcome!=\"SUCCESS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Requests [10m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod, outcome, status) (autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\", outcome!=\"SUCCESS\"})",
       "legendFormat": "{{pod}} - {{outcome}} - {{status}}"
      }
     ]
    },
    {
     "title": "Messages to Delete [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 136 },
     "targets": [
      {
       "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toDelete\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Messages to Delete [10m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 145 },
     "targets": [
      {
       "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toDelete\"}[10m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Messages to Delete[1h]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 145 },
     "targets": [
      {
       "expr": "increase(autocreation_message_counter_total{pod=~\"$pod\", namespace=\"$namespace\", step=\"toDelete\"}[1h])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 154 }, "options": { "content": "# REQUESTS" } },
    {
     "title": "Delete Requests [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\"}[1m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Delete Requests [10m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\"}[10m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Delete Requests [1h]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\"}[1h])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Delete Request [1m]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_BFFClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\"}[1m])) / sum by (pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\"}[1m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Delete Request [10m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_BFFClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\"}[10m])) / sum by (pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\"}[10m])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Time Per Delete Request [1h]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod) (increase(autocreation_BFFClient_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\"}[1h])) / sum by (pod) (increase(autocreation_BFFClient_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", uri=\"/v1/ruptures-web/ruptures/finish\"}[1h])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}