{
 "title": "Receiveit // Async // SLI",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "excluded_urls",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*|/_healthz|/_readiness"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result((group by (namespace) (jvm_classes_loaded_classes) OR group by (namespace) (nodejs_version_info)))"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "query_result(group by (service) ((jvm_classes_loaded_classes{namespace=\"$namespace\",service=~\"$services_with_async_requests\"}) OR (nodejs_version_info{namespace=\"$namespace\",service=~\"$services_with_async_requests\"})))\n"
    }
   },
   {
    "name": "uri",
    "label": "Uri",
    "query": {
     "query": "query_result(group by (uri) (http_server_requests_seconds_sum{namespace=\"$namespace\",service=\"$app\",uri!~\"$excluded_urls\"}) OR group by (path) (http_requests_sum{namespace=\"$namespace\",service=\"$app\",path!~\"$excluded_urls\"}))"
    }
   },
   {
    "name": "rate",
    "label": "Span",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d,60d,90d"
   },
   {
    "name": "services_with_async_requests",
    "label": "services_with_async_requests",
    "query": {
     "query": "label_values(async_requests_bucket, service)"
    }
   },
   {
    "name": "async_metric_name",
    "query": {
     "query": "label_values(async_requests_bucket, name)"
    }
   },
   {
    "name": "locationId",
    "query": {
     "query": "label_values(async_requests_bucket, locationId)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values(async_requests_bucket, status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SLI/SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "SLI Async",
     "expr": "sum(rate(async_requests_count{namespace=\"$namespace\", service=\"$app\", status!=\"timeout\", name=~\"$async_metric_name\", locationId=~\"$locationId\"}[$rate])) / sum(rate(async_requests_count{namespace=\"$namespace\", service=\"$app\", name=~\"$async_metric_name\", locationId=~\"$locationId\"}[$rate]))",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "graph",
   "gridPos": { "h": 11, "w": 19, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(async_requests_count{namespace=\"$namespace\", service=\"$app\", status!=\"timeout\", name=~\"$async_metric_name\", locationId=~\"$locationId\"}[$rate])) / sum(rate(async_requests_count{namespace=\"$namespace\", service=\"$app\", name=~\"$async_metric_name\", locationId=~\"$locationId\"}[$rate]))"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "namespace" },
  {
   "title": "Async Latency",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (name, locationId, status) (rate(async_requests_sum{name=~\"$async_metric_name\", locationId=~\"$locationId\", status=~\"$status\"}[$rate])) / sum by (name, locationId, status) (rate(async_requests_count{name=~\"$async_metric_name\", locationId=~\"$locationId\", status=~\"$status\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Async Latency p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum by (name, locationId, status, le) (\n      rate(async_requests_bucket{name=~\"$async_metric_name\", locationId=~\"$locationId\", status=~\"$status\"}[$rate])\n    )\n  )"
    }
   ]
  },
  {
   "title": "Async Latency p50",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.50,\n    sum by (name, locationId, status, le) (\n      rate(async_requests_bucket{name=~\"$async_metric_name\", locationId=~\"$locationId\", status=~\"$status\"}[$rate])\n    )\n  )"
    }
   ]
  },
  {
   "title": "Async Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (le, name, status, locationId) (rate(async_requests_bucket{namespace=\"$namespace\", service=\"$app\", name=~\"$async_metric_name\", locationId=~\"$locationId\", status=~\"$status\"}[$rate]))",
     "legendFormat": "{{name}} - {{status}} - {{locationId}}"
    },
    {
     "expr": "sum by (le, name, status, locationId) (rate(async_requests_bucket{namespace=\"$namespace\", service=\"$app\", name=~\"$async_metric_name\", locationId=~\"$locationId\", status=~\"$status\"}[$rate]))",
     "legendFormat": "{{name}} - {{status}} - {{locationId}}"
    }
   ]
  },
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Async RPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (name, locationId, status) (rate(async_requests_count{namespace=\"$namespace\", service=\"$app\", name=~\"$async_metric_name\", locationId=~\"$locationId\", status=~\"$status\"}[$rate]))",
     "legendFormat": "{{name}} - {{locationId}} - {{status}}"
    }
   ]
  },
  {
   "title": "ASYNC ERRORS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 36 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (name, locationId) ((rate(async_requests_count{namespace=\"$namespace\", service=\"$app\", name=~\"$async_metric_name\", locationId=~\"$locationId\", status=~\"$status\"}[$rate])))",
     "legendFormat": "{{name}} - {{locationId}} - {{status}}"
    }
   ]
  }
 ]
}