{
 "title": "Certificates Expiration",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(certificates_expiration, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(certificates_expiration{namespace=\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Certificates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (service) (certificates_expiration{namespace=\"$Namespace\", service=\"$Service\"})"
    }
   ]
  },
  {
   "title": "Expired",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((certificates_expiration{namespace=\"$Namespace\", service=\"$Service\"} - time()) / 86400) < bool 0)"
    }
   ]
  },
  {
   "title": "Expiring within 7 days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((certificates_expiration{namespace=\"$Namespace\", service=\"$Service\"} - time()) / 86400) < bool 7)"
    }
   ]
  },
  {
   "title": "Expiring within 28 days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(0 < ((certificates_expiration{namespace=\"$Namespace\", service=\"$Service\"} - time()) / 86400) < bool 28)"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by (service, common_name, organization) (certificates_expiration{namespace=\"$Namespace\", service=\"$Service\"}) - time()) / 86400"
    }
   ]
  }
 ]
}