{
 "title": "HTTP statistic (GO)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(chi_request_duration_milliseconds_count, namespace)"
    }
   },
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values(chi_request_duration_milliseconds_count{namespace=\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "repeat": "Service",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(chi_request_duration_milliseconds_count{namespace=\"$Namespace\", service=\"$Service\", code!~\"5..\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(rate(chi_request_duration_milliseconds_count{namespace=\"$Namespace\", service=\"$Service\", code=~\"5..\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "$Service (IN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Request time (quantile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le, service) (rate(chi_request_duration_milliseconds_bucket{namespace=\"$Namespace\", service=\"$Service\"}[1m])))",
       "legendFormat": "{{service}} (0.5)"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le, service) (rate(chi_request_duration_milliseconds_bucket{namespace=\"$Namespace\", service=\"$Service\"}[1m])))",
       "legendFormat": "{{service}} (0.95)"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le, service) (rate(chi_request_duration_milliseconds_bucket{namespace=\"$Namespace\", service=\"$Service\"}[1m])))",
       "legendFormat": "{{service}} (0.99)"
      }
     ]
    },
    {
     "title": "Status / Method / Uri (requests)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by (code, method, path) (rate(chi_request_duration_milliseconds_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m])) > 0",
       "legendFormat": "{{code}} {{method}} ({{path}})"
      }
     ]
    },
    {
     "title": "Method / Uri (time)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (code, method, path) (rate(chi_request_duration_milliseconds_sum{namespace=\"$Namespace\", service=~\"$Service\"}[2m])) / sum by (code, method, path) (rate(chi_request_duration_milliseconds_count{namespace=\"$Namespace\", service=~\"$Service\"}[2m])) > 0",
       "legendFormat": "{{code}} {{method}} ({{path}})"
      }
     ]
    }
   ]
  }
 ]
}