{
 "title": "Dostovernost-API",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Count of responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starlette_responses_total{service=\"dostovernost-api-task\", path_template!=\"/metrics\", path_template!=\"/docs\"}[1h])",
     "legendFormat": "{{method}}{{path_template}}{{status_code}}"
    }
   ]
  },
  {
   "title": "RPS [Current]",
   "type": "gauge",
   "description": "Current input RPS ",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_processing_time_seconds_count{path_template!=\"/metrics\", service=\"dostovernost-api-task\"}[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "RPS [Avg]",
   "type": "gauge",
   "description": "Average input RPS over selected time period",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_processing_time_seconds_count{path_template!=\"/metrics\", service=\"dostovernost-api-task\"}[1h]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time of response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starlette_requests_processing_time_seconds_sum{service=\"dostovernost-api-task\", path_template!=\"/metrics\"}[1h]) / increase(starlette_requests_processing_time_seconds_count{service=\"dostovernost-api-task\", path_template!=\"/metrics\"}[1h])",
     "legendFormat": "{{method}}{{path_template}}"
    }
   ]
  },
  {
   "title": "status_code [200]",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(starlette_responses_total{service=\"dostovernost-api-task\", status_code=\"200\", path_template!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "status_code [400]",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(starlette_responses_total{service=\"dostovernost-api-task\", status_code=\"400\"})"
    }
   ]
  },
  {
   "title": "status_code [500]",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(starlette_responses_total{service=\"dostovernost-api-task\", status_code=\"500\"})"
    }
   ]
  },
  {
   "title": "Count requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starlette_requests_total{service=\"dostovernost-api-task\", path_template!=\"/metrics\", path_template!=\"/docs\"}[1h])",
     "legendFormat": "{{method}}{{path_template}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(starlette_exceptions_total{service=\"dostovernost-api-task\"}[1h])",
     "legendFormat": "{{exception_type}}"
    }
   ]
  }
 ]
}