{
 "title": "PDP Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance" }
  ]
 },
 "panels": [
  {
   "title": "Store loading time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "data_loading{job=\"custom-lmru-pilot-pdp-exporter\",path=\"/pdp\"}",
     "legendFormat": "Path - \"{{`{{path}}`}}\""
    }
   ]
  },
  {
   "title": "Rendering time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "app_rendering{namespace=\"isomorphic\", path=\"/pdp\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(nodejs_version_info{instance=~\"$instance\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_active_handles_total[5m])",
     "legendFormat": "Active Handler - {{`{{instance}}`}}"
    },
    {
     "expr": "rate(nodejs_active_requests_total[5m])",
     "legendFormat": "Active Request - {{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total[2m]) * 100",
     "legendFormat": "User CPU - {{`{{instance}}`}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total[2m]) * 100",
     "legendFormat": "Sys CPU - {{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes",
     "legendFormat": "Process Memory - {{`{{instance}}`}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes",
     "legendFormat": "Heap Total - {{`{{instance}}`}}"
    },
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Heap Used - {{`{{instance}}`}}" },
    {
     "expr": "nodejs_external_memory_bytes",
     "legendFormat": "External Memory - {{`{{instance}}`}}"
    }
   ]
  }
 ]
}