{
 "title": "WeCare",
 "time": { "from": "2024-06-28T06:26:08.999Z", "to": "2024-06-28T07:26:08.999Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "metric", "query": "detail" },
   {
    "name": "by",
    "query": "by (ingress, service, service_port)"
   },
   {
    "name": "legend_format",
    "query": "{{ingress}} → {{service}}:{{service_port}}"
   },
   { "name": "alt_name", "query": "VHost and Location" },
   { "name": "alt_by", "query": "by (vhost, location)" },
   { "name": "alt_legend_format", "query": "{{vhost}}{{location}}" },
   { "name": "controller", "label": "Controller", "query": ".*" },
   { "name": "app", "label": "App", "query": ".*" },
   { "name": "node", "label": "Node", "query": ".*" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(ingress_nginx_${metric}_info{job=\"nginx-ingress-controller\"}, namespace)"
    }
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(ingress_nginx_${metric}_info{job=\"nginx-ingress-controller\", namespace=~\"$namespace\"}, ingress)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(ingress_nginx_${metric}_info{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress=~\"$ingress\"}, service)"
    }
   },
   {
    "name": "service_port",
    "label": "Service Port",
    "query": {
     "query": "label_values(ingress_nginx_${metric}_info{job=\"nginx-ingress-controller\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\"}, service_port)"
    }
   },
   { "name": "vhost", "label": "VHost", "query": ".*" },
   { "name": "location", "label": "Location", "query": ".*" },
   {
    "name": "content_kind",
    "label": "Content Kind",
    "query": {
     "query": "label_values(ingress_nginx_${metric}_info{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\"}, content_kind)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(ingress_nginx_${metric}_requests_total{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}, method)"
    }
   },
   {
    "name": "status",
    "label": "Method",
    "query": {
     "query": "label_values(ingress_nginx_${metric}_responses_total{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}, status)"
    }
   },
   {
    "name": "pod_ip",
    "label": "Pod IP",
    "query": {
     "query": "label_values(ingress_nginx_${metric}_backend_info{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\"}, pod_ip)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(atomix_role, cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(atomix_role{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, partition)"
    }
   },
   {
    "name": "class_bucket",
    "query": {
     "query": "label_values(job_handle_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}, class)"
    }
   },
   {
    "name": "method_job",
    "query": {
     "query": "label_values(job_handle_time_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\"}, method)"
    }
   },
   {
    "name": "kafka_topic",
    "query": {
     "query": "label_values(kafka_burrow_topic_partition_offset{cluster=~\"$cluster\", namespace=~\"$namespace\"}, topic)"
    }
   },
   {
    "name": "kafka_group",
    "query": {
     "query": "label_values(kafka_burrow_partition_current_offset{cluster=~\"$cluster\", namespace=~\"$namespace\", topic=~\"${kafka_topic}\"}, group)"
    }
   },
   {
    "name": "kafka_instance",
    "query": {
     "query": "label_values(kafka_burrow_partition_current_offset{cluster=~\"$cluster\", namespace=~\"$namespace\", group=~\"${kafka_group}\"}, instance)"
    }
   },
   {
    "name": "repository_service",
    "label": "Repository Service",
    "query": {
     "query": "label_values(kube_service_labels{namespace=~\"$namespace\", service!~\"(kafka-.*)|(zeebe.*)|(receiver)|(event-handler)\"}, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "severity level > 2",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (severity_level) (rate(ALERTS{namespace=~\"$namespace\", severity_level!=\"2\", severity_level!=\"1\"}[15m]))",
     "legendFormat": "__auto",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "severity level 2",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (severity_level) (rate(ALERTS{namespace=~\"$namespace\", severity_level=\"2\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "severity level 1",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (severity_level) (rate(ALERTS{namespace=~\"$namespace\", severity_level=\"1\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count Pod Status Reason",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_reason{namespace=~\"$namespace\", reason=~\".*\"}) by (reason)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Don't ready statefulset",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_statefulset_status_replicas{namespace=~\"$namespace\"} - kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"}) by (statefulset)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Don't ready deployment",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"} - kube_deployment_status_replicas_ready{namespace=~\"$namespace\"}) by (deployment)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod restart count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum by (pod) (kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_${metric}_responses_total{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(ingress_nginx_${metric}_responses_total{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval]), \"status_group\", \"${1}xx\", \"status\", \"([0-9])..\")) by (status_group)\n  / scalar(sum(rate(ingress_nginx_${metric}_responses_total{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_${metric}_requests_total{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval]))"
    },
    {
     "expr": "sum(rate(ingress_nginx_${metric}_requests_total{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) $by > 0"
    }
   ]
  },
  {
   "title": "Request %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_${metric}_requests_total{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) $by\n  / scalar(sum(rate(ingress_nginx_${metric}_requests_total{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval]))) > 0"
    }
   ]
  },
  {
   "title": "Incoming Trafic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_${metric}_received_bytes_sum{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) * 8"
    },
    {
     "expr": "sum(rate(ingress_nginx_${metric}_received_bytes_sum{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) $by * 8 > 0"
    }
   ]
  },
  {
   "title": "Outgoint Trafic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_${metric}_sent_bytes_sum{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) * 8"
    },
    {
     "expr": "sum(rate(ingress_nginx_${metric}_sent_bytes_sum{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) $by * 8 > 0"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ingress_nginx_${metric}_request_seconds_bucket{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) by (le)) * 1000"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ingress_nginx_${metric}_request_seconds_bucket{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) by (le)) * 1000"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ingress_nginx_${metric}_request_seconds_bucket{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) by (le)) * 1000"
    },
    {
     "expr": "sum(rate(ingress_nginx_${metric}_request_seconds_sum{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval]))\n  / sum(rate(ingress_nginx_${metric}_request_seconds_count{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval]))\n  * 1000"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ingress_nginx_${metric}_upstream_response_seconds_bucket{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) by (le)) * 1000"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ingress_nginx_${metric}_upstream_response_seconds_bucket{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) by (le)) * 1000"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ingress_nginx_${metric}_upstream_response_seconds_bucket{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval])) by (le)) * 1000"
    },
    {
     "expr": "sum(rate(ingress_nginx_${metric}_upstream_response_seconds_sum{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval]))\n  / sum(rate(ingress_nginx_${metric}_upstream_response_seconds_count{job=\"nginx-ingress-controller\", controller=~\"$controller\", app=~\"$app\", node=~\"$node\", namespace=~\"$namespace\", ingress=~\"$ingress\", service=~\"$service\", service_port=~\"$service_port\", vhost=~\"$vhost\", location=~\"$location\", content_kind=~\"$content_kind\"}[$__rate_interval]))\n  * 1000"
    }
   ]
  },
  {
   "title": "Endpoint execute time",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_max{namespace=~\"$namespace\", uri!~\"(/actuator/.*|/v3/api-docs.*|/ready.*|/swagger-ui.*)\"}[$__interval_sx4]) > 0",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Endpoint execute time on date",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_max{namespace=~\"$namespace\", uri!~\"(/actuator/.*|/v3/api-docs.*|/ready.*|/swagger-ui.*)\"}[$__interval_sx4]) > 0",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Request"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\",node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Use CPU container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"POD\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Over request cpu container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container)\n  (\n    (\n      sum by(pod, container) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval]))\n      -\n      sum by(pod, container) (rate(container_cpu_usage_seconds_total{node=~\"$node\", container!=\"POD\", namespace=~\"$namespace\"}[$__rate_interval]))\n    )\n  )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Under request cpu container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (container)\n  (\n    (\n      (\n        sum by(pod, container) (rate(container_cpu_usage_seconds_total{node=~\"$node\", container!=\"POD\", namespace=~\"$namespace\"}[$__rate_interval]))\n        -\n        sum by(pod, container) (avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval]))\n      ) or sum by(pod, container) (rate(container_cpu_usage_seconds_total{node=~\"$node\", container!=\"POD\", namespace=~\"$namespace\"}[$__rate_interval]))\n    )\n    > 0\n  )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_rss{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))",
       "legendFormat": "Use"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_cache{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))",
       "legendFormat": "Cache"
      },
      {
       "expr": "sum by (namespace) (avg_over_time(container_memory_swap{node=~\"$node\", namespace=\"$namespace\", container!=\"POD\"}[$__rate_interval]))",
       "legendFormat": "Swap"
      },
      {
       "expr": "sum by(namespace) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\",node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum by(namespace) (avg_over_time(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\",node=~\"$node\", container!=\"POD\", namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Use memory container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "sum by (container) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", namespace=~\"$namespace\", container!=\"POD\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Over Request memory container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "sum by (container)\n  (\n    (\n      sum by(namespace, pod, container) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\",node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval]))\n      -\n      sum by(namespace, pod, container) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", container!=\"POD\", namespace=~\"$namespace\"}[$__rate_interval]))\n    ) > 0\n  )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Under request memory container",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "sum by (container)\n  (\n    (\n      (\n        sum by(pod, container) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", container!=\"POD\", namespace=~\"$namespace\"}[$__rate_interval]))\n        -\n        sum by(pod, container) (avg_over_time(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\",node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval]))\n      ) or sum by(pod, container) (avg_over_time(container_memory_working_set_bytes:without_kmem{node=~\"$node\", container!=\"POD\", namespace=~\"$namespace\"}[$__rate_interval]))\n    )\n    > 0\n  )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Freee space pvc",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim) (\n    max_over_time(kubelet_volume_stats_capacity_bytes{node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval])\n  )\n  * on (persistentvolumeclaim)\n\tsum by (persistentvolumeclaim) (\n\t\tlabel_replace(\n\t\t\tmax_over_time(\n\t\t\t\tkube_persistentvolumeclaim_info{namespace=~\"$namespace\"}[$__rate_interval]),\n\t\t\t\t\"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n\t\t\t\t+ on (persistentvolume) group_left() max by (persistentvolume) (kube_persistentvolume_is_local == 0)\n\t)\n-\nsum by (persistentvolumeclaim) (\n    max_over_time(kubelet_volume_stats_capacity_bytes{node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval]) - max_over_time(kubelet_volume_stats_available_bytes{node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval])\n  )\n  * on (persistentvolumeclaim)\n\tsum by (persistentvolumeclaim) (\n\t\tlabel_replace(\n\t\t\tmax_over_time(\n\t\t\t\tkube_persistentvolumeclaim_info{namespace=~\"$namespace\"}[$__rate_interval]),\n\t\t\t\t\"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n\t\t\t\t+ on (persistentvolume) group_left() max by (persistentvolume) (kube_persistentvolume_is_local == 0)\n\t)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Use pvc %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "  sum by ( persistentvolumeclaim) (\n    max_over_time(kubelet_volume_stats_capacity_bytes{node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval]) - max_over_time(kubelet_volume_stats_available_bytes{node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval])\n  )\n  * on (persistentvolumeclaim)\n\tsum by (persistentvolumeclaim) (\n\t\tlabel_replace(\n\t\t\tmax_over_time(\n\t\t\t\tkube_persistentvolumeclaim_info{namespace=~\"$namespace\"}[$__rate_interval]),\n\t\t\t\t\"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n\t\t\t\t+ on (persistentvolume) group_left() max by (persistentvolume) (kube_persistentvolume_is_local == 0)\n\t)\n/\n  sum by (persistentvolumeclaim) (\n    max_over_time(kubelet_volume_stats_capacity_bytes{node=~\"$node\", namespace=~\"$namespace\"}[$__rate_interval])\n  )\n  * on (persistentvolumeclaim)\n\tsum by (persistentvolumeclaim) (\n\t\tlabel_replace(\n\t\t\tmax_over_time(\n\t\t\t\tkube_persistentvolumeclaim_info{namespace=~\"$namespace\"}[$__rate_interval]),\n\t\t\t\t\"persistentvolume\", \"$1\", \"volumename\", \"(.*)\")\n\t\t\t\t+ on (persistentvolume) group_left() max by (persistentvolume) (kube_persistentvolume_is_local == 0)\n\t)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Zeebe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Health",
     "type": "graph",
     "description": "Shows health per partition and pod",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zeebe_health{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\", pod=~\"$pod\"}",
       "legendFormat": "pod {{pod}}: parition {{partition}}"
      }
     ]
    },
    {
     "title": "Partition Leader",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "atomix_role{namespace=~\"$namespace\"}",
       "legendFormat": "pod {{pod}} Leader partition {{partition}}"
      }
     ]
    },
    {
     "title": "Backpressure Dropping Requests [1m]",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 13, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(rate(zeebe_dropped_request_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[1m])) by (partition) / sum(rate(zeebe_received_request_count_total{cluster=~\"$cluster\", namespace=~\"$namespace\", partition=~\"$partition\"}[1m])) by (partition) ) * 100",
       "legendFormat": "partition: {{partition}}"
      },
      {}
     ]
    },
    {
     "title": "Completed Processes in avg overtime per sec",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 18, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"PROCESS\"}[1m]))"
      }
     ]
    },
    {
     "title": "Overall FNI  per s [1m]",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 13, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", type!=\"PROCESS\", action!=\"activated\"}[1m]))"
      }
     ]
    },
    {
     "title": "Completed Tasks in avg overtime per sec",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 18, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(zeebe_element_instance_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=\"completed\", type=\"SERVICE_TASK\"}[1m]))"
      }
     ]
    },
    {
     "title": "Requests handled by Gateway per sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[1m])) by (grpc_method, code) > 0",
       "legendFormat": "{{grpc_method}} {{code}}"
      }
     ]
    },
    {
     "title": "Processing per Partition skipped or processed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"skipped|processed\"}[1m])) by (pod, partition, processor)",
       "legendFormat": "{{pod}} partition {{partition}}"
      }
     ]
    },
    {
     "title": "Exporting per Partition",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_exporter_events_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\"}[1m])) by (pod, partition, exporter)",
       "legendFormat": "{{pod}} partition {{partition}}"
      }
     ]
    },
    {
     "title": "Processing per Partition written",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_stream_processor_records_total{cluster=~\"$cluster\", namespace=~\"$namespace\",partition=~\"$partition\",pod=~\"$pod\", action=~\"written\"}[1m])) by (pod, partition, processor)",
       "legendFormat": "{{pod}} partition {{partition}}"
      }
     ]
    },
    {
     "title": "Reqest created [5m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(zeebe_gateway_failed_requests_created{namespace=~\"$namespace\"}[5m])) by (error)",
       "legendFormat": "{{error}}"
      },
      {
       "expr": "sum(rate(zeebe_gateway_total_requests_created{namespace=~\"$namespace\"}[5m])) by (requestType)",
       "legendFormat": "{{requestType}}"
      }
     ]
    },
    {
     "title": "Latency request [15m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(zeebe_gateway_request_latency_sum{namespace=~\"$namespace\"}[15m])) by (requestType) > 0",
       "legendFormat": "__auto"
      },
      { "expr": "zeebe_gateway_request_latency_" }
     ]
    },
    {
     "title": "Avg activation|life time job ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "zeebe_job_activation_time_created{namespace=~\"$namespace\"}",
       "legendFormat": "ac_time partition {{partition}}"
      },
      {
       "expr": "zeebe_job_life_time_created{namespace=~\"$namespace\"}",
       "legendFormat": "life_time partition {{partition}}"
      }
     ]
    },
    {
     "title": "Error Backup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zeebe_backup_operations_total{namespace=~\"$namespace\", result!=\"completed\"}) by (partition) /\ncount(zeebe_backup_operations_total{namespace=~\"$namespace\"}) by (partition)"
      }
     ]
    },
    {
     "title": "Partition cache in memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "zeebe_rocksdb_memory_block_cache_capacity{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}} partition {{partition}}"
      }
     ]
    },
    {
     "title": "Replica Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(atomix_role{namespace=~\"$namespace\"} > 0) by (partition)",
       "legendFormat": "partition {{partition}}"
      }
     ]
    },
    {
     "title": "Backpressure count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(zeebe_backpressure_inflight_requests_count{namespace=~\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}} inflight"
      },
      {
       "expr": "sum(zeebe_backpressure_inflight_append_count{namespace=~\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}} append"
      }
     ]
    }
   ]
  },
  {
   "title": "Zeebe worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time secon per job (avg)",
     "type": "graph",
     "description": "Per class",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "job_handle_time_seconds_sum{namespace=~\"$namespace\", method=\"$method_job\"}",
       "legendFormat": "{{class}}"
      }
     ]
    },
    {
     "title": "Count job",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "job_handle_time_seconds_count{namespace=~\"$namespace\", method=~\"$method_job\"}",
       "legendFormat": "{{class}}"
      }
     ]
    },
    {
     "title": "Time last job",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "job_handle_time_seconds_max{namespace=~\"$namespace\", method=~\"$method_job\"}",
       "legendFormat": "{{class}}"
      }
     ]
    },
    {
     "title": "Events total delta (minus)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(zeebe_element_instance_events_total{namespace=~\"$namespace\"}[30m]) < 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Simple Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of unprocessed jobs by specific worker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "job_queue{namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}: {{worker}}"
      }
     ]
    },
    {
     "title": "Rate kafka offset (1m)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_zeebe_events_offset{namespace=~\"$namespace\"}[1m]))"
      }
     ]
    },
    {
     "title": "Rate all tasks db (not success)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(spring_data_repository_invocations_seconds_count{namespace=~\"$namespace\", state!=\"SUCCESS\"}[$__rate_interval])",
       "legendFormat": "{{repository}}-{{method}}: {{state}}"
      }
     ]
    },
    {
     "title": "Rate import databse (1m)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(database_import_operations{namespace=~\"$namespace\"}[1m]))"
      }
     ]
    },
    {
     "title": "Time execute kafka listener",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(kafka_messages_handle_time_seconds_bucket{namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Rate all tasks db (success)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(spring_data_repository_invocations_seconds_count{namespace=~\"$namespace\", state=~\"SUCCESS\", service=\"zeebe-simple-monitor\"}[$__rate_interval])",
       "legendFormat": "{{repository}}-{{method}}: {{state}}"
      }
     ]
    },
    {
     "title": "Time all tasks db (success)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(spring_data_repository_invocations_seconds_sum{namespace=~\"$namespace\", state=~\"SUCCESS\"}[$__rate_interval])",
       "legendFormat": "{{repository}}-{{method}}"
      }
     ]
    },
    {
     "title": "Time all tasks db (not success)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(spring_data_repository_invocations_seconds_sum{namespace=~\"$namespace\", state!=\"SUCCESS\"}[$__rate_interval])",
       "legendFormat": "{{repository}}-{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka connection",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer{namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Kafka Offset lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_lag{namespace=~'$namespace'}) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Kafka Topic stats (only failed)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_burrow_partition_status{namespace=~\"$namespace\", topic=~\"[wecare-].*\"} <= 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Receiver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receiver lopus status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(external_system_availability{namespace=~\"$namespace\"}) by (entity_name, service_name)",
       "legendFormat": "{{entity_name}}-{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}