{
 "title": "SRP Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance" },
   { "name": "namespace", "query": "data_loading" }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_overall_requests_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{service=\"http-metrics-plp\", namespace=\"$namespace\"}[1h]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg rps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(ingress_nginx_overall_requests_total{job=\"nginx-ingress-controller\", namespace=~\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "App rendering",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(app_rendering_histogram_bucket[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_rendering_histogram_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_rendering_histogram_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Data loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(data_loading_histogram_bucket{service=\"http-metrics-plp\", namespace=\"mf\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(data_loading_histogram_bucket{service=\"http-metrics-plp\", namespace=\"mf\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(data_loading_histogram_bucket{service=\"http-metrics-plp\", namespace=\"mf\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Rendering time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "expr": "avg by (value) (app_rendering{job=\"custom-microfronts-plp-exporter\", namespace=~\"$namespace\"})",
     "legendFormat": "Path - \"/catalogue/:id\""
    }
   ]
  },
  {
   "title": "Store loading time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 13 },
   "targets": [
    {
     "expr": "avg by (value) (data_loading{job=\"custom-microfronts-plp-exporter\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "App rendering",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "app_rendering{namespace=\"$namespace\",service=\"http-metrics-plp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data loading",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "data_loading{namespace=\"$namespace\",service=\"http-metrics-plp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{namespace=\"$namespace\"}",
     "legendFormat": " {{`{{service}}  -  {{namespace}} - {{instance}}`}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_active_handles_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Active Handler - {{`{{instance}}`}}"
    },
    {
     "expr": "rate(nodejs_active_requests_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Active Request - {{`{{instance}}`}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{namespace=\"$namespace\"}[2m]) * 100",
     "legendFormat": "User CPU - {{`{{instance}} {{service}}  {{namespace}}`}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{namespace=\"$namespace\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{`{{instance}} {{service}}  {{namespace}}`}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nodejs_gc_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", service=\"http-metrics-plp\"}",
     "legendFormat": "Process Memory - PLP - {{`{{instance}}`}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{namespace=~\"$namespace\", service=\"http-metrics-plp\"}",
     "legendFormat": "Heap Total - PLP - {{`{{instance}}`}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{namespace=~\"$namespace\", service=\"http-metrics-plp\"}",
     "legendFormat": "Heap Used - PLP - {{`{{instance}}`}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{namespace=~\"$namespace\", service=\"http-metrics-plp\"}",
     "legendFormat": "External Memory - PLP - {{`{{instance}}`}}"
    }
   ]
  }
 ]
}