{
 "title": "Read Path",
 "panels": [
  {
   "title": "QPS",
   "type": "graph",
   "description": "Queries duration per second.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_request_duration_seconds_count{job=\"loki\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{`{{`}}status{{`}}`}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Time (in seconds) spent serving HTTP Query requests per request.",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (loki_request_duration_seconds_bucket{job=\"loki\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": "{{`{{`}} route {{`}}`}} 99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le,route) (loki_request_duration_seconds_bucket{job=\"loki\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": "{{`{{`}} route {{`}}`}} 50th Percentile"
    },
    {
     "expr": "1e3 * sum(loki_request_duration_seconds_sum{job=\"loki\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\"}) by (route)  / sum(loki_request_duration_seconds_count{job=\"loki\", route=~\"loki_api_v1_series|api_prom_series|api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_labels|loki_api_v1_label_name_values\"}) by (route) ",
     "legendFormat": "{{`{{`}} route {{`}}`}} Average"
    }
   ]
  }
 ]
}
{
 "title": "BoltDB Query Shipper",
 "panels": [
  {
   "title": "QPS",
   "type": "graph",
   "description": "Queries duration per second using boltdb shipper for Query payload.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_boltdb_shipper_request_duration_seconds_count{job=\"loki\", operation=\"Shipper.Query\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{`{{`}}status{{`}}`}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Time (in seconds) spent serving requests when using boltdb shipper for Query payload per request.",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{job=\"loki\", operation=\"Shipper.Query\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{job=\"loki\", operation=\"Shipper.Query\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_boltdb_shipper_request_duration_seconds_sum{job=\"loki\", operation=\"Shipper.Query\"}[$__rate_interval])) * 1e3 / sum(rate(loki_boltdb_shipper_request_duration_seconds_count{job=\"loki\", operation=\"Shipper.Query\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "title": "Write Path",
 "panels": [
  {
   "title": "QPS",
   "type": "graph",
   "description": "Time (in seconds) spent serving HTTP Push requests.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_request_duration_seconds_count{job=\"loki\", route=~\"api_prom_push|loki_api_v1_push|/httpgrpc.HTTP/Handle\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{`{{`}}status{{`}}`}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Time (in seconds) spent serving HTTP Push requests per request.",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (loki_request_duration_seconds_bucket{job=\"loki\", route=~\"api_prom_push|loki_api_v1_push|/httpgrpc.HTTP/Handle\"})) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (loki_request_duration_seconds_bucket{job=\"loki\", route=~\"api_prom_push|loki_api_v1_push|/httpgrpc.HTTP/Handle\"})) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1e3 * sum(loki_request_duration_seconds_sum{job=\"loki\", route=~\"api_prom_push|loki_api_v1_push|/httpgrpc.HTTP/Handle\"}) / sum(loki_request_duration_seconds_count{job=\"loki\", route=~\"api_prom_push|loki_api_v1_push|/httpgrpc.HTTP/Handle\"})",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "title": "BoltDB Write Shipper",
 "panels": [
  {
   "title": "QPS",
   "type": "graph",
   "description": "Queries duration per second using boltdb shipper for Write operations.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_boltdb_shipper_request_duration_seconds_count{job=\"loki\", operation=\"WRITE\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{`{{`}}status{{`}}`}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Time (in seconds) spent serving requests when using boltdb shipper for Write operations per request.",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{job=\"loki\", operation=\"WRITE\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{job=\"loki\", operation=\"WRITE\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_boltdb_shipper_request_duration_seconds_sum{job=\"loki\", operation=\"WRITE\"}[$__rate_interval])) * 1e3 / sum(rate(loki_boltdb_shipper_request_duration_seconds_count{job=\"loki\", operation=\"WRITE\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}
{
 "title": "Compact and Mark",
 "panels": [
  {
   "title": "Last Compact and Mark Operation Success",
   "type": "stat",
   "description": "Last successful compaction run.",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "yaxes": [
    { "format": "short" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_last_successful_run_timestamp_seconds{namespace=~\"$namespace\",job=\"loki\"} * 1e3"
    }
   ]
  },
  {
   "title": "Compact and Mark Operations Duration",
   "type": "graph",
   "description": "Time (in seconds) spent in compacting all the tables.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_duration_seconds{namespace=~\"$namespace\",job=\"loki\"}",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Compact and Mark Operations Per Status",
   "type": "graph",
   "description": "Compaction operations with statuses.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_boltdb_shipper_compact_tables_operation_total{namespace=~\"$namespace\",job=\"loki\"}[$__rate_interval]))",
     "legendFormat": "{{`{{`}}success{{`}}`}}"
    }
   ]
  }
 ]
}