{
 "title": "AS-DELIVERY business metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Received transition objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Task-in",
   "type": "timeseries",
   "description": "Количество delivery tasks полученных, обработанных, отфильтрованных и отправленных в dlt",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(idelta(billing_delivery_task_in_received_task_count{namespace = \"$namespace\", service=~\"as-delivery-task-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_delivery_task_in_processed_task_count{namespace = \"$namespace\", service=~\"as-delivery-task-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "PROCESSED"
    },
    {
     "expr": "sum(idelta(billing_delivery_task_in_skipped_task_count{namespace = \"$namespace\", service=~\"as-delivery-task-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SKIPPED"
    },
    {
     "expr": "sum(idelta(billing_delivery_task_in_dlt_task_count{namespace = \"$namespace\", service=~\"as-delivery-task-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DLT"
    }
   ]
  },
  {
   "title": "Task-agent-attribute-in",
   "type": "timeseries",
   "description": "Количество delivery task agent attribute полученных, обработанных и отправленных в dlt",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(idelta(billing_delivery_task_agent_attribute_in_received_task_agent_attribute_count{namespace = \"$namespace\", service=~\"as-delivery-task-agent-attribute-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_delivery_task_agent_attribute_in_processed_task_agent_attribute_count{namespace = \"$namespace\", service=~\"as-delivery-task-agent-attribute-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "PROCESSED"
    },
    {
     "expr": "sum(idelta(billing_delivery_task_agent_attribute_in_dlt_task_agent_attribute_count{namespace = \"$namespace\", service=~\"as-delivery-task-agent-attribute-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DLT"
    }
   ]
  },
  {
   "title": "Contract-manager",
   "type": "timeseries",
   "description": "Количество полученных, сохранённых и обновленных",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_contract_manager_received_contracts{namespace = \"$namespace\", service=~\"as-delivery-contract-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_contract_manager_saved_contracts{namespace = \"$namespace\", service=~\"as-delivery-contract-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SAVED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_contract_manager_updated_contracts{namespace = \"$namespace\", service=~\"as-delivery-contract-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "UPDATED"
    }
   ]
  },
  {
   "title": "Receipt-in",
   "type": "timeseries",
   "description": "Количество чеков полученных, обработанных, отфильтрованных и отправленных в dlt",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_receipt_in_received_receipt_count{namespace = \"$namespace\", service=~\"as-delivery-receipt-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_receipt_in_send_receipt_count{namespace = \"$namespace\", service=~\"as-delivery-receipt-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "PROCESSED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_receipt_in_skipped_receipt_count{namespace = \"$namespace\", service=~\"as-delivery-receipt-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SKIPPED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_receipt_in_send_to_dlt_receipt_count{namespace = \"$namespace\", service=~\"as-delivery-receipt-in.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SEND TO DLT"
    }
   ]
  },
  { "title": "Sent transition objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Report-out",
   "type": "timeseries",
   "description": "Количество полученных и отправленных в дата платформу отчётов",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_out_received_report_count{namespace = \"$namespace\", service=~\"as-delivery-report-out.*\"}[$__rate_interval])) >= 0 ",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_out_sent_report_to_dp_count{namespace = \"$namespace\", service=~\"as-delivery-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SEND TO DP"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_out_sent_report_to_oracle_count{namespace = \"$namespace\", service=~\"as-delivery-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SEND TO ORACLE"
    }
   ]
  },
  { "title": "Agent report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Agent report data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_receipt_received_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIPT"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_task_agent_attribute_received_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "TASK_AGENT_ATTRIBUTE"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_reconciliation_received_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECONCILIATION"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_delivery_task_received_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DELIVERY_TASK"
    }
   ]
  },
  {
   "title": "Agent report commands",
   "type": "timeseries",
   "description": "Количество полученных команд",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_compile_command_received_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPILE"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_approve_command_received_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "APPROVE"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_for_payment_command_received_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FOR PAYMENT"
    }
   ]
  },
  {
   "title": "COMPILE commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_compile_command_received_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPLETED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FAILED"
    }
   ]
  },
  {
   "title": " Generated agent reports in DRAFT status",
   "type": "timeseries",
   "description": "Количество сгенерированных отчётов в статусе DRAFT",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_generated_agent_report_draft_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DRAFT"
    }
   ]
  },
  {
   "title": "PROCESSING to COMPLETED transition time COMPILE command",
   "type": "timeseries",
   "description": "Время перевода COMPILE команды из PROCESSING в COMPLETED. Так же эту метрику можно считать временем генерации отчёта.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "PROCESSING to FAILED transition time COMPILE command",
   "type": "timeseries",
   "description": "Время перевода COMPILE команды из PROCESSING в FAILED.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "APPROVE commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_approve_command_received_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPLETED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FAILED"
    }
   ]
  },
  {
   "title": " Generated agent reports in APPROVED status",
   "type": "timeseries",
   "description": "Количество сгенерированных отчётов в статусе APPROVED",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_generated_agent_report_approved_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "APPROVED"
    }
   ]
  },
  {
   "title": "PROCESSING to COMPLETED transition time APPROVE command",
   "type": "timeseries",
   "description": "Время перевода APPROVE команды из PROCESSING в COMPLETED. Так же эту метрику можно считать временем генерации отчёта.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "PROCESSING to FAILED transition time APPROVE command",
   "type": "timeseries",
   "description": "Время перевода APPROVE команды из PROCESSING в FAILED.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "FOR PAYMENT commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_for_payment_command_received_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPLETED"
    },
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FAILED"
    }
   ]
  },
  {
   "title": " Generated agent reports in FOR_PAYMENT status",
   "type": "timeseries",
   "description": "Количество сгенерированных отчётов в статусе FOR_PAYMENT",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_generated_agent_report_for_payment_count{namespace = \"$namespace\", service=~\"as-delivery-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FOR_PAYMENT"
    }
   ]
  },
  {
   "title": "PROCESSING to COMPLETED transition time FOR_PAYMENT command",
   "type": "timeseries",
   "description": "Время перевода FOR_PAYMENT команды из PROCESSING в COMPLETED. Так же эту метрику можно считать временем генерации отчёта.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_completed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "PROCESSING to FAILED transition time FOR_PAYMENT command",
   "type": "timeseries",
   "description": "Время перевода FOR_PAYMENT команды из PROCESSING в FAILED. Так же эту метрику можно считать временем генерации отчёта.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-60s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"60.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-2m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"120.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "2-3m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"180.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-4m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"240.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "4-5m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"300.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-6m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"360.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "6-8m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"480.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "8-12m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"720.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "12-15m"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_report_manager_processing_to_failed_for_payment_command_metric_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", le=\"900.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "15m+"
    }
   ]
  },
  {
   "title": "Printing form generation time",
   "type": "timeseries",
   "description": "Время генерации печатной формы, с момента получения отчёта и до момента когда его можно получить по ссылке",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"0.1\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 0.1s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"0.3\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"0.1\"}[$__rate_interval]))) >= 0",
     "legendFormat": "0.1-0.3s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"1.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"0.5\"}[$__rate_interval]))) >= 0",
     "legendFormat": "0.5-1s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"1.5\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"1.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-1.5s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"5.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"1.5\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1.5-5s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"10.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"5.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-10s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"54.0\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"10.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-54s"
    },
    {
     "expr": "(sum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"+Inf\"}[$__rate_interval])) - \r\nsum(idelta(billing_as_delivery_print_form_manager_processing_reports_seconds_bucket{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", le=\"54.0\"}[$__rate_interval]))) >= 0",
     "legendFormat": "54s+"
    }
   ]
  },
  {
   "title": "Incidents in camunda",
   "type": "timeseries",
   "description": "Будет добавлено в следующих версиях",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum by (processName) (camunda_incident_count{service=~\"as-delivery-report-manager.*\", namespace=\"$namespace\"}))",
     "legendFormat": "{{processName}}"
    }
   ]
  },
  { "title": "Contracts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Contracts count ",
   "type": "stat",
   "description": "Общее количество контрактов в contract-manager",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(billing_as_delivery_contract_manager_total_contracts{namespace=\"$namespace\", service=~\"as-delivery-contract-manager.*\"}) / count by (app) (billing_as_delivery_contract_manager_total_contracts{namespace=\"$namespace\", service=~\"as-delivery-contract-manager.*\"})",
     "legendFormat": "Total contracts:"
    }
   ]
  },
  { "title": "HTTP statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Cost-center-manager api response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"cost-center-manager.*\", uri=~\"/v1.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"cost-center-manager.*\", uri=~\"/v1.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Cost-center-manager api errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"cost-center-manager.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Contract-manager api response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-delivery-contract-manager.*\", uri=~\"/v1.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-contract-manager.*\", uri=~\"/v1.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Contract-manager api errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-delivery-contract-manager.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Commission-manager api response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-delivery-commission-manager.*\", uri=~\"/v1.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-commission-manager.*\", uri=~\"/v1.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Commission-manager api errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-delivery-commission-manager.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Report-manager to Commission-manager api response",
   "type": "timeseries",
   "description": "Время ответа commission-manager при вызове из report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", uri=~\"/v1/commissions.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", uri=~\"/v1/commissions.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Report-manager to Commission-manager api errors",
   "type": "timeseries",
   "description": "Время ошибочного ответа commission-manager при вызове из report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\" ,  uri=~\"/v1/commissions.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Report-manager to Contract-manager api response",
   "type": "timeseries",
   "description": "Время ответа contract-manager при вызове из report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", uri=~\"/v1/contracts.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\", uri=~\"/v1/contracts.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Report-manager to Contract-manager api errors",
   "type": "timeseries",
   "description": "Время ошибочного ответа contract-manager при вызове из report-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-delivery-report-manager.*\",  uri=~\"/v1/contracts.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Print-form-manager api response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/agent-reports.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/agent-reports.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Print-form-manager api errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Cloud-print api response",
   "type": "timeseries",
   "description": "Время ответа cloud-print при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/cloud-print/v1/actions/.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/cloud-print/v1/actions/.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Cloud-print api errors",
   "type": "timeseries",
   "description": "Время jошибочного ответа cloud-print при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/cloud-print/v1/actions/.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0 ",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Print-form-manager to Contract-manager api response",
   "type": "timeseries",
   "description": "Время ответа contract-manager при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/v1/contracts.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/v1/contracts.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Print-form-manager to Contract-manager api errors",
   "type": "timeseries",
   "description": "Время ошибочного ответа contract-manager при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/v1/contracts.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0 ",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Print-form-manager to Cost-center-manager api response",
   "type": "timeseries",
   "description": "Время ответа cost-center-manager при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/v1/cost-centers.*\" }[$__range])) / \r\nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/v1/cost-centers.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "Print-form-manager to Cost-center-manager api errors",
   "type": "timeseries",
   "description": "Время ошибочного ответа cost-center-manager при вызове из print-form-manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "targets": [
    {
     "expr": "sum by (status, uri, method) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-delivery-print-form-manager.*\", uri=~\"/v1/cost-centers.*\", status=~\"3..|4..|5..|CLIENT_ERROR|SERVER_ERROR\"}[$__rate_interval])) >= 0 ",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  }
 ]
}