{
 "title": "AS-MP business metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LAST DRAFT AR count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(year, month) (billing_report_manager_api_agent_report_draft_empty_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"} + billing_report_manager_api_agent_report_draft_utd_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"} + billing_report_manager_api_agent_report_draft_ucd_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"})",
     "legendFormat": "DRAFT {{year}}-{{month}}"
    }
   ]
  },
  {
   "title": "TOTAL APPROVED AR count",
   "type": "bargauge",
   "description": "Общее количество ucd approved отчетов агента в report-manager по месяцам за последние пол года",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(year, month) (billing_report_manager_api_agent_report_approved_ucd_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"} + billing_report_manager_api_agent_report_approved_utd_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"} + billing_report_manager_api_agent_report_approved_empty_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"})",
     "legendFormat": "{{year}}-{{month}}"
    }
   ]
  },
  {
   "title": "GENERATED DRAFT REPORTS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_generated_agent_report_draft_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "DRAFT"
    }
   ]
  },
  {
   "title": "CLAIM COMPOSER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "sum(idelta(billing_claim_composer_sent_composed_claims_count{namespace = \"$namespace\", service=~\"as-mp-claim-composer.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPOSED CLAIM"
    },
    {
     "expr": "sum(idelta(billing_claim_composer_received_claims_count{namespace = \"$namespace\", service=~\"as-mp-claim-composer.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED CLAIM"
    },
    {
     "expr": "sum(idelta(billing_claim_composer_received_orders_count{namespace = \"$namespace\", service=~\"as-mp-claim-composer.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED ORDER"
    }
   ]
  },
  {
   "title": "LAST DRAFT EMPTY AR count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(year, month) (billing_report_manager_api_agent_report_draft_empty_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"})",
     "legendFormat": "DRAFT {{year}}-{{month}}"
    }
   ]
  },
  {
   "title": "APPROVED EMPTY AR count",
   "type": "bargauge",
   "description": "Общее количество empty approved отчетов агента в report-manager по месяцам за последние пол года",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(year, month) (billing_report_manager_api_agent_report_approved_empty_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"})",
     "legendFormat": "{{year}}-{{month}}"
    }
   ]
  },
  {
   "title": "GENERATED APPROVED REPORTS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_generated_agent_report_approved_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "APPROVED"
    }
   ]
  },
  {
   "title": "LAST DRAFT UTD AR count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(year, month) (billing_report_manager_api_agent_report_draft_utd_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"})",
     "legendFormat": "DRAFT {{year}}-{{month}}"
    }
   ]
  },
  {
   "title": "APPROVED UTD AR count",
   "type": "bargauge",
   "description": "Общее количество utd approved отчетов агента в report-manager по месяцам за последние пол года",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(year, month) (billing_report_manager_api_agent_report_approved_utd_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"})",
     "legendFormat": "{{year}}-{{month}}"
    }
   ]
  },
  {
   "title": "GENERATED SUBTOTAL REPORTS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_generated_subtotal_agent_report_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "SUBTOTAL"
    }
   ]
  },
  {
   "title": "CASH FLOW MANAGER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "sum(idelta(billing_cash_flow_manager_generated_direct_cash_flow_report_count{namespace = \"$namespace\", service=~\"as-mp-cash-flow-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "GENERATED DIRECT REPORT"
    },
    {
     "expr": "sum(idelta(billing_cash_flow_manager_generated_refund_cash_flow_report_count{namespace = \"$namespace\", service=~\"as-mp-cash-flow-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "GENERATED REFUND REPORT"
    },
    {
     "expr": "sum(idelta(billing_cash_flow_manager_received_payment_operation_count{namespace = \"$namespace\", service=~\"as-mp-cash-flow-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED PAYMENT OPERATION"
    },
    {
     "expr": "sum(idelta(billing_cash_flow_manager_received_return_payment_operation_count{namespace = \"$namespace\", service=~\"as-mp-cash-flow-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED RETURN PAYMEN OPERATION"
    }
   ]
  },
  {
   "title": "LAST DRAFT UCD AR count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(year, month) (billing_report_manager_api_agent_report_draft_ucd_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"})",
     "legendFormat": "DRAFT {{year}}-{{month}}"
    }
   ]
  },
  {
   "title": "APPROVED UCD AR count",
   "type": "bargauge",
   "description": "Общее количество ucd approved отчетов агента в report-manager по месяцам за последние пол года",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(year, month) (billing_report_manager_api_agent_report_approved_ucd_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\"})",
     "legendFormat": "{{year}}-{{month}}"
    }
   ]
  },
  {
   "title": "Agent-report-out",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 13 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_out_received_agent_report_count{namespace = \"$namespace\", service=~\"as-mp-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(idelta(billing_report_out_processed_agent_report_count{namespace = \"$namespace\", service=~\"as-mp-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "PROCESSED"
    },
    {
     "expr": "sum(idelta(billing_report_out_processed_agent_report_for_dp_count{namespace = \"$namespace\", service=~\"as-mp-report-out.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "PROCESSED FOR DP"
    }
   ]
  },
  {
   "title": "AGENT COMPILE commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_agent_report_compile_command_failed_status_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FAILED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_agent_report_compile_command_completed_status_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPLETED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_received_agent_report_compile_command_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    }
   ]
  },
  {
   "title": "AGENT APPROVE commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_agent_report_approve_command_failed_status_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FAILED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_agent_report_approve_command_completed_status_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPLETED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_received_agent_report_approve_command_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "RECEIVED"
    }
   ]
  },
  {
   "title": "SUBTOTAL COMPILE commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_subtotal_agent_report_compile_command_failed_status_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "FAILED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_subtotal_agent_report_compile_command_completed_status_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPLETED"
    },
    {
     "expr": "sum(idelta(billing_report_manager_received_subtotal_agent_report_compile_command_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": " RECEIVED"
    }
   ]
  },
  {
   "title": "TIME: COMPILE command PROCESSING to COMPLETED",
   "type": "timeseries",
   "description": "Время перевода COMPILE команды из PROCESSING в COMPLETED agent-report за период времени",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-30 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "30-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "60-120 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "120-300 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "300-480 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "480-600 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "600-720 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "720-900 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "900-1200 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1200+ s"
    }
   ]
  },
  {
   "title": "TIME: APPROVE command PROCESSING to COMPLETED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-30 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "30-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "60-120 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "120-300 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "300-480 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "480-600 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "600-720 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "720-900 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "900-1200 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_completed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1200+ s"
    }
   ]
  },
  {
   "title": "TIME: SUBTOTAL command PROCESSING to COMPLETED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-30 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "30-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "60-120 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "120-300 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "300-480 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "480-600 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "600-720 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "720-900 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "900-1200 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1200+ s"
    }
   ]
  },
  {
   "title": "TIME: COMPILE command PROCESSING to FAILED",
   "type": "timeseries",
   "description": "Время перевода COMPILE команды из PROCESSING в FAILED agent-report за период времени",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-30 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "30-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "60-120 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "120-300 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "300-480 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "480-600 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "600-720 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "720-900 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "900-1200 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_compile_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1200+ s"
    }
   ]
  },
  {
   "title": "TIME: APPROVE command PROCESSING to FAILED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-30 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "30-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "60-120 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "120-300 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "300-480 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "480-600 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "600-720 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "720-900 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "900-1200 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_agent_report_processing_to_failed_approve_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1200+ s"
    }
   ]
  },
  {
   "title": "TIME: SUBTOTAL PROCESSING to FAILED",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-30 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "30-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "60-120 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "120-300 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "300-480 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "480-600 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "600-720 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "720-900 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "900-1200 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_subtotal_agent_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1200+ s"
    }
   ]
  },
  {
   "title": "REVENUE COMPILE commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_received_revenue_report_compile_command_count {namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "COMPILE"
    }
   ]
  },
  {
   "title": "TIME: REVENUE command PROCESSING to COMPLETED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-30 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "30-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "60-120 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "120-300 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "300-480 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "480-600 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "600-720 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "720-900 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "900-1200 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_completed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1200+ s"
    }
   ]
  },
  {
   "title": "TIME: REVENUE command PROCESSING to FAILED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "< 10 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-30 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"30.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "30-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "60-120 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "120-300 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "300-480 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"480.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "480-600 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"600.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "600-720 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"720.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "720-900 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"900.0\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "900-1200 s"
    },
    {
     "expr": "(sum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) - \nsum(idelta(billing_report_manager_revenue_report_processing_to_failed_command_metric_seconds_bucket{namespace=\"$namespace\", le=\"1200\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1200+ s"
    }
   ]
  },
  {
   "title": "TIME: AGENT REPORT PRINTING",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"0.1\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) >= 0",
     "legendFormat": "<0.1s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"0.25\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"0.1\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "0.1-0.25s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"0.5\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"0.25\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "0.25-0.5s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"0.75\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"0.5\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "0.5-0.75s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"1.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"0.75\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "0.75-1s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"3.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"1.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "1-3s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"5.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"3.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "3-5s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"5.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "5-10s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"29.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"10.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "10-29s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"29.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "29-60s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"60.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "60-120s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"120.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "120-300s"
    },
    {
     "expr": "(sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"500.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval])) - sum(idelta(billing_report_printer_agent_report_processing_time_metric_seconds_bucket{namespace=\"$namespace\", le=\"300.0\", service=~\"as-mp-report-printer.*\"}[$__rate_interval]))) >= 0",
     "legendFormat": "300-500s"
    }
   ]
  },
  {
   "title": "REPORT PRINTER API responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-mp-report-printer.*\" }[$__range])) / \nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-mp-report-printer.*\", uri=~\"/v1.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "REPORT MANAGER API response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\" }[$__range])) / \nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\", uri=~\"/v1.*\"}[$__range]))",
     "legendFormat": "{{ method }} {{ uri }}"
    }
   ]
  },
  {
   "title": "HTTP statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Report manager api response",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\" }[$__range])) / \nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\", uri=~\"/v1.*\"}[$__range]))",
       "legendFormat": "{{ method }} {{ uri }}"
      }
     ]
    },
    {
     "title": "Report manager api errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-mp-report-manager-api.*\", status=~\"3..|4..|5..\"}[$__rate_interval])) >= 0",
       "legendFormat": "{{status}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Report manager requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-mp-report-manager.*\" }[$__range])) / \nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-mp-report-manager.*\", uri=~\"/mas/assortments/get-vat.*\"}[$__range]))",
       "legendFormat": "{{ method }} {{ uri }}"
      },
      {
       "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-mp-report-manager.*\" }[$__range])) / \nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-mp-report-manager.*\", uri=~\"/v1/contracts.*\"}[$__range]))",
       "legendFormat": "{{ method }} {{ uri }}"
      },
      {
       "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-mp-report-manager.*\" }[$__range])) / \nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-mp-report-manager.*\", uri=~\"/v1/commissions.*\"}[$__range]))",
       "legendFormat": "{{ method }} {{ uri }}"
      }
     ]
    },
    {
     "title": "Report manager errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-mp-report-manager.*\", status=~\"3..|4..|5..\"}[$__rate_interval])) >= 0",
       "legendFormat": "{{status}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Commission calculator requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-mp-commission-calculator.*\" }[$__range])) / \nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-mp-commission-calculator.*\", uri=~\"/mas/commissions/get-categories-commissions.*\"}[$__range]))",
       "legendFormat": "{{ method }} {{ uri }}"
      }
     ]
    },
    {
     "title": "Commission calculator errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-mp-commission-calculator.*\", status=~\"3..|4..|5..\", uri=~\"/mas/commissions/get-categories-commissions.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "{{status}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Report printer responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-mp-report-printer.*\" }[$__range])) / \nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-mp-report-printer.*\", uri=~\"/v1.*\"}[$__range]))",
       "legendFormat": "{{ method }} {{ uri }}"
      }
     ]
    },
    {
     "title": "Report printer errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-mp-report-printer.*\", status=~\"3..|4..|5..\", uri=~\"/v1/agent-reports/.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "{{status}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Parcel in requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_client_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-mp-parcel-in.*\" }[$__range])) / \nsum by (method, uri) (irate(http_client_requests_seconds_count{namespace=\"$namespace\", service=~\"as-mp-parcel-in.*\", uri=~\"/v2/assortments/search.*\"}[$__range]))",
       "legendFormat": "{{ method }} {{ uri }}"
      }
     ]
    },
    {
     "title": "Parcel in errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-mp-parcel-in.*\", status=~\"3..|4..|5..\", uri=~\"/v2/assortments/search.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "{{status}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Contract manager responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, uri) (irate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=~\"as-mp-contract-manager.*\" }[$__range])) / \nsum by (method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"as-mp-contract-manager.*\", uri=~\"/v1/contracts.*\"}[$__range]))",
       "legendFormat": "{{ method }} {{ uri }}"
      }
     ]
    },
    {
     "title": "Contract manager errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status, uri, method) (irate(http_server_requests_seconds_count{ namespace=\"$namespace\", service=~\"as-mp-contract-manager.*\", status=~\"3..|4..|5..\", uri=~\"/v1/contracts.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "{{status}} - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Received transition objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parcel-in",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "sum(idelta(billing_parcel_in_received_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_parcel_in_processed_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      },
      {
       "expr": "sum(idelta(billing_parcel_in_dlt_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DLT"
      },
      {
       "expr": "sum(idelta(billing_parcel_in_retry_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RETRY"
      },
      {
       "expr": "sum(idelta(billing_parcel_in_filtered_by_null_status_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "FILTERED BY NULL STATUS"
      },
      {
       "expr": "sum(idelta(billing_parcel_in_filtered_by_status_type_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "FILTERED BY STATUS TYPE"
      },
      {
       "expr": "sum(idelta(billing_parcel_in_filtered_by_status_code_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "FILTERED BY STATUS CODE"
      }
     ]
    },
    {
     "title": "Return-parcel-in",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "expr": "sum(idelta(billing_return_parcel_in_received_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_return_parcel_in_processed_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      },
      {
       "expr": "sum(idelta(billing_return_parcel_in_dlt_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DLT"
      },
      {
       "expr": "sum(idelta(billing_return_parcel_in_retry_count{namespace = \"$namespace\", service=~\"as-mp-parcel-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RETRY"
      }
     ]
    },
    {
     "title": "Payment-operation-in",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "sum(idelta(billing_payment_operation_in_payment_operation_processed_count{namespace = \"$namespace\", service=~\"as-mp-payment-operation-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      },
      {
       "expr": "sum(idelta(billing_payment_operation_in_payment_operation_received_count{namespace = \"$namespace\", service=~\"as-mp-payment-operation-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_payment_operation_in_payment_operation_dlt_count{namespace = \"$namespace\", service=~\"as-mp-payment-operation-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DLT"
      },
      {
       "expr": "sum(idelta(billing_payment_operation_in_payment_operation_filtered_by_payment_operation_type_count{namespace = \"$namespace\", service=~\"as-mp-payment-operation-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "FILTERED BY PAYMENT OPERATION TYPE"
      }
     ]
    },
    {
     "title": "Return-cash-flow-in",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "sum(idelta(billing_payment_operation_in_return_cash_flow_processed_count{namespace = \"$namespace\", service=~\"as-mp-payment-operation-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      },
      {
       "expr": "sum(idelta(billing_payment_operation_in_return_cash_flow_received_count{namespace = \"$namespace\", service=~\"as-mp-payment-operation-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_payment_operation_in_return_cash_flow_dlt_count{namespace = \"$namespace\", service=~\"as-mp-payment-operation-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DLT"
      }
     ]
    },
    {
     "title": "Agent-report-command-in",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "sum(idelta(billing_command_in_out_agent_report_command_received_count{namespace = \"$namespace\", service=~\"as-mp-command-in-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_command_in_out_agent_report_command_processed_count{namespace = \"$namespace\", service=~\"as-mp-command-in-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      },
      {
       "expr": "sum(idelta(billing_command_in_out_agent_report_command_dlt_count{namespace = \"$namespace\", service=~\"as-mp-command-in-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DLT"
      }
     ]
    },
    {
     "title": "Subtotal-agent-report-command-in",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "sum(idelta(billing_command_in_out_subtotal_agent_report_command_received_count{namespace = \"$namespace\", service=~\"as-mp-command-in-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_command_in_out_subtotal_agent_report_command_processed_count{namespace = \"$namespace\", service=~\"as-mp-command-in-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      },
      {
       "expr": "sum(idelta(billing_command_in_out_subtotal_agent_report_command_dlt_count{namespace = \"$namespace\", service=~\"as-mp-command-in-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DLT"
      }
     ]
    },
    {
     "title": "Document-contract-in",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "sum(idelta(billing_contract_in_document_received_count{namespace = \"$namespace\", service=~\"as-mp-contract-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_contract_in_document_processed_count{namespace = \"$namespace\", service=~\"as-mp-contract-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      },
      {
       "expr": "sum(idelta(billing_contract_in_document_dlt_count{namespace = \"$namespace\", service=~\"as-mp-contract-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DLT"
      }
     ]
    },
    {
     "title": "Merchant-contract-in",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "targets": [
      {
       "expr": "sum(idelta(billing_contract_in_merchant_received_count{namespace = \"$namespace\", service=~\"as-mp-contract-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_contract_in_merchant_processed_count{namespace = \"$namespace\", service=~\"as-mp-contract-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      },
      {
       "expr": "sum(idelta(billing_contract_in_merchant_dlt_count{namespace = \"$namespace\", service=~\"as-mp-contract-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DLT"
      }
     ]
    },
    {
     "title": "Partner-contract-in",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "sum(idelta(billing_contract_in_partner_received_count{namespace = \"$namespace\", service=~\"as-mp-contract-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_contract_in_partner_processed_count{namespace = \"$namespace\", service=~\"as-mp-contract-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      },
      {
       "expr": "sum(idelta(billing_contract_in_partner_dlt_count{namespace = \"$namespace\", service=~\"as-mp-contract-in.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DLT"
      }
     ]
    },
    {
     "title": "Cash flow manager INPUT PAYMENT OPERATION",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "targets": [
      {
       "expr": "sum(idelta(billing_cash_flow_manager_received_payment_operation_count{namespace = \"$namespace\", service=~\"as-mp-cash-flow-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_cash_flow_manager_duplicated_payment_operation_count{namespace = \"$namespace\", service=~\"as-mp-cash-flow-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DUPLICATED"
      }
     ]
    },
    {
     "title": "Claim composer INPUT CLAIM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "sum(idelta(billing_claim_composer_received_claims_count{namespace = \"$namespace\", service=~\"as-mp-claim-composer.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_claim_composer_filtered_claims_count{namespace = \"$namespace\", service=~\"as-mp-claim-composer.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "FILTERED"
      },
      {
       "expr": "sum(idelta(billing_claim_composer_duplicated_claims_count{namespace = \"$namespace\", service=~\"as-mp-claim-composer.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DUPLICATED"
      }
     ]
    },
    {
     "title": "Cash flow manager INPUT RETURN CASH FLOW",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "targets": [
      {
       "expr": "sum(idelta(billing_cash_flow_manager_received_return_cash_flow_count{namespace = \"$namespace\", service=~\"as-mp-cash-flow-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_cash_flow_manager_duplicated_return_cash_flow_count{namespace = \"$namespace\", service=~\"as-mp-cash-flow-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DUPLICATED"
      }
     ]
    },
    {
     "title": "Claim composer INPUT ORDER",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "targets": [
      {
       "expr": "sum(idelta(billing_claim_composer_received_orders_count{namespace = \"$namespace\", service=~\"as-mp-claim-composer.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_claim_composer_duplicated_orders_count{namespace = \"$namespace\", service=~\"as-mp-claim-composer.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DUPLICATED"
      }
     ]
    }
   ]
  },
  {
   "title": "Sent transition objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agent-report-command-status-out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "sum(idelta(billing_command_in_out_agent_report_command_status_received_count{namespace = \"$namespace\", service=~\"as-mp-command-in-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_command_in_out_agent_report_command_status_processed_count{namespace = \"$namespace\", service=~\"as-mp-command-in-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      }
     ]
    },
    {
     "title": "Subtotal-agent-report-command-status-out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "sum(idelta(billing_command_in_out_subtotal_agent_report_command_status_received_count{namespace = \"$namespace\", service=~\"as-mp-command-in-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_command_in_out_subtotal_agent_report_command_status_processed_count{namespace = \"$namespace\", service=~\"as-mp-command-in-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      }
     ]
    },
    {
     "title": "Agent-report-out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "sum(idelta(billing_report_out_received_agent_report_count{namespace = \"$namespace\", service=~\"as-mp-report-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "sum(idelta(billing_report_out_processed_agent_report_count{namespace = \"$namespace\", service=~\"as-mp-report-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED"
      },
      {
       "expr": "sum(idelta(billing_report_out_processed_agent_report_for_dp_count{namespace = \"$namespace\", service=~\"as-mp-report-out.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PROCESSED FOR DP"
      }
     ]
    },
    {
     "title": "Cash-flow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "targets": [
      {
       "expr": "sum(idelta(billing_cash_flow_manager_generated_direct_cash_flow_report_count{namespace = \"$namespace\", service=~\"as-mp-cash-flow-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "DIRECT"
      },
      {
       "expr": "sum(idelta(billing_cash_flow_manager_generated_refund_cash_flow_report_count{namespace = \"$namespace\", service=~\"as-mp-cash-flow-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "REFUND"
      }
     ]
    }
   ]
  },
  {
   "title": "Received objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received report commands",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "sum(idelta(billing_report_manager_received_agent_report_compile_command_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "AGENT COMPILE"
      },
      {
       "expr": "sum(idelta(billing_report_manager_received_agent_report_approve_command_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))  >= 0 ",
       "legendFormat": "AGENT APPROVE"
      },
      {
       "expr": "sum(idelta(billing_report_manager_received_subtotal_agent_report_compile_command_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval]))  >= 0 ",
       "legendFormat": "SUBTOTAL COMPILE"
      }
     ]
    },
    {
     "title": "Received agent report data",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum(idelta(billing_report_manager_received_parcel_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "PARCEL"
      },
      {
       "expr": "sum(idelta(billing_report_manager_received_return_parcel_count{namespace = \"$namespace\", service=~\"as-mp-report-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "RETURN PARCEL"
      },
      {
       "expr": "sum(idelta(billing_report_manager_received_payment_operation_count{namespace = \"$namespace\"}[$__rate_interval])) >= 0",
       "legendFormat": "PAYMENT OPERATION"
      }
     ]
    },
    {
     "title": "Received documents",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "sum(idelta(billing_contract_manager_saved_documents{namespace = \"$namespace\", service=~\"as-mp-contract-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "SAVED"
      },
      {
       "expr": "sum(idelta(billing_contract_manager_updated_documents{namespace = \"$namespace\", service=~\"as-mp-contract-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "UPDATED"
      }
     ]
    },
    {
     "title": "Received merchants",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "sum(idelta(billing_contract_manager_saved_merchants{namespace = \"$namespace\", service=~\"as-mp-contract-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "SAVED"
      },
      {
       "expr": "sum(idelta(billing_contract_manager_updated_merchants{namespace = \"$namespace\", service=~\"as-mp-contract-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "UPDATED"
      }
     ]
    },
    {
     "title": "Received partners",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "sum(idelta(billing_contract_manager_saved_partners{namespace = \"$namespace\", service=~\"as-mp-contract-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "SAVED"
      },
      {
       "expr": "sum(idelta(billing_contract_manager_updated_partners{namespace = \"$namespace\", service=~\"as-mp-contract-manager.*\"}[$__rate_interval])) >= 0",
       "legendFormat": "UPDATED"
      }
     ]
    }
   ]
  }
 ]
}