{
 "title": "Camunda metrics billing",
 "description": "Dashboard for analyzing individual endpoints' performance using metric http_server_requests",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(jvm_classes_loaded_classes, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (processName) (camunda_instance_count{namespace=\"$namespace\"})",
     "legendFormat": "{{ processName }}"
    }
   ]
  },
  {
   "title": "Incident Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (processName) (camunda_incident_count{namespace=\"$namespace\"})",
     "legendFormat": "{{ processName }}"
    }
   ]
  },
  {
   "title": "Human Task Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (processName)(camunda_human_task_count{namespace=\"$namespace\"})",
     "legendFormat": "{{ processName }}"
    }
   ]
  },
  {
   "title": "Job Executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (processName) (camunda_active_job_count{namespace=\"$namespace\"})",
     "legendFormat": "{{ processName }} (active)"
    },
    {
     "expr": "sum by (processName) (camunda_suspended_job_count{namespace=\"$namespace\"})",
     "legendFormat": "{{ processName }} (suspended)"
    }
   ]
  }
 ]
}