{
 "title": "RAP business metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "RAPServices", "label": "RAP Services", "query": "rap.*" },
   {
    "name": "excluded_urls",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|UNKNOWN|/camunda/.*|ROOT|REDIRECTION|root|NOT_FOUND|/webjars/.*"
   },
   {
    "name": "topic",
    "label": "topic",
    "query": "system-int-phtt-receipt-v1, system-int-phtt-solutionDetailed-v1"
   }
  ]
 },
 "panels": [
  {
   "title": "Conductor AB Error Sales Rate",
   "type": "timeseries",
   "description": "Shows how many sales received ERROR state during time (min step 1m)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service) (increase(error_status_absale_count_total[5m]))"
    }
   ]
  },
  {
   "title": "Sale Consuming Rates",
   "type": "timeseries",
   "description": "Shows how many sales were received during time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(service, topic)  (increase(kafka_consumer_fetch_manager_records_consumed_total{namespace=\"$namespace\", topic=~\"$namespace-system-int-rap-ab-sales-v1\"}[5m]))"
    }
   ]
  },
  {
   "title": "Receipts consuming rates",
   "type": "timeseries",
   "description": "Shows how many receipts were received during time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service, topic)(increase(kafka_consumer_fetch_manager_records_consumed_total{namespace=\"$namespace\", topic=~\"$namespace-system-int-rap-receipt-v1\"}[5m]))",
     "legendFormat": "Topic: {{topic}}. Service: {{service}}"
    }
   ]
  },
  {
   "title": "SolutionDetails consuming rates",
   "type": "timeseries",
   "description": "Shows how many solutions were received during time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service, topic)(increase(kafka_consumer_fetch_manager_records_consumed_total{namespace=\"$namespace\", topic=~\"$namespace-system-int-phtt-solutionDetailed-v1\"}[5m]))",
     "legendFormat": "Topic: {{topic}}. Service: {{service}}"
    }
   ]
  },
  {
   "title": "Transfers Rate",
   "type": "timeseries",
   "description": "Shows how many Transfers were generated during time. (min step 5 min)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service, topic)(increase(kafka_producer_topic_record_send_total{namespace=\"$namespace\", topic=~\"$namespace-system-int-phtt-transfer-v1\"}[5m]))",
     "legendFormat": "Topic: {{topic}}. Service: {{service}}"
    }
   ]
  },
  {
   "title": "Transfer Generation Time ",
   "type": "timeseries",
   "description": "Shows how much time it takes to generate a Transfer from the moment the receipt was received",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service) (rate(asset_transfer_generation_time_since_receipt_of_the_receipt_seconds_sum{namespace=\"$namespace\"}[5m])/rate(asset_transfer_generation_time_since_receipt_of_the_receipt_seconds_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Transfer Generation Time",
   "type": "timeseries",
   "description": "Shows how much time it takes to generate a Transfer ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service) (rate(asset_transfer_generation_time_seconds_sum[5m])/rate(asset_transfer_generation_time_seconds_count[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transfer generation time 95 percentile",
   "type": "timeseries",
   "description": "Shows how much time it takes to generate a Transfer ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(avg by (service) (histogram_quantile(0.95, rate(asset_transfer_generation_time_seconds_bucket{namespace=\"$namespace\"}[5m]))))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Turnover overall (goods+delivery)",
   "type": "timeseries",
   "description": "Shows how many amounts was transfered",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by (service) (increase(revenue_delivery_transfer_value_total[5m])))",
     "legendFormat": "Delivery"
    },
    {
     "expr": "(sum by (service) (increase(revenue_transfer_value_total[5m])))",
     "legendFormat": "Goods"
    }
   ]
  },
  {
   "title": "Turnover goods total amount",
   "type": "timeseries",
   "description": "Shows how many amount of goods was transfered",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service) (revenue_transfer_value_total{namespace=\"$namespace\"})",
     "legendFormat": "goods amount"
    },
    {
     "expr": "sum by (service) (revenue_delivery_transfer_value_total{namespace=\"$namespace\"})",
     "legendFormat": "delivery amount"
    }
   ]
  },
  {
   "title": "Conductor Error Receipts Rate",
   "type": "timeseries",
   "description": "Shows how many receipts received ERROR state during time (min step 1m)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service) (increase(broken_receipt_errors_count_total[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reprocessing Receipts Count",
   "type": "timeseries",
   "description": "The graph shows number of daily reprocessed receipts.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum by (service) (increase(reprocessing_receipts_counter_total [1d]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Conductor Invalid Receipts Rate",
   "type": "timeseries",
   "description": "Shows how many receipts received INVALID state during time (min step 1m)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service) (increase(invalid_receipt_count_total[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Percent phtt receipts",
   "type": "timeseries",
   "description": "Shows how much order is phtt relative all receipts",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "(sum by (topic) (increase(kafka_consumer_fetch_manager_records_consumed_total{topic=\"billing-prod-system-int-rap-transfer-command-v1\"}[1h])))/ ignoring(topic) (sum by (topic) (increase(kafka_consumer_fetch_manager_records_consumed_total{topic=\"billing-prod-system-int-phtt-receipt-v1\"}[1h])))",
     "legendFormat": "percent phtt",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Transfers/Commands AB ratio",
   "type": "gauge",
   "description": "Shows the ratio between Transfers and Commands over given <time>",
   "gridPos": { "h": 11, "w": 12, "x": 7, "y": 116 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum by(topic)(increase(kafka_consumer_fetch_manager_records_consumed_total{topic=\"billing-prod-system-int-rap-ab-transfer-command-v1\"}[10m])))/ignoring(topic,service)(sum by(service) (increase(kafka_producer_record_send_total{service=\"rap-transfer-manager-ab\"}[10m])))"
    }
   ]
  },
  {
   "title": "Transfers/Commands MP ratio",
   "type": "gauge",
   "description": "Shows the ratio between Transfers and Commands over given <time>",
   "gridPos": { "h": 11, "w": 12, "x": 7, "y": 127 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum by(topic)(increase(kafka_consumer_fetch_manager_records_consumed_total{topic=\"billing-prod-system-int-rap-mp-transfer-command-v1\"}[10m])))/ignoring(topic,service)(sum by(service) (increase(kafka_producer_record_send_total{service=\"rap-transfer-manager-mp\"}[10m])))"
    }
   ]
  },
  {
   "title": "Transfers/Commands ratio",
   "type": "gauge",
   "description": "Shows the ratio between Transfers and Commands over given <time>",
   "gridPos": { "h": 11, "w": 12, "x": 7, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "100*(sum by(topic)(increase(kafka_consumer_fetch_manager_records_consumed_total{topic=\"billing-prod-system-int-rap-transfer-command-v1\"}[10m])))/ignoring(topic,service)(sum by(service) (increase(kafka_producer_record_send_total{service=\"rap-transfer-manager\"}[10m])))",
     "legendFormat": "Transfers from transfer command",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}