{
 "title": "RAP metrics of incorrect processing",
 "time": { "from": "2023-11-12T23:27:16.506Z", "to": "2023-11-26T23:27:16.506Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "RAPServices", "label": "RAP Services", "query": "rap.*" },
   {
    "name": "excluded_urls",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|UNKNOWN|/camunda/.*|ROOT|REDIRECTION|root|NOT_FOUND|/webjars/.*"
   },
   {
    "name": "topic",
    "label": "topic",
    "query": "system-int-phtt-receipt-v1, system-int-phtt-solutionDetailed-v1"
   }
  ]
 },
 "panels": [
  {
   "title": "rap-etl-solution-in",
   "type": "bargauge",
   "description": "Shows different processing  errors rap-etl-solution-in",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (increase(solution_lines_is_empty_counter_total{service=\"rap-etl-solution-in\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "At least one solution don't have lines"
    },
    {
     "expr": "sum by (service) (increase(document_type_is_not_order_counter_total{service=\"rap-etl-solution-in\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "At least one solution don't have lines"
    },
    {
     "expr": "sum by (service) (increase(more_than_one_delivery_line_counter_total{service=\"rap-etl-solution-in\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "At least one solution have more than one DELIVERY line"
    },
    {
     "expr": "sum by (service) (increase(incorrect_line_type_counter_total{service=\"rap-etl-solution-in\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "At least one solution have lines different from PRODUCT or DELIVERY"
    },
    {
     "expr": "sum by (service) (increase(different_point_of_origin_for_online_counter_total{service=\"rap-etl-solution-in\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Different pointOfOrigin values for solution with \"ONLINE\" type"
    },
    {
     "expr": "sum by (service) (increase(missed_delivery_coordinates_counter_total{service=\"rap-etl-solution-in\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Delivery coordinates are missed in the solution"
    },
    {
     "expr": "sum by (service) (increase(not_valid_store_rap_online_counter_total{service=\"rap-etl-solution-in\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Store isn't valid for rap online"
    },
    {
     "expr": "sum by (service) (increase(not_valid_store_rap_counter_total{service=\"rap-etl-solution-in\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Store isn't valid for rap"
    },
    {
     "expr": "sum by (service) (increase(missed_payment_task_counter_total{service=\"rap-etl-solution-in\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "PaymentTask in the solution is null"
    }
   ]
  },
  {
   "title": "rap-conductor",
   "type": "bargauge",
   "description": "Shows different processing  errors rap-conductor",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (increase(solution_lines_is_empty_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "At least one solution don't have lines"
    },
    {
     "expr": "sum by (service) (increase(document_type_is_not_order_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "At least one solution have not ORDER document type"
    },
    {
     "expr": "sum by (service) (increase(more_than_one_delivery_line_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "At least one solution have more than one DELIVERY line"
    },
    {
     "expr": "sum by (service) (increase(incorrect_line_type_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "At least one solution have lines different from PRODUCT or DELIVERY"
    },
    {
     "expr": "sum by (service) (increase(more_than_one_solution_online_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "There are more than one solution with \"ONLINE\" type"
    },
    {
     "expr": "sum by (service) (increase(different_solution_type_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "There are solutions with different types"
    },
    {
     "expr": "sum by (service) (increase(different_point_of_origin_for_online_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Different pointOfOrigin values for solution with \"ONLINE\" type"
    },
    {
     "expr": "sum by (service) (increase(missed_delivery_coordinates_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Delivery coordinates are missed in the solution"
    },
    {
     "expr": "sum by (service) (increase(missed_payment_task_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "PaymentTask in the solution is null"
    },
    {
     "expr": "sum by (service) (increase(not_valid_store_phtt_online_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Store isn't valid for phtt online"
    },
    {
     "expr": "sum by (service) (increase(different_point_of_sale_and_origin_for_online_counter_total{service=\"rap-conductor\",namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Different pointOfOrigin and pointOfSale values for solution with \"ONLINE\" type"
    },
    {
     "expr": "sum by (service) (increase(solution_not_found_counter_total{service=\"rap-conductor\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Solution not found"
    }
   ]
  },
  {
   "title": "rap-conductor-ab",
   "type": "bargauge",
   "description": "Shows different processing  errors rap-conductor-ab",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (increase(no_lines_counter_total{service=\"rap-conductor-ab\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "There are no lines for transfer!"
    },
    {
     "expr": "sum by (service) (increase(empty_cluster_of_sale_counter_total{service=\"rap-conductor-ab\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Cluster of sale for transit sale is missed"
    },
    {
     "expr": "sum by (service) (increase(deliver_line_in_transit_sale_counter_total{service=\"rap-conductor-ab\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Found delivery line for transit sale"
    },
    {
     "expr": "sum by (service) (increase(more_than_one_delivery_counter_total{service=\"rap-conductor-ab\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "More than one delivery line"
    },
    {
     "expr": "sum by (service) (increase(solution_not_found_error_counter_total{service=\"rap-conductor-ab\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Solution not found"
    }
   ]
  },
  {
   "title": "rap-conductor-mp",
   "type": "bargauge",
   "description": "Shows different processing  errors rap-conductor-mp",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (increase(delivery_not_found_counter_total{service=\"rap-conductor-mp\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Delivery not found"
    },
    {
     "expr": "sum by (service) (increase(parcel_lines_is_empty_counter_total{service=\"rap-conductor-mp\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "There aren’t lines for turnover allocation in the parcel"
    },
    {
     "expr": "sum by (service) (increase(wrong_parcel_states_counter_total{service=\"rap-conductor-mp\", namespace=\"$namespace\"}[$__range])) != 0",
     "legendFormat": "Wrong parcel states"
    }
   ]
  }
 ]
}