{
 "title": "SLOs: Availability and Latency",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "span", "query": "5m, 30m, 1h, 2h, 6h, 1d, 3d" },
   {
    "name": "namespace",
    "query": "label_values(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=~\".*-(test|stage|prod)\"}, namespace) "
   },
   {
    "name": "service",
    "query": "label_values(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\"}, service) "
   },
   {
    "name": "location",
    "query": "label_values(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", namespace=\"$namespace\", service=\"$service\"}, location) "
   }
  ]
 },
 "panels": [
  {
   "title": "Availability Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - kubernetes:error_slo:percent{service=\"$service\", location=\"$location\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Availability over $span",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - kubernetes:service_location_namespace:errors_per_responses:ratio_rate[[span]]{service=\"$service\", location=\"$location\", namespace=\"$namespace\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Availability Status over $span",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * kubernetes:service_location_namespace:errors_per_responses:ratio_rate[[span]]{service=\"$service\", location=\"$location\", namespace=\"$namespace\"}\n> bool on (service, location) kubernetes:error_slo:percent",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "P99 Latency Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kubernetes:latency_p99_slo:seconds{service=\"$service\", location=\"$location\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "P99 Latency over $span",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p99_rate[[span]]{service=\"$service\", location=\"$location\", namespace=\"$namespace\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "P99 Latency Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p99_rate[[span]]{service=\"$service\", location=\"$location\", namespace=\"$namespace\"}\n> bool on (service, location) kubernetes:latency_p99_slo:seconds",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "P90 Latency Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kubernetes:latency_p90_slo:seconds{service=\"$service\", location=\"$location\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "P90 Latency over $span",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p90_rate[[span]]{service=\"$service\", location=\"$location\", namespace=\"$namespace\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "P90 Latency Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p90_rate[[span]]{service=\"$service\", location=\"$location\", namespace=\"$namespace\"}\n> bool on (service, location) kubernetes:latency_p90_slo:seconds",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Errors ratio over 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kubernetes:service_location_namespace:errors_per_responses:ratio_rate5m{service=\"$service\", location=\"$location\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Latency over 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p90_rate5m{service=\"$service\", location=\"$location\", namespace=\"$namespace\"}",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p99_rate5m{service=\"$service\", location=\"$location\", namespace=\"$namespace\"}",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Avg RPS by location",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (location)(rate(ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\", service=\"$service\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ location }}"
    }
   ]
  }
 ]
}