{
 "title": "Cloud Print Service",
 "description": "Business metrics for cloud-print service",
 "tags": [ "cloud-print" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, namespace)"
    }
   },
   { "name": "service", "label": "Service", "query": "cloud-print" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Get Printers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "get-printers (direct) duration [1m]",
   "type": "graph",
   "description": "This method is only called when no value was found in cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(PrintersClient_getPrinters_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m])) / sum(irate(PrintersClient_getPrinters_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "get-printers (direct) average duration by store [1m]",
   "type": "graph",
   "description": "This method is only called when no value was found in cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (hostPrefix) (irate(PrintersClient_getPrinters_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m])) / sum by (hostPrefix) (irate(PrintersClient_getPrinters_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m]))",
     "legendFormat": "{{ hostPrefix }}"
    }
   ]
  },
  {
   "title": "get-printers (direct) top 10 slowest stores [selected range]",
   "type": "bargauge",
   "description": "This method is only called when no value was found in cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by (hostPrefix) (increase(PrintersClient_getPrinters_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[$__range])) / sum by (hostPrefix) (increase(PrintersClient_getPrinters_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[$__range]))))",
     "legendFormat": "{{ hostPrefix }}"
    }
   ]
  },
  {
   "title": "get-printers (direct) errors by (store, exception)",
   "type": "graph",
   "description": "Had to use flat lines, because prometheus 'increase' function can't calculate increase from zero (nothing). ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (hostPrefix, exception) (PrintersClient_getPrinters_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception!=\"none\"})",
     "legendFormat": "{{ hostPrefix }} - {{ exception }}"
    }
   ]
  },
  {
   "title": "get-printers (cached, retried) count by store [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (hostPrefix) (increase(PrintersIntegrationService_getPrinters_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range]) > 0))",
     "legendFormat": "{{ hostPrefix }}"
    }
   ]
  },
  {
   "title": "get-printers (cached, retried) count [selected range]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(PrintersIntegrationService_getPrinters_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "get-printers (cached, retried) count by store [1m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (hostPrefix) (increase(PrintersIntegrationService_getPrinters_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "{{ hostPrefix }}"
    }
   ]
  },
  {
   "title": "get-printers (cached, retried) unique stores [selected range]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (hostPrefix) (increase(PrintersIntegrationService_getPrinters_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range]) > 0))"
    }
   ]
  },
  {
   "title": "get-printers (cached, retried) errors by (store, exception)",
   "type": "graph",
   "description": "When all retries did not help",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (hostPrefix, exception) (PrintersIntegrationService_getPrinters_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception!=\"none\"})",
     "legendFormat": "{{ hostPrefix }} - {{ exception }}"
    }
   ]
  },
  { "title": "Print File", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "print-file duration [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(PrintersClient_printFile_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m])) / sum(irate(PrintersClient_printFile_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "print-file file size KBytes [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(Custom_PrintersIntegrationService_PrintFile_SizeKBytes_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])) / sum(irate(Custom_PrintersIntegrationService_PrintFile_SizeKBytes_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "print-file average duration by store [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (hostPrefix) (irate(PrintersClient_printFile_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m])) / sum by (hostPrefix) (irate(PrintersClient_printFile_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m]))",
     "legendFormat": "{{ hostPrefix }}"
    }
   ]
  },
  {
   "title": "print-file top 10 slowest stores [selected range]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by (hostPrefix) (increase(PrintersClient_printFile_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[$__range])) / sum by (hostPrefix) (increase(PrintersClient_printFile_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[$__range]))))",
     "legendFormat": "{{ hostPrefix }}"
    }
   ]
  },
  {
   "title": "print-file exceptions [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exception) (increase(PrintersClient_printFile_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception!=\"none\"}[5m]))",
     "legendFormat": "{{ exception }}"
    }
   ]
  },
  { "title": "Build Document", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "build-document duration [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ActionsService_fillAndBuildDocument_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m])) / sum(irate(ActionsService_fillAndBuildDocument_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "build-document duration by (fileType, templateName) [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (fileType, templateName) (irate(ActionsService_fillAndBuildDocument_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m])) / sum by (fileType, templateName) (irate(ActionsService_fillAndBuildDocument_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", exception=\"none\"}[1m]))",
     "legendFormat": "[{{ fileType }}] {{ templateName }}"
    }
   ]
  },
  {
   "title": "build-document count by (fileType, templateName) [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fileType, templateName) (increase(ActionsService_fillAndBuildDocument_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "[{{ fileType }}] {{ templateName }}"
    }
   ]
  },
  {
   "title": "build-document count by (fileType, templateName) [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (fileType, templateName) (increase(ActionsService_fillAndBuildDocument_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range]) > 0))",
     "legendFormat": "[{{ fileType }}] {{ templateName }}"
    }
   ]
  },
  {
   "title": "build-document elements count [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(Custom_ActionsService_DocumentContentArraySize_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])) / sum(irate(Custom_ActionsService_DocumentContentArraySize_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "build-document elements count by (fileType, templateName) [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fileType, templateName) (irate(Custom_ActionsService_DocumentContentArraySize_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])) / sum by (fileType, templateName) (irate(Custom_ActionsService_DocumentContentArraySize_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "[{{ fileType }}] {{ templateName }}"
    }
   ]
  },
  {
   "title": "build-document file size KBytes by fileType [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (fileType) (irate(Custom_ActionsService_BuildResultDocumentSizeKBytes_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])) / sum by (fileType) (irate(Custom_ActionsService_BuildResultDocumentSizeKBytes_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "{{ fileType }}"
    }
   ]
  },
  {
   "title": "build-document file size KBytes by (fileType, templateName) [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (fileType, templateName) (irate(Custom_ActionsService_BuildResultDocumentSizeKBytes_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])) / sum by (fileType, templateName) (irate(Custom_ActionsService_BuildResultDocumentSizeKBytes_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "[{{ fileType }}] {{ templateName }}"
    }
   ]
  },
  { "title": "Build And Print", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "build-and-print count by hostPrefix [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (hostPrefix) (increase(ActionsService_fillAndBuildAndSendToPrinter_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "{{ hostPrefix }}"
    }
   ]
  },
  {
   "title": "build-and-print count by (fileType, templateName) [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fileType, templateName) (increase(ActionsService_fillAndBuildAndSendToPrinter_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "[{{ fileType }}] {{ templateName }}"
    }
   ]
  },
  {
   "title": "build-and-print count by store [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 102 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (hostPrefix) (increase(ActionsService_fillAndBuildAndSendToPrinter_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range]) > 0))",
     "legendFormat": "{{ hostPrefix }}"
    }
   ]
  },
  {
   "title": "build-and-print count [selected range]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 102 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(ActionsService_fillAndBuildAndSendToPrinter_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "build-and-print count by (fileType, templateName) [selected range]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 102 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (fileType, templateName) (increase(ActionsService_fillAndBuildAndSendToPrinter_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range]) > 0))",
     "legendFormat": "[{{ fileType }}] {{ templateName }}"
    }
   ]
  },
  {
   "title": "build-and-print unique stores [selected range]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 107 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (hostPrefix) (increase(ActionsService_fillAndBuildAndSendToPrinter_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range]) > 0))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}