{
 "title": "HikariCP & JDBC Dashboard",
 "tags": [
  "spring",
  "prometheus",
  "hikaricp"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(hikaricp_connections{application=\"$application\"},  namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HikariCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections{application=\"$application\",  namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{application=\"$application\",  namespace=\"$namespace\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(hikaricp_connections_idle{application=\"$application\",  namespace=\"$namespace\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(hikaricp_connections_pending{application=\"$application\",  namespace=\"$namespace\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_timeout_total{application=\"$application\",  namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(hikaricp_connections_creation_seconds_sum{application=\"$application\",  namespace=\"$namespace\"}[$__rate_interval])) / sum(rate(hikaricp_connections_creation_seconds_count{application=\"$application\",  namespace=\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(hikaricp_connections_usage_seconds_sum{application=\"$application\",  namespace=\"$namespace\"}[$__rate_interval])) / sum(rate(hikaricp_connections_usage_seconds_count{application=\"$application\",  namespace=\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(hikaricp_connections_acquire_seconds_sum{application=\"$application\",  namespace=\"$namespace\"}[$__rate_interval])) / sum(rate(hikaricp_connections_acquire_seconds_count{application=\"$application\",  namespace=\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "Acquire Time"
    }
   ]
  }
 ]
}