{
 "title": "Camunda",
 "tags": [ "camunda" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "query": "prometheus" },
   {
    "name": "camunda_name",
    "query": "mo : camunda-merchant-order-exporter, oms : camunda-exporter, returns : camunda-returns-exporter"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(camunda_external_tasks_count{service=\"metrics-exporter-camunda-oms-metrics\"} ,namespace) "
    }
   }
  ]
 },
 "panels": [
  { "title": "External Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active External Task Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (pod, instance) (camunda_active_external_task_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Suspended External Task Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (pod, instance) (camunda_suspended_external_task_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Locked External Task Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (pod, instance) (camunda_locked_external_task_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Not-Locked External Task Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (pod, instance) (camunda_external_tasks_not_locked_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "External Tasks with No Reties Left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (pod, instance) (camunda_external_tasks_with_no_retries_left_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "External Tasks with Reties Left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (pod, instance) (camunda_external_tasks_with_retries_left_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active External Tasks Count with Priority between 0 and 100",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (pod, instance) (camunda_external_tasks_with_priority_between_0_and_100{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active External Tasks Count with Priority <= 50",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (pod, instance) (camunda_external_tasks_with_priority_lower_than_or_equals_50{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active External Tasks Count with Priority >= 51",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (pod, instance) (camunda_external_tasks_with_priority_higher_than_or_equals_51{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Timers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Timer Job Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_active_timer_job_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Suspended Timer Job Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_suspended_timer_job_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Incidents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Incidents Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_open_incidents_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Resolved Incidents Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_resolved_incidents_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deleted Incidents Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_deleted_incidents_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Current Incidents Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_incidents_count{service=\"metrics-exporter-camunda-${camunda_name:text}-metrics\",namespace=\"$namespace\"}",
       "legendFormat": "{{definition_key}} v{{definition_version}}, `{{activity_name}}`"
      }
     ]
    }
   ]
  },
  {
   "title": "Event Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Message Subscription Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_message_event_subscription_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Signal Subscription Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_signal_event_subscription_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Conditional Subscription Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_conditional_event_subscription_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Compensation Subscription Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_compensation_event_subscription_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "User Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active User Tasks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_active_user_tasks_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Suspended User Tasks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_suspended_user_tasks_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Active Unassigned User Tasks Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_active_unassigned_user_tasks_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Identity Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tenant count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_identity_service_tenant_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "User Count across all Tenants",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_identity_service_user_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Group count across all Tenants",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_identity_service_group_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Process Instances by Process Definition Key",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_active_process_instance_count{service=\"${camunda_name:value}\",namespace=\"$namespace\"})",
       "legendFormat": "Key: {{process_definition_key}}"
      }
     ]
    },
    {
     "title": "Activity Instance Start/End Rate per 5min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg without (pod, instance) (rate(camunda_metric_job_execution_rejected{service=\"${camunda_name:value}\",namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Execution Rejections"
      },
      {
       "expr": "avg without (pod, instance) (rate(camunda_metric_activity_instance_start{service=\"${camunda_name:value}\",namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Instance Start"
      },
      {
       "expr": "avg without (pod, instance) (rate(camunda_metric_activity_instance_end{service=\"${camunda_name:value}\",namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Instance End"
      }
     ]
    },
    {
     "title": "Activity Instance Start (Flow Node Instances)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_metric_activity_instance_start{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Activity Instance End",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 7, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_metric_activity_instance_end{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Job Execution Rejected",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 14, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_metric_job_execution_rejected{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Successful Executed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_metric_job_successful{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Locked (Exclusive)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 7, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_metric_job_locked_exclusive{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed to Execute",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 14, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_metric_job_failed{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Acquisition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Acquisition Attempts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_metric_job_acquisition_attempt{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Successfully Acquired",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 7, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_metric_job_acquired_success{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Job Acquire Failure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 14, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_metric_job_acquired_failure{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Decision Execution (DMN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Decision Elements Executed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (pod, instance) (camunda_metric_executed_decision_elements{service=\"${camunda_name:value}\",namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "REST API Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tomcat throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (module, servlet) (increase(tomcat_servlet_processingtime_total{namespace=\"$namespace\", service=\"camunda-${camunda_name:text}-jmx\", module=\"localhost/engine-rest\",servlet=\"Resteasy\"}[5m])/increase(tomcat_servlet_requestcount_total{namespace=\"$namespace\", service=\"camunda-${camunda_name:text}-jmx\", module=\"localhost/engine-rest\",servlet=\"Resteasy\"}[5m]))",
       "legendFormat": "response time {{module}}, {{servlet}}"
      },
      {
       "expr": "sum by (module, servlet) (irate(tomcat_servlet_requestcount_total{namespace=\"$namespace\", service=\"camunda-${camunda_name:text}-jmx\", module=\"localhost/engine-rest\",servlet=\"Resteasy\"}[5m]))",
       "legendFormat": "rate {{module}}, {{servlet}}"
      },
      {
       "expr": "sum by (module, servlet) (irate(tomcat_servlet_errorcount_total{namespace=\"$namespace\", service=\"camunda-${camunda_name:text}-jmx\", module=\"localhost/engine-rest\",servlet=\"Resteasy\"}[5m]))",
       "legendFormat": "error rate {{module}}, {{servlet}}"
      }
     ]
    },
    {
     "title": "Tomcat pods throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "increase(tomcat_servlet_processingtime_total{namespace=\"$namespace\", service=\"camunda-${camunda_name:text}-jmx\", module=\"localhost/engine-rest\",servlet=\"Resteasy\"}[5m])/increase(tomcat_servlet_requestcount_total{namespace=\"$namespace\", service=\"camunda-${camunda_name:text}-jmx\", module=\"localhost/engine-rest\",servlet=\"Resteasy\"}[5m])",
       "legendFormat": "response time, pod {{pod}}"
      },
      {
       "expr": "irate(tomcat_servlet_requestcount_total{namespace=\"$namespace\", service=\"camunda-${camunda_name:text}-jmx\", module=\"localhost/engine-rest\",servlet=\"Resteasy\"}[5m])",
       "legendFormat": "rate, pod {{pod}}"
      },
      {
       "expr": "irate(tomcat_servlet_errorcount_total{namespace=\"$namespace\", service=\"camunda-${camunda_name:text}-jmx\", module=\"localhost/engine-rest\",servlet=\"Resteasy\"}[5m])",
       "legendFormat": "error rate, pod {{pod}}"
      }
     ]
    },
    {
     "title": "Response Codes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (method, route, status) (camunda_metric_sent_requests_total{namespace=\"$namespace\"})",
       "legendFormat": "{{method}} {{route}}, {{status}}"
      },
      {
       "expr": "sum by (method, route, status) (rate(camunda_metric_sent_requests_total{namespace=\"$namespace\"}[2m]))",
       "legendFormat": "{{method}} {{route}}, rate {{status}}"
      }
     ]
    },
    {
     "title": "Request Durations SLO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "  sum(rate(camunda_metric_sent_requests_duration_seconds_bucket{namespace=\"$namespace\", le=\"1\", status=\"2XX\"}[2m])) by (method, route)\r\n/\r\n  sum(rate(camunda_metric_sent_requests_duration_seconds_count{namespace=\"$namespace\"}[2m])) by (method, route)",
       "legendFormat": "{{method}} {{route}}"
      }
     ]
    },
    {
     "title": "Response Durations Apdex",
     "type": "graph",
     "gridPos": { "h": 7, "w": 23, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(\r\n  sum(rate(camunda_metric_sent_requests_duration_seconds_bucket{namespace=\"$namespace\", le=\"1\", status=\"2XX\"}[2m])) by (method, route)\r\n+\r\n  sum(rate(camunda_metric_sent_requests_duration_seconds_bucket{namespace=\"$namespace\", le=\"5\", status=\"2XX\"}[2m])) by (method, route)\r\n) / 2 / sum(rate(camunda_metric_sent_requests_duration_seconds_count{namespace=\"$namespace\"}[2m])) by (method, route)",
       "legendFormat": "{{method}} {{route}}"
      }
     ]
    },
    {
     "title": "Response Durations 0.95-quantile",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(camunda_metric_sent_requests_duration_seconds_bucket{namespace=\"$namespace\", status=\"2XX\"}[2m])) by (method, route, le))",
       "legendFormat": "{{method}} {{route}}"
      }
     ]
    }
   ]
  }
 ]
}