{
 "title": "Distribution of orders Emergency mod FFP",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(client_error_total, namespace)"
    }
   },
   { "name": "service", "label": "Service", "query": "fulfillment-promise" },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Client Error Emergency Mode True%[5m]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (client_name) (increase(client_error_total{namespace=\"$namespace\", service=\"$service\", has_emergency_mode=\"true\"}[5m]))\n/\n    sum by (client_name) (increase(client_request_count_total{namespace=\"$namespace\", service=\"$service\"}[5m]))\n) * 100",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Client Error Emergency Mode False%[5m]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n    sum by (client_name) (increase(client_error_total{namespace=\"$namespace\", service=\"$service\", has_emergency_mode=\"false\"}[5m]))\n/\n    sum by (client_name) (increase(client_request_count_total{namespace=\"$namespace\", service=\"$service\"}[5m]))\n) * 100",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Client Error Emergency Mode True [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(service, client_name, has_emergency_mode) (delta(client_error_total{namespace=\"$namespace\", service=\"$service\", has_emergency_mode=\"true\"}[5m])) >= 0",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Client Error Emergency Mode False [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "sum by(service, client_name, has_emergency_mode) (delta(client_error_total{namespace=\"$namespace\", service=\"$service\", has_emergency_mode=\"false\"}[5m]))  >= 0",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Client Error Total [selected range]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(client_error_total{namespace=\"$namespace\", service=\"$service\"}[$__range]) > 0) by (client_name, has_emergency_mode))"
    }
   ]
  },
  {
   "title": "Client Request Total [selected range]",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(client_request_count_total{namespace=\"$namespace\", service=\"$service\"}[$__range]) > 0) by (client_name, has_emergency_mode))"
    }
   ]
  }
 ]
}