{
 "title": "Returns services errors",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values({namespace=\"$namespace\"}, container)"
   },
   { "name": "error_msg", "label": "Error Message", "query": "SC not found in configuration" }
  ]
 },
 "panels": [
  { "title": "Most Common Error Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Most Common Error Messages",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (msg) (\n    count_over_time(\n      {namespace=\"$namespace\", container=\"$container\"} \n      | json \n      | level=\"error\" \n      [${__range}]\n    )\n  )\n)"
    }
   ]
  },
  {
   "title": "Current Message Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", container=~\"$container\"} | json | level=\"error\" | msg=~\"$error_msg\" [$__range])) or vector(0)"
      }
     ]
    },
    {
     "title": "Error per Hour",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(hour) (count_over_time({namespace=\"$namespace\", container=\"$container\"} | json | level=\"error\" | msg =`${error_msg}` [1h])) or vector(0)",
       "legendFormat": "Errors",
       "minInterval": "1h",
       "resolution": 1
      }
     ]
    },
    {
     "title": "Detailed Logs",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=~\"$container\"} | json | level=\"error\" | msg=~\"$error_msg\" | line_format \"container: {{.container}} '|' traceId: {{.traceId}} '|' spanId: {{.spanId}} \""
      }
     ]
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", container=~\"$container\"} | json | level=\"error\"  [$__range])) or vector(0)"
      }
     ]
    },
    {
     "title": "Errors per Hour",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(hour) (count_over_time({namespace=\"$namespace\", container=\"$container\"} | json | level=\"error\" [1h])) or vector(0)",
       "legendFormat": "Errors",
       "minInterval": "1h",
       "resolution": 1
      }
     ]
    },
    {
     "title": "Detailed Logs",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=~\"$container\"} | json | level=\"error\" | msg=~\"$error_msg\" | line_format \"container: {{.container}} '|' traceId: {{.traceId}} '|' spanId: {{.spanId}} '|' msg: {{.msg}}\""
      }
     ]
    }
   ]
  }
 ]
}