{
 "title": "oms storage v3",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "span", "query": "5m, 30m, 1h, 2h, 6h, 1d, 3d" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(process_start_time_seconds{service=\"oms-storage-v3\"},namespace)"
    }
   },
   {
    "name": "service",
    "query": "service=\"oms-storage-v3\""
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=\"oms-storage-v3\", namespace=\"$namespace\"}[5m]))\n / \n sum(rate(process_cpu_seconds_total{service=\"oms-storage-v3\", namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "HTTP API error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_count{status_code!~\"2..\", namespace=\"$namespace\", service=\"oms-storage-v3\"}[$span])) by  (path, method)",
     "legendFormat": "{{method}}: {{path}}"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_user_seconds_total{namespace=\"$namespace\", service=\"oms-storage-v3\"}[2m])) * 100"
    }
   ]
  },
  {
   "title": "Event Loop lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{ namespace=\"$namespace\", service=\"oms-storage-v3\"}"
    }
   ]
  },
  {
   "title": "RSS memoty",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ namespace=\"$namespace\", service=\"oms-storage-v3\"}"
    }
   ]
  },
  { "title": "HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_count{\n    namespace=\"$namespace\", service=\"oms-storage-v3\", path!=\"/favicon.ico\", path!=\"/\"}[$__rate_interval])) by (status_code, path, method)",
     "legendFormat": "{{status_code}}: {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "API Request time, p99",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum(\n        rate(\n            http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"oms-storage-v3\", path!=\"/favicon.ico\", path!=\"/\"}[$span]\n        )\n    ) by (path, le, method)\n)",
     "legendFormat": "{{method}}: {{path}}"
    }
   ]
  },
  {
   "title": "API Request time, p95",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n        rate(\n            http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"oms-storage-v3\", path!=\"/favicon.ico\", path!=\"/\"}[$span]\n        )\n    ) by (path, le, method)\n)",
     "legendFormat": "{{method}}: {{path}}"
    }
   ]
  },
  {
   "title": "InMemory Cache",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(v3_cache_total{namespace=\"$namespace\", service=\"oms-storage-v3\"}[$span]) - rate(v3_cache_hit{namespace=\"$namespace\", $service}[$span])\r\n)\r\n/\r\nsum(\r\n    rate(v3_cache_total{namespace=\"$namespace\", service=\"oms-storage-v3\"}[$span])\r\n)",
     "legendFormat": "Missed {{name}}"
    },
    {
     "expr": "sum(\r\n    rate(v3_cache_hit{namespace=\"$namespace\"}[$span])\r\n)\r\n/\r\nsum(\r\n    rate(v3_cache_total{namespace=\"$namespace\"}[$span])\r\n)",
     "legendFormat": "Hit {{name}}"
    }
   ]
  }
 ]
}