{
 "title": "Order Tracking Main",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(ingress_nginx_detail_responses_total,namespace)"
    }
   },
   {
    "name": "span",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Order Tracking services status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Create Order",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "latency",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p99_rate5m{service=\"oms-orders-post-v2\", namespace=~\"$namespace\"}",
     "legendFormat": "latency",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.5
    },
    {
     "aggregation": "Last",
     "alias": "error",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "kubernetes:service_location_namespace:errors_per_responses:ratio_rate5m{service=\"oms-orders-post-v2\", namespace=~\"$namespace\"}",
     "legendFormat": "error",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.1
    }
   ]
  },
  {
   "title": "Legacy Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "rate",
     "crit": 200,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(\n  rate(\n    grpc_server_handled_total{service=\"oms-storage\",grpc_type=\"unary\", namespace=~\"$namespace\"}[$span]\n  )\n)",
     "legendFormat": "rate",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 100
    },
    {
     "aggregation": "Last",
     "alias": "latency",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n        rate(\n            grpc_server_handling_seconds_bucket{service=\"oms-storage\", grpc_type=\"unary\", namespace=~\"$namespace\"}[$span]\n        )\n    ) by (le)\n)",
     "legendFormat": "latency",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.5
    },
    {
     "aggregation": "Last",
     "alias": "error",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(\n  rate(\n    grpc_server_handled_total{service=\"oms-storage\",grpc_type=\"unary\", namespace=~\"$namespace\",grpc_code!~\"OK\" }[$span]\n  )\n)",
     "legendFormat": "error",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.1
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "rate",
     "crit": 200,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum (\n    rate(\n        http_request_duration_seconds_count{namespace=~\"$namespace\", service=\"oms-storage-v3\"}[$span]\n    )\n)",
     "legendFormat": "rate",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 100
    },
    {
     "aggregation": "Last",
     "alias": "latency",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "histogram_quantile(\n    0.99,\n    sum(\n        rate(\n            http_request_duration_seconds_bucket{service=\"oms-storage-v3\", namespace=~\"$namespace\"}[$span]\n        )\n    ) by (le)\n)",
     "legendFormat": "latency",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.5
    },
    {
     "aggregation": "Last",
     "alias": "error",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum (\n    rate(\n        http_request_duration_seconds_count{namespace=~\"$namespace\", service=\"oms-storage-v3\", status_code!~\"200|201|204\"}[$span]\n    )\n)",
     "legendFormat": "error",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.1
    }
   ]
  },
  {
   "title": "Camunda API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "rate",
     "crit": 200,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(\n    rate(\n        ingress_nginx_detail_requests_total{job=\"nginx-ingress-controller\", service=\"oms-camunda-api\"}[$span]\n    )\n)",
     "legendFormat": "rate",
     "units": "reqps",
     "valueHandler": "Number Threshold",
     "warn": 100
    },
    {
     "aggregation": "Last",
     "alias": "latency",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p99_rate5m{service=\"oms-camunda-api\", namespace=~\"$namespace\"}",
     "legendFormat": "latency",
     "units": "s",
     "valueHandler": "Number Threshold",
     "warn": 0.5
    },
    {
     "aggregation": "Last",
     "alias": "error",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "kubernetes:service_location_namespace:errors_per_responses:ratio_rate5m{service=\"oms-camunda-api\", namespace=~\"$namespace\"}",
     "legendFormat": "error",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.1
    }
   ]
  },
  {
   "title": "Logistic Statuses WMS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "rate",
     "crit": 200,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(\n    rate(\n        http_request_duration_seconds_bucket{namespace=~\"$namespace\", service=\"order-tracking-api\"}[$span]\n    )\n)",
     "legendFormat": "rate",
     "units": "reqps",
     "valueHandler": "Number Threshold",
     "warn": 100
    },
    {
     "aggregation": "Last",
     "alias": "latency",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "histogram_quantile(\n    0.95, \n    sum(\n        rate(\n            http_request_duration_seconds_bucket{namespace=~\"$namespace\", service=\"order-tracking-api\"}[$span]\n        )\n    )\n    by (le)\n)",
     "legendFormat": "latency",
     "units": "s",
     "valueHandler": "Number Threshold",
     "warn": 0.5
    },
    {
     "aggregation": "Last",
     "alias": "error",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(\n    rate(\n        http_request_duration_seconds_bucket{namespace=~\"$namespace\", service=\"order-tracking-api\", status_code!=\"201\"}[$span]\n    )\n)",
     "legendFormat": "error",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.1
    }
   ]
  },
  {
   "title": "Camunda REST API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "rate",
     "crit": 200,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum (\n    rate(\n        camunda_messages_handling_seconds_bucket{namespace=~\"$namespace\"}[$span]\n    )\n)",
     "legendFormat": "rate",
     "units": "reqps",
     "valueHandler": "Number Threshold",
     "warn": 100
    },
    {
     "aggregation": "Last",
     "alias": "latency",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "histogram_quantile(\n    0.95, \n    sum(\n        rate(\n            camunda_messages_handling_seconds_bucket{namespace=~\"$namespace\"}[$span]\n        )\n    )\n    by (le)\n)",
     "legendFormat": "latency",
     "units": "s",
     "valueHandler": "Number Threshold",
     "warn": 0.5
    },
    {
     "aggregation": "Last",
     "alias": "error",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(\n    rate(\n        camunda_incidents_count{service=\"camunda-metrics-exporter\", namespace=~\"$namespace\"}[$span]\n    )\n)",
     "legendFormat": "error",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.1
    }
   ]
  },
  {
   "title": "Logistic Statuses DelRep",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "rate",
     "crit": 200,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(\n    rate(\n        delrep_status_checker_process_count{namespace=~\"$namespace\", service=\"delrep-rabbit-statuses\"}[$span]\n    )\n)",
     "legendFormat": "rate",
     "units": "reqps",
     "valueHandler": "Number Threshold",
     "warn": 100
    },
    {
     "aggregation": "Last",
     "alias": "latency",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "histogram_quantile(\n    0.95, \n    sum(\n        rate(\n            delrep_status_checker_process_bucket{namespace=~\"$namespace\", service=\"delrep-rabbit-statuses\"}[$span]\n        )\n    )\n    by (le)\n)",
     "legendFormat": "latency",
     "units": "s",
     "valueHandler": "Number Threshold",
     "warn": 0.5
    },
    {
     "aggregation": "Last",
     "alias": "error",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(\n    rate(\n        delrep_status_checker_process_bucket{namespace=~\"$namespace\", service=\"delrep-rabbit-statuses\", status!=\"ok\"}[$span]\n    )\n)",
     "legendFormat": "error",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.1
    },
    {
     "aggregation": "Last",
     "alias": "DLQ",
     "crit": 0.2,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(\n    rate(\n        delrep_status_checker_dead_letter_queue{namespace=~\"$namespace\", service=\"delrep-rabbit-statuses\"}[$span]\n    )\n)",
     "legendFormat": "DLQ",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 0.1
    }
   ]
  },
  {
   "title": "OrdersPostV2 - create new order",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Error, 5m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "kubernetes:service_location_namespace:errors_per_responses:ratio_rate5m{service=\"oms-orders-post-v2\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Latency, 5m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p90_rate5m{service=\"oms-orders-post-v2\", namespace=~\"$namespace\"}",
     "legendFormat": "Latency p90"
    },
    {
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p99_rate5m{service=\"oms-orders-post-v2\", namespace=~\"$namespace\"}",
     "legendFormat": "Latency p99"
    }
   ]
  },
  { "title": "Camunda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Incident Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(\r\n    camunda_active_incidents{service=\"camunda-monitoring\", namespace=~\"$namespace\"}[$span]\r\n)",
     "legendFormat": "{{definition_key}} v{{definition_version}}, `{{activity_name}}`"
    }
   ]
  },
  {
   "title": "Worker latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95, \r\n    sum(\r\n        rate(\r\n            camunda_messages_handling_seconds_bucket{namespace=~\"$namespace\"}[$span]\r\n        )\r\n    )\r\n    by (topic_name, status, le)\r\n)",
     "legendFormat": "{{topic_name}} {{status}}"
    }
   ]
  },
  { "title": "Oms storage - grpc api server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    grpc_server_handled_total{service=\"oms-storage\",grpc_type=\"unary\", namespace=~\"$namespace\"}[$span]\r\n  )\r\n) by (grpc_service, grpc_code)",
     "legendFormat": "{{grpc_service}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95,\r\n    sum(\r\n        rate(\r\n            grpc_server_handling_seconds_bucket{service=\"oms-storage\", grpc_type=\"unary\", namespace=~\"$namespace\"}[$span]\r\n        )\r\n    ) by (grpc_service, grpc_method, le)\r\n)",
     "legendFormat": "{{grpc_service}} {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Oms storage v3 - http api server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        http_request_duration_seconds_count{namespace=~\"$namespace\", service=\"oms-storage-v3\"}[$span]\r\n    )\r\n) by (path, status_code)",
     "legendFormat": "{{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Handling time, p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95,\r\n    sum(\r\n        rate(\r\n            http_request_duration_seconds_bucket{service=\"oms-storage-v3\", namespace=~\"$namespace\"}[$span]\r\n        )\r\n    ) by (path, status_code, le)\r\n)",
     "legendFormat": "{{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Logistic statuses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true
  },
  { "title": "Date recalculation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        delrep_status_checker_process_bucket{namespace=~\"$namespace\", service=\"delrep-rabbit-statuses\", status!=\"ok\"}[$span]\r\n    )\r\n)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(\n    rate(\n        delrep_status_checker_dead_letter_queue{namespace=~\"$namespace\", service=\"delrep-rabbit-statuses\"}[$span]\n    )\n)",
     "legendFormat": "DLQ"
    }
   ]
  },
  {
   "title": "DelRerp queue consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        delrep_status_checker_dead_letter_queue{namespace=~\"$namespace\", service=\"delrep-rabbit-statuses\"}[$span]\r\n    )\r\n)",
     "legendFormat": "Dead Letter"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        delrep_status_checker_process_count{namespace=~\"$namespace\", service=\"delrep-rabbit-statuses\"}[$span]\r\n    )\r\n) by (del_rep_status, status)",
     "legendFormat": "{{del_rep_status}} - {{status}}"
    }
   ]
  },
  {
   "title": "Cancel fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        data_recalculation_task_cancels_failed{namespace=~\"scdp-ofl-ot-preprod\"}[$span]\r\n    )\r\n)",
     "legendFormat": "Cancel fails"
    }
   ]
  },
  {
   "title": "DelRep status processing latenncy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95, \r\n    sum(\r\n        rate(\r\n            delrep_status_checker_process_bucket{namespace=~\"$namespace\", service=\"delrep-rabbit-statuses\"}[$span]\r\n        )\r\n    )\r\n    by (del_rep_status, status, le)\r\n)",
     "legendFormat": "{{del_rep_status}} - {{status}}"
    }
   ]
  },
  {
   "title": "WMS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        http_request_duration_seconds_bucket{namespace=~\"$namespace\", service=\"order-tracking-api\", status_code!=\"201\"}[$span]\r\n    )\r\n)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "WMS status processing latenncy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95, \r\n    sum(\r\n        rate(\r\n            http_request_duration_seconds_bucket{namespace=~\"$namespace\", service=\"order-tracking-api\"}[$span]\r\n        )\r\n    )\r\n    by (method, path, status, le)\r\n)",
     "legendFormat": "{{method}}  {{path}}: {{status}}"
    }
   ]
  },
  { "title": "Camunda api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Error, 5m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "kubernetes:service_location_namespace:errors_per_responses:ratio_rate5m{service=\"oms-camunda-api\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Latency, 5m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p90_rate5m{service=\"oms-camunda-api\", namespace=~\"$namespace\"}",
     "legendFormat": "Latency p90"
    },
    {
     "expr": "kubernetes:service_location_namespace:request_latency_seconds:p99_rate5m{service=\"oms-camunda-api\", namespace=~\"$namespace\"}",
     "legendFormat": "Latency p99"
    }
   ]
  }
 ]
}