{
 "title": "rom services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(process_start_time_seconds{service=\"server-service\"},namespace)"
    }
   },
   { "name": "service", "query": "server-service" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=\"$service\", namespace=\"$namespace\"}[5m]))\n / \n sum(rate(process_cpu_seconds_total{service=\"$service\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP API error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_count{status_code=~\"5..\", namespace=\"$namespace\", service=\"$service\"}[5m])) by  (path, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_seconds_count{\n    namespace=\"$namespace\", service=\"$service\", path!=\"/favicon.ico\", path!=\"/\"}[$__rate_interval])) by (status_code, path, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "\n    sum(\n        rate(\n            http_request_duration_seconds_sum{namespace=\"$namespace\", service=\"$service\", path!=\"/favicon.ico\", path!=\"/\"}[5m]\n        )\n    ) by (path, le, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node.JS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{namespace=\"$namespace\", service=\"$service\"}[1m]) / 60",
     "legendFormat": "full cpu"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}