{
 "title": "Airflow dashboard",
 "description": "Dashboard for Airflow",
 "tags": [
  "main",
  "micrometer"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(airflow_dag_status, namespace)"
   },
   {
    "name": "dag_id",
    "label": "dag",
    "query": "label_values(airflow_dag_status{namespace=\"$namespace\"}, dag_id)"
   },
   {
    "name": "task_id",
    "label": "task",
    "query": "label_values(airflow_task_status{namespace=\"$namespace\", dag_id=~\"$dag_id\"}, task_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "DAGs state",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(airflow_dag_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", status=\"success\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(airflow_dag_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", status=\"running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(airflow_dag_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", status=\"failed\"})",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Active tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(airflow_task_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", task_id=~\"$task_id\", status=\"running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(airflow_task_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", task_id=~\"$task_id\", status=\"queued\"})",
     "legendFormat": "queued"
    },
    {
     "expr": "sum(airflow_task_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", task_id=~\"$task_id\", status=\"scheduled\"})",
     "legendFormat": "scheduled"
    }
   ]
  },
  {
   "title": "All tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(airflow_task_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", task_id=~\"$task_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Failed tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(airflow_task_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", task_id=~\"$task_id\", status=\"failed\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Success task count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(airflow_task_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", task_id=~\"$task_id\", status=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "All dags count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(airflow_dag_status{namespace=\"$namespace\", dag_id=~\"$dag_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Failed dags count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(airflow_dag_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", status=\"failed\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Completed dags count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(airflow_dag_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", status=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Dag by statuses",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(airflow_dag_status{namespace=\"$namespace\", dag_id=~\"$dag_id\"}[$__range])) by (status, dag_id )",
     "legendFormat": "{{status}} {{dag_id}}"
    }
   ]
  },
  {
   "title": "Task by statuses",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(airflow_task_status{namespace=\"$namespace\", dag_id=~\"$dag_id\", task_id=~\"$task_id\"}[$__range])) by (status, dag_id )",
     "legendFormat": "{{status}} {{dag_id}}"
    }
   ]
  }
 ]
}