{
 "title": "OPUS UI Dashboard",
 "description": "Dashboard for OPUS UI applications",
 "tags": [
  "main",
  "ui"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(up, namespace)" } },
   {
    "name": "service",
    "label": "Application",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "clientPath",
    "label": "Client Path",
    "query": {
     "query": "label_values(request_client_duration_ms{namespace=\"$namespace\", service=~\"$service\"}, path)"
    }
   },
   {
    "name": "serverPath",
    "label": "Server Path",
    "query": {
     "query": "label_values(request_server_duration_ms{namespace=\"$namespace\", service=~\"$service\"}, path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node.js Process Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"$namespace\", service=\"$service\"}[1m])",
     "legendFormat": "Process - {{pod}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{namespace=\"$namespace\", service=\"$service\"}[1m])",
     "legendFormat": "System - {{pod}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\", service=\"$service\"} * 1000",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_heap_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Process Heap - {{pod}}"
    },
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Process Memory - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Heap Total - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Heap Used - {{pod}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "External Memory - {{pod}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Active Handler - {{pod}}"
    },
    {
     "expr": "nodejs_active_requests_total{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Active Request - {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Heap Total - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "BFF -> ElasticSearch ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "BFF -> ElasticSearch Request Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quantile) (request_elastic_duration_ms{namespace=\"$namespace\", service=\"$service\"})",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "BFF -> ElasticSearch RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(request_elastic_duration_ms_count{namespace=\"$namespace\", service=\"$service\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client -> BFF -> Reponse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client -> BFF Request Time $clientPath",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "repeat": "clientPath",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quantile) (request_client_duration_ms{namespace=\"$namespace\", service=\"$service\", path=~\"$clientPath\"})",
       "legendFormat": "Client - {{quantile}}"
      },
      {
       "expr": "avg by(quantile) (response_server_duration_ms{namespace=\"$namespace\", service=\"$service\", path=~\"$clientPath\"})",
       "legendFormat": "Server - {{quantile}}"
      }
     ]
    },
    {
     "title": "Client -> BFF RPS $clientPath",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "repeat": "clientPath",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(request_client_duration_ms_count{namespace=\"$namespace\", service=\"$service\", path=~\"$clientPath\"}[1m])",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BFF -> LOPUS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server -> Microservice AVG Request Time $serverPath",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "repeat": "serverPath",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(quantile) (request_server_duration_ms{namespace=\"$namespace\", service=\"$service\", path=~\"$serverPath\"})",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Server -> Microservice RPS - $serverPath",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "repeat": "serverPath",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(request_server_duration_ms_count{namespace=\"$namespace\", service=\"$service\", path=~\"$serverPath\"}[1m])",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  }
 ]
}