{
 "title": "Cluster metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_pod_container_status_restarts_total, namespace)"
    }
   },
   {
    "name": "Container",
    "query": {
     "query": "label_values(kube_pod_container_status_restarts_total{namespace=~\"$Namespace\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Container",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "repeat": "Container",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(kube_pod_container_status_ready{namespace=\"$Namespace\", container=\"$Container\"}[5m]))",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "#### **This is an Cluster metrics dashboard of your application's statistics. Select the namespace or service for your product.**"
   }
  },
  {
   "title": "$Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "Container",
   "collapsed": true,
   "panels": [
    {
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "min by (pod) (\n  kube_pod_container_info{namespace=\"$Namespace\", container=\"$Container\"}\n  * on (pod) group_right()\n  (\n    (\n      (min by (pod, phase) (label_replace(min_over_time(kube_pod_container_status_ready{namespace=\"$Namespace\", container=\"$Container\"}[$__rate_interval]), \"phase\", \"Ready\", \"\", \"\")) == 1) * 0 + 0\n    )\n    or on(pod)\n    (\n      (min by (pod, phase) (min_over_time(kube_pod_status_phase{namespace=\"$Namespace\"}[$__rate_interval])) == 1) * 0\n      + on(phase) group_left()\n      (\n        label_replace(vector(1), \"phase\", \"Running\", \"\", \"\") or\n        label_replace(vector(2), \"phase\", \"Pending\", \"\", \"\") or\n        label_replace(vector(3), \"phase\", \"Unknown\", \"\", \"\") or\n        label_replace(vector(4), \"phase\", \"Failed\", \"\", \"\") or\n        label_replace(vector(5), \"phase\", \"Succeeded\", \"\", \"\")\n      )\n    )\n  )  \n)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$Namespace\", container=\"$Container\"}[$__rate_interval])) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU usage by service",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=\"$Container\"}[$__rate_interval]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (container) (kube_pod_container_resource_limits{namespace=\"$Namespace\", container=\"$Container\",resource=\"cpu\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum by (container) (kube_pod_container_resource_requests{namespace=\"$Namespace\", container=\"$Container\",resource=\"cpu\"})",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "CPU usage by pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=\"$Container\"}[$__rate_interval]))",
       "legendFormat": "Usage ({{ pod }})"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_limits{namespace=\"$Namespace\", container=\"$Container\",resource=\"cpu\"})",
       "legendFormat": "Limit ({{ pod }})"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_requests{namespace=\"$Namespace\", container=\"$Container\",resource=\"cpu\"})",
       "legendFormat": "Request {{pod}}"
      }
     ]
    },
    {
     "title": "RAM usage by service",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (container) (avg_over_time(container_memory_working_set_bytes{namespace=\"$Namespace\", container=\"$Container\"}[$__rate_interval]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum by (container) (kube_pod_container_resource_limits{namespace=\"$Namespace\", container=\"$Container\",resource=\"memory\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "sum by (container) (kube_pod_container_resource_requests{namespace=\"$Namespace\", container=\"$Container\",resource=\"memory\"})",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "RAM usage by pod",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$Namespace\", container=\"$Container\"}[$__rate_interval]))",
       "legendFormat": "Usage ({{ pod }})"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_limits{namespace=\"$Namespace\", container=\"$Container\",resource=\"memory\"})",
       "legendFormat": "Limit ({{ pod }})"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_requests{namespace=\"$Namespace\", container=\"$Container\",resource=\"memory\"})",
       "legendFormat": "Request {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}