{
 "title": "GO Statistic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(go_goroutines, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(go_goroutines{namespace=\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (go_memstats_mspan_inuse_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_mspan_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_mcache_inuse_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_mcache_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_buck_hash_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_gc_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_other_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_next_gc_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (go_memstats_heap_alloc_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_heap_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_heap_idle_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_heap_inuse_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_heap_released_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (go_memstats_stack_inuse_bytes{namespace=\"$Namespace\", service=~\"$Service\"}) +\r\nsum by (service) (go_memstats_stack_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (go_memstats_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (go_memstats_mallocs_total{namespace=\"$Namespace\", service=~\"$Service\"}) -\r\nsum by (service) (go_memstats_frees_total{namespace=\"$Namespace\", service=~\"$Service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(go_memstats_lookups_total{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(go_memstats_alloc_bytes_total{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(go_memstats_mallocs_total{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (go_goroutines{namespace=\"$Namespace\", service=~\"$Service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (service) (go_gc_duration_seconds{namespace=\"$Namespace\", service=~\"$Service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "$Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_memstats_mspan_inuse_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "mspan_inuse_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_mspan_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "mspan_sys_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_mcache_inuse_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "mcache_inuse_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_mcache_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "mcache_sys_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_buck_hash_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "buck_hash_sys_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_gc_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "gc_sys_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_other_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "other_sys_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_next_gc_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "next_gc_bytes ({{pod}})"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_memstats_heap_alloc_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "heap_alloc_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_heap_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "heap_sys_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_heap_idle_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "heap_idle_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_heap_inuse_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "heap_inuse_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_heap_released_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "heap_released_bytes ({{pod}})"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_memstats_stack_inuse_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "stack_inuse_bytes ({{pod}})"
      },
      {
       "expr": "sum by (pod) (go_memstats_stack_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "stack_sys_bytes ({{pod}})"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_memstats_sys_bytes{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_memstats_mallocs_total{namespace=\"$Namespace\", service=~\"$Service\"}) - sum by (pod) (go_memstats_frees_total{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(go_memstats_mallocs_total{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(go_memstats_lookups_total{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_goroutines{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(go_memstats_alloc_bytes_total{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (pod) (go_gc_duration_seconds{namespace=\"$Namespace\", service=~\"$Service\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}