{
 "title": "Spring Boot HikariCP / JDBC",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(jdbc_connections_min, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(jdbc_connections_min{namespace=\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Min (jdbc)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(jdbc_connections_min{namespace=\"$Namespace\", service=\"$Service\"})"
      }
     ]
    },
    {
     "title": "Max (jdbc)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(jdbc_connections_max{namespace=\"$Namespace\", service=\"$Service\"})"
      }
     ]
    },
    {
     "title": "Idle (jdbc)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(jdbc_connections_idle{namespace=\"$Namespace\", service=\"$Service\"})"
      }
     ]
    },
    {
     "title": "Active (jdbc)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(jdbc_connections_active{namespace=\"$Namespace\", service=\"$Service\"})"
      }
     ]
    },
    {
     "title": "Min (hikaricp)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hikaricp_connections_min{namespace=\"$Namespace\", service=\"$Service\"})"
      }
     ]
    },
    {
     "title": "Max (hikaricp)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hikaricp_connections_max{namespace=\"$Namespace\", service=\"$Service\"})"
      }
     ]
    },
    {
     "title": "Idle (hikaricp)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hikaricp_connections_idle{namespace=\"$Namespace\", service=\"$Service\"})"
      }
     ]
    },
    {
     "title": "Pending (hikaricp)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hikaricp_connections_pending{namespace=\"$Namespace\", service=\"$Service\"})"
      }
     ]
    },
    {
     "title": "Active (hikaricp)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(hikaricp_connections_active{namespace=\"$Namespace\", service=\"$Service\"})"
      }
     ]
    },
    {
     "title": "Connections Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "sum(rate(hikaricp_connections_usage_seconds_sum{namespace=\"$Namespace\", service=\"$Service\"}[2m])) / sum(rate(hikaricp_connections_usage_seconds_count{namespace=\"$Namespace\", service=\"$Service\"}[2m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(rate(hikaricp_connections_creation_seconds_sum{namespace=\"$Namespace\", service=\"$Service\"}[2m])) / sum(rate(hikaricp_connections_creation_seconds_count{namespace=\"$Namespace\", service=\"$Service\"}[2m]))",
       "legendFormat": "Creation"
      },
      {
       "expr": "sum(rate(hikaricp_connections_acquire_seconds_sum{namespace=\"$Namespace\", service=\"$Service\"}[2m])) / sum(rate(hikaricp_connections_acquire_seconds_count{namespace=\"$Namespace\", service=\"$Service\"}[2m]))",
       "legendFormat": "Acquire"
      }
     ]
    }
   ]
  }
 ]
}