{
 "title": "HTTP statistic (NodeJS)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(http_requests_count, namespace)"
    }
   },
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values(http_requests_count{namespace=\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "Service",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_count{namespace=\"$Namespace\", service=\"$Service\", status!~\"5..\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_requests_count{namespace=\"$Namespace\", service=\"$Service\", status=~\"5..\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "$Service (IN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Request time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(http_requests_bucket{namespace=\"$Namespace\", service=\"$Service\"}[2m]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Status / Method / Uri (requests)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (status, method, path) (increase(http_requests_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m])) > 0",
       "legendFormat": "{{status}} {{method}} ({{path}})"
      }
     ]
    },
    {
     "title": "Method / Uri (time)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (method, path) (rate(http_requests_sum{namespace=\"$Namespace\", service=~\"$Service\"}[1m])) / scalar(sum(rate(http_requests_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))) > 0",
       "legendFormat": "{{status}} {{method}} ({{path}})"
      }
     ]
    }
   ]
  }
 ]
}