{
 "title": "Resources request",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests, namespace)"
    }
   },
   {
    "name": "Container",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{namespace=\"$Namespace\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=~\"$Container\"})"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_info{namespace=\"$Namespace\", horizontalpodautoscaler=\"$Container\"}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=~\"$Container\", container!=\"POD\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$Namespace\", resource=\"cpu\", container=~\"$Container\", container!=\"POD\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$Namespace\", container=~\"$Container\", resource=\"cpu\"}) - sum(rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=~\"$Container\", container!=\"POD\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$Namespace\", container=~\"$Container\", resource=\"cpu\", container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$Namespace\", container=~\"$Container\", container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "RAM Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$Namespace\", resource=\"memory\", container=~\"$Container\", container!=\"POD\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "RAM Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$Namespace\", resource=\"memory\", container=~\"$Container\", container!=\"POD\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "RAM Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$Namespace\", container=~\"$Container\", resource=\"memory\"}) - sum(container_memory_usage_bytes{namespace=\"$Namespace\", container=~\"$Container\", container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "$Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "Container",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Avg",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(sum(rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"}[5m]))[$__range:5m]) / count(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=\"$Container\"})"
      }
     ]
    },
    {
     "title": "CPU Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(sum(rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"}[5m]))[$__range:5m]) / count(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=\"$Container\"})"
      }
     ]
    },
    {
     "title": "CPU Request",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_requests{namespace=\"$Namespace\", resource=\"cpu\", container=~\"$Container\", container!=\"POD\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})) / count(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=\"$Container\"})"
      }
     ]
    },
    {
     "title": "RAM Avg",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(sum(container_memory_usage_bytes{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"})[$__range:5m]) / count(container_memory_usage_bytes{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"})"
      }
     ]
    },
    {
     "title": "RAM Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(sum(container_memory_usage_bytes{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"})[$__range:5m]) / count(container_memory_usage_bytes{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"})"
      }
     ]
    },
    {
     "title": "RAM Request",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_requests{namespace=\"$Namespace\", resource=\"memory\", container=~\"$Container\", container!=\"POD\"} * on (uid) group_left(phase) kube_pod_status_phase{phase=\"Running\"})) / count(container_memory_usage_bytes{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"})"
      }
     ]
    },
    {
     "title": "CPU Request per pod (recommend)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(avg_over_time(sum(rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"}[5m]))[$__range:5m]) / count(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=\"$Container\"})) * 180 / 100"
      }
     ]
    },
    {
     "title": "CPU Limit (recommend)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$Namespace\", container=~\"$Container\", resource=\"cpu\", container!=\"POD\"})"
      }
     ]
    },
    {
     "title": "RAM Request per pod (recommend)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(avg_over_time(sum(container_memory_usage_bytes{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"})[$__range:5m]) / count(container_memory_usage_bytes{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"})) * 120 / 100"
      }
     ]
    },
    {
     "title": "RAM Limit per pod (recommend)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(avg_over_time(sum(container_memory_usage_bytes{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"})[$__range:5m]) / count(container_memory_usage_bytes{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"})) * 150 / 100"
      }
     ]
    },
    {
     "title": "CPU by pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"}[5m]))",
       "legendFormat": "Usage ({{pod}})"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_requests{namespace=\"$Namespace\", container=\"$Container\",resource=\"cpu\"})",
       "legendFormat": "Requests ({{pod}})"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_limits{namespace=\"$Namespace\", container=\"$Container\",resource=\"cpu\"})",
       "legendFormat": "Limits ({{pod}})"
      }
     ]
    },
    {
     "title": "RAM by pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (container_memory_usage_bytes{namespace=\"$Namespace\", container=\"$Container\", container!=\"POD\"})",
       "legendFormat": "Usage ({{pod}})"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_requests{namespace=\"$Namespace\", container=\"$Container\",resource=\"memory\"})",
       "legendFormat": "Requests ({{pod}})"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_limits{namespace=\"$Namespace\", container=\"$Container\",resource=\"memory\"})",
       "legendFormat": "Limits ({{pod}})"
      }
     ]
    }
   ]
  }
 ]
}