{
 "title": "Processed communications (Rejected)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(rejected_communications_total, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(rejected_communications_total{namespace=\"$Namespace\"}, service)"
    }
   },
   {
    "name": "Communication",
    "query": {
     "query": "label_values(rejected_communications_total{namespace=\"$Namespace\", service=~\"$Service\"}, communication_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "Service",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rejected_communications_total{namespace=\"$Namespace\", service=\"$Service\"}[1m]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "Service" },
  {
   "title": "Rejected by communications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (communication_name) (increase(rejected_communications_total{namespace=\"$Namespace\", service=\"$Service\", communication_name=~\"$Communication\"}[1m]))",
     "legendFormat": "{{communication_name}}"
    }
   ]
  },
  { "title": "Overall communications table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Rejected summary",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (service, communication_name) (increase(rejected_communications_total{namespace=~\"$Namespace\", service=~\"$Service\", communication_name=~\"$Communication\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}