{
 "title": "Processed communications",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "sender",
    "label": "Sender",
    "query": "communication,generic-sms,pmp-message,push-sender"
   }
  ]
 },
 "panels": [
  {
   "title": "Total sending percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(processed_communications_total{status=\"success\"}) * 100 / sum(processed_communications_total)"
    },
    {
     "expr": "sum(processed_communications_total{status=\"error\"}) * 100 / sum(processed_communications_total)"
    }
   ]
  },
  {
   "title": "$sender",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "sender",
   "collapsed": true,
   "panels": [
    {
     "title": "Successes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(processed_communications_total{service=\"$sender\", status=\"success\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(processed_communications_total{service=\"$sender\", status=\"error\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Sending rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 18, "x": 6, "y": 5 },
     "targets": [
      {
       "expr": "sum(increase(processed_communications_total{service=\"$sender\", status=\"success\"}[1m]))"
      },
      {
       "expr": "sum(increase(processed_communications_total{service=\"$sender\", status=\"error\"}[1m]))"
      }
     ]
    },
    {
     "title": "Percentage",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(processed_communications_total{service=\"$sender\", status=\"success\"}[$__range])) * 100 / sum(increase(processed_communications_total{service=\"$sender\"}[$__range]))"
      },
      {
       "expr": "sum(increase(processed_communications_total{service=\"$sender\", status=\"error\"}[$__range])) * 100 / sum(increase(processed_communications_total{service=\"$sender\"}[$__range]))"
      }
     ]
    }
   ]
  }
 ]
}