{
 "title": "APM - SLI",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "path",
    "label": "path",
    "query": {
     "query": "label_values(http_requests_bucket{namespace=\"$namespace\", service=\"$app\"}, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SLI",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_bucket{namespace=\"$namespace\", service=\"$app\", path=~\"$path\", outcome!=\"SERVER_ERROR\"})/sum(http_requests_bucket{namespace=\"$namespace\", service=\"$app\", path=~\"$path\"})"
    }
   ]
  },
  {
   "title": "$app",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Status is",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(http_requests_bucket{namespace=\"$namespace\", service=\"$app\", path=~\"$path\", outcome!=\"SERVER_ERROR\"})/sum(http_requests_bucket{namespace=\"$namespace\", service=\"$app\", path=~\"$path\"})",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (path,method) (rate(http_requests_sum{namespace=\"$namespace\",service=\"$app\",path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 13, "w": 9, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(rate(http_requests_sum{namespace=\"$namespace\",service=\"$app\",path=~\"$path\"}[$__rate_interval])[$__range: $__interval]))",
     "legendFormat": "Max"
    },
    {
     "expr": "min(min_over_time(rate(http_server_requests_seconds_sum{exception=\"None\",namespace=\"$namespace\",service=\"$app\",path=~\"$path\"}[$__rate_interval])[$__range: $__interval]))",
     "legendFormat": "MIN"
    },
    {
     "expr": "avg(avg_over_time(rate(http_server_requests_seconds_sum{exception=\"None\",namespace=\"$namespace\",service=\"$app\",path=~\"$path\"}[$__rate_interval])[$__range: $__interval]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (path,method) (rate(http_requests_bucket{namespace=\"$namespace\",service=\"$app\",path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 13, "w": 9, "x": 13, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(rate(http_requests_bucket{namespace=\"$namespace\",service=\"$app\",path=~\"$path\"}[$__rate_interval])[$__range: $__interval]))",
     "legendFormat": "Max"
    },
    {
     "expr": "min(min_over_time(rate(http_requests_bucket{exception=\"None\",namespace=\"$namespace\",service=\"$app\",path=~\"$path\"}[$__rate_interval])[$__range: $__interval]))",
     "legendFormat": "MIN"
    },
    {
     "expr": "avg(avg_over_time(rate(http_requests_bucket{exception=\"None\",namespace=\"$namespace\",service=\"$app\",path=~\"$path\"}[$__rate_interval])[$__range: $__interval]))",
     "legendFormat": "AVG"
    }
   ]
  }
 ]
}