{
 "title": "Lynx speed",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Время работы репозиториев в модули нотификации",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lynx_notificationManager_repository_seconds_sum / lynx_notificationManager_repository_seconds_count",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Среднее время отправки уведомлений",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lynx_notificationManager_notification_seconds_sum / lynx_notificationManager_notification_seconds_count"
    }
   ]
  },
  {
   "title": "Среднее время работы rest клиента",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lynx_notificationManager_restClient_seconds_sum / lynx_notificationManager_restClient_seconds_count",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Количество сохраненных артикулов",
   "type": "graph",
   "description": "Количество сохраненных в базу данных артикулов",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(lynx_dbwriter_articleInserting_seconds_count{method=\"saveChains\"})"
    }
   ]
  },
  {
   "title": "Средняя скорость сохранения",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(lynx_dbwriter_articleInserting_seconds_count{method=\"saveChains\"}) - sum(lynx_dbwriter_articleInserting_seconds_count{method=\"saveChains\"} offset 3m)) / 180",
     "legendFormat": "articles per second"
    }
   ]
  },
  {
   "title": "Количество рассчитанных артикулов",
   "type": "graph",
   "description": "Количество рассчитанных артикулов Costing-модулем",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(lynx_request_processing_seconds_count)"
    }
   ]
  },
  {
   "title": "Максимальное время вставки в базу",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "lynx_dbwriter_articleInserting_seconds_max",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Средняя скорость расчета",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(lynx_article_calculation_seconds_count) - sum(lynx_article_calculation_seconds_count offset 1m))/60",
     "legendFormat": "Articles per second"
    }
   ]
  },
  {
   "title": "Среднее время расчета артикула",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(lynx_article_calculation_seconds_sum) / sum(lynx_article_calculation_seconds_count)",
     "legendFormat": "Calculation"
    },
    {
     "expr": "sum(lynx_request_processing_seconds_sum) / sum(lynx_request_processing_seconds_count)",
     "legendFormat": "Request processing"
    }
   ]
  },
  {
   "title": "Среднее время вставки в базу",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "lynx_dbwriter_articleInserting_seconds_sum / lynx_dbwriter_articleInserting_seconds_count",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Article calculation average time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(lynx_dbwriter_calculation_seconds_sum)/sum(lynx_dbwriter_calculation_seconds_count)"
    }
   ]
  },
  {
   "title": "Время работы функций сохранения",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lynx_dbwriter_dao_seconds_sum / lynx_dbwriter_dao_seconds_count",
     "legendFormat": "{{class}}.{{method}}"
    }
   ]
  },
  {
   "title": "Время работы кэша расчета",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "lynx_cache_seconds_sum/lynx_cache_seconds_count",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Количество артикулов в сохраняемой пачке",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lynx_dbwriter_EntitySaver_cache",
     "legendFormat": "Cache size"
    }
   ]
  },
  {
   "title": "Среднее время расчета DPAC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(lynx_dbwriter_articleInserting_seconds_sum{method=\"dpacCalculation\"})/sum(lynx_dbwriter_articleInserting_seconds_count{method=\"dpacCalculation\"})"
    }
   ]
  },
  {
   "title": "Среднее время записи в базу",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(lynx_dbwriter_insertInDb_seconds_sum)/sum(lynx_dbwriter_insertInDb_seconds_count)"
    }
   ]
  },
  {
   "title": "Топ-3 функций получения данных",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(3, lynx_repository_seconds_sum / lynx_repository_seconds_count)",
     "legendFormat": "{{class}}.{{method}}"
    }
   ]
  }
 ]
}