{
 "title": "Library-metrics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nameMethod",
    "query": "select \"nameMethod\" from \"library-metrics\""
   },
   {
    "name": "libraryVersion",
    "query": "select \"libraryVersion\" from \"library-metrics\""
   }
  ]
 },
 "panels": [
  {
   "title": "Find old version",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"nameMethod\" AS metric,\n  \"jobUrl\"\nFROM \"library-metrics\"\nWHERE\n  $__timeFilter(\"time\") AND\n  \"libraryVersion\" = '$libraryVersion' AND\n  \"nameMethod\" = '$nameMethod'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Counter",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"nameMethod\" AS metric,\n  sum(1) OVER (PARTITION BY \"nameMethod\" ORDER BY \"time\") AS \"1\"\nFROM \"library-metrics\"\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Version usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  \"libraryVersion\" AS metric,\n  sum(1) OVER (PARTITION BY \"libraryVersion\" ORDER BY \"time\") AS \"1\"\nFROM \"library-metrics\"\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Method in time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  \"nameMethod\" AS metric,\n  count(1) AS \"1\"\nFROM \"library-metrics\"\nWHERE\n  $__timeFilter(time) AND\n  \"nameMethod\" = '$nameMethod'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}