{
 "title": "SLO",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "payment-pb-prod" },
   {
    "name": "excluded_urls",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   },
   { "name": "slo_url_availability", "query": ".*availability.*" },
   { "name": "SLA", "query": "0.9,0.99,0.999,0.9999,0.99999" },
   { "name": "slo_url_process", "query": ".*process.*|.*v1/link/.*" },
   {
    "name": "slo_url_bv",
    "query": "/v1/stores/{storeCode}/pin-code|/v1/stores/{storeCode}/customer-order/{solutionId}"
   },
   {
    "name": "slo_url_bv2",
    "query": "/v1/stores/{storeCode}/pin-code|/v1/stores/{storeCode}/sales-order/{solutionId}"
   },
   { "name": "slo_url_task", "query": ".*task.*" },
   {
    "name": "slo_url_solution",
    "query": "/orders/solution-repository/v2/solutions/{solutionId}"
   },
   {
    "name": "slo_url_opus",
    "query": "/opus/api/productrepository/products"
   },
   {
    "name": "slo_url_task_opus",
    "query": "/product/v1/products|/products/artmagrepository/nomenclature/v1/stores"
   },
   { "name": "slo_task_queue", "query": "createPaymentTaskInput" },
   {
    "name": "slo_atol_url",
    "query": "/register-giveaway|/register-refund|/register-sale"
   },
   { "name": "slo_atol_atol", "query": ".*possystem.*" },
   {
    "name": "slo_money_queue",
    "query": "createSberbankDepositTransactionInput|createSberbankDepositTransactionOutput"
   },
   {
    "name": "slo_money_uri",
    "query": "/v1/task/change-status/{taskId}|/v1/task/{taskId}"
   },
   { "name": "slo_money_sberbank", "query": "/payment/rest/deposit.do" },
   {
    "name": "slo_process_sberbank",
    "query": "/payment/{paymentInstrument}/payment.do|/payment/rest/registerPreAuth.do"
   },
   { "name": "slo_notification_rui", "query": "/notification" },
   { "name": "slo_refund_url", "query": "/transaction-refund/{orderId}" },
   {
    "name": "slo_refund_sberbank",
    "query": "/payment/rest/reverse.do|/payment/rest/refund.do"
   },
   {
    "name": "slo_confirmation_url",
    "query": "/v1/task/change-status/{taskId}|/v1/task/edit-quantity/{taskId}|/v1/task/update-deposit-info"
   },
   {
    "name": "slo_giveaway_url",
    "query": "/v1/orchestrator/{taskId}/start-give-away|/v1/task/{taskId}/give-away"
   },
   {
    "name": "slo_changestatus_url",
    "query": "/v1/task/change-status/{taskId}"
   },
   { "name": "slo_tpnet_reg_queue", "query": ".*processTpnet.*" },
   {
    "name": "slo_confirmation_queue",
    "query": "tpnetTransactionDepositedInput|tpnetTransactionGivenAwayInput|salesOrderCheckOutInput"
   },
   {
    "name": "slo_changestatus_queue",
    "query": "paymentTaskModifiedOutboxedOutput"
   }
  ]
 },
 "panels": [
  { "title": "Общий", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", status!~\"5..\", uri!~\"$excluded_urls\"}[$__range:])) / sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", uri!~\"$excluded_urls\"}[$__range:]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Availability by service",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", status!~\"5..\", uri!~\"$excluded_urls\"}[$__range:])) by (service) / sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", uri!~\"$excluded_urls\"}[$__range:])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Получение доступных способов оплаты",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
     "repeat": "slo_interval",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", status!~\"5..\", location=~\"$slo_url_availability\"}[$__range:])) by (namespace) / sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_availability\"}[$__range:])) by (namespace)",
       "legendFormat": "availabilityMethods"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ingress_nginx_detail_request_seconds_bucket{namespace=\"$namespace\", location=~\"$slo_url_availability\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_availability\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_availability\"}[$__range:]))-(sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_availability\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    }
   ]
  },
  {
   "title": "Процессинг платежа",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", status!~\"5..\", location=~\"$slo_url_process\"}[$__range:])) by (namespace) / sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_process\"}[$__range:])) by (namespace)"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ingress_nginx_detail_request_seconds_bucket{namespace=\"$namespace\", location=~\"$slo_url_process\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_process\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_process\"}[$__range:]))-(sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_process\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    },
    {
     "title": "Availability sberbank",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_process_sberbank\"}[$__range:])) by (namespace, uri) / sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_process_sberbank\"}[$__range:])) by (namespace, uri)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "99 percentile sberbank",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_seconds_bucket{namespace=\"$namespace\",  uri=~\"$slo_process_sberbank\"}[$__range:])) by (le, uri))",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Создание Payment Task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", status!~\"5..\", location=~\"$slo_url_task\"}[$__range:])) by (namespace) / sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_task\"}[$__range:])) by (namespace)",
       "legendFormat": "availabilityMethods"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(ingress_nginx_detail_request_seconds_bucket{namespace=\"$namespace\", location=~\"$slo_url_task\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_task\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_task\"}[$__range:]))-(sum(increase(ingress_nginx_detail_responses_total{namespace=\"$namespace\", location=~\"$slo_url_task\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    },
    {
     "title": "Availability queue",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_task_queue\", result=\"success\"}[$__range])) /  sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_task_queue\"}[$__range]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Average queue",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (name) (increase(spring_integration_send_seconds_sum{namespace=\"$namespace\", name=~\"$slo_task_queue\"}[$__range])) /  sum by (name) (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_task_queue\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_task_queue\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_task_queue\"}[$__range]))-(sum(increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_task_queue\", result!~\"success\"}[$__range])) or vector(0))"
      }
     ]
    },
    {
     "title": "Availability OPUS",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", service=\"tasks\", uri=~\"$slo_url_task_opus\"}[$__range:])) by (namespace) / sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", service=\"tasks\", uri=~\"$slo_url_task_opus\"}[$__range:])) by (namespace)",
       "legendFormat": "Availability"
      }
     ]
    },
    {
     "title": "99 percentile OPUS",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_seconds_bucket{namespace=\"$namespace\",  service=\"tasks\", uri=~\"$slo_url_task_opus\"}[$__range:])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Оплата бланка заказа в магазине",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_url_bv\"}[$__range:])) by (namespace) / sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_bv\"}[$__range:])) by (namespace)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_url_bv\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_bv\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_bv\"}[$__range:]))-(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_bv\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    },
    {
     "title": "Availability solution",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_url_solution\"}[$__range:])) by (namespace) / sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_solution\"}[$__range:])) by (namespace)",
       "legendFormat": "Availability"
      }
     ]
    },
    {
     "title": "99 percentile solution",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_seconds_bucket{namespace=\"$namespace\", service=\"tp-net-interaction\", uri=~\"$slo_url_solution\"}[$__range:])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Оплата бланка продажи в магазине",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_url_bv2\"}[$__range:])) by (namespace) / sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_bv2\"}[$__range:])) by (namespace)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_url_bv2\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_bv2\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_bv2\"}[$__range:]))-(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_bv2\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    },
    {
     "title": "Availability solution",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_url_solution\"}[$__range:])) by (namespace) / sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_solution\"}[$__range:])) by (namespace)",
       "legendFormat": "Availability"
      }
     ]
    },
    {
     "title": "99 percentile solution",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_seconds_bucket{namespace=\"$namespace\", service=\"tp-net-interaction\", uri=~\"$slo_url_solution\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Availability OPUS",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_url_opus\"}[$__range:])) by (namespace) / sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_url_opus\"}[$__range:])) by (namespace)",
       "legendFormat": "Availability"
      }
     ]
    },
    {
     "title": "99 percentile OPUS",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_seconds_bucket{namespace=\"$namespace\", service=\"tp-net-interaction\", uri=~\"$slo_url_opus\"}[$__range:])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Регистрация чеков в АТОЛ-Онлайн",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_atol_url\"}[$__range:])) by (namespace) / sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_atol_url\"}[$__range:])) by (namespace)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_atol_url\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_atol_url\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_atol_url\"}[$__range:]))-(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_atol_url\", status=~\"5..\"}[$__range:]))  or vector(0))"
      }
     ]
    },
    {
     "title": "Availability ATOL",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", status!~\"5..|429\", uri=~\"$slo_atol_atol\"}[$__range:])) by (namespace) / sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_atol_atol\"}[$__range:])) by (namespace)",
       "legendFormat": "Availability"
      }
     ]
    },
    {
     "title": "99 percentile ATOL",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_atol_atol\"}[$__range:])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Списание денег",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_money_uri\"}[$__range:])) by (namespace) / sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_money_uri\"}[$__range:])) by (namespace)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_money_uri\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_money_uri\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_money_uri\"}[$__range:]))-(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_atol_url\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    },
    {
     "title": "Availability queue",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_money_queue\", result=\"success\"}[$__range])) /  sum (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_money_queue\"}[$__range]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Average queue",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (increase(spring_integration_send_seconds_sum{namespace=\"$namespace\", name=~\"$slo_money_queue\"}[$__range])) /  sum (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_money_queue\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Availability sberbank",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_money_sberbank\"}[$__range:])) by (namespace) / sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_money_sberbank\"}[$__range:])) by (namespace)",
       "legendFormat": "Availability"
      }
     ]
    },
    {
     "title": "99 percentile sberbank",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_money_sberbank\"}[$__range:])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Получение нотификации об оплате заказа",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_notification_rui\"}[$__range:])) by (namespace) / sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_notification_rui\"}[$__range:])) by (namespace)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_notification_rui\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_notification_rui\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_notification_rui\"}[$__range:]))-(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_notification_rui\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    }
   ]
  },
  {
   "title": "Возврат заказа в банке",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_refund_url\"}[$__range:])) by (namespace) / sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_refund_url\"}[$__range:])) by (namespace)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_refund_url\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_refund_url\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_refund_url\"}[$__range:]))-(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_refund_url\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    },
    {
     "title": "Availability sberbank",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_refund_sberbank\"}[$__range:])) by (namespace) / sum(increase(http_client_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_refund_sberbank\"}[$__range:])) by (namespace)",
       "legendFormat": "Availability"
      }
     ]
    },
    {
     "title": "99 percentile sberbank",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_refund_sberbank\"}[$__range:])) by (le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Регистрация транзакций в TpNet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability queue",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_tpnet_reg_queue\", result=\"success\"}[$__range])) /  sum (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_tpnet_reg_queue\"}[$__range]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Average queue",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (increase(spring_integration_send_seconds_sum{namespace=\"$namespace\", name=~\"$slo_tpnet_queue\"}[$__range])) /  sum (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_tpnet_queue\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Подтверждение от TpNet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_confirmation_url\"}[$__range:])) by (namespace) / sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_confirmation_url\"}[$__range:])) by (namespace)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_confirmation_url\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_confirmation_url\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_confirmation_url\"}[$__range:]))-(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_confirmation_url\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    },
    {
     "title": "Availability queue",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_confirmation_queue\", result=\"success\"}[$__range])) /  sum (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_confirmation_queue\"}[$__range]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Average queue",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (increase(spring_integration_send_seconds_sum{namespace=\"$namespace\", name=~\"$slo_confirmation_queue\"}[$__range])) /  sum (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_confirmation_queue\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Создание выдачи",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_giveaway_url\"}[$__range:])) by (namespace) / sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_giveaway_url\"}[$__range:])) by (namespace)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_giveaway_url\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_giveaway_url\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_giveaway_url\"}[$__range:]))-(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_giveaway_url\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    }
   ]
  },
  {
   "title": "Отправка сообщения о смене статуса в Solution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\", uri=~\"$slo_changestatus_url\"}[$__range:])) by (namespace) / sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_changestatus_url\"}[$__range:])) by (namespace)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "99 percentile",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", uri=~\"$slo_changestatus_url\"}[$__range:])) by (le))"
      }
     ]
    },
    {
     "title": "Bad requests error budget",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_changestatus_url\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "Available error requests",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1-$SLA)*sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_changestatus_url\"}[$__range:]))-(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri=~\"$slo_changestatus_url\", status=~\"5..\"}[$__range:])) or vector(0))"
      }
     ]
    },
    {
     "title": "Availability queue",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum  (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_changestatus_queue\", result=\"success\"}[$__range])) /  sum (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_changestatus_queue\"}[$__range]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Average queue",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (increase(spring_integration_send_seconds_sum{namespace=\"$namespace\", name=~\"$slo_changestatus_queue\"}[$__range])) /  sum (increase(spring_integration_send_seconds_count{namespace=\"$namespace\", name=~\"$slo_changestatus_queue\"}[$__range]))"
      }
     ]
    }
   ]
  }
 ]
}