{
 "title": "Payment-brick Alerts",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(http_server_requests_seconds_count, namespace)"
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   }
  ]
 },
 "panels": [
  { "title": "Atol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Atol response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"atol\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"atol\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "0.7", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Atol 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"atol\", outcome=\"SERVER_ERROR\"}[5m])/3.33))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1", "legendFormat": "alert" }
   ]
  },
  { "title": "Sberbank", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Sberbank /transaction-refund response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"sberbank\", exception=\"None\", uri=\"/transaction-refund/{orderId}\"}[5m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"sberbank\", exception=\"None\", uri=\"/transaction-refund/{orderId}\"}[5m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "3", "legendFormat": "transaction-refund alert" }
   ]
  },
  {
   "title": "Sberbank NOT /transaction-refund response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace = \"$namespace\", service=\"sberbank\", exception=\"None\", uri!~\"$excluded_urls\", uri!=\"/transaction-refund/{orderId}\"}[5m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace = \"$namespace\", service=\"sberbank\", exception=\"None\", uri!~\"$excluded_urls\", uri!=\"/transaction-refund/{orderId}\"}[5m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "2.5", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Sberbank 5xx (/availability not included)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"sberbank\", outcome=\"SERVER_ERROR\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\", uri!=\"/availability\"}[5m])/3.33))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "3", "legendFormat": "alert" }
   ]
  },
  { "title": "Simulation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Simulation response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"simulation\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{service=\"simulation\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "0.4", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Simulation 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"simulation\", outcome=\"SERVER_ERROR\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m])/3.33))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1", "legendFormat": "alert" }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Tasks response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"tasks\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"tasks\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "3", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Tasks 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"tasks\", outcome=\"SERVER_ERROR\"}[1m])/6.66))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1", "legendFormat": "alert" }
   ]
  },
  { "title": "Tp-net-interaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Tp-net-interaction response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"tp-net-interaction\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"tp-net-interaction\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Tp-net-interaction 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"tp-net-interaction\", outcome=\"SERVER_ERROR\"}[1m])/6.66))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1", "legendFormat": "alert" }
   ]
  }
 ]
}