{
 "title": "Payment-brick Alerts",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(http_server_requests_seconds_count, namespace)"
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_responses_total{job=\"nginx-ingress-controller\", vhost=~\"payment-brick-payment.apps.lmru.tech\", status=~\"5..\", location!~\".*orchestrator.*\"}[5m])) by (vhost, location)",
     "legendFormat": "{{location}}"
    },
    { "expr": "2", "legendFormat": "alert" }
   ]
  },
  { "title": "Atol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Atol response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"atol\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"atol\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "2", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Atol 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"atol\", outcome=\"SERVER_ERROR\"}[5m])/3.33))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1", "legendFormat": "alert" }
   ]
  },
  { "title": "Cash", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cash response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"cash\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"cash\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "0.5", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Cash 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"cash\", outcome=\"SERVER_ERROR\"}[5m])/3.33))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1", "legendFormat": "alert" }
   ]
  },
  { "title": "Orchestrator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Orchestrator response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"orchestrator\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"orchestrator\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1.5", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Orchestrator 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"orchestrator\", outcome=\"SERVER_ERROR\"}[5m])/3.33))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "2", "legendFormat": "alert" }
   ]
  },
  { "title": "Sberbank", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Sberbank /refund response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"sberbank\", exception=\"None\", uri=\"/v1/refund/{orderId}\"}[15m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"sberbank\", exception=\"None\", uri=\"/v1/refund/{orderId}\"}[15m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "4", "legendFormat": "transaction-refund alert" }
   ]
  },
  {
   "title": "Sberbank NOT /refund response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"sberbank\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\", uri!=\"/v1/refund/{orderId}\"}[15m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"sberbank\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\", uri!=\"/v1/refund/{orderId}\"}[15m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "3", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Sberbank 5xx (/availability not included)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"sberbank\", outcome=\"SERVER_ERROR\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\", uri!=\"/availability\"}[5m])/3.33))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "3", "legendFormat": "alert" }
   ]
  },
  { "title": "Simulation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Simulation response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"simulation\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{service=\"simulation\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "0.4", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Simulation 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"simulation\", outcome=\"SERVER_ERROR\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[5m])/3.33))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1", "legendFormat": "alert" }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Tasks response time (NOT POST /task)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"tasks\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\", uri!=\"/v1/task\"}[15m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"tasks\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\", uri!=\"/v1/task\"}[15m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "3.5", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Tasks response time (POST /task)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"tasks\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\", uri=\"/v1/task\"}[15m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"tasks\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\", uri=\"/v1/task\"}[15m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "5", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Tasks 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"tasks\", outcome=\"SERVER_ERROR\"}[1m])/6.66))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1", "legendFormat": "alert" }
   ]
  },
  { "title": "Tp-net-interaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Tp-net-interaction response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"tp-net-interaction\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[15m])) / sum by (namespace, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"tp-net-interaction\", exception=\"None\", uri!~\"/actuator.*|.*api-docs.*|.*swagger.*|/metrics|.*webjars.*\"}[15m]))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "3", "legendFormat": "alert" }
   ]
  },
  {
   "title": "Tp-net-interaction 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, method, uri) (round(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"tp-net-interaction\", outcome=\"SERVER_ERROR\"}[1m])/6.66))",
     "legendFormat": "{{method}} {{uri}}"
    },
    { "expr": "1", "legendFormat": "alert" }
   ]
  }
 ]
}