{
 "title": "PaymentBrick - conversion RU/KZ",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "window", "label": "window", "query": "5m,10m,30m,1h,6h,12h,1d" },
   {
    "name": "service",
    "query": {
     "query": "label_values(created_payment_instruments_total,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Payment Instrument", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Payment Instrument (period $window)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(paymentInstrument)(increase(success_payments_total{service=~\"sberbank-interaction|brs-interaction\",paymentInstrument=\"BANK_CARD\"}[$window])) \r\n/ sum by(paymentInstrument)(increase(created_payment_instruments_total {service=~\"sberbank-interaction|brs-interaction\",paymentInstrument=\"BANK_CARD\"}[$window]  offset 5m))",
     "legendFormat": "Банк «Русский стандарт» - банковская карта"
    },
    {
     "expr": "sum by(paymentInstrument)(increase(success_payments_total{service=~\"kaspi-interaction\",paymentInstrument=\"BANK_CARD\"}[$window])) \r\n/ sum by(paymentInstrument)(increase(created_payment_instruments_total {service=~\"kaspi-interaction\",paymentInstrument=\"BANK_CARD\"}[$window]  offset 5m))",
     "legendFormat": " Kaspi bank - банковская карта"
    },
    {
     "expr": "sum by(paymentInstrument)(increase(success_payments_total{service=~\"halyk-interaction\",paymentInstrument=\"BANK_CARD\"}[$window])) \r\n/ sum by(paymentInstrument)(increase(created_payment_instruments_total {service=~\"halyk-interaction\",paymentInstrument=\"BANK_CARD\"}[$window]  offset 5m))",
     "legendFormat": " Halyk bank - банковская карта"
    }
   ]
  },
  {
   "title": "Payment Instrument (period $window)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(paymentInstrument)(increase(success_payments_total{service=~\"sberbank-interaction|brs-interaction\"}[$window])) \r\n/ sum by(paymentInstrument)(increase(created_payment_instruments_total {service=~\"sberbank-interaction|brs-interaction\"}[$window] offset 5m))",
     "legendFormat": "Банк «Русский стандарт» - банковская карта"
    },
    {
     "expr": "sum by(paymentInstrument)(increase(success_payments_total{service=\"kaspi-interaction\"}[$window])) \r\n/ sum by(paymentInstrument)(increase(created_payment_instruments_total {service=\"kaspi-interaction\"}[$window] offset 5m))",
     "legendFormat": "Kaspi bank - банковская карта"
    },
    {
     "expr": "sum by(paymentInstrument)(increase(success_payments_total{service=\"halyk-interaction\"}[$window])) \r\n/ sum by(paymentInstrument)(increase(created_payment_instruments_total {service=\"halyk-interaction\"}[$window] offset 5m))",
     "legendFormat": "Halyk bank - банковская карта"
    }
   ]
  },
  { "title": "Channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Channel (period $window)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(channel)(increase(success_payments_total{service=~\"sberbank-interaction|brs-interaction\", channel=\"MARKETPLACE\",}[$window])) \r\n/ sum by(channel)(increase(created_payment_instruments_total {service=~\"sberbank-interaction|brs-interaction\", channel=\"MARKETPLACE\"}[$window] offset 5m))",
     "legendFormat": "Банк «Русский стандарт» - {{channel}} $window"
    },
    {
     "expr": "sum by(channel)(increase(success_payments_total{service=~\"sberbank-interaction|brs-interaction\", channel=\"SOLUTION\"}[$window])) \r\n/ sum by(channel)(increase(created_payment_instruments_total {service=~\"sberbank-interaction|brs-interaction\", channel=\"SOLUTION\"}[$window]))",
     "legendFormat": "Банк «Русский стандарт» - {{channel}} $window"
    },
    {
     "expr": "sum by(channel)(increase(success_payments_total{service=\"kaspi-interaction\", channel=\"SOLUTION\"}[$window])) \r\n/ sum by(channel)(increase(created_payment_instruments_total {service=\"kaspi-interaction\", channel=\"SOLUTION\"}[$window]))",
     "legendFormat": " Kaspi bank - {{channel}} $window"
    },
    {
     "expr": "sum by(channel)(increase(success_payments_total{service=\"halyk-interaction\", channel=\"SOLUTION\"}[$window])) \r\n/ sum by(channel)(increase(created_payment_instruments_total {service=\"halyk-interaction\", channel=\"SOLUTION\"}[$window]))",
     "legendFormat": "Halyk bank - {{channel}} $window"
    }
   ]
  },
  {
   "title": "Channel (period $window)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(channel)(increase(success_payments_total{service=~\"sberbank-interaction|brs-interaction\"}[$window])) \r\n/ sum by(channel)(increase(created_payment_instruments_total {service=~\"sberbank-interaction|brs-interaction\"}[$window] offset 5m))",
     "legendFormat": "Банк «Русский стандарт» - {{channel}}"
    },
    {
     "expr": "sum by(channel)(increase(success_payments_total{service=\"kaspi-interaction\"}[$window])) \r\n/ sum by(channel)(increase(created_payment_instruments_total {service=\"kaspi-interaction\"}[$window] offset 5m))",
     "legendFormat": " Kaspi bank - {{channel}}"
    },
    {
     "expr": "sum by(channel)(increase(success_payments_total{service=\"halyk-interaction\"}[$window])) \r\n/ sum by(channel)(increase(created_payment_instruments_total {service=\"halyk-interaction\"}[$window] offset 5m))",
     "legendFormat": " Halyk bank - {{channel}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Count created orders (period $window)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(created_payment_instruments_total{namespace=\"payment-pon-prod\", service=\"brs-interaction\"}[$window]))",
     "legendFormat": "Банк «Русский стандарт»"
    },
    {
     "expr": "sum(increase(created_payment_instruments_total{namespace=\"payment-pon-prod\", service=\"kaspi-interaction\"}[$window]))",
     "legendFormat": "Kaspi Bank"
    },
    {
     "expr": "sum(increase(created_payment_instruments_total{namespace=\"payment-pon-prod\", service=\"halyk-interaction\"}[$window]))",
     "legendFormat": "Halyk Bank"
    }
   ]
  },
  {
   "title": "Count created orders (period $window)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(created_payment_instruments_total{namespace=\"payment-pon-prod\", service=\"brs-interaction\"}[$window]))",
     "legendFormat": "Банк «Русский стандарт»"
    },
    {
     "expr": "sum(increase(created_payment_instruments_total{namespace=\"payment-pon-prod\", service=\"kaspi-interaction\"}[$window]))",
     "legendFormat": "Kaspi Bank"
    },
    {
     "expr": "sum(increase(created_payment_instruments_total{namespace=\"payment-pon-prod\", service=\"halyk-interaction\"}[$window]))",
     "legendFormat": "Halyk Bank"
    }
   ]
  },
  {
   "title": "Распределение времени оплаты(%)  для $service  (period $window)",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(success_payments_seconds_bucket{service=~\"$service\"}[$window]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Распределение времени оплаты (кол-во) для $service (period $window)",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 17, "x": 7, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(success_payments_seconds_bucket{service=~\"$service\"}[$window]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}