{
 "title": "Sberbank",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "merchant",
    "query": {
     "query": "label_values(http_client_requests_process_payment_seconds_count,merchant)"
    }
   },
   {
    "name": "paymentInstrument",
    "query": {
     "query": "label_values(http_client_requests_process_payment_seconds_count,paymentInstrument)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "gauge",
   "description": "Доступность",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_process_payment_seconds_count{status!~\"5..\"}[$__range:])) by (paymentInstrument) / sum(increase(http_client_requests_process_payment_seconds_count[$__range:])) by (paymentInstrument)",
     "legendFormat": "{{paymentInstrument}}"
    }
   ]
  },
  {
   "title": "99 percentile",
   "type": "gauge",
   "description": "99 percentile",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_process_payment_seconds_bucket[$__range:])) by (le, paymentInstrument))",
     "legendFormat": "{{paymentInstrument}}"
    }
   ]
  },
  {
   "title": "Response Statuses [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_process_payment_seconds_count[5m])) by (status) / scalar(sum(increase(http_client_requests_process_payment_seconds_count[5m])) by (service))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "$merchant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "merchant" },
  {
   "title": "Availability",
   "type": "gauge",
   "description": "Доступность",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_process_payment_seconds_count{status!~\"5..\", merchant=\"$merchant\"}[$__range:])) by (paymentInstrument) / sum(increase(http_client_requests_process_payment_seconds_count{merchant=\"$merchant\"}[$__range:])) by (paymentInstrument)",
     "legendFormat": "{{paymentInstrument}}"
    }
   ]
  },
  {
   "title": "99 percentile",
   "type": "gauge",
   "description": "99 percentile",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_requests_process_payment_seconds_bucket{merchant=\"$merchant\"}[$__range:])) by (le, paymentInstrument))",
     "legendFormat": "{{paymentInstrument}}"
    }
   ]
  },
  {
   "title": "Response Statuses [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_process_payment_seconds_count{merchant=\"$merchant\"}[5m])) by (status) / scalar(sum(increase(http_client_requests_process_payment_seconds_count{merchant=\"$merchant\"}[5m])) by (service))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}