{
 "title": "CSI транзакционная активность",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "window", "label": "window", "query": "1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Транзакционная активность РФ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count by paymenttype % for $window",
   "type": "stat",
   "gridPos": { "h": 22, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='009',methods=\"BANK_CARD\"}[$window])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='009'}[$window]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='009',methods=\"GIFT_CARD\"}[$window])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='009'}[$window]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='009',methods=\"JURISTIC\"}[$window])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='009'}[$window]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='009',methods=\"CASH\"}[$window])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='009'}[$window]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='009',methods=\"CREDIT\"}[$window])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='009'}[$window]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Count by paymenttype % 5m",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='009'}[5m])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='009'}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Транзакционная активность КЗ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Count by paymenttype % for $window",
   "type": "stat",
   "gridPos": { "h": 22, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='040',methods=\"BANK_CARD\"}[$window])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='040'}[$window]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='040',methods=\"BANK_CARD_OFFLINE\"}[$window])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='040'}[$window]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='040',methods=\"JURISTIC\"}[$window])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='040'}[$window]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='040',methods=\"CASH\"}[$window])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='040'}[$window]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='040',methods=\"CREDIT\"}[$window])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='040'}[$window]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Count by paymenttype % for 5m",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 21, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_offline_operations_count{bu='040'}[5m])) by (methods) / ignoring (methods) group_left sum(sum_over_time(csi_offline_operations_count{bu='040'}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}