{
 "title": "CSI эквайринг",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(csi_bankcardpayment_count, namespace)"
    }
   },
   {
    "name": "bank",
    "query": {
     "query": "label_values(csi_bankcardpayment_count{namespace=\"$namespace\"}, bankid)"
    }
   },
   {
    "name": "store",
    "query": {
     "query": "label_values(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\"}, store)"
    }
   },
   {
    "name": "ok_response",
    "query": "0|000|2000|4451|2002|4455|4457|362|4132|4117|4405|4412|4414|4461|4462|4362|4322|4475|4465|4407|4454|99|2004|4134"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability[range]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\", responsecode=~\"$ok_response\"}[$__range])) by (bankid) / sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\",bankid=~\"$bank\", store=~\"$store\"}[$__range])) by (bankid)",
     "legendFormat": "{{bankid}}"
    }
   ]
  },
  {
   "title": "Availability[range]",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\", responsecode=~\"$ok_response\"}[$__range])) by (bankid) / sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\",bankid=~\"$bank\", store=~\"$store\"}[$__range])) by (bankid)",
     "legendFormat": "{{bankid}}"
    }
   ]
  },
  {
   "title": "Top 10 stores",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\"}[$__range])) by (store))",
     "legendFormat": "{{store}}"
    }
   ]
  },
  {
   "title": "Responses by name",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\"}[$__range])) by (message)",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "success/fail",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\"}[$__interval])) - sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\", responsecode=~\"$ok_response\"}[$__interval]))",
     "legendFormat": "fail"
    },
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\", responsecode=~\"$ok_response\"}[$__interval]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "By response error code count  [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\", responsecode!~\"0|000\"}[1m])) by (responsecode,store) > 0",
     "legendFormat": "Магазин: {{store}} - код ошибки: {{responsecode}}"
    }
   ]
  },
  {
   "title": "By response error code count  [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\", responsecode!~\"0|000\"}[1m])) by (responsecode,cardtype) > 0",
     "legendFormat": "{{cardtype}} - код ошибки: {{ responsecode}}"
    }
   ]
  },
  { "title": "Платёжные системы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Count by card type %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\"}[$__interval])) by (cardtype) / ignoring (cardtype) group_left sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\"}[$__interval]))",
     "legendFormat": "{{cardtype}}"
    }
   ]
  },
  {
   "title": "Count by card type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\"}[$__interval])) by (cardtype)",
     "legendFormat": "{{cardtype}}"
    }
   ]
  },
  {
   "title": "Count by bank %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\"}[$__interval])) by (bankid) / ignoring (bankid) group_left sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\"}[$__interval]))",
     "legendFormat": "{{bankid}}"
    }
   ]
  },
  {
   "title": "Count by bank",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(csi_bankcardpayment_count{namespace=\"$namespace\", bankid=~\"$bank\", store=~\"$store\"}[$__interval])) by (bankid)",
     "legendFormat": "{{bankid}}"
    }
   ]
  }
 ]
}