{
 "title": "POS Data Integration Service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(export_seconds_bucket, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(export_seconds_bucket{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "import",
    "query": {
     "query": "label_values(import_seconds_count{namespace=\"$namespace\", service=\"$service\"}, type)"
    }
   },
   {
    "name": "export",
    "query": {
     "query": "label_values(export_seconds_bucket{namespace=\"$namespace\", service=\"$service\"}, type)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "$import", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "import" },
  {
   "title": "Обработано",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Latency 99 [5m]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(import_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[5m])) by (le, type))"
    }
   ]
  },
  {
   "title": "Latency 99 [1d]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(import_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[1d])) by (le, type))"
    }
   ]
  },
  {
   "title": "Latency 99 [7d]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(import_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[7d])) by (le, type))"
    }
   ]
  },
  {
   "title": "SLO [5m]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum (increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\", status=~\"5..\"}[5m])) > 0 or vector(0)) / (sum (increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[5m])) > 0 or vector(1))"
    }
   ]
  },
  {
   "title": "SLO [1d]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum (increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\", status=~\"5..\"}[1d])) > 0 or vector(0)) / (sum (increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[1d])) > 0 or vector(1))"
    }
   ]
  },
  {
   "title": "SLO [7d]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum (increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\", status=~\"5..\"}[7d])) > 0 or vector(0)) / (sum (increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[7d])) > 0 or vector(1))"
    }
   ]
  },
  {
   "title": "SLO [30d]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum (increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\", status=~\"5..\"}[30d])) > 0 or vector(0)) / (sum (increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[30d])) > 0 or vector(1))"
    }
   ]
  },
  {
   "title": "RPS[$interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Response Status Ratio [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (status) (increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[$interval])) / scalar(sum by (service) (increase(import_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[$interval])))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency[$interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(import_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[$interval])) by (le, type))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(import_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[$interval])) by (le, type))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(import_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$import\"}[$interval])) by (le, type))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "$export", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "export" },
  {
   "title": "Обработано",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Latency 99 [5m]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(export_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[5m])) by (le, type))"
    }
   ]
  },
  {
   "title": "Latency 99 [1d]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(export_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[1d])) by (le, type))"
    }
   ]
  },
  {
   "title": "Latency 99 [7d]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(export_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[7d])) by (le, type))"
    }
   ]
  },
  {
   "title": "SLO [5m]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum (increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\", status=~\"5..\"}[5m])) > 0 or vector(0)) / (sum (increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[5m])) > 0 or vector(1))"
    }
   ]
  },
  {
   "title": "SLO [1d]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum (increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\", status=~\"5..\"}[1d])) > 0 or vector(0)) / (sum (increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[1d])) > 0 or vector(1))"
    }
   ]
  },
  {
   "title": "SLO [7d]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum (increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\", status=~\"5..\"}[7d])) > 0 or vector(0)) / (sum (increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[7d])) > 0 or vector(1))"
    }
   ]
  },
  {
   "title": "SLO [30d]",
   "type": "stat",
   "description": "Количество обработанных транзакций за выбранный интервал",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum (increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\", status=~\"5..\"}[30d])) > 0 or vector(0)) / (sum (increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[30d])) > 0 or vector(1))"
    }
   ]
  },
  {
   "title": "RPS[$interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[$interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Response Status Ratio [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (status) (increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[$interval])) / scalar(sum by (service) (increase(export_seconds_count{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[$interval])))",
     "legendFormat": "{{ status }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency[$interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(export_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[$interval])) by (le, type))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(export_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[$interval])) by (le, type))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(export_seconds_bucket{namespace=\"$namespace\", service=\"$service\", type=\"$export\"}[$interval])) by (le, type))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}