{
 "title": "DAM Custom New",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(renaming_queue_processed_assets, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Битрикс", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Экспортировано ассетов в Битрикс",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Ассеты / 5 мин" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, mediaType) (rate(exported_to_main_ftp_bitrix_assets_count{namespace=\"$namespace\"}[5m])*60*5)",
     "legendFormat": "{{mediaType}}"
    }
   ]
  },
  { "title": "OPUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Экспортированно в Opus ассетов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Ассеты / 5 мин" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, mediaType) (rate(exported_to_opus_assets_count{namespace=\"$namespace\"}[5m])*60*5)",
     "legendFormat": "{{mediaType}}"
    }
   ]
  },
  { "title": "Импорт", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Продолжительность загрузки по стадиям",
   "type": "graph",
   "description": "Время проведенное в каждом состоянии загрузки",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "секунды" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, state) (rate(dam_import_state_changed_milliseconds_bucket_sum{namespace=\"$namespace\"}[1m]))/sum by (namespace, state) (rate(dam_import_state_changed_milliseconds_bucket_count{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "dam_import_duration_second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "секунды" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(dam_import_duration_seconds_bucket_sum{namespace=\"$namespace\"}[1m]))/sum by (namespace) (rate(dam_import_duration_seconds_bucket_count{namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Загрузка ассетов по типам",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Ассеты / 5 мин" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, mediaType) (rate(dam_import_assets_uploaded{namespace=\"$namespace\"}[5m])*60*5)",
     "legendFormat": "{{mediaType}}"
    }
   ]
  },
  { "title": "Общее", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Созданно ассетов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Ассеты / 5 мин" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, mediaType) (rate(dam_assets_created{namespace=\"$namespace\"}[5m])*60*5)",
     "legendFormat": "{{mediaType}}"
    }
   ]
  },
  {
   "title": "Созданно/обновлено товаров",
   "type": "graph",
   "description": "интеграция с сервисом продуктов",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Товары / 5 мин" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(dam_products_processed_messages{namespace=\"$namespace\"}[5m])*5*60)",
     "legendFormat": "товары"
    }
   ]
  },
  {
   "title": "Полнотекстовой индекс для товаров",
   "type": "stat",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(dam_total_products{namespace=\"$namespace\", container=\"dam-validation\"})",
     "legendFormat": "всего товаров"
    },
    {
     "expr": "max(dam_products_indexed{namespace=\"$namespace\", container=\"dam-validation\"})",
     "legendFormat": "Товаров, обработанных с начала полнотекстового индексирования"
    },
    {
     "expr": "max(dam_products_indexing_failed{namespace=\"$namespace\", container=\"dam-validation\"})",
     "legendFormat": "Товаров, для которых полнотекстовый поиск не выявил индекса"
    },
    {
     "expr": "max(dam_products_indexing_pending{namespace=\"$namespace\", container=\"dam-validation\"})",
     "legendFormat": "Количество ожидающих отслеженных изменений к обработке"
    }
   ]
  },
  { "title": "PIM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Созданно/обновленно ассетов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Ассеты / час" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(dam_pim_processed_messages{namespace=\"$namespace\"}[1h])*60*60)"
    }
   ]
  },
  { "title": "Очередь переименования", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Динамика переименования",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "Ассеты / 5 мин" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(renaming_queue_processed_assets{namespace=\"$namespace\"}[5m])*5*60)",
     "legendFormat": "ассеты"
    }
   ]
  },
  {
   "title": "Текущее состояние",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "Количество" }
   ],
   "targets": [
    {
     "expr": "sum(renaming_queue_waiting{namespace=\"$namespace\"})",
     "legendFormat": "in queue"
    },
    {
     "expr": "sum(renaming_queue_failed{namespace=\"$namespace\"})",
     "legendFormat": "error items"
    }
   ]
  },
  {
   "title": "Количество проблемных ассетов",
   "type": "gauge",
   "description": "Не получилось переименовать за 3 попытки",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(renaming_queue_failed{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Ассетов в ожидании переименования",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(renaming_queue_waiting{namespace=\"$namespace\"})"
    }
   ]
  }
 ]
}