{
 "title": "Business Trips. Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kube_service_info{service=~\"businesstrips-advancereport.*\"}, namespace)"
   },
   {
    "name": "service",
    "query": "label_values(kube_service_info{service=~\"businesstrips-advancereport.*\", namespace=~\"$namespace\"}, service)"
   },
   { "name": "locale", "label": "locale", "query": "rus,pro,kaz" },
   {
    "name": "svc_ao",
    "query": "label_values(kube_service_info{service=~\"businesstrips-advancereport-webapi-$locale\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "svc_ones",
    "query": "label_values(kube_service_info{service=~\"businesstrips-integrationto1c-web-api-$locale\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "svc_ones_consumer",
    "query": "label_values(mt_consume_duration_seconds_bucket{namespace=~\"$namespace\", service_name=~\"businesstrips-integrationto1c-consumer-$locale\"}, service_name)"
   }
  ]
 },
 "panels": [
  { "title": "Сервис Авансовых Отчётов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Создано отчетов",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (service) \n(\nincrease(trips_ao_create_report_command_count{service=\"$svc_ao\", namespace=\"$namespace\", status=\"ok\"}[$__range])\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (service) \n(\nincrease(trips_ao_create_report_command_count{service=\"$svc_ao\", namespace=\"$namespace\", status=\"error\"}[$__range])\n)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum by (service) \n(\nincrease(trips_ao_create_report_command_count{service=\"$svc_ao\", namespace=\"$namespace\", status=\"warning\"}[$__range])\n)",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Отправленно на согласование",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (service) \n(\nincrease(trips_ao_send_report_to_approve_command_count{service=\"$svc_ao\", namespace=\"$namespace\", status=\"ok\"}[$__range])\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (service) \n(\nincrease(trips_ao_send_report_to_approve_command_count{service=\"$svc_ao\", namespace=\"$namespace\", status=\"error\"}[$__range])\n)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum by (service) \n(\nincrease(trips_ao_send_report_to_approve_command_count{service=\"$svc_ao\", namespace=\"$namespace\", status=\"warning\"}[$__range])\n)",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Отчётов в Outbox",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (trips_ao_outbox_deferred_events{service=\"$svc_ao\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Dispatcher Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (trips_ao_dispatcher_in_active{service=\"$svc_ao\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Создано авансовых отчётов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, status) \n(\nrate(trips_ao_create_report_command_count{service=\"$svc_ao\", namespace=\"$namespace\"}[$__rate_interval])*90\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Отчётов отправленных на согласование",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, status) \n(\nrate(trips_ao_send_report_to_approve_command_count{service=\"$svc_ao\", namespace=\"$namespace\"}[$__rate_interval])*90\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Сервис интеграции с 1С", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Подписанных отчётов согласующими",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (service) \n(\nincrease(trips_1c_sign_advance_report_by_approver_command_count{service=\"$svc_ones\", namespace=\"$namespace\", status=\"ok\"}[$__range])\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (service) \n(\nincrease(trips_1c_sign_advance_report_by_approver_command_count{service=\"$svc_ones\", namespace=\"$namespace\", status=\"error\"}[$__range])\n)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum by (service) \n(\nincrease(trips_1c_sign_advance_report_by_approver_command_count{service=\"$svc_ones\", namespace=\"$namespace\", status=\"warning\"}[$__range])\n)",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Подписанных отчётов согласующими",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, status) \n(\nrate(trips_1c_sign_advance_report_by_approver_command_count {service=\"$svc_ones\", namespace=\"$namespace\"}[$__rate_interval])*90\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Подписанных отчётов сотрудниками",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (service) \n(\nincrease(trips_1c_sign_advance_report_command_count{service=\"$svc_ones\", namespace=\"$namespace\", status=\"ok\"}[$__range])\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (service) \n(\nincrease(trips_1c_sign_advance_report_command_count{service=\"$svc_ones\", namespace=\"$namespace\", status=\"error\"}[$__range])\n)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum by (service) \n(\nincrease(trips_1c_sign_advance_report_command_count{service=\"$svc_ones\", namespace=\"$namespace\", status=\"warning\"}[$__range])\n)",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Подписанных отчётов сотрудниками",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, status) \n(\nrate(trips_1c_sign_advance_report_command_count {service=\"$svc_ones\", namespace=\"$namespace\"}[$__rate_interval])*90\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cозданных печатных версий отчетов",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (container) \n(\nincrease(trips_1c_advance_report_print_ver_created{container=\"$svc_ones_consumer\", namespace=\"$namespace\", status=\"ok\"}[$__range])\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (container) \n(\nincrease(trips_1c_advance_report_print_ver_created{container=\"$svc_ones_consumer\", namespace=\"$namespace\", status=\"warning\"}[$__range])\n)",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum by (container) \n(\nincrease(trips_1c_advance_report_print_ver_created{container=\"$svc_ones_consumer\", namespace=\"$namespace\", status=\"error\"}[$__range])\n)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Cозданных печатных версий отчетов",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container, status) \n(\nrate(trips_1c_advance_report_print_ver_created {container=\"$svc_ones_consumer\", namespace=\"$namespace\"}[$__rate_interval])*90\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Созданных АО в базе 1С",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (container) \n(\nincrease(trips_1c_advance_report_created_in_1c_db {container=\"$svc_ones_consumer\", namespace=\"$namespace\", status=\"ok\"}[$__range])\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (container) \n(\nincrease(trips_1c_advance_report_created_in_1c_db {container=\"$svc_ones_consumer\", namespace=\"$namespace\", status=\"warning\"}[$__range])\n)",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum by (container) \n(\nincrease(trips_1c_advance_report_created_in_1c_db {container=\"$svc_ones_consumer\", namespace=\"$namespace\", status=\"error\"}[$__range])\n)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Созданных АО в базе 1С",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container, status) \n(\nrate(trips_1c_advance_report_created_in_1c_db{container=\"$svc_ones_consumer\", namespace=\"$namespace\"}[$__rate_interval])*90\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Директум", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Выгружено отчётов в Директум",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (container) \n(\nincrease(trips_directum_processed_reports_count {container=\"directum-consumer\", namespace=\"$namespace\", locale=\"$locale\"}[$__range])\n)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (container) \n(\nincrease(trips_directum_errors_count{container=\"directum-consumer\", namespace=\"$namespace\", locale=\"$locale\"}[$__range])\n)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Выгрузка в Directum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (rate(trips_directum_processed_reports_count{locale=\"$locale\"}[$__rate_interval]))*90",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (container) (rate(trips_directum_errors_count{locale=\"$locale\"}[$__rate_interval]))*90",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}