{
 "title": "LYS-LOAD",
 "time": { "from": "2022-07-06T08:35:04.000Z", "to": "2022-07-06T09:50:04.000Z" },
 "templating": {
  "list": [
   { "name": "SimulationSuccessFailure", "query": "SHOW measurements" },
   { "name": "Duration", "query": "SHOW MEASUREMENTS" }
  ]
 },
 "panels": [
  { "title": "Main (RPS-Request Time)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS (Request per Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "All RPS",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$SimulationSuccessFailure$/",
     "query": "SELECT count(\"value\") AS \"rps\" FROM /^$Measurement$/ WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "description": "Grouped by 1 sec intervals",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Duration$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percentile 95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P(95)",
     "measurement": "http_req_duration",
     "query": "SELECT percentile(\"value\", 95) FROM \"http_req_duration\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percentile 90",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P(90)",
     "measurement": "http_req_duration",
     "query": "SELECT percentile(\"value\", 90) FROM \"http_req_duration\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percentile 99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "P(99)",
     "measurement": "http_req_duration",
     "query": "SELECT percentile(\"value\", 50) FROM \"http_req_duration\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Duration Capacity",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 15, "x": 0, "y": 25 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Propotion",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 9, "x": 15, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$m",
       "measurement": "/^$SimulationSuccessFailure$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET By Customer Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(95)",
       "measurement": "getByCustomerNumberDuration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET By Customer Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(90)",
       "measurement": "getByCustomerNumberDuration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET By Customer Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(99)",
       "measurement": "getByCustomerNumberDuration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "99" ], "type": "percentile" }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET By Card Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(95)",
       "measurement": "getByCardNumberDuration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET By Card Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(90)",
       "measurement": "getByCardNumberDuration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET By Card Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(99)",
       "measurement": "getByCardNumberDuration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "99" ], "type": "percentile" }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET By Customer Duration 404",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(95)",
       "measurement": "getByCustomerNumber404Duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET By Customer Duration 404",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(90)",
       "measurement": "getByCustomerNumber404Duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET By Customer Duration 404",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(99)",
       "measurement": "getByCustomerNumber404Duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         { "params": [ "99" ], "type": "percentile" }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET History",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(95)",
       "measurement": "getHistoryByCardNumberDuration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GET History 404",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(95)",
       "measurement": "getHistoryByCardNumber404Duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Create Account",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "P(95)",
       "measurement": "createAccountDuration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Additional info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Number of Iterations",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Requests",
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$SimulationSuccessFailure$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "errors400th",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "measurement": "errors500th",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request blocked time (95%ile)",
   "type": "graph",
   "description": "Time spent blocked (waiting for a free TCP connection slot) before initiating the request",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_req_blocked",
     "query": "SELECT percentile(\"value\", 95) FROM \"http_req_blocked\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  }
 ]
}