{
 "title": "Processed communications (Detail)",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(processed_communications_total, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(processed_communications_total{namespace=\"$Namespace\"}, service)"
    }
   },
   {
    "name": "Communication",
    "query": {
     "query": "label_values(processed_communications_total{namespace=\"$Namespace\", service=~\"$Service\"}, communication_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total communications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(processed_communications_total{namespace=\"$Namespace\", status=\"success\"}[1m])) * 100 / sum(increase(processed_communications_total{namespace=\"$Namespace\"}[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(processed_communications_total{namespace=\"$Namespace\", status=\"error\"}[1m])) * 100 / sum(increase(processed_communications_total{namespace=\"$Namespace\"}[1m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "$Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "repeat": "Service",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(processed_communications_total{namespace=\"$Namespace\", service=\"$Service\", status=\"success\"}[1m])) * 100 / sum(increase(processed_communications_total{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(processed_communications_total{namespace=\"$Namespace\", service=\"$Service\", status=\"error\"}[1m])) * 100 / sum(increase(processed_communications_total{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "$Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Success",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (communication_name, channel) (increase(processed_communications_total{namespace=\"$Namespace\", service=\"$Service\", communication_name=~\"$Communication\", status=\"success\"}[1m])) OR on() vector(0)",
       "legendFormat": "{{communication_name}} {{channel}}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum by (communication_name, channel) (increase(processed_communications_total{namespace=\"$Namespace\", service=\"$Service\", communication_name=~\"$Communication\", status=\"error\"}[1m])) OR on() vector(0)",
       "legendFormat": "{{communication_name}} {{channel}}"
      }
     ]
    }
   ]
  },
  { "title": "Overall communications table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Communications activity",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (service, communication_name, channel) (increase(processed_communications_total{namespace=~\"$Namespace\", service=~\"$Service\", communication_name=~\"$Communication\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}