{
 "title": "Repository Factory Dashboards all",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(repository_factory_info, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(repository_factory_info{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(repository_factory_info{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node.js Version",
   "type": "stat",
   "description": "The version of Node.js.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Node.js Restarts",
   "type": "stat",
   "description": "The number of times Node.js restarted.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\", service=\"$service\"}[$__range]))",
     "legendFormat": "Node.js"
    }
   ]
  },
  {
   "title": "Repository Factory Version",
   "type": "stat",
   "description": "The version of Repository Factory.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "repository_factory_info{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "stat",
   "description": "The number of processed messages for selected time range",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((increase(kafka_processed_messages{namespace=~\"$namespace\", service=\"$service\"}[$__range])) or vector(0)) + sum((increase(requests_counter{namespace=~\"$namespace\", service=\"$service\", baseUrl=~\"/documents.*\"}[$__range])) or vector(0))"
    }
   ]
  },
  {
   "title": "Delivery Queue",
   "type": "stat",
   "description": "Количество документов в очереди на доставку",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delivery_queue_length{namespace=~\"$namespace\", collection=\"documents.output\", service=\"$service\"})",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Discards Queue",
   "type": "stat",
   "description": "Количество дискардов ожидающих подтверждения доставки",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delivery_queue_length{namespace=~\"$namespace\", collection=\"discards.output\", service=\"$service\"})",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Kafka Lag Offset",
   "type": "stat",
   "description": "Kafka lag offset",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kafka_high_offset{namespace=\"$namespace\", service=\"$service\"}) by (topic, partition) - max(kafka_current_offset{namespace=\"$namespace\", service=\"$service\"}) by (topic, partition)) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Kafka stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Kafka Messages [$interval]",
   "type": "timeseries",
   "description": "Количество сообщений в кафке",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_processed_messages{namespace=\"$namespace\", service=\"$service\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum(rate(kafka_delivered_messages_count{namespace=\"$namespace\", service=\"$service\"}[$interval]))",
     "legendFormat": "delivered"
    }
   ]
  },
  {
   "title": "By statuses [1m]",
   "type": "timeseries",
   "description": "% соотношение по статусам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_processed_messages{namespace=\"$namespace\", service=\"$service\"}[$interval])) by (status) / scalar(sum(increase(kafka_processed_messages{namespace=\"$namespace\",  service=\"$service\"}[$interval])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Kafka Lag Offset",
   "type": "graph",
   "description": "Kafka Lag Offset",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(max(kafka_high_offset{namespace=\"$namespace\", service=\"$service\"}) by (topic, partition) - max(kafka_current_offset{namespace=\"$namespace\", service=\"$service\"}) by (topic, partition)) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Http requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "HTTP Request [$interval]",
   "type": "graph",
   "description": "rps http запросов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", url=~\"/schema.*|/documents.*|discards.*\", service=\"$service\"}[$interval])) by (url, method)",
     "legendFormat": "{{method}} - {{url}}"
    }
   ]
  },
  {
   "title": "HTTP Request Statuses [$interval]",
   "type": "graph",
   "description": "% соотношение по статусам ответа",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", url=~\"/schema.*|/documents.*|discards.*\", service=\"$service\"}[$interval])) by (status) /  scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", url=~\"/schema.*|/documents.*|discards.*\", service=\"$service\"}[$interval])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Request Time [$interval]",
   "type": "graph",
   "description": "время ответа - p95 и среднее значение",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\", url=~\"/schema.*|/documents.*|discards.*\"}[$interval])) by (url, le))",
     "legendFormat": "{{url}} - p95"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\", url=~\"/schema.*|/documents.*|discards.*\"}[1m])) by (url)/sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\", url=~\"/schema.*|/documents.*|discards.*\"}[$interval])) by (url)",
     "legendFormat": "{{url}} - avg"
    }
   ]
  },
  { "title": "Repository Factory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Delivery Time [$interval]",
   "type": "graph",
   "description": "Время подтвержденной доставки в исходящую кафку",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_delivery_time_bucket{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\"}[$interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "sum(rate(kafka_delivery_time_sum{namespace=\"$namespace\", pod=~\"$pod\"}[$interval]))/sum(rate(kafka_delivery_time_count{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Delivery Queue",
   "type": "graph",
   "description": "Количество документов и дискардов в очереди на доставку",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(delivery_queue_length{namespace=\"$namespace\", service=\"$service\"}) by (collection)",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Delivery Queue Longer 5m",
   "type": "graph",
   "description": "Количество документов и дискардов в очереди на доставку дольше 5м",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(delivery_lag_count{namespace=\"$namespace\", service=\"$service\"}) by (collection)",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  { "title": "MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Transaction Time [$interval]",
   "type": "graph",
   "description": "Время батч транзакции",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mongodb_transaction_time_bucket{namespace=\"$namespace\", service=\"$service\"}[$interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "sum(rate(mongodb_transaction_time_sum{namespace=\"$namespace\", service=\"$service\"}[$interval]))/sum(rate(mongodb_transaction_time_count{namespace=\"$namespace\", service=\"$service\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Batch Count [$interval]",
   "type": "graph",
   "description": "Количество сообщений в батче",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_batch_counter{namespace=\"$namespace\", service=\"$service\"}[$interval]))",
     "legendFormat": "batch"
    }
   ]
  },
  {
   "title": "Aborted Transaction [$interval]",
   "type": "graph",
   "description": "Количество ошибочных запросов",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_aborted_transaction_counter{namespace=\"$namespace\", service=\"$service\"}[$interval]))",
     "legendFormat": "aborted"
    }
   ]
  },
  {
   "title": "Transaction Time [$interval] on $pod",
   "type": "graph",
   "description": "Время батч транзакции",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "repeat": "pod",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mongodb_transaction_time_bucket{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\"}[$interval])) by (le, pod))",
     "legendFormat": "p95"
    },
    {
     "expr": "sum(rate(mongodb_transaction_time_sum{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\"}[$interval]))/sum(rate(mongodb_transaction_time_count{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Batch Count [$interval] on $pod",
   "type": "graph",
   "description": "Количество сообщений в батче",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
   "repeat": "pod",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_batch_counter{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "batch"
    }
   ]
  },
  {
   "title": "Aborted Transaction [$interval] on $pod",
   "type": "graph",
   "description": "Количество ошибочных запросов",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
   "repeat": "pod",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_aborted_transaction_counter{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "aborted"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) * 100",
     "legendFormat": "User CPU - {{pod}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) * 100",
     "legendFormat": "System CPU - {{pod}}"
    },
    {
     "expr": "irate(process_cpu_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\"}[1m]) * 100",
     "legendFormat": "Total CPU - {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Time Spent",
   "type": "graph",
   "description": "CPU time spent.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Process Memory - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Heap Total - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Heap Used - {{pod}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "External Memory - {{pod}}"
    }
   ]
  },
  {
   "title": "Active Handlers and Requests",
   "type": "graph",
   "description": "Number of active handle and active requests.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Active Handler - {{pod}}"
    },
    {
     "expr": "nodejs_active_requests_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Active Request - {{pod}}"
    }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "graph",
   "description": "Latency of the event loop.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Last - {{pod}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "P99 - {{pod}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "P50 - {{pod}}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "GC Duration Rate",
   "type": "graph",
   "description": "Rate of garbage collection duration.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{kind}} - {{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "description": "Duration of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{kind}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "description": "Usage of heap memory.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Total - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Used - {{pod}}"
    },
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Resident - {{pod}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "External - {{pod}}"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "graph",
   "description": "Rate of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}} - {{kind}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "description": "Count of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{kind}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "graph",
   "description": "Usage of heap space.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{space}} - {{pod}}"
    }
   ]
  },
  { "title": "HTTP Actuator - health / info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "HTTP Request Time [$interval]",
   "type": "timeseries",
   "description": "время ответа - p95 и среднее значение",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\", url=~\"/probe/.*\"}[$interval])) by (url, le))",
     "legendFormat": "{{url}} - p95"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", url=~\"/probe/.*\"}[$interval])) by (url)/sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", service=\"$service\", url=~\"/probe/.*\"}[$interval])) by (url)",
     "legendFormat": "{{url}} - avg"
    }
   ]
  },
  {
   "title": "HTTP Request Statuses [$interval]",
   "type": "graph",
   "description": "% соотношение по статусам ответа",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", url=~\"/metrics|/probe/(healthz|readiness)\", service=\"$service\"}[$interval])) by (status) /  scalar(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", url=~\"/metrics|/probe/(healthz|readiness)\", service=\"$service\"}[$interval])))",
     "legendFormat": "{{statusCode}}"
    }
   ]
  },
  { "title": "Kubernetes Pods Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Pods quantity",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "sum(label_replace(min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Running\"}[$__rate_interval]),\"pod_bunch\", \"$1\", \"pod\", \"([a-z-]+)-.*\")) by (pod_bunch)",
     "legendFormat": "{{pod_bunch}}"
    }
   ]
  },
  {
   "title": "Pods Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n) > 0",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum (\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", controller=~\"$controller\", pod=~\"$pod\"}[$__rate_interval])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "(\n  min by (pod) (\n    kube_controller_pod{namespace=\"$namespace\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Running\"}[$__rate_interval])\n  ) == 1\n) * 0",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Pending\"}[$__rate_interval])\n  ) == 1\n) * 1",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Unknown\"}[$__rate_interval])\n  ) == 1\n) * 2",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Failed\"}[$__rate_interval])\n  ) == 1\n) * 3",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Succeeded\"}[$__rate_interval])\n  ) == 1\n) * 4",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "(\n  min by (pod) (\n    kube_controller_pod{node=~\"$node\", namespace=\"$namespace\"}\n    * on (pod) group_right()\n    min by (pod) (min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n  ) == 0\n) + 5",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Kubernetes Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_working_set_bytes{container!=\"POD\", pod=~\"$pod\", namespace=\"$namespace\"}[$__rate_interval]))\n)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 129 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\", namespace=\"$namespace\"}[$__rate_interval]))\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}