{
 "title": "spring_integration_send",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(spring_integration_send_seconds_count, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(spring_integration_send_seconds_count{namespace=~\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service $Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "spring_integration_send_seconds by service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (service) (rate(spring_integration_send_seconds_sum{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "spring_integration_send_seconds by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(spring_integration_send_seconds_sum{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "spring_integration_send_count by service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (service) (rate(spring_integration_send_seconds_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "spring_integration_send_count by pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(spring_integration_send_seconds_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "spring_data_repository_invocations_count by state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (result, name) (rate(spring_integration_send_seconds_count{namespace=\"$Namespace\", service=~\"$Service\"}[1m]))",
       "legendFormat": "{{result}} ({{name}})"
      }
     ]
    }
   ]
  }
 ]
}