{
 "title": "Managed REDIS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(redis_is_alive, namespace)"
    }
   },
   {
    "name": "Resource",
    "query": {
     "query": "label_values(redis_is_alive{namespace=\"$Namespace\"}, resource_id)"
    }
   },
   {
    "name": "Host",
    "query": {
     "query": "label_values(redis_is_alive{namespace=\"$Namespace\", resource_id=\"$Resource\"}, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Host",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "repeat": "Host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_is_master{namespace=\"$Namespace\", host=~\"$Host\"}"
    }
   ]
  },
  {
   "title": "$Host",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "repeat": "Host",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_is_alive{namespace=\"$Namespace\", host=~\"$Host\"}"
    }
   ]
  },
  {
   "title": "Evicted keys",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_evicted_keys{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"})"
    }
   ]
  },
  {
   "title": "OOM count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_oom_count{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"})"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=\"$Namespace\", resource_id=~\"$Resource\", host=~\"$Host\"}",
     "legendFormat": "Connected ({{node}})"
    },
    {
     "expr": "redis_blocked_clients{namespace=\"$Namespace\", resource_id=~\"$Resource\", host=~\"$Host\"}",
     "legendFormat": "Blocked ({{node}})"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "redis_instantaneous_ops_per_sec{namespace=\"$Namespace\", resource_id=~\"$Resource\", host=~\"$Host\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Slowlog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "slowlog_new{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
     "legendFormat": "New ({{node}})"
    }
   ]
  },
  {
   "title": "Slowlog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "slowlog_top{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
     "legendFormat": "{{cmd}} ({{node}})"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_used_memory{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
     "legendFormat": "Used ({{node}})"
    },
    {
     "expr": "redis_used_memory_rss{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
     "legendFormat": "Rss ({{node}})"
    },
    {
     "expr": "redis_used_memory_dataset{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
     "legendFormat": "Dataset ({{node}})"
    }
   ]
  },
  {
   "title": "Database",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "redis_dbsize{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
     "legendFormat": "Size ({{node}})"
    },
    {
     "expr": "redis_keys_db{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
     "legendFormat": "Keys ({{node}})"
    }
   ]
  },
  {
   "title": "$Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "Host",
   "collapsed": true,
   "panels": [
    {
     "title": "Load average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "load_avg_1min{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "1 min"
      },
      {
       "expr": "load_avg_5min{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "5 min"
      },
      {
       "expr": "load_avg_15min{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "15 min"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "cpu_guest{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Guest"
      },
      {
       "expr": "cpu_idle{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "cpu_iowait{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "IOwait"
      },
      {
       "expr": "cpu_irq{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "IRQ"
      },
      {
       "expr": "cpu_nice{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Nice"
      },
      {
       "expr": "cpu_softirq{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "SoftIRQ"
      },
      {
       "expr": "cpu_steal{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Steal"
      },
      {
       "expr": "cpu_system{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "System"
      },
      {
       "expr": "cpu_user{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "User"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mem_buffers_bytes{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Buffers"
      },
      {
       "expr": "mem_cached_bytes{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Cached"
      },
      {
       "expr": "mem_free_bytes{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "mem_shared_bytes{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Shared"
      },
      {
       "expr": "mem_used_bytes{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_free_bytes{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "disk_total_bytes{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "disk_used_bytes{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Disk IO (utilization)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "io_utilization{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Disk IO (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "io_read_bytes{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "io_write_bytes{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Disk IO (count)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "io_read_count{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "io_write_count{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Network (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "net_bytes_recv{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Recived"
      },
      {
       "expr": "net_bytes_sent{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Network (packets)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "net_packets_recv{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Recived"
      },
      {
       "expr": "net_packets_sent{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Network (drop)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "net_dropin{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "In"
      },
      {
       "expr": "net_dropout{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Network (error)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "net_errin{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "In"
      },
      {
       "expr": "net_errout{namespace=\"$Namespace\", resource_id=\"$Resource\", host=~\"$Host\"}",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  }
 ]
}