{
 "title": "Managed S3",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(space_usage, namespace)"
    }
   },
   {
    "name": "Resource",
    "query": {
     "query": "label_values(space_usage{namespace=\"$Namespace\"}, resource_id)"
    }
   },
   {
    "name": "ObjectType",
    "query": {
     "query": "label_values(space_usage{namespace=\"$Namespace\", resource_id=~\"$Resource\"}, object_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Resource",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "Resource",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_size{namespace=\"$Namespace\", resource_id=~\"$Resource\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "sum(space_usage{namespace=\"$Namespace\", resource_id=~\"$Resource\", storage_type=\"All\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(space_usage{namespace=\"$Namespace\", resource_id=~\"$Resource\", storage_type=\"All\"}) * 100 / sum(max_size{namespace=\"$Namespace\", resource_id=~\"$Resource\"})",
     "legendFormat": "Usage (%)"
    }
   ]
  },
  {
   "title": "$Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "Resource",
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (method) (rps{namespace=\"$Namespace\", resource_id=~\"$Resource\"})",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (bytes) (traffic{namespace=\"$Namespace\", resource_id=~\"$Resource\"})",
       "legendFormat": "{{bytes}}"
      }
     ]
    },
    {
     "title": "Objects count by type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (object_type) (objects_count{namespace=\"$Namespace\", resource_id=~\"$Resource\", object_type=~\"$ObjectType\"})",
       "legendFormat": "{{object_type}}"
      }
     ]
    },
    {
     "title": "Space usage by type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (object_type) (space_usage{namespace=\"$Namespace\", resource_id=~\"$Resource\", object_type=~\"$ObjectType\"})",
       "legendFormat": "{{object_type}}"
      }
     ]
    }
   ]
  }
 ]
}