{
 "title": "JVM Statistic",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(jvm_info, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(jvm_info{namespace=\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Service (uptime)",
   "type": "stat",
   "repeat": "Service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service) (process_uptime_seconds{namespace=\"$Namespace\", service=\"$Service\"})"
    }
   ]
  },
  {
   "title": "$Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "Service",
   "collapsed": true,
   "panels": [
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (service) (process_start_time_seconds{namespace=\"$Namespace\", service=\"$Service\"}*1000)"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 7, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"heap\"}) * 100 / sum(jvm_memory_max_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"nonheap\"}) * 100 / sum(jvm_memory_max_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"nonheap\"})"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"heap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"heap\"})",
       "legendFormat": "Committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"heap\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"nonheap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"nonheap\"})",
       "legendFormat": "Committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"nonheap\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$Namespace\", service=\"$Service\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=\"$Namespace\", service=\"$Service\"})",
       "legendFormat": "Committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=\"$Namespace\", service=\"$Service\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{namespace=\"$Namespace\", service=\"$Service\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_daemon_threads{namespace=\"$Namespace\", service=\"$Service\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{namespace=\"$Namespace\", service=\"$Service\"}",
       "legendFormat": "Peak"
      },
      {
       "expr": "process_threads{namespace=\"$Namespace\", service=\"$Service\"}",
       "legendFormat": "Process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{namespace=\"$Namespace\", service=\"$Service\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "GC Pressure",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{namespace=\"$Namespace\", service=\"$Service\"}[1m])) by (application, instance) / on(application, instance) system_cpu_count",
       "legendFormat": "CPU time spent on GC"
      }
     ]
    },
    {
     "title": "Log Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "increase(logback_events_total{namespace=\"$Namespace\", service=\"$Service\"}[1m])",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_files_open_files{namespace=\"$Namespace\", service=\"$Service\"}",
       "legendFormat": "Open"
      },
      {
       "expr": "process_files_max_files{namespace=\"$Namespace\", service=\"$Service\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory pool (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "repeat": "jvm_memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (id) (jvm_memory_used_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"heap\"})",
       "legendFormat": "{{id}} (used)"
      },
      {
       "expr": "sum by (id) (jvm_memory_committed_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"heap\"})",
       "legendFormat": "{{id}} (commited)"
      },
      {
       "expr": "sum by (id) (jvm_memory_max_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"heap\"})",
       "legendFormat": "{{id}} (max)"
      }
     ]
    },
    {
     "title": "Memory pool (noheap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (id) (jvm_memory_used_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"nonheap\"})",
       "legendFormat": "{{id}} (used)"
      },
      {
       "expr": "sum by (id) (jvm_memory_committed_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"nonheap\"})",
       "legendFormat": "{{id}} (commited)"
      },
      {
       "expr": "sum by (id) (jvm_memory_max_bytes{namespace=\"$Namespace\", service=\"$Service\", area=\"nonheap\"})",
       "legendFormat": "{{id}} (max)"
      }
     ]
    },
    {
     "title": "GC collections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{namespace=\"$Namespace\", service=\"$Service\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "GC pause durations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{namespace=\"$Namespace\", service=\"$Service\"}[1m]) / rate(jvm_gc_pause_seconds_count{namespace=\"$Namespace\", service=\"$Service\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{namespace=\"$Namespace\", service=\"$Service\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "GC allocated/promoted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{namespace=\"$Namespace\", service=\"$Service\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{namespace=\"$Namespace\", service=\"$Service\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    },
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{namespace=\"$Namespace\", service=\"$Service\"}",
       "legendFormat": "Loaded"
      }
     ]
    },
    {
     "title": "Class delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{namespace=\"$Namespace\", service=\"$Service\"}[1m])",
       "legendFormat": "Delta-1m"
      }
     ]
    },
    {
     "title": "Buffer pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "repeat": "jvm_buffer_pool",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (id) (jvm_buffer_memory_used_bytes{namespace=\"$Namespace\", service=\"$Service\"})",
       "legendFormat": "{{id}} (used)"
      },
      {
       "expr": "sum by (id) (jvm_buffer_total_capacity_bytes{namespace=\"$Namespace\", service=\"$Service\"})",
       "legendFormat": "{{id}} (capacity)"
      },
      {
       "expr": "sum by (id) (jvm_buffer_count_buffers{namespace=\"$Namespace\", service=\"$Service\"})",
       "legendFormat": "{{id}} (buffers)"
      }
     ]
    }
   ]
  }
 ]
}