{
 "title": "Deferred Task",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(up, namespace)" } },
   {
    "name": "service",
    "label": "Application",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Task Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(deferred_task_collection_size{service=\"$service\", namespace=\"$namespace\"}) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg(deferred_task_collection_size{service=\"$service\", namespace=\"$namespace\"}) by (node))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Number of Active Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg(deferred_task_live_nodes{service=\"$service\", namespace=\"$namespace\"}) by (node))",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Execution Time for execute(ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(deferred_task_execute_time_seconds{service=\"$service\", namespace=\"$namespace\", quantile=\"0.5\"}) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "avg(deferred_task_execute_time_seconds{service=\"$service\", namespace=\"$namespace\", quantile=\"0.75\"}) * 1000",
     "legendFormat": "0.75"
    },
    {
     "expr": "avg(deferred_task_execute_time_seconds{service=\"$service\", namespace=\"$namespace\", quantile=\"0.99\"}) * 1000",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Task Queue Insertion Rate (tasks/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(deferred_task_input_total{service=\"$service\", namespace=\"$namespace\"}[5m])*60",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(deferred_task_input_total{service=\"$service\", namespace=\"$namespace\"}[5m])) * 60\n",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Number of Processed Documents (documents/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(deferred_task_output_total{service=\"$service\", namespace=\"$namespace\"}[5m])*60",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(deferred_task_output_total{service=\"$service\", namespace=\"$namespace\"}[5m])*60)",
     "legendFormat": "TOTAL"
    }
   ]
  }
 ]
}