{
 "title": "search services dashboard (aggregated)",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot,)",
 "tags": [
  "main",
  "micrometer"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(up, namespace)" } },
   {
    "name": "service",
    "label": "Application",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=\"$namespace\", service=~\"$service\"}, uri)"
    }
   },
   {
    "name": "clientName",
    "label": "Client",
    "query": {
     "query": "label_values(http_client_requests_seconds{service=~\"$service\"},client_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"$path\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or sum(increase(http_server_requests_seconds_count{service=\"$service\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "200 HTTP response (count)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"$path\", status=~\"2..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or sum(increase(http_server_requests_seconds_count{status=~\"2..\", service=\"$service\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "500 HTTP response (count)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"$path\", status=~\"5..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or sum(increase(http_server_requests_seconds_count{status=~\"5..\", service=\"$service\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "500 HTTP response (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (sum(increase(http_server_requests_seconds_count{uri=\"$path\", status=~\"5..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or vector(0))\n    /\n  sum(increase(http_server_requests_seconds_count{uri=\"$path\", service=\"$service\", namespace=\"$namespace\"}[$__range]))\n)\n  or\n(\n  (sum(increase(http_server_requests_seconds_count{status=~\"5..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or vector(0))\n    /\n  sum(increase(http_server_requests_seconds_count{service=\"$service\", namespace=\"$namespace\"}[$__range]))\n)"
    }
   ]
  },
  {
   "title": "400 HTTP response (count)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"$path\", status=~\"4..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or sum(increase(http_server_requests_seconds_count{status=~\"4..\", service=\"$service\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "400 HTTP response (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (sum(increase(http_server_requests_seconds_count{uri=\"$path\", status=~\"4..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or vector(0))\n    /\n  sum(increase(http_server_requests_seconds_count{uri=\"$path\", service=\"$service\", namespace=\"$namespace\"}[$__range]))\n)\n  or\n(\n  (sum(increase(http_server_requests_seconds_count{status=~\"4..\", service=\"$service\", namespace=\"$namespace\"}[$__range])) or vector(0))\n    /\n  sum(increase(http_server_requests_seconds_count{service=\"$service\", namespace=\"$namespace\"}[$__range]))\n)"
    }
   ]
  },
  {
   "title": "Average API response $path",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (quantile, status) (http_server_requests_seconds{uri=~\"$path\", service=\"$service\", namespace=\"$namespace\", exception=\"none\"})",
     "legendFormat": "{{status}} {{quantile}}"
    },
    {
     "expr": "avg by (quantile, status, exception) (http_server_requests_seconds{uri=~\"$path\", exception!=\"none\", service=\"$service\", namespace=\"$namespace\", quantile=\"0.95\"})",
     "legendFormat": "{{status}} {{exception}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Requests per second $path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"$path\", service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "$path"
    }
   ]
  },
  { "title": "HTTP Client Percentiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Request per second $clientName",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "repeat": "clientName",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum by (service, uri, clientName) (rate(http_client_requests_seconds_count{client_name=\"$clientName\", namespace=\"$namespace\", service=\"$service\"}[1m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "API response $clientName",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "repeat": "clientName",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (service, clientName, quantile, uri, status) (http_client_requests_seconds{namespace=\"$namespace\", service=\"$service\", client_name=\"$clientName\", outcome=\"SUCCESS\"})",
     "legendFormat": "{{uri}} {{status}} {{quantile}}"
    },
    {
     "expr": "avg by (service, clientName, quantile, uri, status) (http_client_requests_seconds{namespace=\"$namespace\", service=\"$service\", client_name=\"$clientName\", outcome!=\"SUCCESS\", quantile=\"0.95\"})",
     "legendFormat": "{{uri}} {{status}} {{quantile}}"
    }
   ]
  }
 ]
}