{
 "title": "Payment Loan(BNPL) - Conversion",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "window", "label": "window", "query": "3d, 7d, 30d, 90d, 180d, 360d" }
  ]
 },
 "panels": [
  {
   "title": "Stores  (period $window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(storeId)(increase(bnpl_payments_holded_total{namespace='payment-credit-test', service='bnpl'}[$window])) \r\n/ sum by(storeId)(increase(bnpl_payments_created_total {namespace='payment-credit-test', service='bnpl'}[$window]))"
    }
   ]
  },
  {
   "title": "Conversion (period $window)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(storeId)(increase(bnpl_payments_holded_total{namespace='payment-credit-test', service='bnpl'}[$window])) \r\n/ sum by(storeId)(increase(bnpl_payments_created_total {namespace='payment-credit-test', service='bnpl'}[$window] offset 5m))"
    }
   ]
  },
  {
   "title": "Created  (period $window)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(storeId)(increase(bnpl_payments_created_total {storeId='35', namespace='payment-credit-test', service='bnpl'}[$window]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(storeId)(increase(bnpl_payments_created_total {storeId='2', namespace='payment-credit-test', service='bnpl'}[$window]))"
    }
   ]
  },
  {
   "title": "Holded  (period $window)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(storeId)(increase(bnpl_payments_holded_total {storeId='35', namespace='payment-credit-test', service='bnpl'}[$window]))"
    },
    {
     "expr": "sum by(storeId)(increase(bnpl_payments_holded_total {storeId='2', namespace='payment-credit-test', service='bnpl'}[$window]))"
    }
   ]
  }
 ]
}