{
 "title": "Migration",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, namespace)"
    }
   },
   { "name": "service", "label": "service", "query": "migration" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   },
   {
    "name": "excluded_urls",
    "label": "Excluded URLs",
    "query": "/actuator.*|.*api-docs.*|.*swagger.*|/metrics|UNKNOWN|/camunda/.*|ROOT|REDIRECTION|root|NOT_FOUND|/webjars/.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Processed receipts pages count [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(receipts_page_processing_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\", uri!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "Processed receipt pages"
    }
   ]
  },
  {
   "title": "Processed receipts count [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (receiptType) (increase(receipt_processing_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "{{ receiptType }}"
    }
   ]
  },
  {
   "title": "Receipts page processing time [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(receipts_page_loading_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])) / sum (irate(receipts_page_loading_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "Loading"
    },
    {
     "expr": "sum (irate(receipts_page_processing_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])) / sum (irate(receipts_page_processing_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "Processing"
    },
    {
     "expr": "(sum (irate(receipts_page_loading_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])) / sum (irate(receipts_page_loading_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))) + (sum (irate(receipts_page_processing_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])) / sum (irate(receipts_page_processing_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Receipt processing time [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (receiptType) (irate(receipt_processing_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m])) / sum by (receiptType) (irate(receipt_processing_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "{{ receiptType }}"
    }
   ]
  },
  {
   "title": "Sent to kafka receipts count [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(sent_historical_receipts_count_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "Sent to Kafka receipts"
    }
   ]
  },
  {
   "title": "Sent to DLT receipts count [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(receipt_processing_errors_count_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[1m]))",
     "legendFormat": "Sent to DLT receipts"
    }
   ]
  },
  {
   "title": "AVG receipts page loading time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(receipts_page_loading_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range:])) / sum (irate(receipts_page_loading_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range:]))",
     "legendFormat": "AVG receipts page loading time"
    }
   ]
  },
  {
   "title": "AVG receipts page processing time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(receipts_page_processing_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range:])) / sum (irate(receipts_page_processing_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range:]))"
    }
   ]
  },
  {
   "title": "AVG receipt processing time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(receipt_processing_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range:])) / sum (irate(receipt_processing_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$service\"}[$__range:]))"
    }
   ]
  }
 ]
}