{
 "title": "Clusters overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Pods count",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lm_intraru3_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_intraru3_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_api_manager_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_api_manager_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_bricks_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_bricks_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_cft_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_cft_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_customer_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_customer_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_data_accel_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_data_accel_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_delivery_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_delivery_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_fulfillment_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_fulfillment_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_local_opus_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_local_opus_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_magfront_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_magfront_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_marketplace_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_marketplace_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_payment_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_payment_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_search_nav_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_search_nav_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_shared_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_shared_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_supply_chain_production_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_supply_chain_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_gogomonia_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_rnd_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_e2e_stage_pods_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lm_intraru3_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_intraru3_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_api_manager_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_api_manager_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_bricks_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_bricks_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_cft_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_cft_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_customer_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_customer_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_data_accel_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_data_accel_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_delivery_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_delivery_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_fulfillment_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_fulfillment_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_local_opus_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_local_opus_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_magfront_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_magfront_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_marketplace_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_marketplace_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_payment_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_payment_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_search_nav_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_search_nav_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_shared_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_shared_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_supply_chain_production_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_supply_chain_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_gogomonia_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_rnd_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_e2e_stage_capacity_cpu{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lm_intraru3_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_intraru3_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_api_manager_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_api_manager_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_bricks_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_bricks_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_cft_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_cft_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_customer_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_customer_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_data_accel_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_data_accel_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_delivery_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_delivery_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_fulfillment_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_fulfillment_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_local_opus_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_local_opus_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_magfront_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_magfront_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_marketplace_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_marketplace_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_payment_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_payment_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_search_nav_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_search_nav_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_shared_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_shared_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_supply_chain_production_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_supply_chain_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_gogomonia_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_rnd_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_e2e_stage_capacity_ram{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    }
   ]
  },
  {
   "title": "Ingresses Count",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lm_intraru3_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_intraru3_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_api_manager_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_api_manager_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_bricks_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_bricks_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_cft_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_cft_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_customer_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_customer_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_data_accel_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_data_accel_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_delivery_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_delivery_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_fulfillment_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_fulfillment_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_local_opus_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_local_opus_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_magfront_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_magfront_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_marketplace_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_marketplace_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_payment_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_payment_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_search_nav_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_search_nav_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_shared_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_shared_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_supply_chain_production_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_supply_chain_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_gogomonia_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_rnd_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    },
    {
     "expr": "lm_e2e_stage_ingresses_count{namespace=\"kube-blender-server\",service=\"kube-blender-server-service\"}\t"
    }
   ]
  }
 ]
}