{
 "title": "Store Authorization Gateway APIs",
 "tags": [
  "prometheus",
  "nodejs",
  "api"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{application=\"store-authorization-gateway\"}, namespace)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{application=\"store-authorization-gateway\", namespace=\"$namespace\"}, method)"
    }
   },
   {
    "name": "path",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{application=\"store-authorization-gateway\", namespace=\"$namespace\", method=~\"$method\"}, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Statuses Percentage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\", application=\"store-authorization-gateway\", method=~\"$method\", path=~\"$path\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "status {{status_code}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{namespace=\"$namespace\", application=\"store-authorization-gateway\", status_code=~\"2..\", method=~\"$method\", path=~\"$path\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Redirects",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{namespace=\"$namespace\", application=\"store-authorization-gateway\", status_code=~\"3..\", method=~\"$method\", path=~\"$path\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Client Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{namespace=\"$namespace\", application=\"store-authorization-gateway\", status_code=~\"4..\", method=~\"$method\", path=~\"$path\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Server Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{namespace=\"$namespace\", application=\"store-authorization-gateway\", status_code=~\"5..\", method=~\"$method\", path=~\"$path\"}[$__range]))"
    }
   ]
  },
  {
   "title": "RPS by path",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\", application=\"store-authorization-gateway\", method=~\"$method\", path=~\"$path\"}[$__rate_interval])) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Latency by uri",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{namespace=\"$namespace\", application=\"store-authorization-gateway\", method=~\"$method\", path=~\"$path\"}[$__rate_interval])) by (method,path) / sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\", application=\"store-authorization-gateway\", method=~\"$method\", path=~\"$path\"}[$__rate_interval])) by (method,path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}