{
 "title": "Spring Boot Observability",
 "tags": [ "http" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=\"$application\"},namespace)"
    }
   },
   { "name": "application", "label": "Application Name", "query": { "query": "label_values(application)" } },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\"},method)"
    }
   },
   {
    "name": "uri",
    "label": "request_uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\"},uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, uri) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"}[$__range]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, uri) (http_server_requests_seconds_sum{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"}) / sum by(method, uri) (http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\", outcome!=\"SUCCESS\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(method, uri) (http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\", outcome=\"SUCCESS\"}) / sum by(method, uri) (http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Percent of non 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(method, uri) (http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\", outcome!=\"SUCCESS\"}) / sum by(method, uri) (http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(method, uri, le) (rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"}[1m])))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(method, uri, le) (rate(http_server_requests_seconds_bucket{namespace=\"$namespace\", application=\"$application\", method=~\"$method\", uri=~\"$uri\"}[1m])))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}