{
 "title": "Data - Veracity",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Testing the Metrics Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last start daily task",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT date, type_source, initialization\r\nFROM (\r\n    SELECT *, ROW_NUMBER() OVER (PARTITION BY type_source ORDER BY date DESC) AS row_num\r\n    FROM app_system.tasks\r\n    WHERE type_source LIKE '%daily_task%'\r\n) AS ranked_tasks\r\nWHERE row_num = 1;\r\n"
    }
   ]
  },
  {
   "title": "Last start daily task for source",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT date, type_source, initialization\r\nFROM (\r\n    SELECT *, ROW_NUMBER() OVER (PARTITION BY type_source ORDER BY date DESC) AS row_num\r\n    FROM app_system.tasks\r\n    WHERE type_source LIKE 'daily%'\r\n) AS ranked_tasks\r\nWHERE row_num = 1;\r\n"
    }
   ]
  },
  { "title": "Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Account.account  -> lysloyalty_ods.account (creationdate) - Rows per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT date_, count_ AS mdb_count FROM reports.mdb_account_creationdate;"
    },
    {
     "rawSql": "SELECT date_, count_ AS gp_count FROM reports.gp_lysloyalty_ods_v_account_creationdate;"
    }
   ]
  },
  {
   "title": "Account.account -> lysloyalty_ods.account (creationdate) - Count rows in sources",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(count_) AS mdb FROM reports.mdb_account_creationdate;"
    },
    {
     "rawSql": "SELECT sum(count_) AS gp FROM reports.gp_lysloyalty_ods_v_account_creationdate;"
    },
    {
     "rawSql": "SELECT\r\n  (SELECT sum(count_) FROM reports.mdb_account_creationdate) - \r\n  (SELECT sum(count_) FROM reports.gp_lysloyalty_ods_v_account_creationdate) AS delta;\r\n"
    }
   ]
  },
  {
   "title": "Account.account -> lysloyalty_ods.account (creationdate) - Deltas per date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT mdb.date_, gp.count_ - mdb.count_ AS delta_creationdate\r\nFROM reports.mdb_account_creationdate AS mdb\r\nJOIN reports.gp_lysloyalty_ods_v_account_creationdate AS gp\r\n  ON mdb.date_ = gp.date_"
    },
    {
     "rawSql": "SELECT mdb.date_, gp.count_ - mdb.count_ AS delta_updatedate\r\nFROM reports.mdb_account_updatedate AS mdb\r\nJOIN reports.gp_lysloyalty_ods_v_account_updatedate AS gp\r\n  ON mdb.date_ = gp.date_\r\n"
    },
    {
     "rawSql": "SELECT mdb.date_, 0 AS baseline\r\nFROM reports.mdb_account_creationdate AS mdb"
    }
   ]
  },
  {
   "title": "Not updates rows",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SELECT sum(count_) FROM reports.mdb_account_updatedate) - \r\n  (SELECT sum(count_) FROM reports.gp_lysloyalty_ods_v_account_updatedate) AS update_rows;\r\n"
    }
   ]
  },
  {
   "title": "Diff created/updates rows",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (\r\n    (SELECT sum(count_) FROM reports.mdb_account_creationdate) - \r\n    (SELECT sum(count_) FROM reports.gp_lysloyalty_ods_v_account_creationdate)\r\n  ) -\r\n  (\r\n    (SELECT sum(count_) FROM reports.mdb_account_updatedate) - \r\n    (SELECT sum(count_) FROM reports.gp_lysloyalty_ods_v_account_updatedate)\r\n  ) AS new_rows;\r\n\r\n"
    },
    {
     "rawSql": "SELECT\r\n  (SELECT sum(count_) FROM reports.mdb_account_updatedate) - \r\n  (SELECT sum(count_) FROM reports.gp_lysloyalty_ods_v_account_updatedate) AS update_rows;\r\n"
    }
   ]
  },
  {
   "title": "Account.clearedSupport (updatedate)-> lysloyalty_ods.cleared_support (validityenddate) - Rows per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT date_, count_ AS mdb_count FROM reports.mdb_clearedsupport_updatedate;"
    },
    {
     "rawSql": "SELECT date_, count_ AS gp_count FROM reports.gp_lysloyalty_ods_v_cleared_support_validityenddate;"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "events.eventHistory (eventdate)-> lysloyalty_ods.event (eventdate) - Rows per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT date_, count_ AS mdb_count FROM reports.mdb_eventhistory_eventdate;"
    },
    {
     "rawSql": "SELECT date_, count_ AS gp_count FROM reports.gp_lysloyalty_ods_v_event_eventdate;"
    }
   ]
  },
  {
   "title": "Events (eventdate) - Count rows in sources",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(count_) AS mdb FROM reports.mdb_eventhistory_eventdate;"
    },
    {
     "rawSql": "SELECT sum(count_) AS gp FROM reports.gp_lysloyalty_ods_v_event_eventdate;"
    },
    {
     "rawSql": "SELECT\r\n  (SELECT sum(count_) FROM reports.mdb_eventhistory_eventdate) - \r\n  (SELECT sum(count_) FROM reports.gp_lysloyalty_ods_v_event_eventdate) AS delta;\r\n"
    }
   ]
  },
  {
   "title": "events.eventHistory (eventdate)-> lysloyalty_ods.event (eventdate) - Deltas per date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT mdb.date_, gp.count_ - mdb.count_ AS delta\r\nFROM reports.mdb_eventhistory_eventdate AS mdb\r\nJOIN reports.gp_lysloyalty_ods_v_event_eventdate AS gp\r\n  ON mdb.date_ = gp.date_"
    },
    {
     "rawSql": "SELECT mdb.date_, 0 AS baseline\r\nFROM reports.mdb_eventhistory_eventdate AS mdb"
    }
   ]
  },
  {
   "title": "Events (eventdate) - Count rows in sources",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(gp.count_ - mdb.count_) AS total_negative_delta\r\nFROM reports.mdb_eventhistory_eventdate AS mdb\r\nJOIN reports.gp_lysloyalty_ods_v_event_eventdate AS gp\r\n  ON mdb.date_ = gp.date_\r\nWHERE gp.count_ - mdb.count_ < 0;\r\n"
    }
   ]
  },
  { "title": "DiscountHistory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Discount-history.transactions  -> lysloyalty_rewards_ods - Rows per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT date_, count_ AS mdb_count FROM reports.mdb_transactions_creationdate;"
    },
    {
     "rawSql": "SELECT date_, count_ AS gp_count_receipt_header FROM reports.gp_lysloyalty_rewards_ods_v_receipt_lys_header_creationdate;"
    },
    {
     "rawSql": "SELECT date_, count_ AS gp_count_receipt_lines FROM reports.gp_lysloyalty_rewards_ods_v_receipt_lys_lines_creationdate;"
    }
   ]
  },
  {
   "title": "Discount-history.transactions  -> lysloyalty_rewards_ods - Count rows in sources",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(count_) AS mdb_transactions FROM reports.mdb_transactions_creationdate;"
    },
    {
     "rawSql": "SELECT sum(count_) AS gp_receipt_header FROM reports.gp_lysloyalty_rewards_ods_v_receipt_lys_header_creationdate;"
    },
    {
     "rawSql": "SELECT sum(count_) AS gp_rewards_lines FROM reports.gp_lysloyalty_rewards_ods_v_receipt_lys_lines_creationdate;"
    }
   ]
  },
  {
   "title": "Discount-history.transactions  -> lysloyalty_rewards_ods - Deltas per date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT mdb.date_, gp.count_ - mdb.count_ AS delta_receipt_header\r\nFROM reports.mdb_transactions_creationdate AS mdb\r\nJOIN reports.gp_lysloyalty_rewards_ods_v_receipt_lys_header_creationdate AS gp\r\n  ON mdb.date_ = gp.date_"
    },
    {
     "rawSql": "SELECT mdb.date_, gp.count_ - mdb.count_ AS delta_receipt_lines\r\nFROM reports.mdb_transactions_creationdate AS mdb\r\nJOIN reports.gp_lysloyalty_rewards_ods_v_receipt_lys_lines_creationdate AS gp\r\n  ON mdb.date_ = gp.date_"
    },
    {
     "rawSql": "SELECT mdb.date_, 0 AS baseline\r\nFROM reports.mdb_transactions_creationdate AS mdb"
    }
   ]
  },
  {
   "title": "Discount-history.transactions  -> lysloyalty_rewards_ods - Count rows in sources",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SELECT sum(count_) FROM reports.mdb_transactions_creationdate) - \r\n  (SELECT sum(count_) FROM reports.gp_lysloyalty_rewards_ods_v_receipt_lys_header_creationdate) AS delta_receipt_header;\r\n"
    },
    {
     "rawSql": "SELECT\r\n  (SELECT sum(count_) FROM reports.mdb_transactions_creationdate) - \r\n  (SELECT sum(count_) FROM reports.gp_lysloyalty_rewards_ods_v_receipt_lys_lines_creationdate) AS delta_receipt_lines;\r\n"
    }
   ]
  },
  { "title": "EarnBurn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "earnBurn.aggregatedcounter -> lysloyalty_ods.aggregated_counter (updatedate) - Deltas per date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT mdb.date_, gp.count_ - mdb.count_ AS delta\r\nFROM reports.mdb_aggregatedcounter_updatedate AS mdb\r\nJOIN reports.gp_lysloyalty_ods_v_aggregated_counter_updatedate AS gp\r\n  ON mdb.date_ = gp.date_"
    }
   ]
  },
  {
   "title": "earnBurn.rank-> lysloyalty_ods.rank (updatedate) - Deltas per date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT mdb.date_, gp.count_ - mdb.count_ AS delta\r\nFROM reports.mdb_rank_updatedate AS mdb\r\nJOIN reports.gp_lysloyalty_ods_v_rank_updatedate AS gp\r\n  ON mdb.date_ = gp.date_"
    }
   ]
  }
 ]
}