{
 "title": "lys_loyalty_integration",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(lys_loyalty_integration_get_account_lmru_created , namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(lys_loyalty_integration_get_account_lmru_created{namespace=~\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service $Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Service" },
  {
   "title": "lys_loyalty_integration_get_account_lmru_created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lys_loyalty_integration_get_account_lmru_created{namespace=\"$Namespace\", service=~\"$Service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "lys_loyalty_integration_get_account_lmru_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lys_loyalty_integration_get_account_lmru_total{namespace=\"$Namespace\", service=~\"$Service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "lys_loyalty_integration_get_account_lys_created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lys_loyalty_integration_get_account_lys_created{namespace=\"$Namespace\", service=~\"$Service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "lys_loyalty_integration_get_account_lys_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lys_loyalty_integration_get_account_lys_total{namespace=\"$Namespace\", service=~\"$Service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "lys_loyalty_integration_membership_lmru_created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lys_loyalty_integration_membership_lmru_created{namespace=\"$Namespace\", service=~\"$Service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "lys_loyalty_integration_membership_lmru_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lys_loyalty_integration_membership_lmru_total{namespace=\"$Namespace\", service=~\"$Service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "lys_loyalty_integration_membership_lys_created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lys_loyalty_integration_membership_lys_created{namespace=\"$Namespace\", service=~\"$Service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "lys_loyalty_integration_membership_lys_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lys_loyalty_integration_membership_lys_total{namespace=\"$Namespace\", service=~\"$Service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}