{
 "title": "search-engine additional dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(up, namespace)" } },
   {
    "name": "service",
    "label": "Application",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\", service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Search Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Search Method Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(search_method_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m])) by (search_method)",
     "legendFormat": "{{search_method}}"
    },
    {
     "expr": "sum(increase(search_method_counter_total{service=\"$service\", namespace=\"$namespace\", search_method=~\"FULL_TEXT.*\"}[1m]))",
     "legendFormat": "FULL_TEXT_ALL"
    }
   ]
  },
  {
   "title": "Search Params Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(search_params_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m])) by (show_facets, show_products)",
     "legendFormat": "{{show_facets, show_products}}"
    }
   ]
  },
  {
   "title": "Requests By Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(search_channel_counter_total{service=\"$service\", namespace=\"$namespace\"}[60s])) by (channel_id)",
     "legendFormat": "{{channel_id}}"
    },
    {}
   ]
  },
  {
   "title": "Requests By Regions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(search_region_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m])) by (region_id)",
     "legendFormat": "{{region_id}}"
    }
   ]
  },
  { "title": "Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Empty Results Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(empty_result_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "empty results"
    }
   ]
  },
  { "title": "Remote Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Cacheable Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(cacheable_requests_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Non Cacheable Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(non_cacheable_requests_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Hit Rate (0.0 - 1.0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(search_cache_gets_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m])) / (sum(increase(search_cache_gets_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m])) + sum(increase(search_cache_empty_gets_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m])))",
     "legendFormat": "hit rate"
    }
   ]
  },
  {
   "title": "Search Cache Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(search_cache_errors_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Search Cache Gets Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(search_cache_gets_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "non-empty gets"
    }
   ]
  },
  {
   "title": "Search Cache Puts Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(search_cache_puts_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "puts"
    }
   ]
  },
  {
   "title": "Search Cache Empty Gets Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(search_cache_empty_gets_counter_total{service=\"$service\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "empty gets"
    }
   ]
  },
  { "title": "Local Cache (Pods)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Local cache size (objects)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cache_size{pod=\"$pod\", service=\"$service\"}",
     "legendFormat": "{{name}} ({{cacheManager}})"
    }
   ]
  },
  {
   "title": "Cache Evictions Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(cache_evictions_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cache Evictions Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(cache_evictions_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}