{
 "title": "API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "customTarget",
    "query": {
     "query": "label_values(python_info{}, job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(python_info{job=\"$customTarget\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Common info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Python",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version) (python_info{job=\"$customTarget\", namespace=\"$namespace\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Instance count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$customTarget\", namespace=\"$namespace\",})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$customTarget\", namespace=\"$namespace\",}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "5xx Errors Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$customTarget\", namespace=\"$namespace\", handler!=\"/metrics\", status=~\"|5.+\"}[1m])) / sum(rate(http_requests_total{job=\"$customTarget\", namespace=\"$namespace\", handler!=\"/metrics\", }[1m]))"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$customTarget\", namespace=\"$namespace\", handler!=\"/metrics\", status=~\"4.+|5.+\"}[1m])) / sum(rate(http_requests_total{job=\"$customTarget\", namespace=\"$namespace\", handler!=\"/metrics\", }[1m]))"
    }
   ]
  },
  { "title": "Platform resource consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$customTarget\", namespace=\"$namespace\"}[10m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$customTarget\", namespace=\"$namespace\",}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$customTarget\", namespace=\"$namespace\", handler!=\"none\", handler!=\"/openapi.json\"}[5m])*60) by (handler) ",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$customTarget\", namespace=\"$namespace\", handler!=\"none\", handler!=\"/openapi.json\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Latency 99q",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.99,\r\n    sum(rate(http_request_duration_seconds_bucket{job=\"$customTarget\", namespace=\"$namespace\", handler!=\"none\", handler!=\"/openapi.json\"}[1m])) by (le, handler)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 50q",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.5,\r\n    sum(rate(http_request_duration_seconds_bucket{job=\"$customTarget\", namespace=\"$namespace\", handler!=\"none\", handler!=\"/openapi.json\"}[1m])) by (le, handler)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum{job=\"$customTarget\", namespace=\"$namespace\",handler!=\"none\"}) by (handler)\r\n/\r\nsum(http_request_duration_seconds_count{job=\"$customTarget\", namespace=\"$namespace\",handler!=\"none\"}) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Errors/Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$customTarget\", namespace=\"$namespace\",status=~\"4.+|5.+\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Error/Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "err/min" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$customTarget\", namespace=\"$namespace\", handler!=\"/metrics\", handler!=\"none\", handler!=\"/openapi.json\", status=~\"4.+|5.+\"}[1m])) by (status)"
    }
   ]
  }
 ]
}