{
 "title": "Clickhouse",
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Host:", "query": { "query": "ClickHouseAsyncMetrics_Uptime" } },
   {
    "name": "nodeexpport",
    "query": {
     "query": "label_values(node_uname_info{instance=~\"$instance:(.*)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Clickhouse overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Query",
   "type": "graph",
   "description": "Number of queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_Query{instance=\"$instance:8001\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Select Query",
   "type": "graph",
   "description": "Only for SELECT queries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_SelectQuery{instance=\"$instance:8001\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Insert Query",
   "type": "graph",
   "description": "Only for INSERT queries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_InsertQuery{instance=\"$instance:8001\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "tcp - Number of connections to TCP server (clients with native interface), also included server-server distributed query connections\n\nhttp - Number of connections to HTTP server\n\ninterserver - Number of connections from other replicas to fetch parts\n\nmysql - Number of client connections using MySQL protocol",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection{instance=\"$instance:8001\"}",
     "legendFormat": "tcp {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection{instance=\"$instance:8001\"}",
     "legendFormat": "http {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_InterserverConnection{instance=\"$instance:8001\"}",
     "legendFormat": "interserver {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_MySQLConnection{instance=\"$instance:8001\"}",
     "legendFormat": "mysql {{instance}}"
    }
   ]
  },
  {
   "title": "Table size",
   "type": "timeseries",
   "description": "size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "clickhouse_table_exporter_table_size",
     "legendFormat": "{{database}} - {{table}}"
    },
    {
     "expr": "sum(clickhouse_table_exporter_table_size)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Rows in table",
   "type": "timeseries",
   "description": "size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Row" } },
   "targets": [
    {
     "expr": "clickhouse_table_exporter_table_rows",
     "legendFormat": "{{database}} - {{table}}"
    }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "graph",
   "description": "Number of active tasks in BackgroundProcessingPool (merges, mutations, fetches, or replication queue bookkeeping)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundPoolTask{instance=\"$instance:8001\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "description": "Number of files opened.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_FileOpen{instance=\"$instance:8001\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read/Write Syscalls",
   "type": "graph",
   "description": "Number of read (read, pread, io_getevents, etc.) syscalls in fly\n\nNumber of write (write, pwrite, io_getevents, etc.) syscalls in fly",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_Read{instance=\"$instance:8001\"}",
     "legendFormat": "Read {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_Write{instance=\"$instance:8001\"}",
     "legendFormat": "Write {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Read/Write with a File Descriptor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead{instance=\"$instance:8001\"}[1m])",
     "legendFormat": "Number of Reads {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{instance=\"$instance:8001\"}[1m])",
     "legendFormat": "Failed Reads {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{instance=\"$instance:8001\"}[1m])",
     "legendFormat": "Number of Writes {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteFailed{instance=\"$instance:8001\"}[1m])",
     "legendFormat": "Failed Writes {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes of Read/Write with a File Descriptor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes{instance=\"$instance:8001\"}[1m])",
     "legendFormat": "Bytes of Reads {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes{instance=\"$instance:8001\"}[1m])",
     "legendFormat": "Bytes of Writes {{instance}}"
    }
   ]
  },
  { "title": "Kafka Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "KafkaRebalance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaRebalanceRevocations[$__rate_interval])",
     "legendFormat": "Revocations"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaRebalanceAssignments[$__rate_interval])",
     "legendFormat": "Assignments"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaRebalanceErrors[$__rate_interval])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "KafkaMessages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaMessagesPolled[$__rate_interval])",
     "legendFormat": "Polled"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaMessagesRead[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaMessagesFailed[$__rate_interval])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Kafka Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaRowsRead[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaRowsRejected[$__rate_interval])",
     "legendFormat": "Rejected"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaRowsWritten[$__rate_interval])",
     "legendFormat": "Written"
    }
   ]
  },
  {
   "title": "Kafka Producer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaProducerFlushes[$__rate_interval])",
     "legendFormat": "Flushes"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaMessagesProduced[$__rate_interval])",
     "legendFormat": "Messages Produced"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaProducerErrors[$__rate_interval])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Kafka Commit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaCommits[$__rate_interval])",
     "legendFormat": "Commits"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaCommitFailures[$__rate_interval])",
     "legendFormat": "Commit Failures"
    }
   ]
  },
  {
   "title": "Kafka Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaConsumerErrors[$__rate_interval])",
     "legendFormat": "Errors"
    },
    {
     "expr": "ClickHouseMetrics_KafkaConsumers",
     "legendFormat": "consumers"
    }
   ]
  },
  {
   "title": "Kafka Writes",
   "type": "timeseries",
   "description": "Number of writes (inserts) to Kafka tables ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaWrites[$__rate_interval])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"${instance}:${nodeexpport}\"}) /  count(count(node_cpu_seconds_total{instance=~\"${instance}:${nodeexpport}\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"${instance}:${nodeexpport}\"}) /  count(count(node_cpu_seconds_total{instance=~\"${instance}:${nodeexpport}\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance}:${nodeexpport}\"}"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host\",fstype!=\"rootfs\"}"
    }
   ]
  },
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"${instance}:${nodeexpport}\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"${instance}:${nodeexpport}\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"${instance}:${nodeexpport}\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"${instance}:${nodeexpport}\"} * 100) / node_memory_MemTotal_bytes{instance=~\"${instance}:${nodeexpport}\"})"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Total DataFS",
   "type": "stat",
   "description": "Total DataFS",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host/data\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "stat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"${instance}:${nodeexpport}\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"${instance}:${nodeexpport}\"} - node_boot_time_seconds{instance=~\"${instance}:${nodeexpport}\"}"
    }
   ]
  },
  {
   "title": "Used Data FS",
   "type": "stat",
   "description": "Used Data FS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host/data\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"${instance}:${nodeexpport}\",mountpoint=\"/host/data\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"${instance}:${nodeexpport}\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"${instance}:${nodeexpport}\"}[10m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"${instance}:${nodeexpport}\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance}:${nodeexpport}\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance}:${nodeexpport}\"} - node_memory_MemFree_bytes{instance=~\"${instance}:${nodeexpport}\"} - (node_memory_Cached_bytes{instance=~\"${instance}:${nodeexpport}\"} + node_memory_Buffers_bytes{instance=~\"${instance}:${nodeexpport}\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"${instance}:${nodeexpport}\"} + node_memory_Buffers_bytes{instance=~\"${instance}:${nodeexpport}\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"${instance}:${nodeexpport}\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"${instance}:${nodeexpport}\"} - node_memory_SwapFree_bytes{instance=~\"${instance}:${nodeexpport}\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance}:${nodeexpport}\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance}:${nodeexpport}\"} - node_memory_MemFree_bytes{instance=~\"${instance}:${nodeexpport}\"} - (node_memory_Cached_bytes{instance=~\"${instance}:${nodeexpport}\"} + node_memory_Buffers_bytes{instance=~\"${instance}:${nodeexpport}\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"${instance}:${nodeexpport}\"} + node_memory_Buffers_bytes{instance=~\"${instance}:${nodeexpport}\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"${instance}:${nodeexpport}\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"${instance}:${nodeexpport}\"} - node_memory_SwapFree_bytes{instance=~\"${instance}:${nodeexpport}\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"${instance}:${nodeexpport}\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"${instance}:${nodeexpport}\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"${instance}:${nodeexpport}\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"${instance}:${nodeexpport}\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Container info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\", instance=\"${instance}:18080\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",instance=\"${instance}:18080\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\",instance=\"${instance}:18080\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\",instance=\"${instance}:18080\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\", instance=\"${instance}:18080\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\",instance=\"${instance}:18080\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Overall memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "OS Memory ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemory.*\",instance=~\"$instance.*\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "ClickHouse Memory ($instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*Memory.*\",__name__ !~ \"ClickHouseAsyncMetrics_.*OSMemory.*\",instance=~\"$instance.*\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "jemalloc All  ($instance)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__=~ \"ClickHouseAsyncMetrics_jemalloc.*\", __name__!=\"ClickHouseAsyncMetrics_jemalloc_metadata_thp\", __name__!~ \"ClickHouseAsyncMetrics_jemalloc_background_thread.*\", instance=~\"$instance.*\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "OS Memory: Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemoryTotal\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Memory: Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemoryAvailable\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Memory: Free Without Cached",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemoryFreeWithoutCached\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Memory: Cached",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*Buffers\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Memory: Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemoryBuffers\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Memory: Swap Cached",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemorySwapCached\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Memory: Free Plus Cached",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*OSMemoryFreePlusCached\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CH Memory: Resident",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*MemoryResident\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CH Memory: Shared",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*MemoryShared\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CH Memory: Code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*MemoryCode\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CH Memory: Data And Stack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 234 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*MemoryDataAndStack\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CH Memory: Virtual",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "({__name__ =~ \"ClickHouseAsyncMetrics_.*Virtual\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 248 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replicas",
     "type": "graph",
     "description": "Number of Replicated tables that are leaders. Leader replica is responsible for assigning merges, cleaning old blocks for deduplications and a few more bookkeeping tasks. There may be no more than one leader across all replicas at one moment of time. If there is no leader it will be elected soon or it indicate an issue.",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_LeaderReplica{environment=\"$environment\",job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ReadOnly replica",
     "type": "stat",
     "description": "Number of Replicated tables that are currently in readonly state due to re-initialization after ZooKeeper session loss or due to startup without ZooKeeper configured.",
     "gridPos": { "h": 8, "w": 2, "x": 11, "y": 241 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ClickHouseMetrics_ReadonlyReplica{environment=\"$environment\",job=\"$job\"})"
      }
     ]
    },
    {
     "title": "Replication",
     "type": "graph",
     "description": "Number of data parts checking for consistency\n\nNumber of data parts being fetched from replica\n\nNumber of data parts being sent to replicas",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 241 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_ReplicatedChecks{environment=\"$environment\",job=\"$job\"}",
       "legendFormat": "Checking for consistency on {{instance}}"
      },
      {
       "expr": "ClickHouseMetrics_ReplicatedFetch{environment=\"$environment\",job=\"$job\"}",
       "legendFormat": "Fetched from replica on {{instance}}"
      },
      {
       "expr": "ClickHouseMetrics_ReplicatedSend{environment=\"$environment\",job=\"$job\"}",
       "legendFormat": "Sent to replicas from {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}