{
 "title": "Aqua",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU consuption",
   "type": "stat",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_cpu_consumption" }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    { "expr": "aqua_memory_consumption" }
   ]
  },
  {
   "title": "Connected Enforcers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_enforcers_connected" }
   ]
  },
  {
   "title": "Success Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "aqua_logins_success" }
   ]
  },
  {
   "title": "Connected Gateways",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_gateways_connected" }
   ]
  },
  {
   "title": "Failure Logins",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "aqua_logins_failure" }
   ]
  },
  {
   "title": "Image Assurance Policies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_policies_image_assurance" }
   ]
  },
  {
   "title": "Network Policies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_policies_network" }
   ]
  },
  {
   "title": "Runtime Policies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_policies_runtime" }
   ]
  },
  {
   "title": "Scanqueue Done",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_scanqueue_done" }
   ]
  },
  {
   "title": "Scanqueue Failure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_scanqueue_failure" }
   ]
  },
  {
   "title": "Scanqueue In Progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_scanqueue_in_progress" }
   ]
  },
  {
   "title": "Scanqueue Pending",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_scanqueue_pending" }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_users" }
   ]
  },
  {
   "title": "User Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_user_sessions" }
   ]
  },
  {
   "title": "Secrets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_secrets" }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqua_services" }
   ]
  }
 ]
}