{
 "title": "Account Repository Migration Tool",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(jvm_classes_loaded_classes{namespace=~\"payment-wallet-.*\"})"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "query_result(jvm_classes_loaded_classes{namespace=\"$namespace\"})"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$app\"})"
    }
   },
   {
    "name": "db_connection",
    "label": "Database",
    "query": {
     "query": "query_result(service_crud_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"})"
    }
   },
   {
    "name": "crud_service",
    "label": "Crud Service",
    "query": {
     "query": "query_result(service_crud_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Migration (band width: $__interval)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"processed\", entity=\"Account\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"processed\", entity=\"Account\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Processed Accounts"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"processed\", entity=\"Transaction\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"processed\", entity=\"Transaction\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Processed Transactions"
    }
   ]
  },
  {
   "title": "Verification (band width: $__interval)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"processed\", entity=\"Account\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"processed\", entity=\"Account\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Processed Accounts"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"processed\", entity=\"Transaction\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"processed\", entity=\"Transaction\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Processed Transactions"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"verification-error\", entity=\"Account\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"verification-error\", entity=\"Account\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Verification error by Accounts"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"verification-error\", entity=\"Transaction\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"verification-error\", entity=\"Transaction\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Verification error by Transactions"
    }
   ]
  },
  {
   "title": "Migration events (band width: $__interval)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"started\", entity=\"Account\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"started\", entity=\"Account\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Started for Accounts"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"started\", entity=\"Transaction\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"started\", entity=\"Transaction\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Started for Transactions"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"completed\", entity=\"Account\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"completed\", entity=\"Account\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Completed for Accounts"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"completed\", entity=\"Transaction\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"completed\", entity=\"Transaction\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Completed for Transactions"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"failed\", entity=\"Account\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"failed\", entity=\"Account\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Failed for Accounts"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"failed\", entity=\"Transaction\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Migration\", event=\"failed\", entity=\"Transaction\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Failed for Transactions"
    }
   ]
  },
  {
   "title": "Verification events (band width: $__interval)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"started\", entity=\"Account\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"started\", entity=\"Account\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Started for Accounts"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"started\", entity=\"Transaction\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"started\", entity=\"Transaction\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Started for Transactions"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"completed\", entity=\"Account\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"completed\", entity=\"Account\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Completed for Accounts"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"completed\", entity=\"Transaction\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"completed\", entity=\"Transaction\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Completed for Transactions"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"failed\", entity=\"Account\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"failed\", entity=\"Account\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Failed for Accounts"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"failed\", entity=\"Transaction\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"failed\", entity=\"Transaction\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Failed for Transactions"
    }
   ]
  },
  {
   "title": "Verification errors (band width: $__interval)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"verification-error\", entity=\"Account\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"verification-error\", entity=\"Account\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Accounts"
    },
    {
     "expr": "clamp_min(\r\n  sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"verification-error\", entity=\"Transaction\"} OR vector(0))\r\n  - sum(service_process_events_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", process=\"Verification\", event=\"verification-error\", entity=\"Transaction\"} offset $__interval OR vector(0)) \r\n, 0)",
     "legendFormat": "Transactions"
    }
   ]
  },
  { "title": "CRUD Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Rate per minute (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (simple_class, method, connection) (rate(service_crud_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", connection=~\"$db_connection\", simple_class=~\"$crud_service\"}[$__rate_interval])) * 60",
     "legendFormat": "{{simple_class}}.{{method}}({{connection}})"
    }
   ]
  },
  {
   "title": "Duration (seconds) [1m]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (simple_class, method, connection) (increase(service_crud_seconds_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", connection=~\"$db_connection\", simple_class=~\"$crud_service\"}[$__rate_interval])) / sum by (simple_class, method, connection) (increase(service_crud_seconds_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", connection=~\"$db_connection\", simple_class=~\"$crud_service\"}[$__rate_interval]))",
     "legendFormat": "{{simple_class}}.{{method}}({{connection}})"
    }
   ]
  }
 ]
}