{
 "title": "Sales Price Repository",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "query_result(group (prices_repository_transitions_total{status=\"received\"}) by (namespace))"
    }
   },
   {
    "name": "origin",
    "query": {
     "query": "query_result(group (prices_repository_transitions_total{status=\"received\"}) by (origin))"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proposed Prices",
   "type": "stat",
   "description": "Total number of prices that came to the repository",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"proposed\"}[$period]\r\n)\r\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Created Prices",
   "type": "stat",
   "description": "Newly created prices",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"created\"}[$period]\r\n)\r\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Updated Prices",
   "type": "stat",
   "description": "Updates of the existing prices",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"updated\"}[$period]\r\n)\r\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Discarded Prices",
   "type": "stat",
   "description": "Prices that the repository automatically filtered out and didn't insert",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"discarded\"}[$period]\r\n)\r\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Search Latency 95% [$period]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "  histogram_quantile(\r\n    0.95,\r\n    sum(\r\n      rate(\r\n        ingress_nginx_detail_request_seconds_bucket{\r\n          namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", location=\"/prices-mashup/(.*)\"}[$__interval]\r\n        )\r\n    ) by (le)\r\n) * 1000"
    }
   ]
  },
  {
   "title": "Max Search Throughput [$period]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    irate(\r\n        ingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", status=~\"2..\", location=~\"/prices-mashup/(.*)|/pricerepository/(.*)\"}[$__interval]\r\n    )\r\n)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Announced Prices",
   "type": "stat",
   "description": "Price changes that have been announced asynchronously",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(prices_announcer_announced_total{namespace=\"vspspr-${environment}\", container=\"price-changes-announcer\"}[$period])) or vector(0)"
    }
   ]
  },
  {
   "title": "Pending Prices",
   "type": "stat",
   "description": "Prices waiting to be inserted into the repository",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\r\n        kafka_consumer_fetch_manager_records_lag {\r\n                client_id!~\".*retry.*\",\r\n                container=\"prices-uploader\",\r\n                namespace=\"vspspr-${environment}\"\r\n        }\r\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Max Insertion Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "prices/s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "\r\n    sum (\r\n      rate(\r\n         prices_repository_transitions_total { namespace=\"vspspr-${environment}\", container=\"price-changes-api\", status=~\"created|updated|discarded\" }    [$period]\r\n)\r\n    )\r\n"
    }
   ]
  },
  {
   "title": "Stuck Prices",
   "type": "stat",
   "description": "Prices for which the repository experienced an error during the insertion process",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n        kafka_consumer_fetch_manager_records_lag {\r\n                client_id=~\".*retry.*\",\r\n                container=\"prices-uploader\",\r\n                namespace=\"vspspr-${environment}\"\r\n        }\r\n) or vector(0)",
     "legendFormat": "Remaining To Process"
    }
   ]
  },
  {
   "title": "Search Availability",
   "type": "stat",
   "description": "% of the search requests that received a response from the repository",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    ingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", content_kind!=\"served-without-upstream\"}[$__range])\r\n)\r\n/\r\nsum(\r\n  increase(\r\n    ingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\"}[$__range]\r\n    )\r\n)"
    }
   ]
  },
  {
   "title": "Search Correctness",
   "type": "stat",
   "description": "% of successful queries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    irate(\r\n        ingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", location=~\"/prices-mashup/(.*)|/pricerepository/(.*)\", status=~\"2..\"}[$__range]\r\n    )\r\n)\r\n/\r\nsum(\r\n    irate(\r\n        ingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", location=~\"/prices-mashup/(.*)|/pricerepository/(.*)\"}[$__range]\r\n    )\r\n)"
    }
   ]
  },
  {
   "title": "Search Еfficiency",
   "type": "stat",
   "description": "% of fulfilled searches where the repository found a price for the requested (item, location) pair",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (\r\n    increase(\r\n        prices_repository_search_products_total{namespace=\"vspspr-${environment}\", container=\"prices-api\", status=\"found\"}[$__range]\r\n    )\r\n)/\r\nsum (\r\n    increase(\r\n        prices_repository_search_products_total{namespace=\"vspspr-${environment}\", container=\"prices-api\"}[$__range]\r\n    )\r\n)"
    }
   ]
  },
  { "title": "Prices Uploading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Inserted Prices [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"created\"}[$period]\r\n)\r\n) or vector(0)",
     "legendFormat": "created"
    },
    {
     "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"updated\"}[$period]\r\n)\r\n) or vector(0)",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Discarded and Stuck Prices [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (cause) (\r\n      increase(\r\n         prices_repository_transitions_total { namespace=\"vspspr-${environment}\", status=\"discarded\" }[$period]\r\n)\r\n)",
     "legendFormat": "{{cause}}"
    },
    {
     "expr": "sum (\r\n      increase(\r\n            prices_repository_transitions_total {namespace=\"vspspr-${environment}\", status=\"stuck\"}[$period]\r\n        )\r\n)",
     "legendFormat": "stuck"
    }
   ]
  },
  {
   "title": "Price Upload Outcomes",
   "type": "text",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 19 },
   "options": {
    "content": "<table>\n  <tr>\n    <td style=\"width:113px\">🔈 <b>Proposed</b></td>\n    <td>Received for uploading</td>\n  </tr>\n  <tr>\n    <td>✔️ <b>Created</b></td>\n    <td>Created new price</td>\n  </tr>\n  <tr>\n    <td>✔️ <b>Updated</b></td>\n    <td>Updated existing price</td>\n  </tr>\n  <tr>\n    <td>⚠️ <b>Stuck</b></td>\n    <td>Faced an error at uploading</td>\n  </tr>\n  <tr>\n    <td>❌ <b>Invalid</b></td>\n    <td>Discared due to invalid parameters</td>\n  </tr>\n  <tr>\n    <td>❌ <b>Equivalent</b></td>\n    <td>Ignored as exact copy of existing</td>\n  </tr>\n  <tr>\n    <td>❌ <b>Duplicate</b></td>\n    <td>Ignored as copy of other proposed</td>\n  </tr>\n  <tr>\n    <td>❌ <b>Outdated</b></td>\n    <td>Ignored as old update of existing</td>\n  </tr>\n  <tr>\n    <td>❌ <b>Uneditable</b></td>\n    <td>Ignored as forbidden update of immutable fields OR statuses</td>\n  </tr>\n  <tr>\n    <td>📣 <b>Announced</b></td>\n    <td>Available for async consumption</td>\n  </tr>\n</table>\n"
   }
  },
  {
   "title": "Upload Statistics By Location",
   "type": "table",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 19 },
   "targets": [
    {
     "expr": "sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"proposed\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"created\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"updated\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"stuck\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"discarded\", cause=\"invalid\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"discarded\", cause=\"equivalent_exists\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"discarded\", cause=\"duplicate_at_request\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"discarded\", cause=\"outdated\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"discarded\", cause=\"uneditable\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (location) (\r\n  increase(\r\n    prices_announcer_announced_total{namespace=\"vspspr-${environment}\"}[$period]\r\n) or vector(0)\r\n)"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{namespace=\"vspspr-${environment}\"} | pod_labels_app_kubernetes_io_name=~\"price-changes-api|prices-uploader|price-changes-announcer\" | json | level=~\"ERROR|WARN\"| line_format \"| {{ printf \\\"%-3.3s\\\" .origin }} | {{.message | replace \\\"\\\\n\\\" \\\" \\\" }}\""
    }
   ]
  },
  { "title": "Prices Lifecycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Activated/deactivated prices [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum (\r\n      increase(\r\n         prices_repository_transitions_total { namespace=\"vspspr-${environment}\", status=\"activated\" }[$period]\r\n      )\r\n)",
     "legendFormat": "activated"
    },
    {
     "expr": "sum (\r\n      increase(\r\n         prices_repository_transitions_total { namespace=\"vspspr-${environment}\", status=\"deactivated\" }[$period]\r\n      )\r\n)",
     "legendFormat": "deactivated"
    }
   ]
  },
  {
   "title": "Prices Lifecycle",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 41 },
   "options": {
    "content": "<table>\n  <tr>\n    <td style=\"width:116px\">🚀 <b>Activated</b></td>\n    <td> Reached start date, became available for consumers</td>\n  </tr>\n  <tr>\n    <td> 🗑️ <b>Deactivated</b></td>\n    <td>Substituted by other price, moved to archive</td>\n  </tr>\n</table>\n"
   }
  },
  {
   "title": "LIfecycle Statistics by Location",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 41 },
   "targets": [
    {
     "expr": "sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"activated\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (location) (\r\n  increase(\r\n    prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"deactivated\"}[$period]\r\n) or vector(0)\r\n)"
    }
   ]
  },
  { "title": "Prices Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Successful Searches Rate 2xx [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        ingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", status=~\"2..\", location=\"/prices-mashup/(.*)\"}[$__rate_interval]\r\n    )\r\n)\r\n",
     "legendFormat": "Canonical API"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        ingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", status=~\"2..\", location=\"/pricerepository/(.*)\"}[$__rate_interval]\r\n    )\r\n)",
     "legendFormat": "Old LOPUS API"
    }
   ]
  },
  {
   "title": "Search Latency [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum(\r\n    rate(\r\n      ingress_nginx_detail_request_seconds_bucket{\r\n        namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", location=\"/prices-mashup/(.*)\"}[$__interval]\r\n      )\r\n  ) by (le)\r\n) * 1000",
     "legendFormat": "50% of requests"
    },
    {
     "expr": "histogram_quantile(\r\n  0.75,\r\n  sum(\r\n    rate(\r\n      ingress_nginx_detail_request_seconds_bucket{\r\n        namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", location=\"/prices-mashup/(.*)\"}[$__interval]\r\n      )\r\n  ) by (le)\r\n) * 1000",
     "legendFormat": "75% of requests"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(\r\n    rate(\r\n      ingress_nginx_detail_request_seconds_bucket{\r\n        namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", location=\"/prices-mashup/(.*)\"}[$__interval]\r\n      )\r\n  ) by (le)\r\n) * 1000",
     "legendFormat": "95% of requests"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum(\r\n    rate(\r\n      ingress_nginx_detail_request_seconds_bucket{\r\n        namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", location=\"/prices-mashup/(.*)\"}[$__interval]\r\n      )\r\n  ) by (le)\r\n) * 1000",
     "legendFormat": "99% of requests"
    }
   ]
  },
  {
   "title": "Client Errors 4xx [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(\r\n    increase(\r\n    \tingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", status=~\"4..\", location=\"/prices-mashup/(.*)\"}[$__interval]\r\n    )\r\n) or vector (0)",
     "legendFormat": "Canonical API"
    },
    {
     "expr": "sum(\r\n    increase(\r\n    \tingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", status=~\"4..\", location=\"/pricerepository/(.*)\"}[$__interval]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Old LOPUS API"
    },
    {
     "expr": "sum(\r\n    increase(\r\n    \thttp_client_requests_seconds_count{namespace=\"vspspr-${environment}\",  container=\"prices-mashup\", pod=~\".*\", uri= \"none\", outcome=\"CLIENT_ERROR\"}[$__interval]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Prices API"
    },
    {
     "expr": "sum(\r\n    increase(\r\n    \thttp_client_requests_seconds_count{namespace=\"vspspr-${environment}\",  container=\"prices-mashup\", pod=~\".*\", uri=\"/sales-price-history:search\", outcome=\"CLIENT_ERROR\"}[$__interval]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Prices History API"
    }
   ]
  },
  {
   "title": "Server Errors 5xx [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(\r\n    increase(\r\n    \tingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", status=~\"5..\", location=\"/prices-mashup/(.*)\"}[$__interval]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Canonical API"
    },
    {
     "expr": "sum(\r\n    increase(\r\n    \tingress_nginx_detail_responses_total{namespace=\"vspspr-${environment}\", service=\"prices-mashup-balancer\", status=~\"5..\", location=\"/pricerepository/(.*)\"}[$__interval]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Old LOPUS API"
    },
    {
     "expr": "sum(\r\n    increase(\r\n    \thttp_client_requests_seconds_count{namespace=\"vspspr-${environment}\",  container=\"prices-mashup\", pod=~\".*\", uri= \"none\", outcome=\"SERVER_ERROR\"}[$__interval]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Prices API"
    },
    {
     "expr": "sum(\r\n    increase(\r\n    \thttp_client_requests_seconds_count{namespace=\"vspspr-${environment}\",  container=\"prices-mashup\", pod=~\".*\", uri=\"/sales-price-history:search\", outcome=\"SERVER_ERROR\"}[$__interval]\r\n    )\r\n) or vector(0)",
     "legendFormat": "Prices History API"
    }
   ]
  },
  {
   "title": "Search Efficiency",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (location) (\r\n    increase(\r\n        prices_repository_search_products_total{namespace=\"vspspr-${environment}\", container=\"prices-api\", status=\"found\"}[$__range]\r\n    )\r\n)",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (location) (\r\n    increase(\r\n        prices_repository_search_products_total{namespace=\"vspspr-${environment}\", container=\"prices-api\", status=\"absent\"}[$__range]\r\n    )\r\n)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "{namespace=\"vspspr-${environment}\"} | pod_labels_app_kubernetes_io_name=~\"prices-api|prices-mashup\" | json | level=~\"ERROR|WARN\"| line_format \"| {{.message | replace \\\"\\\\n\\\" \\\" \\\" }}}}\""
    }
   ]
  },
  {
   "title": "Prices Uploading - ${origin}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "repeat": "origin",
   "collapsed": true,
   "panels": [
    {
     "title": "Received Prices",
     "type": "stat",
     "description": "Total number of prices that were read from the integration source",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"received\", origin=\"${origin}\"}[$period]\r\n)\r\n) or vector(0)"
      }
     ]
    },
    {
     "title": "Proposed Prices",
     "type": "stat",
     "description": "Total number of prices that came to the repository",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"proposed\", origin=\"${origin}\"}[$period]\r\n)\r\n) or vector(0)"
      }
     ]
    },
    {
     "title": "Created Prices",
     "type": "stat",
     "description": "Newly created prices",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"created\", origin=\"${origin}\"}[$period]\r\n)\r\n) or vector(0)"
      }
     ]
    },
    {
     "title": "Discarded Prices",
     "type": "stat",
     "description": "Prices that the repository automatically filtered out and didn't insert",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"discarded\", origin=\"${origin}\"}[$period]\r\n)\r\n) or vector(0)"
      }
     ]
    },
    {
     "title": "Pending Prices",
     "type": "stat",
     "description": "Prices waiting to be inserted into the repository",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 87 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (\r\n    kafka_consumer_fetch_manager_records_lag {\r\n        client_id=~\".*${origin}.*\",\r\n        client_id!~\".*retry.*\",\r\n        container=\"prices-uploader\",\r\n        namespace=\"vspspr-${environment}\"\r\n    }\r\n)"
      }
     ]
    },
    {
     "title": "Stuck Prices",
     "type": "stat",
     "description": "Prices for which the repository experienced an error during the insertion process",
     "gridPos": { "h": 4, "w": 6, "x": 15, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"stuck\", origin=\"${origin}\"}[$period]\r\n)\r\n) or vector(0)",
       "legendFormat": "Total"
      },
      {
       "expr": "sum (\r\n        kafka_consumer_fetch_manager_records_lag {\r\n                client_id=~\".*retry.*\",\r\n                client_id=~\".*${origin}.*\",\r\n                container=\"prices-uploader\",\r\n                namespace=\"vspspr-${environment}\"\r\n        }\r\n) or vector(0)",
       "legendFormat": "Remaining To Process"
      }
     ]
    },
    {
     "title": "Unreadable Prices",
     "type": "stat",
     "description": "Prices that have an unreadable format and can't be handled by the repository",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"unreadable\", origin=\"${origin}\"}[$period]\r\n)\r\n) or vector(0)"
      }
     ]
    },
    {
     "title": "Updated Prices",
     "type": "stat",
     "description": "Updates of the existing prices",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"updated\", origin=\"${origin}\"}[$period]\r\n)\r\n) or vector(0)"
      }
     ]
    },
    {
     "title": "Excess Prices",
     "type": "stat",
     "description": "Prices that exists in the integration source, but are irrelevant to the price repository (e.g. inactive prices)",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"excess\", origin=\"${origin}\"}[$period]\r\n)\r\n) or vector(0)"
      }
     ]
    },
    {
     "title": "Inserted Prices [$period]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"created\", origin=\"${origin}\"}[$period]\r\n)\r\n) or vector(0)",
       "legendFormat": "created"
      },
      {
       "expr": "sum (\r\n    increase(\r\n      prices_repository_transitions_total{namespace=\"vspspr-${environment}\", status=\"updated\", origin=\"${origin}\"}[$period]\r\n)\r\n) or vector(0)",
       "legendFormat": "updated"
      }
     ]
    },
    {
     "title": "Discarded and Stuck Prices [$period]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "sum by (cause) (\r\n      increase(\r\n         prices_repository_transitions_total { namespace=\"vspspr-${environment}\", status=\"discarded\", origin=\"${origin}\" }[$period]\r\n)\r\n)",
       "legendFormat": "{{cause}}"
      },
      {
       "expr": "sum (\r\n      increase(\r\n            prices_repository_transitions_total {namespace=\"vspspr-${environment}\", status=\"stuck\", origin=\"${origin}\"}[$period]\r\n        )\r\n)",
       "legendFormat": "stuck"
      }
     ]
    }
   ]
  }
 ]
}