{
 "title": "Sales Price Decision Maker",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "query_result(group (kube_pod_info{namespace=~\"vspspdm-.*\"}) by (namespace))"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Triggers",
   "type": "stat",
   "description": "The total number of actions generated by triggers",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum (\n    increase(kafka_consumer_fetch_manager_records_lead { namespace=\"vspspdm-${environment}\", container=~\".*-trigger-collector\"} [$period])\n  )\n)"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "stat",
   "description": "The total number of actions generated by triggers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(decision_maker_pricing_action_processed_seconds_count{namespace=\"vspspdm-${environment}\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Price Calculation Tasks",
   "type": "stat",
   "description": "The total number of produced calculation tasks",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(decision_maker_sales_price_calculation_task_produced_total{namespace=\"vspspdm-${environment}\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Workflows - Scheduled",
   "type": "stat",
   "description": "The total number of scheduled workflows",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(decision_maker_workflow_transitions_seconds_count{namespace=\"vspspdm-${environment}\", status=\"SCHEDULED\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Workflows - Finished",
   "type": "stat",
   "description": "The total number of finished workflows",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(decision_maker_workflow_transitions_seconds_count{namespace=\"vspspdm-${environment}\", status=\"FINISHED\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Workflows - Cancelled",
   "type": "stat",
   "description": "The total number of cancelled workflows",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(decision_maker_workflow_transitions_seconds_count{namespace=\"vspspdm-${environment}\", status=\"CANCELLED\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  { "title": "Triggers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Trigger Messages by Container [$period]",
   "type": "bargauge",
   "description": "Number of trigger messages received by collectors",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\r\n  sum by (container) (\r\n    increase(kafka_consumer_fetch_manager_records_lead { namespace=\"vspspdm-${environment}\", container=~\".*-trigger-collector\"} [$period])\r\n  )\r\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Triggers by Type",
   "type": "piechart",
   "description": "Distribution of triggers by their type",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(sum by (type) (\r\n  (\r\n    increase(decision_maker_triggers_processed_total{namespace=\"vspspdm-${environment}\"} [$period]\r\n  )\r\n  )\r\n))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Triggers [$period]",
   "type": "timeseries",
   "description": "Number of generated pricing actions by type",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "round(sum by(type) (increase(decision_maker_triggers_processed_total{namespace=\"vspspdm-${environment}\"}[$period])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{namespace=\"vspspdm-${environment}\", container=~\".*trigger-collector\", pod=~\".*\"} | json | level=~\"ERROR|WARN\"| line_format \"| {{.message | replace \\\"\\\\n\\\" \\\" \\\" }}\"",
     "maxLines": 2000
    }
   ]
  },
  { "title": "Workflows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Actions by Type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(sum by (price_reason) (\r\n        increase(decision_maker_pricing_action_processed_seconds_count{namespace=\"vspspdm-${environment}\"}\r\n        [$period])\r\n    )\r\n)",
     "legendFormat": "{{price_reason}}"
    }
   ]
  },
  {
   "title": "Actions [$period]",
   "type": "timeseries",
   "description": "Number of processed pricing actions by type",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "round(sum by(price_reason) (increase(decision_maker_pricing_action_processed_seconds_count{namespace=\"vspspdm-${environment}\"}[$period])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Workflow Statistics By Price Reason",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": " sum by (price_reason) (\r\n  increase(\r\n    decision_maker_workflow_transitions_seconds_count{namespace=\"vspspdm-${environment}\", status=\"CANCELLED\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (price_reason) (\r\n  increase(\r\n    decision_maker_workflow_transitions_seconds_count{namespace=\"vspspdm-${environment}\", status=\"SCHEDULED\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (price_reason) (\r\n  increase(\r\n    decision_maker_workflow_transitions_seconds_count{namespace=\"vspspdm-${environment}\", status=\"FINISHED\"}[$period]\r\n) or vector(0)\r\n)"
    }
   ]
  },
  {
   "title": "Workflow Statistics By Location",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": " sum by (location_id) (\r\n  increase(\r\n    decision_maker_workflow_transitions_seconds_count{namespace=\"vspspdm-${environment}\", status=\"CANCELLED\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (location_id) (\r\n  increase(\r\n    decision_maker_workflow_transitions_seconds_count{namespace=\"vspspdm-${environment}\", status=\"SCHEDULED\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (location_id) (\r\n  increase(\r\n    decision_maker_workflow_transitions_seconds_count{namespace=\"vspspdm-${environment}\", status=\"FINISHED\"}[$period]\r\n) or vector(0)\r\n)"
    }
   ]
  },
  {
   "title": "Workflows [$period]",
   "type": "timeseries",
   "description": "Number of workflows that changed status",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "round(sum by (status) (\r\n  increase(\r\n    decision_maker_workflow_transitions_seconds_count{namespace=\"vspspdm-${environment}\"}[$period]\r\n)\r\n))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "{namespace=\"vspspdm-${environment}\", container=~\".*workflow.*\", pod=~\".*\"} | json | level=~\"ERROR|WARN\"| line_format \"| {{.message | replace \\\"\\\\n\\\" \\\" \\\" }}\"",
     "maxLines": 2000
    }
   ]
  },
  { "title": "Price Calculation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Sales Price Calculation Tasks [$period]",
   "type": "timeseries",
   "description": "Number of produced calucaltion tasks by price reason",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "round(sum by(price_reason) (increase(decision_maker_sales_price_calculation_task_produced_total{namespace=\"vspspdm-${environment}\"}[$period])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Calculation Tasks Statistics By Location",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "round(sum by(location_id) (increase(decision_maker_sales_price_calculation_task_produced_total{namespace=\"vspspdm-${environment}\"}[$period])))"
    }
   ]
  }
 ]
}