{
 "title": "Sales Price Calculator",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "query_result(group(prices_calculation_transitions_seconds_count) by (namespace))"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Received",
   "type": "stat",
   "description": "The total number of price calculations that passed into each status during the interval",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"RECEIVED\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Supplementing",
   "type": "stat",
   "description": "The total number of price calculations that passed into each status during the interval",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"SUPPLEMENTING\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Calculating",
   "type": "stat",
   "description": "The total number of price calculations that passed into each status during the interval",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"CALCULATING\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Handled",
   "type": "stat",
   "description": "The total number of price calculations that passed into each status during the interval",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"HANDLED\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Mean calculation time [$period]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(prices_calculation_transitions_seconds_sum{namespace=\"vspspc-${environment}\", status = \"HANDLED\"}[$period]))\n / sum(increase(prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status = \"HANDLED\"}[$period]))"
    }
   ]
  },
  {
   "title": "Cancelled",
   "type": "stat",
   "description": "The total number of price calculations that passed into each status during the interval",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"CANCELLED\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Discarded",
   "type": "stat",
   "description": "The total number of price calculations that passed into each status during the interval",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n  (\n      increase(prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"DISCARDED\"}[$period])\n  )\n)\n) or vector(0)"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "HANDLED calculations [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "round(sum(increase(prices_calculation_transitions_seconds_count{namespace=\"vspspc-$environment\", status=\"HANDLED\"}[$period]))) or vector(0)",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "DISCARDED and CANCELLED calculations [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "round(sum(increase(prices_calculation_transitions_seconds_count{namespace=\"vspspc-$environment\", status = \"DISCARDED\"}[$period]))) or vector(0)",
     "legendFormat": "Discarded"
    },
    {
     "expr": "round(sum(increase(prices_calculation_transitions_seconds_count{namespace=\"vspspc-$environment\", status = \"CANCELLED\"}[$period]))) or vector(0)",
     "legendFormat": "Cancelled"
    }
   ]
  },
  {
   "title": "Status changes Statistics By Location",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": " sum by (location_id) (\r\n  increase(\r\n    prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"RECEIVED\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (location_id) (\r\n  increase(\r\n    prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"DISCARDED\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (location_id) (\r\n  increase(\r\n    prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"SUPPLEMENTING\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (location_id) (\r\n  increase(\r\n    prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"CALCULATING\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (location_id) (\r\n  increase(\r\n    prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"CANCELLED\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (location_id) (\r\n  increase(\r\n    prices_calculation_transitions_seconds_count{namespace=\"vspspc-${environment}\", status=\"HANDLED\"}[$period]\r\n) or vector(0)\r\n)"
    }
   ]
  },
  {
   "title": "Status changes Statistics By Reason code",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": " sum by (reason_code) (\r\n  increase(\r\n    prices_calculation_transitions_by_reason_total{namespace=\"vspspc-${environment}\", status=\"RECEIVED\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (reason_code) (\r\n  increase(\r\n    prices_calculation_transitions_by_reason_total{namespace=\"vspspc-${environment}\", status=\"DISCARDED\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (reason_code) (\r\n  increase(\r\n    prices_calculation_transitions_by_reason_total{namespace=\"vspspc-${environment}\", status=\"SUPPLEMENTING\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (reason_code) (\r\n  increase(\r\n    prices_calculation_transitions_by_reason_total{namespace=\"vspspc-${environment}\", status=\"CALCULATING\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (reason_code) (\r\n  increase(\r\n    prices_calculation_transitions_by_reason_total{namespace=\"vspspc-${environment}\", status=\"CANCELLED\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (reason_code) (\r\n  increase(\r\n    prices_calculation_transitions_by_reason_total{namespace=\"vspspc-${environment}\", status=\"HANDLED\"}[$period]\r\n) or vector(0)\r\n)"
    }
   ]
  },
  { "title": "Correctness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Application Errors",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{namespace=\"vspspc-${environment}\"} | json | level=~\"ERROR|WARN\"| line_format \"| {{.message | replace \\\"\\\\n\\\" \\\" \\\" }}\"",
     "maxLines": 2000
    }
   ]
  }
 ]
}