{
 "title": "Sales Price Monitoring",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "query_result(group (kube_pod_info{namespace=~\"vsppm-.*\"}) by (namespace))"
    }
   },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "query_result(group(delta(price_monitoring_benchmarks_transitions_total{namespace=\"vsppm-${environment}\"}[$__range]) > 0) by (location_id))"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Competitor Prices - Gathered [$period]",
   "type": "stat",
   "description": "The number of collected prices of competitors that were published by the anti-corruption layer",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "round(sum((increase(price_monitoring_legacy_competitor_prices_transitions_total{namespace=\"vsppm-${environment}\",location_id =~ \"$location\", status=\"gathered\"}[$period])))) or vector(0)"
    }
   ]
  },
  {
   "title": "Benchmarks - Started [$period]",
   "type": "stat",
   "description": "Number of benchmarks that Scheduler transferred to IN_PROGRESS status",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  increase(\r\n    price_monitoring_benchmarks_transitions_total{\r\n      namespace=\"vsppm-${environment}\",\r\n      location_id =~ \"$location\",      \r\n      status = \"started\"\r\n    }[$period]\r\n  )\r\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Benchmarks - Competed [$period]",
   "type": "stat",
   "description": "Number of benchmarks that Scheduler transferred to FINISHED status",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  increase(\r\n    price_monitoring_benchmarks_transitions_total{\r\n      namespace=\"vsppm-${environment}\",\r\n      location_id =~ \"$location\",      \r\n      status = \"finished\"\r\n    }[$period]\r\n  )\r\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Benchmarks - Wrong [$period]",
   "type": "stat",
   "description": "Number of benchmarks that differ from the target value",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  increase(\r\n    price_monitoring_benchmarks_transitions_total{\r\n      namespace=\"vsppm-${environment}\",\r\n      location_id =~ \"$location\",  \r\n      status = \"wrong\"\r\n    }[$period]\r\n  )\r\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Benchmarks - Failed [$period]",
   "type": "stat",
   "description": "Number of benchmarks that Scheduler transferred to FAILED status.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  increase(\r\n    price_monitoring_benchmarks_transitions_total{\r\n      namespace=\"vsppm-${environment}\",\r\n      location_id =~ \"$location\",      \r\n      status = \"failed\"\r\n    }[$period]\r\n  )\r\n) or vector(0)"
    }
   ]
  },
  {
   "title": " Benchmarks - Max Rate [$period]",
   "type": "stat",
   "description": "The maximum number of benchmarks per second that the Benchmark Service saved during the selected aggregation period",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  sum(rate(price_monitoring_benchmarks_transitions_total{\r\n    namespace=\"vsppm-${environment}\",\r\n    status=\"stored\",\r\n    location_id =~ \"$location\"\r\n  }[5m]))[$period:]\r\n)"
    }
   ]
  },
  {
   "title": "Benchmarks - Stored [$period]",
   "type": "stat",
   "description": "Number of benchmarks that Benchmark Service saved",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  increase(\r\n    price_monitoring_benchmarks_transitions_total{\r\n      namespace=\"vsppm-${environment}\",\r\n      location_id =~ \"$location\",      \r\n      status = \"stored\"\r\n    }[$period]\r\n  )\r\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Benchmarks - Reported [$period]",
   "type": "stat",
   "description": "Number of benchmarks that Benchmark Service saved",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  increase(\r\n    price_monitoring_benchmarks_transitions_total{\r\n      namespace=\"vsppm-${environment}\",\r\n      location_id =~ \"$location\",      \r\n      status = \"reported\"\r\n    }[$period]\r\n  )\r\n) or vector(0)"
    }
   ]
  },
  { "title": "Legacy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Benchmarks - Processed [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (status) (\n  increase(\n    price_monitoring_legacy_benchmarks_transitions_total{\n      namespace=\"vsppm-${environment}\",\n      location_id =~ \"$location\",\n      status=\"completed\"   \n    }[$period]\n  )\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Benchmarks - Failed [$period]",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (cause) (\n  increase(\n    price_monitoring_legacy_benchmarks_transitions_total{\n      namespace=\"vsppm-${environment}\",\n      location_id =~ \"$location\",\n      status=\"failed\"   \n    }[$period]\n  )\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sales Prices - Published [$period]",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (cause) (\n  increase(\n    price_monitoring_legacy_benchmarks_transitions_total{\n      namespace=\"vsppm-${environment}\",\n      location_id =~ \"$location\",\n      status=~\"failed|skipped\"\n    }[$period]\n  )\n) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sales Prices - Totals By Location  [$period]",
   "type": "table",
   "description": "Table showing statistics on processed sales prices by location",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": " sum by (location_id) (\r\n  increase(\r\n    price_monitoring_legacy_benchmarks_transitions_total{namespace=\"vsppm-${environment}\", status=~\"skipped\", location_id =~ \"$location\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (location_id) (\r\n  increase(\r\n    price_monitoring_legacy_benchmarks_transitions_total{namespace=\"vsppm-${environment}\", status=~\"failed\", location_id =~ \"$location\"}[$period]\r\n) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (location_id) (\r\n  increase(\r\n    price_monitoring_legacy_benchmarks_transitions_total{namespace=\"vsppm-${environment}\", status=~\"completed\", location_id =~ \"$location\"}[$period]\r\n) or vector(0)\r\n)"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "description": "Shows WARN and ERROR level logs that occurred in the anti-corruption-layer container",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{namespace=\"vsppm-${environment}\", container=\"anti-corruption-layer\", location_id =~ \"$location\"} | json | level=~\"ERROR|WARN\"| line_format \"| {{.message | replace \\\"\\\\n\\\" \\\" \\\" }}\"",
     "maxLines": 2000
    }
   ]
  },
  { "title": "Competitor Prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Competitor Prices - Published [$period]",
   "type": "timeseries",
   "description": "A bar chart over time showing the number of competitor prices published by ACL",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    price_monitoring_legacy_competitor_prices_transitions_total{\n      namespace=\"vsppm-${environment}\",\n      location_id =~ \"$location\",\n      status=\"gathered\"   \n    }[$period]\n  )\n) ",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Competitor Prices - Totals By Location [$period]",
   "type": "table",
   "description": "Table showing statistics on processed sales prices by location",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": " sum by (location_id) (\r\n  increase(\r\n    price_monitoring_legacy_competitor_prices_transitions_total{namespace=\"vsppm-${environment}\", status=~\"gathered\", location_id =~ \"$location\"}[$period]\r\n)\r\n)"
    }
   ]
  },
  { "title": "Benchmarks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Benchmarks - Scheduled [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "round(sum(increase(price_monitoring_benchmarks_transitions_total{namespace=\"vsppm-$environment\", location_id =~ \"$location\", status=\"pending\"}[$period])))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Benchmarks - Completed  [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "round(sum(increase(price_monitoring_benchmarks_transitions_total{namespace=\"vsppm-$environment\", location_id =~ \"$location\", status=\"finished\"}[$period])))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": " Benchmarks - Wrong  [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "round(sum(increase(price_monitoring_benchmarks_transitions_total{namespace=\"vsppm-$environment\", location_id =~ \"$location\", status=\"wrong\"}[$period])))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": " Benchmarks - Failed  [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "round(sum(increase(price_monitoring_benchmarks_transitions_total{namespace=\"vsppm-$environment\",location_id =~ \"$location\", status=\"failed\"}[$period])))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "description": "Shows WARN and ERROR level logs that occurred in the anti-corruption-layer container",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "{namespace=\"vsppm-${environment}\", container=~\"benchmark-.*\", location_id =~ \"$location\"} | json | level=~\"ERROR|WARN\" | line_format \"| {{.message | replace \\\"\\\\n\\\" \\\" \\\" }}\"\n",
     "maxLines": 2000
    }
   ]
  }
 ]
}