{
 "title": "Store Price Label Manager",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "query_result(group (prices_label_manager_labels_total) by (namespace))"
    }
   },
   {
    "name": "store",
    "label": "Store",
    "query": {
     "query": "query_result(group(delta(prices_label_manager_labels_total{namespace=\"vspsplm-${environment}\"}[$__range]) > 0) by (store_id))"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stores - Interacted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\r\n  group(\r\n    delta(\r\n      prices_label_manager_labels_total{ namespace = \"vspsplm-${environment}\", store_id =~ \"$store\" }[$__range]\r\n    ) > 0\r\n  ) by (store_id)\r\n)"
    }
   ]
  },
  {
   "title": "Sessions - Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    prices_label_manager_sessions_total{ namespace = \"vspsplm-${environment}\", store_id =~ \"$store\", status = \"completed\" }[$period]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "% Completed - On-time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    prices_label_manager_sessions_total{namespace = \"vspsplm-${environment}\", store_id =~ \"$store\", status=\"completed\", delivery=\"on-time\"}[$__range]\r\n  )\r\n) \r\n/\r\nsum(\r\n  increase(\r\n    prices_label_manager_sessions_total{namespace = \"vspsplm-${environment}\", store_id =~ \"$store\", status=\"completed\" }[$__range]\r\n  )\r\n) "
    }
   ]
  },
  {
   "title": "Pages - Printed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    prices_label_manager_pages_total{ namespace = \"vspsplm-${environment}\", store_id =~ \"$store\", status=\"printed\" }[$period]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Labels - Printed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    prices_label_manager_labels_total{ namespace = \"vspsplm-${environment}\", store_id =~ \"$store\", status=\"printed\" }[$period]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "% Successful Prints",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    http_server_requests_seconds_count{ namespace = \"vspsplm-${environment}\", outcome=\"SUCCESS\", store_id =~ \"$store\", uri=\"/printing/printTagTask\" }[$__range]\r\n  )\r\n) / sum(\r\n  increase(\r\n    http_server_requests_seconds_count{ namespace = \"vspsplm-${environment}\", uri=\"/printing/printTagTask\" }[$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Triggers - Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kafka_consumer_fetch_manager_records_lag {\r\n    container=\"plp-generator\",\r\n    namespace=\"vspsplm-${environment}\"\r\n  }\r\n)"
    }
   ]
  },
  {
   "title": "Triggers - Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    prices_label_manager_generations_total{ namespace = \"vspsplm-${environment}\", store_id =~ \"$store\", status = \"queued\" }[$period]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Sessions - Generated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    prices_label_manager_sessions_total{ namespace = \"vspsplm-${environment}\", store_id =~ \"$store\", status = \"created\" }[$period]\r\n  )\r\n)"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Labels Printed [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (template_size) (\r\n    increase(\r\n      prices_label_manager_labels_total{namespace=\"vspsplm-${environment}\", store_id =~ \"$store\", status=\"printed\"}[$period]\r\n    )\r\n)",
     "legendFormat": "{{template_size}}"
    }
   ]
  },
  {
   "title": "Pages Printed [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (template_size) (\r\n    increase(\r\n      prices_label_manager_pages_total{namespace=\"vspsplm-${environment}\", store_id =~ \"$store\", status=\"printed\"}[$period]\r\n    )\r\n)",
     "legendFormat": "{{template_size}}"
    }
   ]
  },
  {
   "title": "Label Management By Store",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (store_id) (\r\n  increase(\r\n    prices_label_manager_generations_total{namespace=\"vspsplm-${environment}\", store_id =~ \"$store\", status=\"queued\"}[$period]\r\n  ) or vector(0)\r\n)"
    },
    {
     "expr": " sum by (store_id) (\r\n  increase(\r\n    prices_label_manager_sessions_total{namespace=\"vspsplm-${environment}\", store_id =~ \"$store\", status=\"created\"}[$period]\r\n  ) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (store_id) (\n  increase(\n    prices_label_manager_sessions_total{namespace=\"vspsplm-${environment}\", store_id =~ \"$store\", status=\"completed\"}[$period]\n  ) or vector(0)\n)"
    },
    {
     "expr": "sum by (store_id) (\n  increase(\n    prices_label_manager_sessions_total{namespace=\"vspsplm-${environment}\", store_id =~ \"$store\", status=\"completed\", delivery=\"on-time\"}[$period]\n  ) or vector(0)\n)"
    },
    {
     "expr": " sum by (store_id) (\r\n  increase(\r\n    prices_label_manager_labels_total{namespace=\"vspsplm-${environment}\", store_id =~ \"$store\", status=\"printed\" }[$period]\r\n  ) or vector(0)\r\n)"
    },
    {
     "expr": "sum by (store_id) (\r\n  increase(\r\n    prices_label_manager_pages_total{namespace=\"vspsplm-${environment}\", store_id =~ \"$store\", status=\"printed\"}[$period]\r\n  ) or vector(0)\r\n)"
    }
   ]
  },
  {
   "title": "Triggers - Received [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum (\r\n    increase(\r\n      prices_label_manager_generations_total{namespace=\"vspsplm-${environment}\", store_id =~ \"$store\", status=\"queued\"}[$period]\r\n    )\r\n)",
     "legendFormat": "Generations"
    }
   ]
  },
  {
   "title": "Sessions - Generated [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum (\r\n    increase(\r\n      prices_label_manager_sessions_total{namespace=\"vspsplm-${environment}\", store_id =~ \"$store\", status=\"created\"}[$period]\r\n    )\r\n)",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Application Errors",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{namespace=\"vspsplm-${environment}\"} | json | level = \"ERROR\" and store =~ \"$store\" | line_format \"| {{.message}}\"",
     "maxLines": 2000
    },
    {
     "expr": "{namespace=\"vspsplm-${environment}\", container=\"plp-mobile-bff\"} |= \"Exception\" | stream = \"stderr\" | line_format \"| {{ __line__ }}\"",
     "maxLines": 2000
    }
   ]
  }
 ]
}