{
 "title": "Store Sales Price Checker",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "query_result(group (prices_checker_service_calls_total) by (namespace))"
    }
   },
   {
    "name": "store",
    "label": "Store",
    "query": {
     "query": "query_result(group(delta(prices_checker_service_calls_total{namespace=\"vspsspc-${environment}\"}[$__range]) > 0) by (store_id))"
    }
   },
   {
    "name": "period",
    "label": "Period",
    "query": "2m,5m,10m,15m,30m,1h,2h,3h,6h,12h"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Found Prices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", status = \"OK\", store_id =~ \"$store\" }[$__range]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Found Prices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", status != \"OK\", store_id =~ \"$store\" }[$__range]\n    )\n  )\n)"
    }
   ]
  },
  {
   "title": "% Found Prices",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "(\n  sum(\n    increase(\n      prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", store_id =~ \"$store\" }[$__range]\n    )\n  )\n  - \n  sum(\n    increase(\n      prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", status != \"OK\", store_id =~ \"$store\"}[$__range]\n    )\n  )\n) \n/\nsum(\n  increase(\n    prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", store_id =~ \"$store\"}[$__range]\n  )\n) \n* 100",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Devices Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  group by (store_id, client_ip) (\n    delta(\n      prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", store_id =~ \"$store\", client_ip =~ \".+\" }[$__range]\n    ) > 0\n  ) \n)"
    }
   ]
  },
  {
   "title": "Stores Involved",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  group(\n    delta(\n      prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", store_id =~ \"$store\" }[$__range]\n    ) > 0\n  ) by (store_id)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (\r\n    irate(\r\n        spring_integration_send_seconds_count{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$__rate_interval]\r\n    )\r\n)*60"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  irate(\n    spring_integration_send_seconds_sum{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    spring_integration_send_seconds_count{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$__rate_interval]\n  )\n)"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Usage [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", store_id =~ \"$store\" }[$period]\n  )\n)",
     "legendFormat": "# of Usages"
    }
   ]
  },
  {
   "title": "Usage By Stores",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "sort_desc(\n    sum by (store_id) (\n        increase(\n            prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", status = \"OK\", store_id =~ \"$store\" }[$__range]\n        )\n    )\n) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (store_id) (\n    increase(\n        prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", status != \"OK\", store_id =~ \"$store\" }[$__range]\n    )\n) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (store_id) (\r\n    group by (store_id, client_ip) (\r\n        delta(\r\n            prices_checker_service_calls_total{namespace = \"vspsspc-${environment}\", store_id =~ \"$store\", client_ip =~ \".+\"}[$__range]\r\n        ) > 0\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Correctness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Errors Dynamic [$period]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", status != \"OK\", store_id =~ \"$store\" }[$period]\n  )\n) or vector(0)",
     "legendFormat": "# of Errors"
    }
   ]
  },
  {
   "title": "Errors Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (\n  increase(\n    prices_checker_service_calls_total{ namespace = \"vspsspc-${environment}\", status !~ \"OK\", store_id =~ \"$store\" }[$__range]\n  ) > 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Errors",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{namespace=\"vspsspc-${environment}\"} | json | level = \"ERROR\" and storeId=~\"$store\" | line_format \"| Store {{ printf \\\"%-3.3s\\\" .storeId }} | {{.message}}\""
    },
    {
     "expr": "{namespace=\"vspsspc-${environment}\"} |= \"Exception\" | stream = \"stderr\" | line_format \"| {{ __line__ }}\""
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Response Time [$period]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(\n  0.95,\n  increase(\n    spring_integration_send_seconds_sum{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$period]\n  )\n  /\n  increase(\n    spring_integration_send_seconds_count{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$period]\n  )\n)",
     "legendFormat": "95% of requests"
    },
    {
     "expr": "quantile(\n  0.90, \n  increase(\n    spring_integration_send_seconds_sum{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$period]\n  )\n  /\n  increase(\n    spring_integration_send_seconds_count{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$period]\n  )\n)",
     "legendFormat": "90% of requests"
    },
    {
     "expr": "quantile(\n  0.75, \n  increase(\n    spring_integration_send_seconds_sum{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$period]\n  )\n  /\n  increase(\n    spring_integration_send_seconds_count{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$period]\n  )\n)",
     "legendFormat": "75% of requests"
    },
    {
     "expr": "quantile(\n  0.5, \n  increase(\n    spring_integration_send_seconds_sum{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$period]\n  )\n  /\n  increase(\n    spring_integration_send_seconds_count{ name = \"inboundChannel\", namespace=\"vspsspc-${environment}\" }[$period]\n  )\n)",
     "legendFormat": "50% of requests"
    }
   ]
  }
 ]
}