{
 "title": "MP-MRS Dashboard with custom metrics",
 "tags": [ "main" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kubernetes_build_info, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$node\"}, namespace)"
    }
   },
   {
    "name": "controller_type",
    "label": "Controller Type",
    "query": {
     "query": "label_values(kube_controller_pod{node=~\"$node\", namespace=~\"$namespace\"}, controller_type)"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(kube_controller_pod{node=~\"$node\", namespace=~\"$namespace\", controller_type=~\"$controller_type\"}, controller)"
    }
   },
   {
    "name": "uri",
    "label": "Uri",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"}, uri)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"}, method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "WMS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "First Reception Listener (Count)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds_count{method=\"firstReceptionFinishedListener\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "First Reception Listener (Seconds)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds{method=\"firstReceptionFinishedListener\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "method_timed_seconds{method=\"firstReceptionFinishedListener\", quantile=\"0.9\"}",
     "legendFormat": "90%"
    },
    {
     "expr": "method_timed_seconds{method=\"firstReceptionFinishedListener\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Create shipment (Count)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds_count{method=\"createShipment\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Create shipment (Seconds)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds{method=\"createShipment\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "method_timed_seconds{method=\"createShipment\", quantile=\"0.9\"}",
     "legendFormat": "90%"
    },
    {
     "expr": "method_timed_seconds{method=\"createShipment\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Second Reception Listener (Count)",
   "type": "graph",
   "description": "The number of Pods controlled by the Controller",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds_count{method=\"secondReceptionFinishedListener\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Second Reception Listener (Seconds)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds{method=\"secondReceptionFinishedListener\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "method_timed_seconds{method=\"secondReceptionFinishedListener\", quantile=\"0.9\"}",
     "legendFormat": "90%"
    },
    {
     "expr": "method_timed_seconds{method=\"secondReceptionFinishedListener\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Shipment status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "wms_service_shipments_not_sent_total/(wms_service_shipments_not_sent_total + wms_service_shipments_sent_total)",
     "legendFormat": "Not Sent / Total"
    },
    {
     "expr": "wms_service_shipments_sent_total/(wms_service_shipments_not_sent_total + wms_service_shipments_sent_total)",
     "legendFormat": "Sent / Total"
    },
    {
     "expr": "wms_service_shipments_not_sent_total/wms_service_shipments_sent_total",
     "legendFormat": "Not Sent / Sent"
    }
   ]
  },
  {
   "title": "StockRepo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "GetStockByProductAndStore(Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"getStockByProductAndStore\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "GetStockByProductAndStore (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"getStockByProductAndStore\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"getStockByProductAndStore\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"getStockByProductAndStore\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    }
   ]
  },
  {
   "title": "Lopus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GetPriceByRegions(Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"getPriceByRegions\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "GetPriceByRegions (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"getPriceByRegions\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"getPriceByRegions\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"getPriceByRegions\", quantile=\"0.99\"} ",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "GetPriceByStores(Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"getPriceByStores\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "GetPriceByStores (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"getPriceByStores\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"getPriceByStores\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"getPriceByStores\", quantile=\"0.99\"} ",
       "legendFormat": "99%"
      }
     ]
    }
   ]
  },
  {
   "title": "MAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "LogBrick",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "GetProductByCode (Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"getProductByCode\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "GetProductByCode (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"getProductByCode\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"getProductByCode\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"getProductByCode\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    }
   ]
  },
  { "title": "PIM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Download Asset (Count)",
   "type": "graph",
   "description": "The number of Pods controlled by the Controller",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds_count{method=\"downloadAsset\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Download Asset (Seconds)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds{method=\"downloadAsset\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "method_timed_seconds{method=\"downloadAsset\", quantile=\"0.9\"}",
     "legendFormat": "90%"
    },
    {
     "expr": "method_timed_seconds{method=\"downloadAsset\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "GetProducts (Count)",
   "type": "graph",
   "description": "The number of Pods controlled by the Controller",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds_count{method=\"getProducts\"}",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "GetProducts (Seconds)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "method_timed_seconds{method=\"getProducts\", quantile=\"0.5\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "method_timed_seconds{method=\"getProducts\", quantile=\"0.9\"}",
     "legendFormat": "90%"
    },
    {
     "expr": "method_timed_seconds{method=\"getProducts\", quantile=\"0.99\"}",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Products",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "GetProducts (Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"getProducts\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "GetProducts (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"getProducts\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"getProducts\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"getProducts\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    }
   ]
  },
  {
   "title": "Replenishment Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Create (Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"create\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Create (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"create\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"create\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"create\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "Update (Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"update\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Update(Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"update\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"update\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"update\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "AddItem (Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"addItem\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "AddItem (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"addItem\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"addItem\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"addItem\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "UpdateItem (Count)",
     "type": "graph",
     "description": "The number of Pods controlled by the Controller",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"updateItem\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "UpdateItem (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"updateItem\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"updateItem\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"updateItem\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "DeleteItem (Count)",
     "type": "graph",
     "description": "The number of Pods controlled by the Controller",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"deleteItem\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "DeleteItem(Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"deleteItem\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"deleteItem\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"deleteItem\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "SendToApproval (Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"sendToApproval\"}",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "SendToApproval (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"sendToApproval\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"sendToApproval\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"sendToApproval\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "Approve (Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"approve\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Approve (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"approve\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"approve\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"approve\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "Reject (Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"reject\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Reject (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"reject\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"reject\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"reject\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "Appoint (Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"appoint\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Appoint (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"appoint\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"appoint\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"appoint\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "GetAllByMerchant (Count)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"getAllByMerchant\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "GetAllByMerchant (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"getAllByMerchant\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"getAllByMerchant\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"getAllByMerchant\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    },
    {
     "title": "GetById (Count)",
     "type": "graph",
     "description": "The number of Pods controlled by the Controller",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds_count{method=\"getById\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "GetById (Seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "method_timed_seconds{method=\"getById\", quantile=\"0.5\"}",
       "legendFormat": "50%"
      },
      {
       "expr": "method_timed_seconds{method=\"getById\", quantile=\"0.9\"}",
       "legendFormat": "90%"
      },
      {
       "expr": "method_timed_seconds{method=\"getById\", quantile=\"0.99\"}",
       "legendFormat": "99%"
      }
     ]
    }
   ]
  }
 ]
}