{
 "title": "VED NestJS Applications",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(target_info{telemetry_sdk_language=\"nodejs\", telemetry_sdk_name=\"opentelemetry\"}, namespace)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(target_info{namespace=\"$namespace\", telemetry_sdk_language=\"nodejs\", telemetry_sdk_name=\"opentelemetry\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(target_info{namespace=\"$namespace\", service=\"$app\", telemetry_sdk_language=\"nodejs\", telemetry_sdk_name=\"opentelemetry\"}, pod)"
    }
   },
   { "name": "excluded_urls", "label": "Excluded URLs", "query": "/.*swagger.*|" },
   { "name": "excluded_hosts", "label": "Excluded hosts", "query": "::1|localhost" }
  ]
 },
 "panels": [
  { "title": "HTTP Server I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request count [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (method, path) (floor(increase(http_server_request_count_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[1m])))",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "sum by (service) (floor(increase(http_server_request_count_total{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[1m])))",
     "legendFormat": "total (press ctrl(cmd) + left click to hide)"
    }
   ]
  },
  {
   "title": "Request count [selected range]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_request_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[$__range]) > 0) by (method, path))",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Total Requests [selected range]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(http_server_request_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[$__range])) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (method, path) (irate(http_server_duration_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[1m])) / sum by (method, path) (irate(http_server_duration_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[1m]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Response Time p99 [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[1m])) by (le, path, method))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Response Time p95 [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[1m])) by (le, path, method))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Response Status Groups 2xx / 3xx/ 4xx / 5xx [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_response_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\", status=~\"2..\"}[5m])) / scalar(sum(increase(http_server_response_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "2xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "sum(increase(http_server_response_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\", status=~\"3..\"}[5m])) / scalar(sum(increase(http_server_response_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "3xx"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_response_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\", status=~\"4..\"}[5m])) / scalar(sum(increase(http_server_response_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "4xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(http_server_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\", status=~\"5..\"}[5m])) / scalar(sum(increase(http_server_response_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[5m])) by (service))",
     "legendFormat": "5xx",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Response Statuses [selected range]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_response_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\"}[$__range]) > 0) by (status))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Response Status Error % by (method, path) [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_count{namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\", status=~\"[45]..\"}[5m])) by (method, path) / (sum(increase(http_server_duration_count{namespace=\"$namespace\", service=\"$app\", path!~\"$excluded_urls\"}[5m])) by (method, path) > 0)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Response Status Error Count by (method, path, status) [selected range]",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_server_response_count_total{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", path!~\"$excluded_urls\", status=~\"[45]..\"}[$__range]) > 0) by (method, path, status))",
     "legendFormat": "{{method}} {{path}} : {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Client I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request count [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum by (net_peer_name) (floor(increase(http_client_duration_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", net_peer_name!~\"$excluded_hosts\"}[1m])))",
       "legendFormat": "{{net_peer_name}}"
      },
      {
       "expr": "sum by (service) (floor(increase(http_client_duration_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", net_peer_name!~\"$excluded_hosts\"}[1m])))",
       "legendFormat": "total (press ctrl(cmd) + left click to hide)"
      }
     ]
    },
    {
     "title": "Request count [selected range]",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", net_peer_name!~\"$excluded_hosts\"}[$__range]) > 0) by (net_peer_name))",
       "legendFormat": "{{ net_peer_name }}"
      }
     ]
    },
    {
     "title": "Total Requests [selected range]",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(floor(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", net_peer_name!~\"$excluded_hosts\"}[$__range])) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response Time [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (net_peer_name) (irate(http_client_duration_sum{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", net_peer_name!~\"$excluded_hosts\"}[1m])) / sum by (net_peer_name) (irate(http_client_duration_count{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", net_peer_name!~\"$excluded_hosts\"}[1m]))",
       "legendFormat": "{{net_peer_name}}"
      }
     ]
    },
    {
     "title": "Response Time p99 [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_client_duration_bucket{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", net_peer_name!~\"$excluded_hosts\"}[1m])) by (le, net_peer_name))",
       "legendFormat": "{{net_peer_name}}"
      }
     ]
    },
    {
     "title": "Response Time p95 [1m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_client_duration_bucket{pod=~\"$pod\", namespace=\"$namespace\", service=\"$app\", net_peer_name!~\"$excluded_hosts\"}[1m])) by (le, net_peer_name))",
       "legendFormat": "{{net_peer_name}}"
      }
     ]
    },
    {
     "title": "Response Status Groups 2xx / 3xx/ 4xx / 5xx [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", http_status_code=~\"2..\", net_peer_name!~\"$excluded_hosts\"}[5m])) / scalar(sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", net_peer_name!~\"$excluded_hosts\"}[5m])) by (service))",
       "legendFormat": "2xx",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "expr": "sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", http_status_code=~\"3..\", net_peer_name!~\"$excluded_hosts\"}[5m])) / scalar(sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", net_peer_name!~\"$excluded_hosts\"}[5m])) by (service))",
       "legendFormat": "3xx"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", http_status_code=~\"4..\", net_peer_name!~\"$excluded_hosts\"}[5m])) / scalar(sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", net_peer_name!~\"$excluded_hosts\"}[5m])) by (service))",
       "legendFormat": "4xx",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", http_status_code=~\"5..\", net_peer_name!~\"$excluded_hosts\"}[5m])) / scalar(sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", net_peer_name!~\"$excluded_hosts\"}[5m])) by (service))",
       "legendFormat": "5xx",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Response Statuses [selected range]",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", net_peer_name!~\"$excluded_hosts\"}[$__range]) > 0) by (http_status_code))",
       "legendFormat": "{{ http_status_code }}"
      }
     ]
    },
    {
     "title": "Response Status Error % by (host) [5m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", http_status_code=~\"[45]..\", net_peer_name!~\"$excluded_hosts\"}[5m])) by (net_peer_name) / (sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", net_peer_name!~\"$excluded_hosts\"}[5m])) by (net_peer_name) > 0)",
       "legendFormat": "{{net_peer_name}}"
      }
     ]
    },
    {
     "title": "Response Status Error Count by (host, status) [selected range]",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_client_duration_count{namespace=\"$namespace\", service=\"$app\", pod=~\"$pod\", http_status_code=~\"[45]..\", net_peer_name!~\"$excluded_hosts\"}[$__range]) > 0) by (net_peer_name))",
       "legendFormat": "{{net_peer_name}} : {{http_status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO, WARNINGS, ERRORS (by pod) [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 201 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (increase(info_count_total{namespace=\"$namespace\", service=\"$app\"}[5m]))",
       "legendFormat": "INFO {{pod}}"
      },
      {
       "expr": "sum by (pod) (increase(warning_count_total{namespace=\"$namespace\", service=\"$app\"}[5m]))",
       "legendFormat": "WARNINGS {{pod}}"
      },
      {
       "expr": "sum by (pod) (increase(error_count_total{namespace=\"$namespace\", service=\"$app\"}[5m]))",
       "legendFormat": "ERRORS {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Pods Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Status",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "(\n  min by (pod) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Running\"}[$__rate_interval])\n  ) == 1\n) * 0",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Pending\"}[$__rate_interval])\n  ) == 1\n) * 1",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Unknown\"}[$__rate_interval])\n  ) == 1\n) * 2",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Failed\"}[$__rate_interval])\n  ) == 1\n) * 3",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "(\n  min by (pod, phase) (\n    kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min_over_time(kube_pod_status_phase{namespace=\"$namespace\", pod=~\"$pod\", phase=\"Succeeded\"}[$__rate_interval])\n  ) == 1\n) * 4",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "(\n  min by (pod) (\n    kube_controller_pod{node=~\"$node\", namespace=\"$namespace\", controller=\"deploy/$app\"}\n    * on (pod) group_right()\n    min by (pod) (min_over_time(kube_pod_container_status_ready{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n  ) == 0\n) + 5",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pods Restarts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}[$__rate_interval])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n) > 0",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "sum (\n  sum by (pod) (avg_over_time(kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}[$__rate_interval])) \n  * on (pod)\n  sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))\n)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 401 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"}[$__rate_interval]))\n)",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", container=\"$app\", pod=~\"$pod\"})",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 401 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (\n  kube_controller_pod{namespace=\"$namespace\", controller=\"deploy/$app\", pod=~\"$pod\"}\n  * on (pod)\n  sum by (pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\", namespace=\"$namespace\"}[$__rate_interval]))\n)",
       "legendFormat": "{{ pod }}"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", container=\"$app\"})",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  }
 ]
}