{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "ingress_nginx_detail_backend_responses_total fe  5m",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_backend_responses_total{ingress=\"fe\", namespace=\"techgate-prod\"}[5m])) by (status_class, group)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Status bff 5m",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_backend_responses_total{ingress=\"bff\", namespace=\"techgate-prod\"}[5m])) by (status_class, group)",
     "legendFormat": "{{status_class}}"
    }
   ]
  },
  {
   "title": "Pod status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "((kube_pod_status_phase{namespace=\"techgate-prod\",phase=\"Running\"})==1)*2",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "((kube_pod_status_phase{namespace=\"techgate-prod\",phase=\"Failed\"})==1)*1",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "((kube_pod_status_phase{namespace=\"techgate-prod\",phase=\"Succeeded\"})==1)*5",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "((kube_pod_status_phase{namespace=\"techgate-prod\",phase=\"Pending\"})==1)*0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "((kube_pod_status_phase{namespace=\"techgate-prod\",phase=\"Unknown\"})==1)*3",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "503",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ingress_nginx_detail_responses_total{namespace=\"techgate-prod\", status=\"503\"}",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "ingress_nginx_detail_upstream_response_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ingress_nginx_detail_upstream_response_seconds_sum{namespace=\"techgate-prod\"}",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "404",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ingress_nginx_detail_responses_total{namespace=\"techgate-prod\", status=\"404\"}",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "container_memory_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "namespace:container_memory_usage_bytes:sum{namespace=\"techgate-prod\"}"
    }
   ]
  },
  {
   "title": "ingress_nginx_detail_backend_responses_total bff 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_backend_responses_total{ingress=\"bff\",namespace=\"techgate-prod\"}[5m])) by (status_class, group)",
     "legendFormat": "{{status_class}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"techgate-prod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ingress_nginx_detail_requests_total  bff 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_nginx_detail_requests_total{ingress=\"bff\",namespace=\"techgate-prod\"}[5m])) by (method, group)"
    }
   ]
  },
  {
   "title": "container_cpu_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namespace:container_cpu_usage:sum{namespace=\"techgate-prod\"}"
    }
   ]
  }
 ]
}